/* Generated by tools/cs2_gen_opcodes/gen_opcodes.py from RuneStar/cs2 Opcodes.kt */
#ifndef CS2_OPCODE_H
#define CS2_OPCODE_H

#define CS2_OPCODE_MAX 7252
#define CS2_OPCODE_COUNT 766

#define CS2_OP_SS_AND -2
#define CS2_OP_SS_OR -1
/* PUSH_CONSTANT_INT — Push int constant.
 * operand: int constant
 * int stack in:   -      
 * str stack in:   -      
 * int stack out:  operand
 * str stack out:  -      
 */
#define CS2_OP_PUSH_CONSTANT_INT 0
/* PUSH_VAR — Read varp.
 * operand: varp id
 * int stack in:   -            
 * str stack in:   -            
 * int stack out:  varp[operand]
 * str stack out:  -            
 */
#define CS2_OP_PUSH_VAR 1
/* POP_VAR — Write varp.
 * operand: varp id
 * int stack in:   value
 * str stack in:   -    
 * int stack out:  -    
 * str stack out:  -    
 * notes: varp[operand] = value
 */
#define CS2_OP_POP_VAR 2
/* PUSH_CONSTANT_STRING — Push string constant.
 * operand: string index
 * int stack in:   -                     
 * str stack in:   -                     
 * int stack out:  -                     
 * str stack out:  script_string[operand]
 */
#define CS2_OP_PUSH_CONSTANT_STRING 3
/* BRANCH — Unconditional branch.
 * operand: branch offset
 * int stack in:   -
 * str stack in:   -
 * int stack out:  -
 * str stack out:  -
 * notes: pc += operand
 */
#define CS2_OP_BRANCH 6
/* BRANCH_NOT — Branch if false.
 * operand: branch offset
 * int stack in:   cond
 * str stack in:   -   
 * int stack out:  -   
 * str stack out:  -   
 * notes: pc += operand if cond == 0
 */
#define CS2_OP_BRANCH_NOT 7
/* BRANCH_EQUALS — Branch if equal.
 * operand: branch offset
 * int stack in:   a, b  (b = top)
 * str stack in:   -   
 * int stack out:  -   
 * str stack out:  -   
 * notes: pc += operand if a == b
 */
#define CS2_OP_BRANCH_EQUALS 8
/* BRANCH_LESS_THAN — Branch if less.
 * operand: branch offset
 * int stack in:   a, b  (b = top)
 * str stack in:   -   
 * int stack out:  -   
 * str stack out:  -   
 * notes: pc += operand if a < b
 */
#define CS2_OP_BRANCH_LESS_THAN 9
/* BRANCH_GREATER_THAN — Branch if greater.
 * operand: branch offset
 * int stack in:   a, b  (b = top)
 * str stack in:   -   
 * int stack out:  -   
 * str stack out:  -   
 * notes: pc += operand if a > b
 */
#define CS2_OP_BRANCH_GREATER_THAN 10
/* RETURN — Return from script.
 * int stack in:   return value (optional)
 * str stack in:   -                      
 * int stack out:  -                      
 * str stack out:  -                      
 * notes: pops frame
 */
#define CS2_OP_RETURN 21
/* PUSH_VARBIT — Read varbit.
 * operand: varbit id
 * int stack in:   -              
 * str stack in:   -              
 * int stack out:  varbit[operand]
 * str stack out:  -              
 */
#define CS2_OP_PUSH_VARBIT 25
/* POP_VARBIT — Write varbit.
 * operand: varbit id
 * int stack in:   value
 * str stack in:   -    
 * int stack out:  -    
 * str stack out:  -    
 * notes: varbit[operand] = value
 */
#define CS2_OP_POP_VARBIT 27
/* BRANCH_LESS_THAN_OR_EQUALS — Branch if less than or equal.
 * operand: branch offset
 * int stack in:   a, b  (b = top)
 * str stack in:   -   
 * int stack out:  -   
 * str stack out:  -   
 * notes: pc += operand if a <= b
 */
#define CS2_OP_BRANCH_LESS_THAN_OR_EQUALS 31
/* BRANCH_GREATER_THAN_OR_EQUALS — Branch if greater than or equal.
 * operand: branch offset
 * int stack in:   a, b  (b = top)
 * str stack in:   -   
 * int stack out:  -   
 * str stack out:  -   
 * notes: pc += operand if a >= b
 */
#define CS2_OP_BRANCH_GREATER_THAN_OR_EQUALS 32
/* PUSH_INT_LOCAL — Push int local.
 * operand: local index
 * int stack in:   -                 
 * str stack in:   -                 
 * int stack out:  int_local[operand]
 * str stack out:  -                 
 */
#define CS2_OP_PUSH_INT_LOCAL 33
/* POP_INT_LOCAL — Pop int local.
 * operand: local index
 * int stack in:   value
 * str stack in:   -    
 * int stack out:  -    
 * str stack out:  -    
 * notes: int_local[operand] = value
 */
#define CS2_OP_POP_INT_LOCAL 34
/* PUSH_STRING_LOCAL — Push string local.
 * operand: local index
 * int stack in:   -                 
 * str stack in:   -                 
 * int stack out:  -                 
 * str stack out:  str_local[operand]
 */
#define CS2_OP_PUSH_STRING_LOCAL 35
/* POP_STRING_LOCAL — Pop string local.
 * operand: local index
 * int stack in:   -    
 * str stack in:   value
 * int stack out:  -    
 * str stack out:  -    
 * notes: str_local[operand] = value
 */
#define CS2_OP_POP_STRING_LOCAL 36
/* JOIN_STRING — Concatenate strings.
 * int stack in:   -    
 * str stack in:   a, b   (b = top)
 * int stack out:  -    
 * str stack out:  a + b
 */
#define CS2_OP_JOIN_STRING 37
/* POP_INT_DISCARD — Discard int.
 * operand: repeat count
 * int stack in:   value
 * str stack in:   -    
 * int stack out:  -    
 * str stack out:  -    
 * notes: discards operand times
 */
#define CS2_OP_POP_INT_DISCARD 38
/* POP_STRING_DISCARD — Discard string.
 * operand: repeat count
 * int stack in:   -    
 * str stack in:   value
 * int stack out:  -    
 * str stack out:  -    
 * notes: discards operand times
 */
#define CS2_OP_POP_STRING_DISCARD 39
/* GOSUB_WITH_PARAMS — Call script.
 * int stack in:   callee args per signature   
 * str stack in:   -                           
 * int stack out:  callee returns per signature
 * str stack out:  -                           
 */
#define CS2_OP_GOSUB_WITH_PARAMS 40
/* PUSH_VARC_INT — Read client int varc.
 * operand: varc id
 * int stack in:   -                
 * str stack in:   -                
 * int stack out:  varc_int[operand]
 * str stack out:  -                
 */
#define CS2_OP_PUSH_VARC_INT 42
/* POP_VARC_INT — Write client int varc.
 * operand: varc id
 * int stack in:   value
 * str stack in:   -    
 * int stack out:  -    
 * str stack out:  -    
 * notes: varc_int[operand] = value
 */
#define CS2_OP_POP_VARC_INT 43
/* DEFINE_ARRAY — Define int array.
 * operand: array id
 * int stack in:   size
 * str stack in:   -   
 * int stack out:  -   
 * str stack out:  -   
 * notes: creates array[operand]
 */
#define CS2_OP_DEFINE_ARRAY 44
/* PUSH_ARRAY_INT — Read array element.
 * operand: array id
 * int stack in:   index                
 * str stack in:   -                    
 * int stack out:  array[operand][index]
 * str stack out:  -                    
 */
#define CS2_OP_PUSH_ARRAY_INT 45
/* POP_ARRAY_INT — Write array element.
 * operand: array id
 * int stack in:   index, value  (value = top)
 * str stack in:   -           
 * int stack out:  -           
 * str stack out:  -           
 * notes: array[operand][index] = value
 */
#define CS2_OP_POP_ARRAY_INT 46
#define CS2_OP_PUSH_VARC_STRING_OLD 47
#define CS2_OP_POP_VARC_STRING_OLD 48
/* PUSH_VARC_STRING — Read client string varc.
 * operand: varc id
 * int stack in:   -                   
 * str stack in:   -                   
 * int stack out:  -                   
 * str stack out:  varc_string[operand]
 */
#define CS2_OP_PUSH_VARC_STRING 49
/* POP_VARC_STRING — Write client string varc.
 * operand: varc id
 * int stack in:   -    
 * str stack in:   value
 * int stack out:  -    
 * str stack out:  -    
 * notes: varc_string[operand] = value
 */
#define CS2_OP_POP_VARC_STRING 50
/* SWITCH — Switch jump.
 * int stack in:   key
 * str stack in:   -  
 * int stack out:  -  
 * str stack out:  -  
 * notes: pc = case target or fall through
 */
#define CS2_OP_SWITCH 60
#define CS2_OP_PUSH_VARCLANSETTING 74
#define CS2_OP_PUSH_VARCLAN 76
/* CC_CREATE — Create dynamic child component.
 * operand: widget type
 * int stack in:   sub_id
 * str stack in:   -     
 * int stack out:  -     
 * str stack out:  -     
 * notes: sets active to new child
 */
#define CS2_OP_CC_CREATE 100
#define CS2_OP_CC_DELETE 101
#define CS2_OP__103 103
#define CS2_OP__104 104
/* CC_DELETEALL — Delete all dynamic children of active parent.
 * int stack in:   -
 * str stack in:   -
 * int stack out:  -
 * str stack out:  -
 */
#define CS2_OP_CC_DELETEALL 102
/* CC_FIND — Find child by sub-id.
 * int stack in:   parent, sub                     (sub = top)
 * str stack in:   -                             
 * int stack out:  1 if found (active set) else 0
 * str stack out:  -                             
 */
#define CS2_OP_CC_FIND 200
/* IF_FIND — Find interface component.
 * int stack in:   component                     
 * str stack in:   -                             
 * int stack out:  1 if found (active set) else 0
 * str stack out:  -                             
 */
#define CS2_OP_IF_FIND 201
#define CS2_OP__202 202
#define CS2_OP__203 202
/* CC_SETPOSITION — Set position modes.
 * int stack in:   x, y, x_mode, y_mode  (y_mode = top)
 * str stack in:   -                   
 * int stack out:  -                   
 * str stack out:  -                   
 */
#define CS2_OP_CC_SETPOSITION 1000
/* CC_SETSIZE — Set size modes.
 * int stack in:   w, h, w_mode, h_mode  (h_mode = top)
 * str stack in:   -                   
 * int stack out:  -                   
 * str stack out:  -                   
 */
#define CS2_OP_CC_SETSIZE 1001
/* CC_SETHIDE — Hide active child.
 * int stack in:   hide
 * str stack in:   -   
 * int stack out:  -   
 * str stack out:  -   
 */
#define CS2_OP_CC_SETHIDE 1003
/* CC_SETNOCLICKTHROUGH — Set no-click-through.
 * int stack in:   enabled
 * str stack in:   -      
 * int stack out:  -      
 * str stack out:  -      
 */
#define CS2_OP_CC_SETNOCLICKTHROUGH 1005
#define CS2_OP_CC_SETNOSCROLLTHROUGH 1006
#define CS2_OP_CC_SETSCROLLPOS 1100
/* CC_SETCOLOUR — Set colour on active child.
 * int stack in:   colour
 * str stack in:   -     
 * int stack out:  -     
 * str stack out:  -     
 */
#define CS2_OP_CC_SETCOLOUR 1101
/* CC_SETFILL — Set rectangle fill.
 * int stack in:   filled
 * str stack in:   -     
 * int stack out:  -     
 * str stack out:  -     
 */
#define CS2_OP_CC_SETFILL 1102
/* CC_SETTRANS — Set transparency.
 * int stack in:   trans
 * str stack in:   -    
 * int stack out:  -    
 * str stack out:  -    
 */
#define CS2_OP_CC_SETTRANS 1103
#define CS2_OP_CC_SETLINEWID 1104
/* CC_SETGRAPHIC — Set sprite graphic.
 * int stack in:   graphic_id
 * str stack in:   -         
 * int stack out:  -         
 * str stack out:  -         
 */
#define CS2_OP_CC_SETGRAPHIC 1105
#define CS2_OP_CC_SET2DANGLE 1106
/* CC_SETTILING — Set sprite tiling.
 * int stack in:   tiled
 * str stack in:   -    
 * int stack out:  -    
 * str stack out:  -    
 */
#define CS2_OP_CC_SETTILING 1107
#define CS2_OP_CC_SETMODEL 1108
#define CS2_OP_CC_SETMODELANGLE 1109
#define CS2_OP_CC_SETMODELANIM 1110
#define CS2_OP_CC_SETMODELORTHOG 1111
/* CC_SETTEXT — Set text on active child.
 * int stack in:   -   
 * str stack in:   text
 * int stack out:  -   
 * str stack out:  -   
 */
#define CS2_OP_CC_SETTEXT 1112
/* CC_SETTEXTFONT — Set font on active child.
 * int stack in:   font_id
 * str stack in:   -      
 * int stack out:  -      
 * str stack out:  -      
 */
#define CS2_OP_CC_SETTEXTFONT 1113
/* CC_SETTEXTALIGN — Set text alignment.
 * int stack in:   x_align, y_align, line_height  (line_height = top)
 * str stack in:   -                            
 * int stack out:  -                            
 * str stack out:  -                            
 */
#define CS2_OP_CC_SETTEXTALIGN 1114
/* CC_SETTEXTSHADOW — Set text shadow.
 * int stack in:   shadowed
 * str stack in:   -       
 * int stack out:  -       
 * str stack out:  -       
 */
#define CS2_OP_CC_SETTEXTSHADOW 1115
/* CC_SETOUTLINE — Set sprite outline.
 * int stack in:   outline
 * str stack in:   -      
 * int stack out:  -      
 * str stack out:  -      
 */
#define CS2_OP_CC_SETOUTLINE 1116
/* CC_SETGRAPHICSHADOW — Set sprite shadow.
 * int stack in:   shadow
 * str stack in:   -     
 * int stack out:  -     
 * str stack out:  -     
 */
#define CS2_OP_CC_SETGRAPHICSHADOW 1117
#define CS2_OP_CC_SETVFLIP 1118
#define CS2_OP_CC_SETHFLIP 1119
#define CS2_OP_CC_SETSCROLLSIZE 1120
#define CS2_OP_CC_RESUME_PAUSEBUTTON 1121
#define CS2_OP__1122 1122
#define CS2_OP_CC_SETFILLCOLOUR 1123
#define CS2_OP__1124 1124
#define CS2_OP__1125 1125
#define CS2_OP_CC_SETLINEDIRECTION 1126
#define CS2_OP_CC_SETMODELTRANSPARENT 1127
#define CS2_OP__1128 1128
/* CC_SETOBJECT — Set object icon on active child.
 * int stack in:   obj_count, obj_id  (obj_id = top)
 * str stack in:   -                
 * int stack out:  -                
 * str stack out:  -                
 */
#define CS2_OP_CC_SETOBJECT 1200
#define CS2_OP_CC_SETNPCHEAD 1201
#define CS2_OP_CC_SETPLAYERHEAD_SELF 1202
/* CC_SETOBJECT_NONUM — Set object icon without qty.
 * int stack in:   obj_id
 * str stack in:   -     
 * int stack out:  -     
 * str stack out:  -     
 */
#define CS2_OP_CC_SETOBJECT_NONUM 1205
/* CC_SETOBJECT_ALWAYS_NUM — Set object icon always showing qty.
 * int stack in:   obj_count, obj_id  (obj_id = top)
 * str stack in:   -                
 * int stack out:  -                
 * str stack out:  -                
 */
#define CS2_OP_CC_SETOBJECT_ALWAYS_NUM 1212
/* CC_SETOP — Set right-click op.
 * int stack in:   index
 * str stack in:   text 
 * int stack out:  -    
 * str stack out:  -    
 */
#define CS2_OP_CC_SETOP 1300
/* CC_SETDRAGGABLE — Set draggable parent/child.
 * int stack in:   parent_uid, child_index  (child_index = top)
 * str stack in:   -                      
 * int stack out:  -                      
 * str stack out:  -                      
 */
#define CS2_OP_CC_SETDRAGGABLE 1301
/* CC_SETDRAGGABLEBEHAVIOR — Set drag behavior.
 * int stack in:   behavior
 * str stack in:   -       
 * int stack out:  -       
 * str stack out:  -       
 */
#define CS2_OP_CC_SETDRAGGABLEBEHAVIOR 1302
/* CC_SETDRAGDEADZONE — Set drag dead zone pixels.
 * int stack in:   zone
 * str stack in:   -   
 * int stack out:  -   
 * str stack out:  -   
 */
#define CS2_OP_CC_SETDRAGDEADZONE 1303
/* CC_SETDRAGDEADTIME — Set drag dead time ms.
 * int stack in:   time
 * str stack in:   -   
 * int stack out:  -   
 * str stack out:  -   
 */
#define CS2_OP_CC_SETDRAGDEADTIME 1304
/* CC_SETOPBASE — Set op base text.
 * int stack in:   -   
 * str stack in:   text
 * int stack out:  -   
 * str stack out:  -   
 */
#define CS2_OP_CC_SETOPBASE 1305
/* CC_SETTARGETVERB — Set target verb (stub).
 * int stack in:   -   
 * str stack in:   text
 * int stack out:  -   
 * str stack out:  -   
 */
#define CS2_OP_CC_SETTARGETVERB 1306
/* CC_CLEAROPS — Clear all ops on active child.
 * int stack in:   -
 * str stack in:   -
 * int stack out:  -
 * str stack out:  -
 */
#define CS2_OP_CC_CLEAROPS 1307
#define CS2_OP__1308 1308
#define CS2_OP__1309 1309
#define CS2_OP_CC_SETOPKEY 1350
#define CS2_OP_CC_SETOPTKEY 1351
#define CS2_OP_CC_SETOPKEYRATE 1352
#define CS2_OP_CC_SETOPTKEYRATE 1353
#define CS2_OP_CC_SETOPKEYIGNOREHELD 1354
#define CS2_OP_CC_SETOPTKEYIGNOREHELD 1355
#define CS2_OP_CC_SETONCLICK 1400
#define CS2_OP_CC_SETONHOLD 1401
#define CS2_OP_CC_SETONRELEASE 1402
#define CS2_OP_CC_SETONMOUSEOVER 1403
#define CS2_OP_CC_SETONMOUSELEAVE 1404
#define CS2_OP_CC_SETONDRAG 1405
#define CS2_OP_CC_SETONTARGETLEAVE 1406
#define CS2_OP_CC_SETONVARTRANSMIT 1407
#define CS2_OP_CC_SETONTIMER 1408
#define CS2_OP_CC_SETONOP 1409
#define CS2_OP_CC_SETONDRAGCOMPLETE 1410
#define CS2_OP_CC_SETONCLICKREPEAT 1411
#define CS2_OP_CC_SETONMOUSEREPEAT 1412
/* CC_SETONINVTRANSMIT — Register inv-transmit script on active child.
 * operand: script id
 * int stack in:   -
 * str stack in:   -
 * int stack out:  -
 * str stack out:  -
 * notes: signature args on stack
 */
#define CS2_OP_CC_SETONINVTRANSMIT 1414
#define CS2_OP_CC_SETONSTATTRANSMIT 1415
#define CS2_OP_CC_SETONTARGETENTER 1416
#define CS2_OP_CC_SETONSCROLLWHEEL 1417
#define CS2_OP_CC_SETONCHATTRANSMIT 1418
#define CS2_OP_CC_SETONKEY 1419
#define CS2_OP_CC_SETONFRIENDTRANSMIT 1420
#define CS2_OP_CC_SETONCLANTRANSMIT 1421
#define CS2_OP_CC_SETONMISCTRANSMIT 1422
#define CS2_OP_CC_SETONDIALOGABORT 1423
#define CS2_OP_CC_SETONSUBCHANGE 1424
#define CS2_OP_CC_SETONSTOCKTRANSMIT 1425
#define CS2_OP__1426 1426
#define CS2_OP_CC_SETONRESIZE 1427
#define CS2_OP_CC_SETONCLANSETTINGSTRANSMIT 1428
#define CS2_OP_CC_SETONCLANCHANNELTRANSMIT 1429
/* CC_GETX — Get relative X of active child.
 * int stack in:   -
 * str stack in:   -
 * int stack out:  x
 * str stack out:  -
 */
#define CS2_OP_CC_GETX 1500
/* CC_GETY — Get relative Y of active child.
 * int stack in:   -
 * str stack in:   -
 * int stack out:  y
 * str stack out:  -
 */
#define CS2_OP_CC_GETY 1501
/* CC_GETWIDTH — Get layout width.
 * int stack in:   -    
 * str stack in:   -    
 * int stack out:  width
 * str stack out:  -    
 */
#define CS2_OP_CC_GETWIDTH 1502
/* CC_GETHEIGHT — Get layout height.
 * int stack in:   -     
 * str stack in:   -     
 * int stack out:  height
 * str stack out:  -     
 */
#define CS2_OP_CC_GETHEIGHT 1503
/* CC_GETHIDE — Get hidden flag.
 * int stack in:   -             
 * str stack in:   -             
 * int stack out:  hidden ? 1 : 0
 * str stack out:  -             
 */
#define CS2_OP_CC_GETHIDE 1504
/* CC_GETLAYER — Get parent component id.
 * int stack in:   -        
 * str stack in:   -        
 * int stack out:  parent_id
 * str stack out:  -        
 */
#define CS2_OP_CC_GETLAYER 1505
/* CC_GETSCROLLX — Get scroll X (stub).
 * int stack in:   -
 * str stack in:   -
 * int stack out:  0
 * str stack out:  -
 */
#define CS2_OP_CC_GETSCROLLX 1600
/* CC_GETSCROLLY — Get scroll Y (stub).
 * int stack in:   -
 * str stack in:   -
 * int stack out:  0
 * str stack out:  -
 */
#define CS2_OP_CC_GETSCROLLY 1601
/* CC_GETTEXT — Get text.
 * int stack in:   -   
 * str stack in:   -   
 * int stack out:  -   
 * str stack out:  text
 */
#define CS2_OP_CC_GETTEXT 1602
/* CC_GETSCROLLWIDTH — Get scroll content width.
 * int stack in:   -           
 * str stack in:   -           
 * int stack out:  scroll_width
 * str stack out:  -           
 */
#define CS2_OP_CC_GETSCROLLWIDTH 1603
/* CC_GETSCROLLHEIGHT — Get scroll content height.
 * int stack in:   -            
 * str stack in:   -            
 * int stack out:  scroll_height
 * str stack out:  -            
 */
#define CS2_OP_CC_GETSCROLLHEIGHT 1604
#define CS2_OP_CC_GETMODELZOOM 1605
#define CS2_OP_CC_GETMODELANGLE_X 1606
#define CS2_OP_CC_GETMODELANGLE_Z 1607
#define CS2_OP_CC_GETMODELANGLE_Y 1608
#define CS2_OP_CC_GETTRANS 1609
#define CS2_OP__1610 1610
#define CS2_OP_CC_GETCOLOUR 1611
#define CS2_OP_CC_GETFILLCOLOUR 1612
#define CS2_OP__1613 1613
#define CS2_OP_CC_GETMODELTRANSPARENT 1614
#define CS2_OP__1615 1615
#define CS2_OP__1616 1616
#define CS2_OP_CC_GETINVOBJECT 1700
#define CS2_OP_CC_GETINVCOUNT 1701
/* CC_GETID — Get active component id.
 * int stack in:   -               
 * str stack in:   -               
 * int stack out:  active_component
 * str stack out:  -               
 */
#define CS2_OP_CC_GETID 1702
#define CS2_OP_CC_GETTARGETMASK 1800
/* CC_GETOP — Get op text.
 * int stack in:   op_index
 * str stack in:   -       
 * int stack out:  -       
 * str stack out:  op text 
 */
#define CS2_OP_CC_GETOP 1801
/* CC_GETOPBASE — Get op base text.
 * int stack in:   -      
 * str stack in:   -      
 * int stack out:  -      
 * str stack out:  op_base
 */
#define CS2_OP_CC_GETOPBASE 1802
#define CS2_OP_CC_CALLONRESIZE 1927
#define CS2_OP_CC_TRIGGEROP 1928
/* IF_SETPOSITION — Set position.
 * int stack in:   x, y, x_mode, y_mode, component  (component = top)
 * str stack in:   -                              
 * int stack out:  -                              
 * str stack out:  -                              
 */
#define CS2_OP_IF_SETPOSITION 2000
/* IF_SETSIZE — Set size.
 * int stack in:   width, height, width_mode, height_mode, component  (component = top)
 * str stack in:   -                                                
 * int stack out:  -                                                
 * str stack out:  -                                                
 */
#define CS2_OP_IF_SETSIZE 2001
/* IF_SETHIDE — Set hidden.
 * int stack in:   component, hide  (hide = top)
 * str stack in:   -              
 * int stack out:  -              
 * str stack out:  -              
 */
#define CS2_OP_IF_SETHIDE 2003
/* IF_SETNOCLICKTHROUGH — Set no-click-through.
 * int stack in:   component, enabled  (enabled = top)
 * str stack in:   -                 
 * int stack out:  -                 
 * str stack out:  -                 
 */
#define CS2_OP_IF_SETNOCLICKTHROUGH 2005
#define CS2_OP_IF_SETNOSCROLLTHROUGH 2006
/* IF_SETSCROLLPOS — Set scroll position (stub).
 * int stack in:   component, scroll_x, scroll_y  (scroll_y = top)
 * str stack in:   -                            
 * int stack out:  -                            
 * str stack out:  -                            
 */
#define CS2_OP_IF_SETSCROLLPOS 2100
/* IF_SETCOLOUR — Set colour.
 * int stack in:   component, colour  (colour = top)
 * str stack in:   -                
 * int stack out:  -                
 * str stack out:  -                
 */
#define CS2_OP_IF_SETCOLOUR 2101
/* IF_SETFILL — Set fill.
 * int stack in:   component, filled  (filled = top)
 * str stack in:   -                
 * int stack out:  -                
 * str stack out:  -                
 */
#define CS2_OP_IF_SETFILL 2102
/* IF_SETTRANS — Set transparency.
 * int stack in:   component, trans  (trans = top)
 * str stack in:   -               
 * int stack out:  -               
 * str stack out:  -               
 */
#define CS2_OP_IF_SETTRANS 2103
#define CS2_OP_IF_SETLINEWID 2104
/* IF_SETGRAPHIC — Set graphic.
 * int stack in:   component, graphic_id  (graphic_id = top)
 * str stack in:   -                    
 * int stack out:  -                    
 * str stack out:  -                    
 */
#define CS2_OP_IF_SETGRAPHIC 2105
#define CS2_OP_IF_SET2DANGLE 2106
#define CS2_OP_IF_SETTILING 2107
/* IF_SETMODEL — Set model id.
 * int stack in:   model_id, component  (component = top)
 * str stack in:   -                  
 * int stack out:  -                  
 * str stack out:  -                  
 */
#define CS2_OP_IF_SETMODEL 2108
#define CS2_OP_IF_SETMODELANGLE 2109
#define CS2_OP_IF_SETMODELANIM 2110
#define CS2_OP_IF_SETMODELORTHOG 2111
/* IF_SETTEXT — Set text.
 * int stack in:   component
 * str stack in:   text     
 * int stack out:  -        
 * str stack out:  -        
 */
#define CS2_OP_IF_SETTEXT 2112
/* IF_SETTEXTFONT — Set font.
 * int stack in:   component, font_id  (font_id = top)
 * str stack in:   -                 
 * int stack out:  -                 
 * str stack out:  -                 
 */
#define CS2_OP_IF_SETTEXTFONT 2113
/* IF_SETTEXTALIGN — Set text alignment.
 * int stack in:   x_align, y_align, line_height, component  (component = top)
 * str stack in:   -                                       
 * int stack out:  -                                       
 * str stack out:  -                                       
 */
#define CS2_OP_IF_SETTEXTALIGN 2114
/* IF_SETTEXTSHADOW — Set text shadow.
 * int stack in:   component, shadow  (shadow = top)
 * str stack in:   -                
 * int stack out:  -                
 * str stack out:  -                
 */
#define CS2_OP_IF_SETTEXTSHADOW 2115
#define CS2_OP_IF_SETOUTLINE 2116
#define CS2_OP_IF_SETGRAPHICSHADOW 2117
#define CS2_OP_IF_SETVFLIP 2118
#define CS2_OP_IF_SETHFLIP 2119
/* IF_SETSCROLLSIZE — Set scroll size.
 * int stack in:   component, scroll_w, scroll_h  (scroll_h = top)
 * str stack in:   -                            
 * int stack out:  -                            
 * str stack out:  -                            
 */
#define CS2_OP_IF_SETSCROLLSIZE 2120
#define CS2_OP_IF_RESUME_PAUSEBUTTON 2121
#define CS2_OP__2122 2122
#define CS2_OP_IF_SETFILLCOLOUR 2123
#define CS2_OP__2124 2124
#define CS2_OP__2125 2125
#define CS2_OP_IF_SETLINEDIRECTION 2126
/* IF_SETMODELTRANSPARENT — Set model transparency.
 * int stack in:   transparent, component  (component = top)
 * str stack in:   -                     
 * int stack out:  -                     
 * str stack out:  -                     
 */
#define CS2_OP_IF_SETMODELTRANSPARENT 2127
#define CS2_OP__2128 2128
/* IF_SETOBJECT — Set object icon.
 * int stack in:   obj_id, obj_count, component  (component = top)
 * str stack in:   -                           
 * int stack out:  -                           
 * str stack out:  -                           
 */
#define CS2_OP_IF_SETOBJECT 2200
#define CS2_OP_IF_SETNPCHEAD 2201
#define CS2_OP_IF_SETPLAYERHEAD_SELF 2202
/* IF_SETOBJECT_NONUM — Set object icon without qty.
 * int stack in:   obj_id, obj_count, component  (component = top)
 * str stack in:   -                           
 * int stack out:  -                           
 * str stack out:  -                           
 */
#define CS2_OP_IF_SETOBJECT_NONUM 2205
/* IF_SETOBJECT_ALWAYS_NUM — Set object icon always showing qty.
 * int stack in:   obj_id, obj_count, component  (component = top)
 * str stack in:   -                           
 * int stack out:  -                           
 * str stack out:  -                           
 */
#define CS2_OP_IF_SETOBJECT_ALWAYS_NUM 2212
/* IF_SETOP — Set op text.
 * int stack in:   index, component  (component = top)
 * str stack in:   text            
 * int stack out:  -               
 * str stack out:  -               
 */
#define CS2_OP_IF_SETOP 2300
/* IF_SETDRAGGABLE — Set draggable.
 * int stack in:   component, parent_uid, child_index  (child_index = top)
 * str stack in:   -                                 
 * int stack out:  -                                 
 * str stack out:  -                                 
 */
#define CS2_OP_IF_SETDRAGGABLE 2301
/* IF_SETDRAGGABLEBEHAVIOR — Set drag behavior.
 * int stack in:   component, behavior  (behavior = top)
 * str stack in:   -                  
 * int stack out:  -                  
 * str stack out:  -                  
 */
#define CS2_OP_IF_SETDRAGGABLEBEHAVIOR 2302
/* IF_SETDRAGDEADZONE — Set drag dead zone.
 * int stack in:   component, zone  (zone = top)
 * str stack in:   -              
 * int stack out:  -              
 * str stack out:  -              
 */
#define CS2_OP_IF_SETDRAGDEADZONE 2303
/* IF_SETDRAGDEADTIME — Set drag dead time.
 * int stack in:   component, time  (time = top)
 * str stack in:   -              
 * int stack out:  -              
 * str stack out:  -              
 */
#define CS2_OP_IF_SETDRAGDEADTIME 2304
/* IF_SETOPBASE — Set op base.
 * int stack in:   component
 * str stack in:   text     
 * int stack out:  -        
 * str stack out:  -        
 */
#define CS2_OP_IF_SETOPBASE 2305
/* IF_SETTARGETVERB — Set target verb (stub).
 * int stack in:   component
 * str stack in:   text     
 * int stack out:  -        
 * str stack out:  -        
 */
#define CS2_OP_IF_SETTARGETVERB 2306
/* IF_CLEAROPS — Clear ops.
 * int stack in:   component
 * str stack in:   -        
 * int stack out:  -        
 * str stack out:  -        
 */
#define CS2_OP_IF_CLEAROPS 2307
#define CS2_OP__2308 2308
#define CS2_OP__2309 2309
#define CS2_OP_IF_SETOPKEY 2350
#define CS2_OP_IF_SETOPTKEY 2351
#define CS2_OP_IF_SETOPKEYRATE 2352
#define CS2_OP_IF_SETOPTKEYRATE 2353
#define CS2_OP_IF_SETOPKEYIGNOREHELD 2354
#define CS2_OP_IF_SETOPTKEYIGNOREHELD 2355
#define CS2_OP_IF_SETONCLICK 2400
#define CS2_OP_IF_SETONHOLD 2401
#define CS2_OP_IF_SETONRELEASE 2402
#define CS2_OP_IF_SETONMOUSEOVER 2403
#define CS2_OP_IF_SETONMOUSELEAVE 2404
#define CS2_OP_IF_SETONDRAG 2405
#define CS2_OP_IF_SETONTARGETLEAVE 2406
#define CS2_OP_IF_SETONVARTRANSMIT 2407
#define CS2_OP_IF_SETONTIMER 2408
#define CS2_OP_IF_SETONOP 2409
#define CS2_OP_IF_SETONDRAGCOMPLETE 2410
#define CS2_OP_IF_SETONCLICKREPEAT 2411
#define CS2_OP_IF_SETONMOUSEREPEAT 2412
/* IF_SETONINVTRANSMIT — Register inv-transmit script.
 * operand: script id
 * int stack in:   component
 * str stack in:   -        
 * int stack out:  -        
 * str stack out:  -        
 * notes: signature args on stack
 */
#define CS2_OP_IF_SETONINVTRANSMIT 2414
#define CS2_OP_IF_SETONSTATTRANSMIT 2415
#define CS2_OP_IF_SETONTARGETENTER 2416
#define CS2_OP_IF_SETONSCROLLWHEEL 2417
#define CS2_OP_IF_SETONCHATTRANSMIT 2418
#define CS2_OP_IF_SETONKEY 2419
#define CS2_OP_IF_SETONFRIENDTRANSMIT 2420
#define CS2_OP_IF_SETONCLANTRANSMIT 2421
#define CS2_OP_IF_SETONMISCTRANSMIT 2422
#define CS2_OP_IF_SETONDIALOGABORT 2423
#define CS2_OP_IF_SETONSUBCHANGE 2424
#define CS2_OP_IF_SETONSTOCKTRANSMIT 2425
#define CS2_OP__2426 2426
#define CS2_OP_IF_SETONRESIZE 2427
#define CS2_OP_IF_SETONCLANSETTINGSTRANSMIT 2428
#define CS2_OP_IF_SETONCLANCHANNELTRANSMIT 2429
/* IF_GETX — Get relative X.
 * int stack in:   component
 * str stack in:   -        
 * int stack out:  x        
 * str stack out:  -        
 */
#define CS2_OP_IF_GETX 2500
/* IF_GETY — Get relative Y.
 * int stack in:   component
 * str stack in:   -        
 * int stack out:  y        
 * str stack out:  -        
 */
#define CS2_OP_IF_GETY 2501
/* IF_GETWIDTH — Get layout width.
 * int stack in:   component
 * str stack in:   -        
 * int stack out:  width    
 * str stack out:  -        
 */
#define CS2_OP_IF_GETWIDTH 2502
/* IF_GETHEIGHT — Get layout height.
 * int stack in:   component
 * str stack in:   -        
 * int stack out:  height   
 * str stack out:  -        
 */
#define CS2_OP_IF_GETHEIGHT 2503
/* IF_GETHIDE — Get hidden flag.
 * int stack in:   component     
 * str stack in:   -             
 * int stack out:  hidden ? 1 : 0
 * str stack out:  -             
 */
#define CS2_OP_IF_GETHIDE 2504
/* IF_GETLAYER — Get parent component id.
 * int stack in:   component
 * str stack in:   -        
 * int stack out:  parent_id
 * str stack out:  -        
 */
#define CS2_OP_IF_GETLAYER 2505
/* IF_GETSCROLLX — Get scroll X (stub).
 * int stack in:   component
 * str stack in:   -        
 * int stack out:  0        
 * str stack out:  -        
 */
#define CS2_OP_IF_GETSCROLLX 2600
/* IF_GETSCROLLY — Get scroll Y (stub).
 * int stack in:   component
 * str stack in:   -        
 * int stack out:  0        
 * str stack out:  -        
 */
#define CS2_OP_IF_GETSCROLLY 2601
/* IF_GETTEXT — Get text.
 * int stack in:   component
 * str stack in:   -        
 * int stack out:  -        
 * str stack out:  text     
 */
#define CS2_OP_IF_GETTEXT 2602
/* IF_GETSCROLLWIDTH — Get scroll content width.
 * int stack in:   component   
 * str stack in:   -           
 * int stack out:  scroll_width
 * str stack out:  -           
 */
#define CS2_OP_IF_GETSCROLLWIDTH 2603
/* IF_GETSCROLLHEIGHT — Get scroll content height.
 * int stack in:   component    
 * str stack in:   -            
 * int stack out:  scroll_height
 * str stack out:  -            
 */
#define CS2_OP_IF_GETSCROLLHEIGHT 2604
#define CS2_OP_IF_GETMODELZOOM 2605
#define CS2_OP_IF_GETMODELANGLE_X 2606
#define CS2_OP_IF_GETMODELANGLE_Z 2607
#define CS2_OP_IF_GETMODELANGLE_Y 2608
#define CS2_OP_IF_GETTRANS 2609
#define CS2_OP__2610 2610
#define CS2_OP_IF_GETCOLOUR 2611
#define CS2_OP_IF_GETFILLCOLOUR 2612
#define CS2_OP__2613 2613
#define CS2_OP_IF_GETMODELTRANSPARENT 2614
#define CS2_OP__2615 2615
#define CS2_OP__2616 2616
#define CS2_OP_IF_GETINVOBJECT 2700
#define CS2_OP_IF_GETINVCOUNT 2701
#define CS2_OP_IF_HASSUB 2702
/* IF_GETTOP — Get root component id.
 * int stack in:   -                  
 * str stack in:   -                  
 * int stack out:  top component or -1
 * str stack out:  -                  
 */
#define CS2_OP_IF_GETTOP 2706
#define CS2_OP_IF_GETTARGETMASK 2800
/* IF_GETOP — Get op text.
 * int stack in:   component, op_index  (op_index = top)
 * str stack in:   -                  
 * int stack out:  -                  
 * str stack out:  op text            
 */
#define CS2_OP_IF_GETOP 2801
/* IF_GETOPBASE — Get op base text.
 * int stack in:   component
 * str stack in:   -        
 * int stack out:  -        
 * str stack out:  op_base  
 */
#define CS2_OP_IF_GETOPBASE 2802
#define CS2_OP_IF_CALLONRESIZE 2927
#define CS2_OP_IF_TRIGGEROP 2928
#define CS2_OP_MES 3100
#define CS2_OP_ANIM 3101
#define CS2_OP_IF_CLOSE 3103
#define CS2_OP_RESUME_COUNTDIALOG 3104
#define CS2_OP_RESUME_NAMEDIALOG 3105
#define CS2_OP_RESUME_STRINGDIALOG 3106
#define CS2_OP_OPPLAYER 3107
#define CS2_OP_IF_DRAGPICKUP 3108
#define CS2_OP_CC_DRAGPICKUP 3109
#define CS2_OP_SETMOUSECAM 3110
#define CS2_OP_GETREMOVEROOFS 3111
#define CS2_OP_SETREMOVEROOFS 3112
#define CS2_OP_OPENURL 3113
#define CS2_OP_RESUME_OBJDIALOG 3115
#define CS2_OP_BUG_REPORT 3116
#define CS2_OP_SETSHIFTCLICKDROP 3117
#define CS2_OP_SETSHOWMOUSEOVERTEXT 3118
#define CS2_OP_RENDERSELF 3119
#define CS2_OP__3120 3120
#define CS2_OP__3121 3121
#define CS2_OP__3122 3122
#define CS2_OP__3123 3123
#define CS2_OP__3124 3124
#define CS2_OP_SETSHOWMOUSECROSS 3125
#define CS2_OP_SETSHOWLOADINGMESSAGES 3126
#define CS2_OP_SETTAPTODROP 3127
#define CS2_OP_GETTAPTODROP 3128
#define CS2_OP__3129 3129
#define CS2_OP__3130 3130
#define CS2_OP__3131 3131
#define CS2_OP_GETCANVASSIZE 3132
#define CS2_OP_MOBILE_SETFPS 3133
#define CS2_OP_MOBILE_OPENSTORE 3134
#define CS2_OP_MOBILE_OPENSTORECATEGORY 3135
#define CS2_OP__3136 3136
#define CS2_OP__3137 3137
#define CS2_OP__3138 3138
#define CS2_OP__3139 3139
#define CS2_OP__3140 3140
#define CS2_OP_SETHIDEUSERNAME 3141
#define CS2_OP_GETHIDEUSERNAME 3142
#define CS2_OP_SETREMEMBERUSERNAME 3143
#define CS2_OP_GETREMEMBERUSERNAME 3144
#define CS2_OP_SHOW_IOS_REVIEW 3145
#define CS2_OP__3157 3157
#define CS2_OP_SETBRIGHTNESS 3181
#define CS2_OP_GETBRIGHTNESS 3182
#define CS2_OP_SETANTIDRAG 3183
#define CS2_OP__3184 3184
#define CS2_OP_SOUND_SYNTH 3200
#define CS2_OP_SOUND_SONG 3201
#define CS2_OP_SOUND_JINGLE 3202
#define CS2_OP_SETVOLUMEMUSIC 3203
#define CS2_OP_GETVOLUMEMUSIC 3204
#define CS2_OP_SETVOLUMESOUNDS 3205
#define CS2_OP_GETVOLUMESOUNDS 3206
#define CS2_OP_SETVOLUMEAREASOUNDS 3207
#define CS2_OP_GETVOLUMEAREASOUNDS 3208
#define CS2_OP__3209 3209
#define CS2_OP__3210 3210
/* CLIENTCLOCK — Get client tick counter.
 * int stack in:   -          
 * str stack in:   -          
 * int stack out:  clock_ticks
 * str stack out:  -          
 */
#define CS2_OP_CLIENTCLOCK 3300
/* INV_GETOBJ — Get inventory item id.
 * int stack in:   inv_id, slot           (slot = top)
 * str stack in:   -                    
 * int stack out:  obj_id or -1 if empty
 * str stack out:  -                    
 */
#define CS2_OP_INV_GETOBJ 3301
/* INV_GETNUM — Get inventory stack size.
 * int stack in:   inv_id, slot  (slot = top)
 * str stack in:   -           
 * int stack out:  count       
 * str stack out:  -           
 */
#define CS2_OP_INV_GETNUM 3302
/* INV_TOTAL — Count item across inventory.
 * int stack in:   inv_id, item_id  (item_id = top)
 * str stack in:   -              
 * int stack out:  total qty      
 * str stack out:  -              
 */
#define CS2_OP_INV_TOTAL 3303
/* INV_SIZE — Get inventory capacity.
 * int stack in:   inv_id    
 * str stack in:   -         
 * int stack out:  slot_count
 * str stack out:  -         
 */
#define CS2_OP_INV_SIZE 3304
#define CS2_OP_STAT 3305
#define CS2_OP_STAT_BASE 3306
#define CS2_OP_STAT_XP 3307
/* COORD — Get player coord packed (stub).
 * int stack in:   -
 * str stack in:   -
 * int stack out:  0
 * str stack out:  -
 */
#define CS2_OP_COORD 3308
/* COORDX — Extract X from packed coord.
 * int stack in:   packed                 
 * str stack in:   -                      
 * int stack out:  (packed >> 14) & 0x3FFF
 * str stack out:  -                      
 */
#define CS2_OP_COORDX 3309
#define CS2_OP_COORDY 3310
#define CS2_OP_COORDZ 3311
/* MAP_MEMBERS — Is members world (stub).
 * int stack in:   -
 * str stack in:   -
 * int stack out:  1
 * str stack out:  -
 */
#define CS2_OP_MAP_MEMBERS 3312
#define CS2_OP_INVOTHER_GETOBJ 3313
#define CS2_OP_INVOTHER_GETNUM 3314
#define CS2_OP_INVOTHER_TOTAL 3315
#define CS2_OP_STAFFMODLEVEL 3316
#define CS2_OP_REBOOTTIMER 3317
/* MAP_WORLD — Get world id (stub).
 * int stack in:   -  
 * str stack in:   -  
 * int stack out:  301
 * str stack out:  -  
 */
#define CS2_OP_MAP_WORLD 3318
#define CS2_OP_RUNENERGY_VISIBLE 3321
/* RUNWEIGHT_VISIBLE — Get visible player weight.
 * int stack in:   -                    
 * str stack in:   -                    
 * int stack out:  weight kg (0 default)
 * str stack out:  -                    
 */
#define CS2_OP_RUNWEIGHT_VISIBLE 3322
#define CS2_OP_PLAYERMOD 3323
#define CS2_OP_WORLDFLAGS 3324
#define CS2_OP_MOVECOORD 3325
#define CS2_OP_MOUSE_GETX 3326
#define CS2_OP_MOUSE_GETY 3327
#define CS2_OP__3330 3330
#define CS2_OP_ENUM_STRING 3400
/* ENUM — Enum lookup.
 * int stack in:   input_type, output_type, enum_id, key  (key = top)
 * str stack in:   -                                    
 * int stack out:  mapped value or -1                   
 * str stack out:  -                                    
 */
#define CS2_OP_ENUM 3408
/* ENUM_GETOUTPUTCOUNT — Get enum output count.
 * int stack in:   enum_id
 * str stack in:   -      
 * int stack out:  count  
 * str stack out:  -      
 */
#define CS2_OP_ENUM_GETOUTPUTCOUNT 3411
#define CS2_OP_FRIEND_COUNT 3600
#define CS2_OP_FRIEND_GETNAME 3601
#define CS2_OP_FRIEND_GETWORLD 3602
#define CS2_OP_FRIEND_GETRANK 3603
#define CS2_OP_FRIEND_SETRANK 3604
#define CS2_OP_FRIEND_ADD 3605
#define CS2_OP_FRIEND_DEL 3606
#define CS2_OP_IGNORE_ADD 3607
#define CS2_OP_IGNORE_DEL 3608
#define CS2_OP_FRIEND_TEST 3609
#define CS2_OP_CLAN_GETCHATDISPLAYNAME 3611
#define CS2_OP_CLAN_GETCHATCOUNT 3612
#define CS2_OP_CLAN_GETCHATUSERNAME 3613
#define CS2_OP_CLAN_GETCHATUSERWORLD 3614
#define CS2_OP_CLAN_GETCHATUSERRANK 3615
#define CS2_OP_CLAN_GETCHATMINKICK 3616
#define CS2_OP_CLAN_KICKUSER 3617
#define CS2_OP_CLAN_GETCHATRANK 3618
#define CS2_OP_CLAN_JOINCHAT 3619
#define CS2_OP_CLAN_LEAVECHAT 3620
#define CS2_OP_IGNORE_COUNT 3621
#define CS2_OP_IGNORE_GETNAME 3622
#define CS2_OP_IGNORE_TEST 3623
#define CS2_OP_CLAN_ISSELF 3624
#define CS2_OP_CLAN_GETCHATOWNERNAME 3625
#define CS2_OP_CLAN_ISFRIEND 3626
#define CS2_OP_CLAN_ISIGNORE 3627
#define CS2_OP__3628 3628
#define CS2_OP__3629 3629
#define CS2_OP__3630 3630
#define CS2_OP__3631 3631
#define CS2_OP__3632 3632
#define CS2_OP__3633 3633
#define CS2_OP__3634 3634
#define CS2_OP__3635 3635
#define CS2_OP__3636 3636
#define CS2_OP__3637 3637
#define CS2_OP__3638 3638
#define CS2_OP__3639 3639
#define CS2_OP__3640 3640
#define CS2_OP__3641 3641
#define CS2_OP__3642 3642
#define CS2_OP__3643 3643
#define CS2_OP__3644 3644
#define CS2_OP__3645 3645
#define CS2_OP__3646 3646
#define CS2_OP__3647 3647
#define CS2_OP__3648 3648
#define CS2_OP__3649 3649
#define CS2_OP__3650 3650
#define CS2_OP__3651 3651
#define CS2_OP__3652 3652
#define CS2_OP__3653 3653
#define CS2_OP__3654 3654
#define CS2_OP__3655 3655
#define CS2_OP__3656 3656
#define CS2_OP__3657 3657
#define CS2_OP__3700 3700
#define CS2_OP__3701 3701
#define CS2_OP__3702 3702
#define CS2_OP_ACTIVECLANSETTINGS_FIND_LISTENED 3800
#define CS2_OP_ACTIVECLANSETTINGS_FIND_AFFINED 3801
#define CS2_OP_ACTIVECLANSETTINGS_GETCLANNAME 3802
#define CS2_OP_ACTIVECLANSETTINGS_GETALLOWUNAFFINED 3803
#define CS2_OP_ACTIVECLANSETTINGS_GETRANKTALK 3804
#define CS2_OP_ACTIVECLANSETTINGS_GETRANKKICK 3805
#define CS2_OP_ACTIVECLANSETTINGS_GETRANKLOOTSHARE 3806
#define CS2_OP_ACTIVECLANSETTINGS_GETCOINSHARE 3807
#define CS2_OP_ACTIVECLANSETTINGS_GETAFFINEDCOUNT 3809
#define CS2_OP_ACTIVECLANSETTINGS_GETAFFINEDDISPLAYNAME 3810
#define CS2_OP_ACTIVECLANSETTINGS_GETAFFINEDRANK 3811
#define CS2_OP_ACTIVECLANSETTINGS_GETBANNEDCOUNT 3812
#define CS2_OP_ACTIVECLANSETTINGS_GETBANNEDDISPLAYNAME 3813
#define CS2_OP_ACTIVECLANSETTINGS_GETAFFINEDEXTRAINFO 3814
#define CS2_OP_ACTIVECLANSETTINGS_GETCURRENTOWNER_SLOT 3815
#define CS2_OP_ACTIVECLANSETTINGS_GETREPLACEMENTOWNER_SLOT 3816
#define CS2_OP_ACTIVECLANSETTINGS_GETAFFINEDSLOT 3817
#define CS2_OP_ACTIVECLANSETTINGS_GETSORTEDAFFINEDSLOT 3818
#define CS2_OP_AFFINEDCLANSETTINGS_ADDBANNED_FROMCHANNEL 3819
#define CS2_OP_ACTIVECLANSETTINGS_GETAFFINEDJOINRUNEDAY 3820
#define CS2_OP_AFFINEDCLANSETTINGS_SETMUTED_FROMCHANNEL 3821
#define CS2_OP_ACTIVECLANSETTINGS_GETAFFINEDMUTED 3822
#define CS2_OP_ACTIVECLANCHANNEL_FIND_LISTENED 3850
#define CS2_OP_ACTIVECLANCHANNEL_FIND_AFFINED 3851
#define CS2_OP_ACTIVECLANCHANNEL_GETCLANNAME 3852
#define CS2_OP_ACTIVECLANCHANNEL_GETRANKKICK 3853
#define CS2_OP_ACTIVECLANCHANNEL_GETRANKTALK 3854
#define CS2_OP_ACTIVECLANCHANNEL_GETUSERCOUNT 3855
#define CS2_OP_ACTIVECLANCHANNEL_GETUSERDISPLAYNAME 3856
#define CS2_OP_ACTIVECLANCHANNEL_GETUSERRANK 3857
#define CS2_OP_ACTIVECLANCHANNEL_GETUSERWORLD 3858
#define CS2_OP_ACTIVECLANCHANNEL_KICKUSER 3859
#define CS2_OP_ACTIVECLANCHANNEL_GETUSERSLOT 3860
#define CS2_OP_ACTIVECLANCHANNEL_GETSORTEDUSERSLOT 3861
#define CS2_OP_CLANPROFILE_FIND 3890
#define CS2_OP_STOCKMARKET_GETOFFERTYPE 3903
#define CS2_OP_STOCKMARKET_GETOFFERITEM 3904
#define CS2_OP_STOCKMARKET_GETOFFERPRICE 3905
#define CS2_OP_STOCKMARKET_GETOFFERCOUNT 3906
#define CS2_OP_STOCKMARKET_GETOFFERCOMPLETEDCOUNT 3907
#define CS2_OP_STOCKMARKET_GETOFFERCOMPLETEDGOLD 3908
#define CS2_OP_STOCKMARKET_ISOFFEREMPTY 3910
#define CS2_OP_STOCKMARKET_ISOFFERSTABLE 3911
#define CS2_OP_STOCKMARKET_ISOFFERFINISHED 3912
#define CS2_OP_STOCKMARKET_ISOFFERADDING 3913
#define CS2_OP_TRADINGPOST_SORTBY_NAME 3914
#define CS2_OP_TRADINGPOST_SORTBY_PRICE 3915
#define CS2_OP_TRADINGPOST_SORTFILTERBY_WORLD 3916
#define CS2_OP_TRADINGPOST_SORTBY_AGE 3917
#define CS2_OP_TRADINGPOST_SORTBY_COUNT 3918
#define CS2_OP_TRADINGPOST_GETTOTALOFFERS 3919
#define CS2_OP_TRADINGPOST_GETOFFERWORLD 3920
#define CS2_OP_TRADINGPOST_GETOFFERNAME 3921
#define CS2_OP_TRADINGPOST_GETOFFERPREVIOUSNAME 3922
#define CS2_OP_TRADINGPOST_GETOFFERAGE 3923
#define CS2_OP_TRADINGPOST_GETOFFERCOUNT 3924
#define CS2_OP_TRADINGPOST_GETOFFERPRICE 3925
#define CS2_OP_TRADINGPOST_GETOFFERITEM 3926
/* ADD — Integer add.
 * int stack in:   a, b   (b = top)
 * str stack in:   -    
 * int stack out:  a + b
 * str stack out:  -    
 */
#define CS2_OP_ADD 4000
/* SUB — Integer subtract.
 * int stack in:   a, b   (b = top)
 * str stack in:   -    
 * int stack out:  a - b
 * str stack out:  -    
 */
#define CS2_OP_SUB 4001
/* MULTIPLY — Integer multiply.
 * int stack in:   a, b   (b = top)
 * str stack in:   -    
 * int stack out:  a * b
 * str stack out:  -    
 */
#define CS2_OP_MULTIPLY 4002
/* DIV — Integer divide.
 * int stack in:   a, b   (b = top)
 * str stack in:   -    
 * int stack out:  a / b
 * str stack out:  -    
 * notes: 0 if b == 0
 */
#define CS2_OP_DIV 4003
#define CS2_OP_RANDOM 4004
/* RANDOMINC — Random inclusive.
 * int stack in:   max               
 * str stack in:   -                 
 * int stack out:  rand() % (max + 1)
 * str stack out:  -                 
 */
#define CS2_OP_RANDOMINC 4005
/* INTERPOLATE — Linear interpolate.
 * int stack in:   a, b, c, d, e                    (e = top)
 * str stack in:   -                              
 * int stack out:  a + (b - a) * (e - c) / (d - c)
 * str stack out:  -                              
 */
#define CS2_OP_INTERPOLATE 4006
#define CS2_OP_ADDPERCENT 4007
/* SETBIT — Set bit in value.
 * int stack in:   value, bit          (bit = top)
 * str stack in:   -                 
 * int stack out:  value with bit set
 * str stack out:  -                 
 */
#define CS2_OP_SETBIT 4008
/* CLEARBIT — Clear bit in value.
 * int stack in:   value, bit              (bit = top)
 * str stack in:   -                     
 * int stack out:  value with bit cleared
 * str stack out:  -                     
 */
#define CS2_OP_CLEARBIT 4009
/* TESTBIT — Test bit set.
 * int stack in:   value, bit                 (bit = top)
 * str stack in:   -                        
 * int stack out:  (value & (1 << bit)) != 0
 * str stack out:  -                        
 */
#define CS2_OP_TESTBIT 4010
/* MOD — Integer modulo.
 * int stack in:   a, b   (b = top)
 * str stack in:   -    
 * int stack out:  a % b
 * str stack out:  -    
 * notes: 0 if b == 0
 */
#define CS2_OP_MOD 4011
#define CS2_OP_POW 4012
#define CS2_OP_INVPOW 4013
/* AND — Bitwise and.
 * int stack in:   a, b   (b = top)
 * str stack in:   -    
 * int stack out:  a & b
 * str stack out:  -    
 */
#define CS2_OP_AND 4014
/* OR — Bitwise or.
 * int stack in:   a, b   (b = top)
 * str stack in:   -    
 * int stack out:  a | b
 * str stack out:  -    
 */
#define CS2_OP_OR 4015
/* SCALE — Scale interpolate (c*a)/b.
 * int stack in:   a, b, c  (c = top)
 * str stack in:   -      
 * int stack out:  result 
 * str stack out:  -      
 * notes: b == 0 yields 0
 */
#define CS2_OP_SCALE 4018
#define CS2_OP_BITCOUNT 4025
#define CS2_OP_TOGGLEBIT 4026
#define CS2_OP_SETBIT_RANGE 4027
#define CS2_OP_CLEARBIT_RANGE 4028
#define CS2_OP_GETBIT_RANGE 4029
#define CS2_OP_SETBIT_RANGE_TOINT 4030
#define CS2_OP_SIN_DEG 4032
#define CS2_OP_COS_DEG 4033
#define CS2_OP__4034 4034
#define CS2_OP_ABS 4035
/* APPEND_NUM — Append int as decimal.
 * int stack in:   value       
 * str stack in:   dest        
 * int stack out:  -           
 * str stack out:  dest + value
 */
#define CS2_OP_APPEND_NUM 4100
/* APPEND — Append string.
 * int stack in:   -         
 * str stack in:   dest, src   (src = top)
 * int stack out:  -         
 * str stack out:  dest + src
 */
#define CS2_OP_APPEND 4101
/* APPEND_SIGNNUM — Append signed int.
 * int stack in:   value              
 * str stack in:   dest               
 * int stack out:  -                  
 * str stack out:  dest + signed value
 */
#define CS2_OP_APPEND_SIGNNUM 4102
#define CS2_OP_LOWERCASE 4103
#define CS2_OP_FROMDATE 4104
#define CS2_OP_TEXT_GENDER 4105
/* TOSTRING — Int to string.
 * int stack in:   value         
 * str stack in:   -             
 * int stack out:  -             
 * str stack out:  decimal string
 */
#define CS2_OP_TOSTRING 4106
#define CS2_OP_COMPARE 4107
/* PARAHEIGHT — Wrapped line count.
 * int stack in:   max_width, font_id  (font_id = top)
 * str stack in:   text              
 * int stack out:  lines             
 * str stack out:  -                 
 */
#define CS2_OP_PARAHEIGHT 4108
/* PARAWIDTH — Wrapped max line width.
 * int stack in:   max_width, font_id  (font_id = top)
 * str stack in:   text              
 * int stack out:  pixels            
 * str stack out:  -                 
 */
#define CS2_OP_PARAWIDTH 4109
#define CS2_OP_TEXT_SWITCH 4110
#define CS2_OP_ESCAPE 4111
/* APPEND_CHAR — Append char.
 * int stack in:   ch         
 * str stack in:   dest       
 * int stack out:  -          
 * str stack out:  dest + char
 */
#define CS2_OP_APPEND_CHAR 4112
#define CS2_OP_CHAR_ISPRINTABLE 4113
#define CS2_OP_CHAR_ISALPHANUMERIC 4114
#define CS2_OP_CHAR_ISALPHA 4115
#define CS2_OP_CHAR_ISNUMERIC 4116
/* STRING_LENGTH — String length.
 * int stack in:   -     
 * str stack in:   str   
 * int stack out:  strlen
 * str stack out:  -     
 */
#define CS2_OP_STRING_LENGTH 4117
#define CS2_OP_SUBSTRING 4118
#define CS2_OP_REMOVETAGS 4119
#define CS2_OP_STRING_INDEXOF_CHAR 4120
#define CS2_OP_STRING_INDEXOF_STRING 4121
#define CS2_OP_OC_NAME 4200
#define CS2_OP_OC_OP 4201
#define CS2_OP_OC_IOP 4202
#define CS2_OP_OC_COST 4203
#define CS2_OP_OC_STACKABLE 4204
#define CS2_OP_OC_CERT 4205
#define CS2_OP_OC_UNCERT 4206
#define CS2_OP_OC_MEMBERS 4207
#define CS2_OP_OC_PLACEHOLDER 4208
/* OC_UNPLACEHOLDER — Resolve placeholder item.
 * int stack in:   item_id                 
 * str stack in:   -                       
 * int stack out:  underlying id or item_id
 * str stack out:  -                       
 */
#define CS2_OP_OC_UNPLACEHOLDER 4209
#define CS2_OP_OC_FIND 4210
#define CS2_OP_OC_FINDNEXT 4211
#define CS2_OP_OC_FINDRESET 4212
#define CS2_OP_CHAT_GETFILTER_PUBLIC 5000
#define CS2_OP_CHAT_SETFILTER 5001
#define CS2_OP_CHAT_SENDABUSEREPORT 5002
#define CS2_OP_CHAT_GETHISTORY_BYTYPEANDLINE 5003
#define CS2_OP_CHAT_GETHISTORY_BYUID 5004
#define CS2_OP_CHAT_GETFILTER_PRIVATE 5005
#define CS2_OP_CHAT_SENDPUBLIC 5008
#define CS2_OP_CHAT_SENDPRIVATE 5009
#define CS2_OP_CHAT_SENDCLAN 5010
#define CS2_OP_CHAT_PLAYERNAME 5015
#define CS2_OP_CHAT_GETFILTER_TRADE 5016
#define CS2_OP_CHAT_GETHISTORYLENGTH 5017
#define CS2_OP_CHAT_GETNEXTUID 5018
#define CS2_OP_CHAT_GETPREVUID 5019
#define CS2_OP_DOCHEAT 5020
#define CS2_OP_CHAT_SETMESSAGEFILTER 5021
#define CS2_OP_CHAT_GETMESSAGEFILTER 5022
#define CS2_OP_WRITECONSOLE 5023
#define CS2_OP_CHAT_SETTIMESTAMPS 5024
#define CS2_OP_CHAT_GETTIMESTAMPS 5025
#define CS2_OP_CHAT_GETHISTORYEX_BYTYPEANDLINE 5030
#define CS2_OP_CHAT_GETHISTORYEX_BYUID 5031
#define CS2_OP_GETWINDOWMODE 5306
#define CS2_OP_SETWINDOWMODE 5307
#define CS2_OP_GETDEFAULTWINDOWMODE 5308
#define CS2_OP_SETDEFAULTWINDOWMODE 5309
#define CS2_OP__5310 5310
#define CS2_OP__5311 5311
#define CS2_OP__5312 5312
#define CS2_OP__5350 5350
#define CS2_OP__5351 5351
#define CS2_OP_CAM_FORCEANGLE 5504
#define CS2_OP_CAM_GETANGLE_XA 5505
#define CS2_OP_CAM_GETANGLE_YA 5506
#define CS2_OP_CAM_SETFOLLOWHEIGHT 5530
#define CS2_OP_CAM_GETFOLLOWHEIGHT 5531
#define CS2_OP_LOGOUT 5630
#define CS2_OP_FEDERATED_LOGIN 5631
#define CS2_OP__5632 5632
#define CS2_OP__5633 5633
#define CS2_OP_VIEWPORT_SETFOV 6200
#define CS2_OP_VIEWPORT_SETZOOM 6201
#define CS2_OP_VIEWPORT_CLAMPFOV 6202
#define CS2_OP_VIEWPORT_GETEFFECTIVESIZE 6203
#define CS2_OP_VIEWPORT_GETZOOM 6204
#define CS2_OP_VIEWPORT_GETFOV 6205
#define CS2_OP__6210 6210
#define CS2_OP__6212 6212
#define CS2_OP__6220 6220
#define CS2_OP__6221 6221
#define CS2_OP__6222 6222
#define CS2_OP__6223 6223
#define CS2_OP_WORLDLIST_FETCH 6500
#define CS2_OP_WORLDLIST_START 6501
#define CS2_OP_WORLDLIST_NEXT 6502
#define CS2_OP_WORLDLIST_SPECIFIC 6506
#define CS2_OP_WORLDLIST_SORT 6507
#define CS2_OP__6511 6511
#define CS2_OP_SETFOLLOWEROPSLOWPRIORITY 6512
#define CS2_OP_NC_PARAM 6513
#define CS2_OP_LC_PARAM 6514
#define CS2_OP_OC_PARAM 6515
/* STRUCT_PARAM — Read struct param.
 * int stack in:   struct_id, param_id   (param_id = top)
 * str stack in:   -                   
 * int stack out:  param value         
 * str stack out:  param value (string)
 * notes: pushes int or str depending on param type
 */
#define CS2_OP_STRUCT_PARAM 6516
/* ON_MOBILE — Is mobile client (stub).
 * int stack in:   -
 * str stack in:   -
 * int stack out:  0
 * str stack out:  -
 */
#define CS2_OP_ON_MOBILE 6518
/* CLIENTTYPE — Get client type (stub).
 * int stack in:   - 
 * str stack in:   - 
 * int stack out:  10
 * str stack out:  - 
 */
#define CS2_OP_CLIENTTYPE 6519
#define CS2_OP__6520 6520
#define CS2_OP_MOBILE_KEYBOARDHIDE 6521
#define CS2_OP__6522 6522
#define CS2_OP__6523 6523
#define CS2_OP_MOBILE_BATTERYLEVEL 6524
#define CS2_OP_MOBILE_BATTERYCHARGING 6525
#define CS2_OP_MOBILE_WIFIAVAILABLE 6526
#define CS2_OP__6527 6527
#define CS2_OP__6600 6600
#define CS2_OP_WORLDMAP_GETMAPNAME 6601
#define CS2_OP_WORLDMAP_SETMAP 6602
#define CS2_OP_WORLDMAP_GETZOOM 6603
#define CS2_OP_WORLDMAP_SETZOOM 6604
#define CS2_OP_WORLDMAP_ISLOADED 6605
#define CS2_OP_WORLDMAP_JUMPTODISPLAYCOORD 6606
#define CS2_OP_WORLDMAP_JUMPTODISPLAYCOORD_INSTANT 6607
#define CS2_OP_WORLDMAP_JUMPTOSOURCECOORD 6608
#define CS2_OP_WORLDMAP_JUMPTOSOURCECOORD_INSTANT 6609
#define CS2_OP_WORLDMAP_GETDISPLAYPOSITION 6610
#define CS2_OP_WORLDMAP_GETCONFIGORIGIN 6611
#define CS2_OP_WORLDMAP_GETCONFIGSIZE 6612
#define CS2_OP_WORLDMAP_GETCONFIGBOUNDS 6613
#define CS2_OP_WORLDMAP_GETCONFIGZOOM 6614
#define CS2_OP__6615 6615
#define CS2_OP_WORLDMAP_GETCURRENTMAP 6616
#define CS2_OP_WORLDMAP_GETDISPLAYCOORD 6617
#define CS2_OP__6618 6618
#define CS2_OP__6619 6619
#define CS2_OP__6620 6620
#define CS2_OP_WORLDMAP_COORDINMAP 6621
#define CS2_OP_WORLDMAP_GETSIZE 6622
#define CS2_OP__6623 6623
#define CS2_OP__6624 6624
#define CS2_OP__6625 6625
#define CS2_OP__6626 6626
#define CS2_OP__6627 6627
#define CS2_OP_WORLDMAP_PERPETUALFLASH 6628
#define CS2_OP_WORLDMAP_FLASHELEMENT 6629
#define CS2_OP_WORLDMAP_FLASHELEMENTCATEGORY 6630
#define CS2_OP_WORLDMAP_STOPCURRENTFLASHES 6631
#define CS2_OP_WORLDMAP_DISABLEELEMENTS 6632
#define CS2_OP_WORLDMAP_DISABLEELEMENT 6633
#define CS2_OP_WORLDMAP_DISABLEELEMENTCATEGORY 6634
#define CS2_OP_WORLDMAP_GETDISABLEELEMENTS 6635
#define CS2_OP_WORLDMAP_GETDISABLEELEMENT 6636
#define CS2_OP_WORLDMAP_GETDISABLEELEMENTCATEGORY 6637
#define CS2_OP__6638 6638
#define CS2_OP_WORLDMAP_LISTELEMENT_START 6639
#define CS2_OP_WORLDMAP_LISTELEMENT_NEXT 6640
#define CS2_OP_MEC_TEXT 6693
#define CS2_OP_MEC_TEXTSIZE 6694
#define CS2_OP_MEC_CATEGORY 6695
#define CS2_OP_MEC_SPRITE 6696
#define CS2_OP_WORLDMAP_ELEMENT 6697
#define CS2_OP__6698 6698
#define CS2_OP_WORLDMAP_ELEMENTCOORD 6699
#define CS2_OP__6700 6700
#define CS2_OP__6701 6701
#define CS2_OP__6702 6702
#define CS2_OP__6703 6703
#define CS2_OP__6704 6704
#define CS2_OP__6705 6705
#define CS2_OP__6706 6706
#define CS2_OP__6707 6707
#define CS2_OP__6708 6708
#define CS2_OP__6709 6709
#define CS2_OP__6750 6750
#define CS2_OP__6751 6751
#define CS2_OP__6752 6752
#define CS2_OP__6753 6753
#define CS2_OP_NC_NAME 6754
#define CS2_OP__6800 6800
#define CS2_OP__6801 6801
#define CS2_OP__6802 6802
#define CS2_OP__6850 6850
#define CS2_OP__6851 6851
#define CS2_OP__6852 6852
#define CS2_OP__6853 6853
#define CS2_OP__6900 6900
#define CS2_OP__6902 6902
#define CS2_OP__6903 6903
#define CS2_OP__6904 6904
#define CS2_OP__6905 6905
#define CS2_OP__6950 6950
#define CS2_OP__7000 7000
#define CS2_OP_HIGHLIGHT_NPC_ON 7001
#define CS2_OP_HIGHLIGHT_NPC_OFF 7002
#define CS2_OP__7003 7003
#define CS2_OP__7004 7004
#define CS2_OP__7005 7005
#define CS2_OP_HIGHLIGHT_NPCTYPE_ON 7006
#define CS2_OP_HIGHLIGHT_NPCTYPE_OFF 7007
#define CS2_OP__7008 7008
#define CS2_OP__7009 7009
#define CS2_OP__7010 7010
#define CS2_OP_HIGHLIGHT_LOC_ON 7011
#define CS2_OP_HIGHLIGHT_LOC_OFF 7012
#define CS2_OP__7013 7013
#define CS2_OP__7014 7014
#define CS2_OP__7015 7015
#define CS2_OP_HIGHLIGHT_LOCTYPE_ON 7016
#define CS2_OP_HIGHLIGHT_LOCTYPE_OFF 7017
#define CS2_OP__7018 7018
#define CS2_OP__7019 7019
#define CS2_OP__7020 7020
#define CS2_OP_HIGHLIGHT_OBJ_ON 7021
#define CS2_OP_HIGHLIGHT_OBJ_OFF 7022
#define CS2_OP__7023 7023
#define CS2_OP__7024 7024
#define CS2_OP__7025 7025
#define CS2_OP_HIGHLIGHT_OBJTYPE_ON 7026
#define CS2_OP_HIGHLIGHT_OBJTYPE_OFF 7027
#define CS2_OP__7028 7028
#define CS2_OP__7029 7029
#define CS2_OP__7030 7030
#define CS2_OP_HIGHLIGHT_PLAYER_ON 7031
#define CS2_OP_HIGHLIGHT_PLAYER_OFF 7032
#define CS2_OP__7033 7033
#define CS2_OP__7034 7034
#define CS2_OP__7035 7035
#define CS2_OP_HIGHLIGHT_TILE_ON 7036
#define CS2_OP_HIGHLIGHT_TILE_OFF 7037
#define CS2_OP__7038 7038
#define CS2_OP__7039 7039
#define CS2_OP__7100 7100
#define CS2_OP__7101 7101
#define CS2_OP__7102 7102
#define CS2_OP__7103 7103
#define CS2_OP__7104 7104
#define CS2_OP__7105 7105
#define CS2_OP__7106 7106
#define CS2_OP__7107 7107
#define CS2_OP__7108 7108
#define CS2_OP__7109 7109
#define CS2_OP__7110 7110
#define CS2_OP__7120 7120
#define CS2_OP__7121 7121
#define CS2_OP__7122 7122
#define CS2_OP__7200 7200
#define CS2_OP__7201 7201
#define CS2_OP__7202 7202
#define CS2_OP__7203 7203
#define CS2_OP__7204 7204
#define CS2_OP__7205 7205
#define CS2_OP__7206 7206
#define CS2_OP__7207 7207
#define CS2_OP__7208 7208
#define CS2_OP__7209 7209
#define CS2_OP__7210 7210
#define CS2_OP__7211 7211
#define CS2_OP__7212 7212
#define CS2_OP__7213 7213
#define CS2_OP__7214 7214
#define CS2_OP_SETMINIMAPLOCK 7250
#define CS2_OP__7252 7252

#endif
