#ifndef PACKETOUT_H
#define PACKETOUT_H

#include <stdint.h>

enum PacketOutType_LC245_2
{
    PKTOUT_LC245_2_NO_TIMEOUT = 206, // index: 6 - NXT naming

    PKTOUT_LC245_2_IDLE_TIMER = 102,    // index: 30
    PKTOUT_LC245_2_EVENT_TRACKING = 19, // index: 34

    // autogenerated as part of obfuscation process
    PKTOUT_LC245_2_ANTICHEAT_OPLOGIC1 = 87,  // index: 60
    PKTOUT_LC245_2_ANTICHEAT_OPLOGIC2 = 95,  // index: 61
    PKTOUT_LC245_2_ANTICHEAT_OPLOGIC3 = 146, // index: 62
    PKTOUT_LC245_2_ANTICHEAT_OPLOGIC4 = 186, // index: 63
    PKTOUT_LC245_2_ANTICHEAT_OPLOGIC5 = 74,  // index: 64
    PKTOUT_LC245_2_ANTICHEAT_OPLOGIC6 = 250, // index: 65
    PKTOUT_LC245_2_ANTICHEAT_OPLOGIC7 = 119, // index: 66
    PKTOUT_LC245_2_ANTICHEAT_OPLOGIC8 = 171, // index: 67
    PKTOUT_LC245_2_ANTICHEAT_OPLOGIC9 = 233, // index: 68

    // autogenerated as part of obfuscation process
    PKTOUT_LC245_2_ANTICHEAT_CYCLELOGIC1 = 136, // index: 70
    PKTOUT_LC245_2_ANTICHEAT_CYCLELOGIC2 = 223, // index: 71
    PKTOUT_LC245_2_ANTICHEAT_CYCLELOGIC3 = 181, // index: 74
    PKTOUT_LC245_2_ANTICHEAT_CYCLELOGIC4 = 94,  // index: 72
    PKTOUT_LC245_2_ANTICHEAT_CYCLELOGIC5 = 63,  // index: 75
    PKTOUT_LC245_2_ANTICHEAT_CYCLELOGIC6 = 112, // index: 73

    PKTOUT_LC245_2_OPOBJ1 = 113, // index: 80 - NXT naming
    PKTOUT_LC245_2_OPOBJ2 = 238, // index: 81 - NXT naming
    PKTOUT_LC245_2_OPOBJ3 = 55,  // index: 82 - NXT naming
    PKTOUT_LC245_2_OPOBJ4 = 17,  // index: 83 - NXT naming
    PKTOUT_LC245_2_OPOBJ5 = 247, // index: 84 - NXT naming
    PKTOUT_LC245_2_OPBJT = 122,  // index: 88 - NXT naming
    PKTOUT_LC245_2_OPOBJU = 143, // index: 89 - NXT naming

    PKTOUT_LC245_2_OPNPC1 = 180, // index: 100 - NXT naming
    PKTOUT_LC245_2_OPNPC2 = 252, // index: 101 - NXT naming
    PKTOUT_LC245_2_OPNPC3 = 196, // index: 102 - NXT naming
    PKTOUT_LC245_2_OPNPC4 = 107, // index: 103 - NXT naming
    PKTOUT_LC245_2_OPNPC5 = 43,  // index: 104 - NXT naming
    PKTOUT_LC245_2_OPNPCT = 141, // index: 108 - NXT naming
    PKTOUT_LC245_2_OPNPCU = 14,  // index: 109 - NXT naming

    PKTOUT_LC245_2_OPLOC1 = 1,   // index: 120 - NXT naming
    PKTOUT_LC245_2_OPLOC2 = 219, // index: 121 - NXT naming
    PKTOUT_LC245_2_OPLOC3 = 226, // index: 122 - NXT naming
    PKTOUT_LC245_2_OPLOC4 = 204, // index: 123 - NXT naming
    PKTOUT_LC245_2_OPLOC5 = 86,  // index: 124 - NXT naming
    PKTOUT_LC245_2_OPLOCT = 208, // index: 128 - NXT naming
    PKTOUT_LC245_2_OPLOCU = 147, // index: 129 - NXT naming

    PKTOUT_LC245_2_OPPLAYER1 = 135, // index: 140 - NXT naming
    PKTOUT_LC245_2_OPPLAYER2 = 165, // index: 141 - NXT naming
    PKTOUT_LC245_2_OPPLAYER3 = 172, // index: 142 - NXT naming
    PKTOUT_LC245_2_OPPLAYER4 = 54,  // index: 143 - NXT naming
    PKTOUT_LC245_2_OPPLAYERT = 52,  // index: 148 - NXT naming
    PKTOUT_LC245_2_OPPLAYERU = 210, // index: 149 - NXT naming

    PKTOUT_LC245_2_OPHELD1 = 104, // index: 160 - name based on runescript trigger
    PKTOUT_LC245_2_OPHELD2 = 193, // index: 161 - name based on runescript trigger
    PKTOUT_LC245_2_OPHELD3 = 115, // index: 162 - name based on runescript trigger
    PKTOUT_LC245_2_OPHELD4 = 194, // index: 163 - name based on runescript trigger
    PKTOUT_LC245_2_OPHELD5 = 9,   // index: 164 - name based on runescript trigger
    PKTOUT_LC245_2_OPHELDT = 188, // index: 168 - name based on runescript trigger
    PKTOUT_LC245_2_OPHELDU = 126, // index: 169 - name based on runescript trigger

    PKTOUT_LC245_2_INV_BUTTON1 = 13, // index: 190 - NXT has "IF_ BUTTON1" but for our interface
                                     // system, this makes more sense
    PKTOUT_LC245_2_INV_BUTTON2 =
        58, // index: 191 - NXT has "IF_BUTTON2" but for our interface system, this makes more sense
    PKTOUT_LC245_2_INV_BUTTON3 =
        48, // index: 192 - NXT has "IF_BUTTON3" but for our interface system, this makes more sense
    PKTOUT_LC245_2_INV_BUTTON4 = 183, // index: 193 - NXT has "IF_BUTTON4" but for our interface
                                      // system, this makes more sense
    PKTOUT_LC245_2_INV_BUTTON5 = 242, // index: 194 - NXT has "IF_BUTTON5" but for our interface
                                      // system, this makes more sense

    PKTOUT_LC245_2_IF_BUTTON = 177,            // index: 200 - NXT naming
    PKTOUT_LC245_2_LOGOUT = 36,                // client sends to request logout (opcode 36)
    PKTOUT_LC245_2_RESUME_PAUSEBUTTON = 239,   // index: 201 - NXT naming
    PKTOUT_LC245_2_CLOSE_MODAL = 245,          // index: 202 - NXT naming
    PKTOUT_LC245_2_RESUME_P_COUNTDIALOG = 241, // index: 203 - NXT naming
    PKTOUT_LC245_2_TUTORIAL_CLICKSIDE = 243,   // index: 204

    PKTOUT_LC245_2_MOVE_OPCLICK =
        216, // index: 242 - comes with OP packets, name based on other MOVE packets
    PKTOUT_LC245_2_REPORT_ABUSE = 205,      // index: 243
    PKTOUT_LC245_2_MOVE_MINIMAPCLICK = 198, // index: 244 - NXT naming
    PKTOUT_LC245_2_INV_BUTTOND =
        7, // index: 245 - NXT has "IF_BUTTOND" but for our interface system, this makes more sense
    PKTOUT_LC245_2_IGNORELIST_DEL = 4,    // index: 246 - NXT naming
    PKTOUT_LC245_2_IGNORELIST_ADD = 20,   // index: 247 - NXT naming
    PKTOUT_LC245_2_IF_PLAYERDESIGN = 150, // index: 248
    PKTOUT_LC245_2_CHAT_SETMODE = 8,      // index: 249 - NXT naming
    PKTOUT_LC245_2_MESSAGE_PRIVATE = 99,  // index: 250 - NXT naming
    PKTOUT_LC245_2_FRIENDLIST_DEL = 61,   // index: 251 - NXT naming
    PKTOUT_LC245_2_FRIENDLIST_ADD = 116,  // index: 252 - NXT naming
    PKTOUT_LC245_2_CLIENT_CHEAT = 11,     // index: 253 - NXT naming
    PKTOUT_LC245_2_MESSAGE_PUBLIC = 78,   // index: 254 - NXT naming
    PKTOUT_LC245_2_MOVE_GAMECLICK = 182,  // index: 255 - NXT naming
};

#endif