#ifndef PACKETIN_LC245_2_H
#define PACKETIN_LC245_2_H

#include "net/rev/pktnames.h"

#include <assert.h>
#include <stdint.h>

#ifndef PKTIN_LENGTH_VARU8
#define PKTIN_LENGTH_VARU8 (-1)
#define PKTIN_LENGTH_VARU16 (-2)
#endif

/* Wire opcodes of the Lost City rev 245_2 build (from v0). These are the
 * obfuscated per-build numbers; everything above the table keys on the
 * canonical PKT_NAME_* values instead. */
enum PacketInType_LC245_2
{
    PKTIN_LC245_2_IF_OPENCHAT = 7,
    PKTIN_LC245_2_IF_OPENMAIN_SIDE = 229,
    PKTIN_LC245_2_IF_CLOSE = 174,
    PKTIN_LC245_2_IF_SETTAB = 29,
    PKTIN_LC245_2_IF_OPENMAIN = 177,
    PKTIN_LC245_2_IF_OPENSIDE = 236,
    PKTIN_LC245_2_IF_SETTAB_ACTIVE = 8,
    PKTIN_LC245_2_IF_SETCOLOUR = 135,
    PKTIN_LC245_2_IF_SETHIDE = 225,
    PKTIN_LC245_2_IF_SETOBJECT = 153,
    PKTIN_LC245_2_IF_SETMODEL = 60,
    PKTIN_LC245_2_IF_SETANIM = 69,
    PKTIN_LC245_2_IF_SETPLAYERHEAD = 83,
    PKTIN_LC245_2_IF_SETTEXT = 32,
    PKTIN_LC245_2_IF_SETNPCHEAD = 76,
    PKTIN_LC245_2_IF_SETPOSITION = 230,
    PKTIN_LC245_2_IF_SETSCROLLPOS = 226,
    PKTIN_LC245_2_TUT_FLASH = 132,
    PKTIN_LC245_2_TUT_OPEN = 152,
    PKTIN_LC245_2_UPDATE_INV_STOP_TRANSMIT = 143,
    PKTIN_LC245_2_UPDATE_INV_FULL = 156,
    PKTIN_LC245_2_UPDATE_INV_PARTIAL = 95,
    PKTIN_LC245_2_CAM_LOOKAT = 123,
    PKTIN_LC245_2_CAM_SHAKE = 103,
    PKTIN_LC245_2_CAM_MOVETO = 86,
    PKTIN_LC245_2_CAM_RESET = 134,
    PKTIN_LC245_2_NPC_INFO = 105,
    PKTIN_LC245_2_PLAYER_INFO = 161,
    PKTIN_LC245_2_FINISH_TRACKING = 165,
    PKTIN_LC245_2_ENABLE_TRACKING = 28,
    PKTIN_LC245_2_MESSAGE_GAME = 175,
    PKTIN_LC245_2_UPDATE_IGNORELIST = 181,
    PKTIN_LC245_2_CHAT_FILTER_SETTINGS = 2,
    PKTIN_LC245_2_MESSAGE_PRIVATE = 207,
    PKTIN_LC245_2_UPDATE_FRIENDLIST = 109,
    PKTIN_LC245_2_UNSET_MAP_FLAG = 233,
    PKTIN_LC245_2_UPDATE_RUNWEIGHT = 70,
    PKTIN_LC245_2_HINT_ARROW = 243,
    PKTIN_LC245_2_UPDATE_REBOOT_TIMER = 26,
    PKTIN_LC245_2_UPDATE_STAT = 110,
    PKTIN_LC245_2_UPDATE_RUNENERGY = 208,
    PKTIN_LC245_2_RESET_ANIMS = 144,
    PKTIN_LC245_2_UPDATE_PID = 49,
    PKTIN_LC245_2_LAST_LOGIN_INFO = 238,
    PKTIN_LC245_2_LOGOUT = 36,
    PKTIN_LC245_2_P_COUNTDIALOG = 56,
    PKTIN_LC245_2_SET_MULTIWAY = 35,
    PKTIN_LC245_2_REBUILD_NORMAL = 66,
    PKTIN_LC245_2_VARP_SMALL = 192,
    PKTIN_LC245_2_VARP_LARGE = 75,
    PKTIN_LC245_2_VARP_SYNC = 25,
    PKTIN_LC245_2_SYNTH_SOUND = 209,
    PKTIN_LC245_2_MIDI_SONG = 96,
    PKTIN_LC245_2_MIDI_JINGLE = 39,
    PKTIN_LC245_2_UPDATE_ZONE_PARTIAL_FOLLOWS = 203,
    PKTIN_LC245_2_UPDATE_ZONE_FULL_FOLLOWS = 140,
    PKTIN_LC245_2_UPDATE_ZONE_PARTIAL_ENCLOSED = 15,
    // Merges a loc with a player to fix animations and drawing orders.
    PKTIN_LC245_2_LOC_MERGE = 188,
    PKTIN_LC245_2_LOC_ANIM = 71,
    PKTIN_LC245_2_OBJ_DEL = 13,
    PKTIN_LC245_2_OBJ_REVEAL = 190,
    PKTIN_LC245_2_LOC_ADD_CHANGE = 119,
    PKTIN_LC245_2_MAP_PROJANIM = 187,
    PKTIN_LC245_2_LOC_DEL = 198,
    PKTIN_LC245_2_OBJ_COUNT = 151,
    PKTIN_LC245_2_MAP_ANIM = 141,
    PKTIN_LC245_2_OBJ_ADD = 94
};

#ifndef PACKET_DEFINITION
struct PacketInDefinition
{
    int name; /* canonical GameProtoPktName */
    int code; /* wire opcode */
    int length;
};

/* Always use positional struct elements. Lookup is by scanning .code/.name (see packetin_size_*).
 * Do not use MSVC's [name] = form: MSVC C++ parses `[` as a lambda capture in this context. */
#define PACKET_DEFINITION(name, code, length) { name, code, length }
#endif

static const struct PacketInDefinition g_packet_in_definitions_lc245_2[] = {
    PACKET_DEFINITION(PKT_NAME_IF_OPENCHAT, PKTIN_LC245_2_IF_OPENCHAT, 2),
    PACKET_DEFINITION(PKT_NAME_IF_OPENMAIN_SIDE, PKTIN_LC245_2_IF_OPENMAIN_SIDE, 4),
    PACKET_DEFINITION(PKT_NAME_IF_CLOSE, PKTIN_LC245_2_IF_CLOSE, 0),
    PACKET_DEFINITION(PKT_NAME_IF_SETTAB, PKTIN_LC245_2_IF_SETTAB, 3),
    PACKET_DEFINITION(PKT_NAME_IF_OPENMAIN, PKTIN_LC245_2_IF_OPENMAIN, 2),
    PACKET_DEFINITION(PKT_NAME_IF_OPENSIDE, PKTIN_LC245_2_IF_OPENSIDE, 2),
    PACKET_DEFINITION(PKT_NAME_IF_SETTAB_ACTIVE, PKTIN_LC245_2_IF_SETTAB_ACTIVE, 1),
    PACKET_DEFINITION(PKT_NAME_IF_SETCOLOUR, PKTIN_LC245_2_IF_SETCOLOUR, 4),
    PACKET_DEFINITION(PKT_NAME_IF_SETHIDE, PKTIN_LC245_2_IF_SETHIDE, 3),
    PACKET_DEFINITION(PKT_NAME_IF_SETOBJECT, PKTIN_LC245_2_IF_SETOBJECT, 6),
    PACKET_DEFINITION(PKT_NAME_IF_SETMODEL, PKTIN_LC245_2_IF_SETMODEL, 4),
    PACKET_DEFINITION(PKT_NAME_IF_SETANIM, PKTIN_LC245_2_IF_SETANIM, 4),
    PACKET_DEFINITION(PKT_NAME_IF_SETPLAYERHEAD, PKTIN_LC245_2_IF_SETPLAYERHEAD, 2),
    PACKET_DEFINITION(PKT_NAME_IF_SETTEXT, PKTIN_LC245_2_IF_SETTEXT, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_IF_SETNPCHEAD, PKTIN_LC245_2_IF_SETNPCHEAD, 4),
    PACKET_DEFINITION(PKT_NAME_IF_SETPOSITION, PKTIN_LC245_2_IF_SETPOSITION, 6),
    PACKET_DEFINITION(PKT_NAME_IF_SETSCROLLPOS, PKTIN_LC245_2_IF_SETSCROLLPOS, 4),
    PACKET_DEFINITION(PKT_NAME_TUT_FLASH, PKTIN_LC245_2_TUT_FLASH, 1),
    PACKET_DEFINITION(PKT_NAME_TUT_OPEN, PKTIN_LC245_2_TUT_OPEN, 2),
    PACKET_DEFINITION(PKT_NAME_UPDATE_INV_STOP_TRANSMIT, PKTIN_LC245_2_UPDATE_INV_STOP_TRANSMIT, 2),
    PACKET_DEFINITION(PKT_NAME_UPDATE_INV_FULL, PKTIN_LC245_2_UPDATE_INV_FULL, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_UPDATE_INV_PARTIAL, PKTIN_LC245_2_UPDATE_INV_PARTIAL, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_CAM_LOOKAT, PKTIN_LC245_2_CAM_LOOKAT, 6),
    PACKET_DEFINITION(PKT_NAME_CAM_SHAKE, PKTIN_LC245_2_CAM_SHAKE, 4),
    PACKET_DEFINITION(PKT_NAME_CAM_MOVETO, PKTIN_LC245_2_CAM_MOVETO, 6),
    PACKET_DEFINITION(PKT_NAME_CAM_RESET, PKTIN_LC245_2_CAM_RESET, 0),
    PACKET_DEFINITION(PKT_NAME_NPC_INFO, PKTIN_LC245_2_NPC_INFO, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_PLAYER_INFO, PKTIN_LC245_2_PLAYER_INFO, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_FINISH_TRACKING, PKTIN_LC245_2_FINISH_TRACKING, 0),
    PACKET_DEFINITION(PKT_NAME_ENABLE_TRACKING, PKTIN_LC245_2_ENABLE_TRACKING, 0),
    PACKET_DEFINITION(PKT_NAME_MESSAGE_GAME, PKTIN_LC245_2_MESSAGE_GAME, PKTIN_LENGTH_VARU8),
    PACKET_DEFINITION(PKT_NAME_UPDATE_IGNORELIST, PKTIN_LC245_2_UPDATE_IGNORELIST, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_CHAT_FILTER_SETTINGS, PKTIN_LC245_2_CHAT_FILTER_SETTINGS, 3),
    PACKET_DEFINITION(PKT_NAME_MESSAGE_PRIVATE, PKTIN_LC245_2_MESSAGE_PRIVATE, PKTIN_LENGTH_VARU8),
    PACKET_DEFINITION(PKT_NAME_UPDATE_FRIENDLIST, PKTIN_LC245_2_UPDATE_FRIENDLIST, 9),
    PACKET_DEFINITION(PKT_NAME_UNSET_MAP_FLAG, PKTIN_LC245_2_UNSET_MAP_FLAG, 0),
    PACKET_DEFINITION(PKT_NAME_UPDATE_RUNWEIGHT, PKTIN_LC245_2_UPDATE_RUNWEIGHT, 2),
    PACKET_DEFINITION(PKT_NAME_HINT_ARROW, PKTIN_LC245_2_HINT_ARROW, 6),
    PACKET_DEFINITION(PKT_NAME_UPDATE_REBOOT_TIMER, PKTIN_LC245_2_UPDATE_REBOOT_TIMER, 2),
    PACKET_DEFINITION(PKT_NAME_UPDATE_STAT, PKTIN_LC245_2_UPDATE_STAT, 6),
    PACKET_DEFINITION(PKT_NAME_UPDATE_RUNENERGY, PKTIN_LC245_2_UPDATE_RUNENERGY, 1),
    PACKET_DEFINITION(PKT_NAME_RESET_ANIMS, PKTIN_LC245_2_RESET_ANIMS, 0),
    PACKET_DEFINITION(PKT_NAME_UPDATE_PID, PKTIN_LC245_2_UPDATE_PID, 3),
    PACKET_DEFINITION(PKT_NAME_LAST_LOGIN_INFO, PKTIN_LC245_2_LAST_LOGIN_INFO, 10),
    PACKET_DEFINITION(PKT_NAME_LOGOUT, PKTIN_LC245_2_LOGOUT, 0),
    PACKET_DEFINITION(PKT_NAME_P_COUNTDIALOG, PKTIN_LC245_2_P_COUNTDIALOG, 0),
    PACKET_DEFINITION(PKT_NAME_SET_MULTIWAY, PKTIN_LC245_2_SET_MULTIWAY, 1),
    PACKET_DEFINITION(PKT_NAME_REBUILD_NORMAL, PKTIN_LC245_2_REBUILD_NORMAL, 4),
    PACKET_DEFINITION(PKT_NAME_VARP_SMALL, PKTIN_LC245_2_VARP_SMALL, 3),
    PACKET_DEFINITION(PKT_NAME_VARP_LARGE, PKTIN_LC245_2_VARP_LARGE, 6),
    PACKET_DEFINITION(PKT_NAME_VARP_SYNC, PKTIN_LC245_2_VARP_SYNC, 0),
    PACKET_DEFINITION(PKT_NAME_SYNTH_SOUND, PKTIN_LC245_2_SYNTH_SOUND, 5),
    PACKET_DEFINITION(PKT_NAME_MIDI_SONG, PKTIN_LC245_2_MIDI_SONG, 2),
    PACKET_DEFINITION(PKT_NAME_MIDI_JINGLE, PKTIN_LC245_2_MIDI_JINGLE, 4),
    PACKET_DEFINITION(PKT_NAME_UPDATE_ZONE_PARTIAL_FOLLOWS, PKTIN_LC245_2_UPDATE_ZONE_PARTIAL_FOLLOWS, 2),
    PACKET_DEFINITION(PKT_NAME_UPDATE_ZONE_FULL_FOLLOWS, PKTIN_LC245_2_UPDATE_ZONE_FULL_FOLLOWS, 2),
    PACKET_DEFINITION(PKT_NAME_UPDATE_ZONE_PARTIAL_ENCLOSED, PKTIN_LC245_2_UPDATE_ZONE_PARTIAL_ENCLOSED, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_LOC_MERGE, PKTIN_LC245_2_LOC_MERGE, 14),
    PACKET_DEFINITION(PKT_NAME_LOC_ANIM, PKTIN_LC245_2_LOC_ANIM, 4),
    PACKET_DEFINITION(PKT_NAME_OBJ_DEL, PKTIN_LC245_2_OBJ_DEL, 3),
    PACKET_DEFINITION(PKT_NAME_OBJ_REVEAL, PKTIN_LC245_2_OBJ_REVEAL, 7),
    PACKET_DEFINITION(PKT_NAME_LOC_ADD_CHANGE, PKTIN_LC245_2_LOC_ADD_CHANGE, 4),
    PACKET_DEFINITION(PKT_NAME_MAP_PROJANIM, PKTIN_LC245_2_MAP_PROJANIM, 15),
    PACKET_DEFINITION(PKT_NAME_LOC_DEL, PKTIN_LC245_2_LOC_DEL, 2),
    PACKET_DEFINITION(PKT_NAME_OBJ_COUNT, PKTIN_LC245_2_OBJ_COUNT, 7),
    PACKET_DEFINITION(PKT_NAME_MAP_ANIM, PKTIN_LC245_2_MAP_ANIM, 6),
    PACKET_DEFINITION(PKT_NAME_OBJ_ADD, PKTIN_LC245_2_OBJ_ADD, 5)
};

#define PACKET_IN_DEFINITION_COUNT_LC245_2 \
    ((int)(sizeof(g_packet_in_definitions_lc245_2) / sizeof(g_packet_in_definitions_lc245_2[0])))

/** Wire opcode -> payload length (>=0 fixed, -1 var-u8, -2 var-u16). */
static inline int
packetin_size_lc245_2(int wire_opcode)
{
    assert(wire_opcode >= 0 && wire_opcode < 256);
    for( int i = 0; i < PACKET_IN_DEFINITION_COUNT_LC245_2; i++ )
    {
        if( g_packet_in_definitions_lc245_2[i].code == wire_opcode )
        {
            return g_packet_in_definitions_lc245_2[i].length;
        }
    }
    return 0;
}

/** Wire opcode -> canonical PKT_NAME_*; PKT_NAME_NONE (0) = unknown. */
static inline int
packetin_code_lc245_2(int wire_opcode)
{
    assert(wire_opcode >= 0 && wire_opcode < 256);
    for( int i = 0; i < PACKET_IN_DEFINITION_COUNT_LC245_2; i++ )
    {
        if( g_packet_in_definitions_lc245_2[i].code == wire_opcode )
        {
            return g_packet_in_definitions_lc245_2[i].name;
        }
    }
    return PKT_NAME_NONE;
}

/** Canonical PKT_NAME_* -> wire opcode; -1 = packet absent from this rev. */
static inline int
packetin_wire_lc245_2(int pkt_name)
{
    for( int i = 0; i < PACKET_IN_DEFINITION_COUNT_LC245_2; i++ )
    {
        if( g_packet_in_definitions_lc245_2[i].name == pkt_name )
        {
            return g_packet_in_definitions_lc245_2[i].code;
        }
    }
    return -1;
}

#endif
