; torirs plugin settings

[plugin:tile-indicator-c]
enabled=0
true_color=#0FF9EF
dest_color=#F9F60F
hover_color=#FEFEFD

[plugin:minimap-orbs]
enabled=1

[plugin:xp-drop-orbs]
enabled=1

[plugin:gameframe-layout]
enabled=1
layout=Modern Resizable

[plugin:entity-highlighter]
enabled=0
tags=3029,3105,3106,3108

[plugin:loot-beam]
low_value=0
high_value=100000
insane_value=100000
low_color=#65B2FB
medium_color=#99FC9B
high_color=#F9950F
insane_color=#FB65B6

[plugin:ground-items]
hidden_items=Vial, Ashes, Coins, Bucket, Jug, Seaweed
default_color=#FEFEFD
highlighted_color=#AE0EF6
hidden_color=#87807B
low_color=#65B2FB
medium_color=#99FC9B
high_color=#F9950F
insane_color=#FB65B6

[plugin:screenshot]
enabled=0
