; torirs plugin settings

[plugin:tile-indicator-c]
enabled=0
true_color=#0FF9EF
dest_color=#F9F60F
hover_color=#FEFEFD

[plugin:entity-highlighter]
tags=3029,3105,3106,3108

[plugin:loot-beam]
style=light
high_value=100000
insane_value=100000
low_color=#65B2FB
medium_color=#99FC9B
high_color=#F9950F
insane_color=#FB65B6
