-- Generated by tools/quest_gate/new_quest.py from Quest Helper's
-- helpers/quests/druidicritual/ -- docs/QUEST_SUITE_KIT.md phase 3.
-- Tier (quest_inventory.tsv): 1.
-- Items from getItemRequirements(): 4 given in setup (::give), 0 left as gather markers.
-- Setup always starts with ::clearinv: the fresh character carries fourteen
-- slots of tutorial kit that block a non-stackable requirement fitting in the backpack.
-- Rewards from Quest Helper: 1 experience, 0 item, quest points 4 (QuestPointReward).
--
-- Fixture start: fresh_lumbridge.ini stands the player at 3206,3233,0 (Lumbridge, beside
-- Hans). Every step below carries its own Quest Helper WorldPoint; the
-- FIRST emitted t.player.goto_tile is what actually leaves that tile.
--
-- Three rules the first pilot pass broke -- read before touching this file:
-- (a) "blocked" means a t.blocked("...") row followed by return -- a file
--     that runs on to expect_complete() after a failure is rejected.
-- (b) a talk_to/click answering screen_position or not_visible means you
--     are not standing near the target -- fix the goto, not the verb.
-- (c) never add a fixture or a helper file -- this quest file is the only
--     file you edit.

return {
    id = "druid",
    fixture = "fresh_lumbridge.ini",
    setup = {
        "::clearinv", -- the fixture's fourteen tutorial slots, so a requirement fits
        "::give raw_rat_meat 1",
        "::give raw_bear_meat 1",
        "::give raw_beef 1",
        "::give raw_chicken 1",
    },

    run = function(t)
        local bind_result, bind_detail = t.quest.bind({
            varp = "druidquest",
            constants = {
                complete = 4,
                given_ingredients = 3,
                not_started = 0,
                spoken_sanfew = 2,
                started = 1,
            },
            row = "quest_druidicritual",
            display = "Druidic Ritual",
            points = 4,
        })
        t.step("quest.bind", bind_result == "ok" and "PASS" or "FAIL", bind_detail)

        t.exec("goto-talkToKaqemeex", t.player.goto_tile, 2925, 3486, 0) -- first step -- leaves the fixture's start tile
        -- Talk to Kaqemeex in the Druids' Circle in Taverley.
        t.exec("talkToKaqemeex", t.player.talk_to, "kaqemeex", 1)
        t.exec("talkToKaqemeex-dialog-1", t.chat.play, {
            "player:Hello there.",
            "npc:What brings you to our holy monument?",
            "choose:I'm in search of a quest.",
        })
        t.exec("talkToKaqemeex-dialog-2", t.chat.play, {
            "player:I'm in search of a quest.",
            "npc:Hmm. I think I may have a worthwhile quest for you actually. I don't know if you are familiar with the stone circle south of Varrock or not, but...",
            "npc:That used to be OUR stone circle. Unfortunately, many many years ago, dark wizards cast a wicked spell upon it so that they could corrupt its power for their own evil ends.",
            "npc:When they cursed the rocks for their rituals they made them useless to us and our magics. We require a brave adventurer to go on a quest for us to help purify the circle of Varrock.",
            "mesbox:Start the Druidic Ritual quest?",
            "choose:Yes.",
            "mesbox:This quest is recommended for players with a combat level of 10 or above. You can still start it.",
            "choose:Yes.",
            "player:Yes.",
            "npc:Excellent. Go to the village south of this place and speak to my fellow Sanfew who is working on the purification ritual. He knows better than I what is required to complete it.",
            "player:Will do.",
        })

        t.exec("expect_stage-after-kaqemeex", t.quest.expect_stage, "started")

        -- Talk to Sanfew upstairs in the Taverley herblore store.
        t.exec("goto-talkToSanfew", t.player.goto_tile, 2899, 3429, 1) -- plane change (0 -> 1)
        -- Talk to Sanfew upstairs in the Taverley herblore store.
        t.exec("talkToSanfew", t.player.talk_to, "sanfew", 1)
        t.exec("talkToSanfew-dialog-1", t.chat.play, {
            "npc:What can I do for you young 'un?",
            "choose:I've been sent to help purify the Varrock stone circle.",
            "player:I've been sent to assist you with the ritual to purify the Varrockian stone circle.",
            "npc:Well, what I'm struggling with right now is the meats needed for the potion to honour Guthix. I need the raw meat of four different animals for it, but not just any old meats will do.",
            "npc:Each meat has to be dipped individually into the Cauldron of Thunder for it to work correctly.",
            "choose:Ok, I'll do that then.",
            "player:Ok, I'll do that then.",
            "npc:Well thank you very much!",
        })

        -- Enter Taverley Dungeon and travel to the cauldron of thunder.
        t.exec("goto-cauldron", t.player.goto_tile, 2893, 9831, 0)
        -- Use the chicken meat on the cauldron in Taverley dungeon.
        local cauldron = t.player.by_symbol("loc", "cauldron_of_thunder")
        t.exec("useChickenOnCauldron", t.player.use_on, "raw_chicken", cauldron)

        -- Use the beef meat on the cauldron in Taverley dungeon.
        t.exec("useBeefOnCauldron", t.player.use_on, "raw_beef", cauldron)

        -- Use the bear meat on the cauldron in Taverley dungeon.
        t.exec("useBearOnCauldron", t.player.use_on, "raw_bear_meat", cauldron)

        -- Use the rat meat on the cauldron in Taverley dungeon.
        t.exec("useRatOnCauldron", t.player.use_on, "raw_rat_meat", cauldron)

        -- Return to Sanfew upstairs in the Taverley herblore store with the enchanted meats.
        t.exec("goto-talkToSanfewWithMeat-upper", t.player.goto_tile, 2899, 3429, 1)
        t.exec("talkToSanfewWithMeat", t.player.talk_to, "sanfew", 1)
        t.exec("talkToSanfewWithMeat-dialog", t.chat.play, {
            "npc:Did you bring me the required ingredients for the potion?",
            "player:Yes, I have all four now!",
            "npc:Well hand 'em over then lad!",
            "npc:Thank you so much adventurer! These meats will allow our potion to honour Guthix to be completed, and bring one step closer to reclaiming our stone circle!",
            "npc:Now go and talk to Kaqemeex and he will introduce you to the wonderful world of herblore and potion making!",
        })

        t.exec("expect_stage-given_ingredients", t.quest.expect_stage, "given_ingredients")

        t.exec("goto-talkToKaqemeexToFinish", t.player.goto_tile, 2925, 3486, 0) -- plane change (1 -> 0)

        -- Reward snapshot before the FINAL hand-in step (H2, docs/QUEST_SUITE_KIT.md)
        local reward_snapshot_result, reward_before = t.skill.snapshot()
        t.step("reward.snapshot", reward_snapshot_result == "ok" and "PASS" or "FAIL", "skill.snapshot before the hand-in -> " .. tostring(reward_snapshot_result))

        -- Return to Kaqemeex in the Druids' Circle to finish the quest.
        t.exec("talkToKaqemeexToFinish", t.player.talk_to, "kaqemeex", 1)
        t.exec("talkToKaqemeexToFinish-dialog", t.chat.play, {
            "player:Hello there.",
            "npc:I have word from Sanfew that you have been very helpful in assisting him with his preparations for the purification ritual. As promised I will now teach you the ancient arts of Herblore.",
            "npc:Herblore is the skill of working with herbs and other ingredients, to make useful potions and poison.",
            "npc:First you will need a vial, which can be found or made with the crafting skill.",
            "npc:Then you must gather the herbs needed to make the potion you want.",
            "npc:You must fill your vial with water and add the ingredients you need. There are normally 2 ingredients to each type of potion.",
            "npc:Bear in mind, you must first clean each herb before you can use it.",
            "npc:You may also have to grind some ingredients before you can use them. You will need a pestle and mortar in order to do this.",
            "npc:Herbs can be found on the ground, and are also dropped by some monsters when you kill them.",
            "npc:Let's try an example Attack potion: The first ingredient is Guam leaf; the next is Eye of Newt.",
            "npc:Mix these in your water-filled vial, and you will produce an Attack potion.",
            "npc:Drink this potion to increase your Attack level.",
            "npc:Different potions also require different Herblore levels before you can make them.",
            "npc:Good luck with your Herblore practices, Good day adventurer.",
            "player:Thanks for your help.",
        })

        t.ticks(3)
        t.quest.expect_complete()

        -- Reward checks -- the quest's actual reward, not just its completion (H2, docs/QUEST_SUITE_KIT.md).
        t.check("reward.herblore", t.skill.expect_gain("herblore", 250, reward_before))

        t.finish(0)
    end,
}
