return {
    id = "gettingahead",
    fixture = "fresh_lumbridge.ini",
    setup = { "::clearinv", "::give rune_scimitar 1", "::give adamant_platebody 1", "::give rune_platelegs 1", "::give rune_full_helm 1", "::give rune_kiteshield 1", "::give shark 10",
        -- ::complete quest_xmarksthespot is not a prerequisite: Veos's Port Sarim ferry runs only after X Marks the Spot (cok_veos_sarim_gate, clientofkourend.rs2)
        "::setlevel attack 99", "::setlevel strength 99", "::setlevel defence 99", "::setlevel hitpoints 99", "::setlevel crafting 30", "::setlevel construction 26", "::complete quest_xmarksthespot" },
    run = function(t)
        t.quest.bind({ varp = "varb693_ga",
            constants = { not_started = 0, mary = 2, flour = 4, gate = 8, trail = 10, lair = 12, gordon2 = 14, mary2 = 16, clay = 18, gordon_clay = 20, fur = 22, gordon_fur = 24, dye = 26, gordon_dye = 28, mount = 30, finish = 32, complete = 34 },
            display = "Getting Ahead", points = 1,
            row = "quest_gettingahead" })
        t.ticks(3)
        -- Gordon's house: outer door 1245,3685 (west edge), inner door 1242,3682 (north edge); every visit passes both, in and out.
        local function house_in(tag)
            t.exec(tag .. ".outerIn", t.player.pass_door, { closed = "canafis_door_ground", open = "canafis_door_ground_open",
                at = { 1245, 3685, 0 }, near = { 1246, 3685 }, far = { 1244, 3685 } })
            t.exec(tag .. ".innerIn", t.player.pass_door, { closed = "canafis_door_ground", open = "canafis_door_ground_open",
                at = { 1242, 3682, 0 }, near = { 1242, 3683 }, far = { 1242, 3681 } })
        end
        local function house_out(tag)
            t.exec(tag .. ".innerOut", t.player.pass_door, { closed = "canafis_door_ground", open = "canafis_door_ground_open",
                at = { 1242, 3682, 0 }, near = { 1242, 3681 }, far = { 1242, 3683 } })
            t.exec(tag .. ".outerOut", t.player.pass_door, { closed = "canafis_door_ground", open = "canafis_door_ground_open",
                at = { 1245, 3685, 0 }, near = { 1244, 3685 }, far = { 1246, 3685 } })
        end
        t.expect("quest.stage.not_started", t.quest.expect_stage("not_started"))
        t.exec("wearWeapon", t.player.equip, "rune_scimitar")
        t.exec("wearBody", t.player.equip, "adamant_platebody")
        t.exec("wearLegs", t.player.equip, "rune_platelegs")
        t.exec("wearHelm", t.player.equip, "rune_full_helm")
        t.exec("wearShield", t.player.equip, "rune_kiteshield")
        -- 0: travel the real way (no ::gettingahead placement: it would put the player in Kebos and skip the ferry):
        -- Port Sarim -> Veos "Can you take me to Great Kourend?" -> Port Piscarilius dock, then overland west.
        t.exec("goto-veosSarim", t.player.goto_tile, 3054, 3246, 0)
        t.exec("talkToVeos", t.player.talk_to, "veos_sarim", 1)
        t.exec("talkToVeos-menu", t.chat.drain, { stop_at = "options" })
        t.exec("talkToVeos-sail", t.chat.choose, "Can you take me to Great Kourend?")
        t.exec("talkToVeos-done", t.chat.drain, {})
        t.ticks(4)
        local _, dock_arrival = t.world.tile()
        t.check("talkToVeos-landed", dock_arrival ~= nil and dock_arrival.x >= 1800 and dock_arrival.x < 1850, "landed at the Piscarilius dock")
        t.exec("goto-hop1", t.player.goto_tile, 1750, 3680, 0)
        t.exec("goto-hop2", t.player.goto_tile, 1650, 3700, 0)
        t.exec("goto-hop3", t.player.goto_tile, 1550, 3686, 0)
        t.exec("goto-hop4", t.player.goto_tile, 1350, 3700, 0)
        t.exec("goto-hop5", t.player.goto_tile, 1300, 3680, 0)
        t.exec("goto-gordon", t.player.goto_tile, 1247, 3686, 0)
        t.exec("ga.gordon", t.player.talk_to, "ga_gordon")
        t.exec("ga.gordon.chat", t.chat.play, { "player:Need a hand", "npc:*", "options", "choose:Yes.", "player:Yes", "npc:*" })
        t.expect("quest.stage.mary", t.quest.expect_stage("mary"))
        t.exec("goto-front", t.player.goto_tile, 1247, 3685, 0)
        house_in("enter1")
        t.player.walk_to(1238, 3681, 10)
        t.exec("ga.mary", t.player.talk_to, "ga_mary")
        t.exec("ga.mary.chat", t.chat.play, { "player:*", "npc:*" })
        t.expect("quest.stage.flour", t.quest.expect_stage("flour"))
        -- 4: pot of flour upstairs
        t.player.walk_to(1240, 3684, 8)
        t.exec("ga.up", t.player.click_loc, "kebos_spiralstairs_bottom", 1)
        t.expect("ga.up.level", select(2, t.world.level()) == 1 and "ok" or "refused", "level")
        local _, o_needle = t.world.obj_near("needle", 12)
        t.exec("take.needle", t.drive.click_minimenu, o_needle, 3)
        t.exec("take.needle.has", t.inv.await, "needle", 1, 15)
        local _, o_thread = t.world.obj_near("thread", 12)
        t.exec("take.thread", t.drive.click_minimenu, o_thread, 3)
        t.exec("take.thread.has", t.inv.await, "thread", 1, 15)
        t.player.walk_to(1243, 3683, 8)
        t.exec("door1243_3682", t.player.click_loc, "canafis_door_ground", 1, { at = {1243, 3682} })
        t.player.walk_to(1243, 3681, 8)
        t.exec("door1243_3681", t.player.click_loc, "canafis_door_ground", 1, { at = {1243, 3681} })
        t.player.walk_to(1241, 3681, 8)
        t.exec("door1240_3681", t.player.click_loc, "canafis_door_ground", 1, { at = {1240, 3681} })
        t.player.walk_to(1239, 3679, 8)
        local _, o_pot = t.world.obj_near("pot_empty", 12)
        t.exec("take.pot", t.drive.click_minimenu, o_pot, 3)
        t.exec("take.pot.has", t.inv.await, "pot_empty", 1, 15)
        t.player.walk_to(1238, 3678, 8)
        t.exec("ga.fillPot", t.player.click_loc, "ga_flourbarrel", 1)
        t.exec("ga.fillPot.has", t.inv.await, "pot_flour", 1, 12)
        t.ticks(3)
        t.exec("ga.down", t.player.click_loc, "kebos_spiralstairs_top", 1)
        t.expect("ga.down.level", select(2, t.world.level()) == 0 and "ok" or "refused", "level")
        house_out("leave1")
        t.exec("goto-hammer", t.player.goto_tile, 1258, 3685, 0)
        t.exec("take.hammer", t.player.click_obj, "hammer", 3)
        t.exec("take.hammer.has", t.inv.await, "hammer", 1, 15)
        t.exec("goto-gate", t.player.goto_tile, 1256, 3686, 0)
        local gate = t.player.by_symbol("loc", "ga_fencegate_l")
        t.exec("ga.flourGate", t.player.use_on, "pot_flour", gate)
        t.exec("ga.trail", t.var.await, "varb693_ga", 10, 30)
        t.exec("ga.potBack", t.inv.await, "pot_empty", 1, 3)
        -- 10: follow the trail: pickaxe, clay, planks, bear fur, cave
        t.exec("goto-rocks", t.player.goto_tile, 1223, 3655, 0)
        t.exec("ga.takePickaxe", t.player.click_loc, "ga_rocks_pickaxe", 1)
        t.exec("ga.takePickaxe.has", t.inv.await, "bronze_pickaxe", 1, 10)
        t.exec("goto-clay", t.player.goto_tile, 1219, 3657, 0)
        t.exec("ga.mineClay", t.player.click_loc, "clayrock1", 1)
        t.exec("ga.mineClay.has", t.inv.await, "clay", 1, 40)
        t.exec("goto-planks", t.player.goto_tile, 1204, 3650, 0)
        local _, o_plank1 = t.world.obj_near("woodplank", 12)
        t.exec("take.plank1", t.drive.click_minimenu, o_plank1, 3)
        t.exec("take.plank1.has", t.inv.await, "woodplank", 1, 15)
        t.exec("goto-planks2", t.player.goto_tile, 1204, 3653, 0)
        local _, pl = t.world.obj_near("woodplank", 12)
        t.exec("take.plank2", t.drive.click_minimenu, pl, 3)
        t.exec("take.plank2.has", t.inv.await, "woodplank", 2, 15)
        t.exec("goto-bear", t.player.goto_tile, 1218, 3678, 0)
        t.exec("ga.bear", t.player.attack, "brownbear", 2, 40)
        t.exec("ga.bear.dead", t.npc.await_dead_engaged, 200, 12, { eat = { item = "shark", below = 40 } })
        t.exec("ga.bear.fur", t.player.click_obj, "fur", 3)
        t.exec("ga.bear.fur.has", t.inv.await, "fur", 1, 10)
        t.exec("goto-cave", t.player.goto_tile, 1212, 3650, 0)
        t.exec("ga.cave", t.player.click_loc, "ga_cave", 1)
        t.exec("ga.cave.chat", t.chat.play, { "options", "choose:Yes." })
        t.exec("ga.cave.lair", t.var.await, "varb693_ga", 12, 10)
        t.exec("ga.beastPresent", t.npc.await_present, "ga_beast", 20, 10)
        t.exec("ga.attack", t.player.attack, "ga_beast", 2, 40)
        t.exec("ga.kill", t.npc.await_dead_engaged, 300, 12, { eat = { item = "shark", below = 40 } })
        t.check("ga.special", t.msg.expect("stamps the ground") == "ok", "rock-fall special seen")
        t.check("ga.rockhit", t.msg.expect("rock crashes") == "ok", "rock damage seen")
        t.exec("ga.stage14", t.var.await, "varb693_ga", 14, 5)
        t.exec("ga.skeleton", t.player.click_loc, "ga_skeleton", 1)
        t.exec("ga.skeleton.has", t.inv.await, "ga_journal", 1, 10)
        t.exec("ga.journal", t.player.inv_op, "ga_journal", 1)
        t.exec("ga.journal.read", t.chat.play, { "mesbox:*", "mesbox:*" })
        t.exec("ga.caveOut", t.player.click_loc, "ga_cave_out", 1)
        t.ticks(3)
        -- 14: Gordon
        -- ga_cave_out lands on 1212,3648, the opening in front of the cave mouth (gettingahead.constant
        -- ga_cave_out_coord = 0_18_57_60_0; ga_cave fills x1211-1213 z3646-3647, inviswalls ring it).
        local _, cave_exit = t.world.tile()
        t.check("ga.caveOut-landed", cave_exit ~= nil and cave_exit.x == 1212 and cave_exit.z == 3648 and cave_exit.level == 0,
            "cave exit tile " .. tostring(cave_exit and cave_exit.x) .. "," .. tostring(cave_exit and cave_exit.z) .. " (want 1212,3648)")
        t.player.walk_to(1212, 3650, 8)
        t.exec("goto-gordon2", t.player.goto_tile, 1247, 3686, 0)
        t.exec("ga.gordon14", t.player.talk_to, "ga_gordon")
        t.exec("ga.gordon14.chat", t.chat.play, { "player:*", "npc:*", "player:*", "npc:*" })
        t.expect("quest.stage.mary2", t.quest.expect_stage("mary2"))
        t.exec("goto-front2", t.player.goto_tile, 1247, 3685, 0)
        house_in("enter2")
        t.player.walk_to(1238, 3681, 10)
        t.exec("ga.mary16", t.player.talk_to, "ga_mary")
        t.exec("ga.mary16.chat", t.chat.play, { "player:*", "npc:*", "npc:*" })
        t.expect("quest.stage.clay", t.quest.expect_stage("clay"))
        local _, o_knife = t.world.obj_near("knife", 12)
        t.exec("take.knife", t.drive.click_minimenu, o_knife, 3)
        t.exec("take.knife.has", t.inv.await, "knife", 1, 15)
        local _, o_bucket = t.world.obj_near("bucket_empty", 12)
        t.exec("take.bucket", t.drive.click_minimenu, o_bucket, 3)
        t.exec("take.bucket.has", t.inv.await, "bucket_empty", 1, 15)
        t.exec("ga.fillBucket", t.player.use_on, "bucket_empty", t.player.by_symbol("loc", "fai_varrock_cooking_kitchen_sink"))
        t.exec("ga.fillBucket.has", t.inv.await, "bucket_water", 1, 10)
        t.ticks(6)
        t.exec("ga.wetClay", t.player.use_item_on_item, "clay", "bucket_water")
        t.exec("ga.wetClay.has", t.inv.await, "softclay", 1, 10)
        t.ticks(4)
        t.exec("ga.carve", t.player.use_item_on_item, "knife", "softclay")
        t.exec("ga.carve.chat", t.chat.play, { "options", "choose:Yes." })
        t.exec("ga.carve.has", t.inv.await, "ga_clayhead", 1, 10)
        t.expect("quest.stage.gordon_clay", t.quest.expect_stage("gordon_clay"))
        house_out("leave2")
        t.exec("goto-gordon3", t.player.goto_tile, 1247, 3686, 0)
        t.exec("ga.gordon20", t.player.talk_to, "ga_gordon")
        t.exec("ga.gordon20.chat", t.chat.play, { "player:*", "npc:*" })
        t.expect("quest.stage.fur", t.quest.expect_stage("fur"))
        t.exec("ga.fur", t.player.use_item_on_item, "fur", "ga_clayhead")
        t.exec("ga.fur.chat", t.chat.play, { "options", "choose:Yes." })
        t.exec("ga.fur.has", t.inv.await, "ga_furhead", 1, 10)
        t.expect("quest.stage.gordon_fur", t.quest.expect_stage("gordon_fur"))
        t.exec("ga.gordon24", t.player.talk_to, "ga_gordon")
        t.exec("ga.gordon24.chat", t.chat.play, { "player:*", "npc:*", "npc:*" })
        t.expect("quest.stage.dye", t.quest.expect_stage("dye"))
        t.exec("goto-front3", t.player.goto_tile, 1247, 3685, 0)
        house_in("enter3")
        t.player.walk_to(1239, 3688, 10)
        t.exec("ga.shelves", t.player.click_loc, "ga_shelves", 1)
        t.exec("ga.shelves.chat", t.chat.play, { "options", "choose:Take some red dye." })
        t.exec("ga.shelves.has", t.inv.await, "reddye", 1, 10)
        t.exec("ga.dye", t.player.use_item_on_item, "reddye", "ga_furhead")
        t.exec("ga.dye.chat", t.chat.play, { "options", "choose:Yes." })
        t.exec("ga.dye.has", t.inv.await, "ga_bloodhead", 1, 10)
        t.expect("quest.stage.gordon_dye", t.quest.expect_stage("gordon_dye"))
        house_out("leave3")
        t.exec("goto-gordon4", t.player.goto_tile, 1247, 3686, 0)
        t.exec("ga.gordon28", t.player.talk_to, "ga_gordon")
        t.exec("ga.gordon28.chat", t.chat.play, { "player:*", "npc:*", "npc:*" })
        t.expect("quest.stage.mount", t.quest.expect_stage("mount"))
        t.player.walk_to(1247, 3697, 8)
        t.exec("door1246_3697", t.player.click_loc, "farming_fencegate_l", 1, { at = {1246, 3697} })
        t.player.walk_to(1240, 3697, 10)
        local _, o_saw = t.world.obj_near("poh_saw", 12)
        t.exec("take.saw", t.drive.click_minimenu, o_saw, 3)
        t.exec("take.saw.has", t.inv.await, "poh_saw", 1, 15)
        t.exec("ga.nails", t.player.click_loc, "ga_workbench", 1)
        t.exec("ga.nails.chat", t.chat.play, { "options", "choose:Take the nails." })
        t.exec("ga.nails.has", t.inv.await, "nails_iron", 20, 10)
        t.player.walk_to(1245, 3697, 8)
        -- the leaf opened on the way in is still open: walk out through it
        t.player.walk_to(1247, 3685, 10)
        house_in("enter4")
        t.player.walk_to(1239, 3684, 10)
        t.exec("ga.build", t.player.click_loc, "ga_mounted_head_hotspot", 1)
        t.exec("ga.build.chat", t.chat.play, { "options", "choose:Yes." })
        t.exec("ga.build.stage", t.var.await, "varb693_ga", 32, 10)
        t.exec("ga.build.planksGone", t.inv.await_all, { woodplank = 0 }, 3)
        house_out("leave4")
        t.exec("goto-gordon5", t.player.goto_tile, 1247, 3686, 0)
        local _, snap = t.skill.snapshot()
        t.exec("ga.gordon32", t.player.talk_to, "ga_gordon")
        t.exec("ga.gordon32.chat", t.chat.play, { "player:*", "npc:*", "npc:*" })
        t.exec("ga.coins", t.inv.await, "coins", 3000, 10)
        t.check("ga.xp.crafting", t.skill.expect_gain("crafting", 4000, snap) == "ok", "4000 crafting xp")
        t.check("ga.xp.construction", t.skill.expect_gain("construction", 3200, snap) == "ok", "3200 construction xp")
        t.quest.expect_complete()
        t.finish(0)
    end,
}
