-- Generated by tools/quest_gate/new_quest.py from Quest Helper's
-- helpers/quests/horrorfromthedeep/ -- docs/QUEST_SUITE_KIT.md phase 3.
-- (author pass) was UNREVIEWED: every marker below was resolved by a live run; formerly a later
-- phase had to confirm this against a live run before it counted as a passing
-- quest test. Tier (quest_inventory.tsv): 3.
-- Items from getItemRequirements(): 8 given in setup (::give), none left to gather (Quest Helper canBeObtainedDuringQuest()).
-- Setup always starts with ::clearinv: the fresh character carries fourteen
-- slots of tutorial kit that block a non-stackable requirement fitting in the backpack.
-- Rewards from Quest Helper: 3 experience, 0 item, quest points 2 (QuestPointReward). Reward checks NOT emitted -- see the CHECK near boss_fight above.
--
-- Fixture start: fresh_lumbridge.ini stands the player at 3206,3233,0 (Lumbridge, beside
-- Hans). Every step below carries its own Quest Helper WorldPoint; the
-- FIRST emitted t.player.goto_tile is what actually leaves that tile.
--
-- Three rules the first pilot pass broke -- read before touching this file:
-- (a) "blocked" means a t.blocked("...") row followed by return -- a file
--     that runs on to expect_complete() after a failure is rejected.
-- (b) a talk_to/click answering screen_position or not_visible means you
--     are not standing near the target -- fix the goto, not the verb.
-- (c) never add a fixture or a helper file -- this quest file is the only
--     file you edit.

return {
    id = "horror",
    fixture = "fresh_lumbridge.ini",
    setup = {
        "::clearinv",
        "::give airrune 300", -- the wall takes one; the rest feed the strike spells on the mother
        "::give waterrune 300",
        "::give earthrune 300",
        "::give firerune 300",
        "::give mindrune 300",
        "::give molten_glass 1",
        "::give tinderbox 1",
        "::give woodplank 2",
        "::give swamp_tar 1",
        "::give nails 60", -- thirty steel nails per plank (horror_interactions.rs2 ^horror_bridge_nails_each)
        "::give hammer 1",
        "::give bronze_sword 1", -- the strange wall's sword
        "::give bronze_arrow 1", -- the strange wall's arrow
        "::setlevel agility 35",
        "::setlevel magic 60",
        "::give deathrune 300", -- blast spells
        "::setlevel hitpoints 99", -- the juvenile (78 attack) and the mother hit for real
        "::setlevel defence 60",
        "::give shark 60",
    },

    run = function(t)
        local bind_result, bind_detail = t.quest.bind({
            varp = "varb34_horrorquest",
            constants = {
                not_started = 0,
                started = 1,
                entered_lighthouse = 2,
                fixing_lighthouse = 3,
                repaired_lighthouse = 4,
                defeated_dagjr = 5,
                complete = 10,
            },
            display = "Horror from the Deep",
            points = 2,
        })
        t.step("quest.bind", bind_result == "ok" and "PASS" or "FAIL", bind_detail)
        t.ticks(3)
        t.expect("quest.stage.not_started", t.quest.expect_stage("not_started"))
        -- Prerequisite: Alfred Grimhand's Barcrawl is on the Quest Helper list but no horror .rs2 reads it
        -- (grep barcrawl quest_horror/scripts -> nothing), and its row has no cheat arm.

        -- Route (door rule, b69): Lumbridge -> the lighthouse has no on-foot route but the members'
        -- gate south of Taverley (reach.py 3206,3233 -> 2520,3571: NEEDS-DOOR via membergater
        -- @2933,3320), then open ground to the beach north of the Barbarian Outpost, then the basalt
        -- rocks (basalt_rocks.rs2 [oploc1,horror_jumping_spot1..10], each "Jump-to" a fixed
        -- start -> final tile; the map stores them on raw level 1, m39_56.jl2:246-255, hence
        -- loc_level = 1). spot3 (north) and spot8 (south) roll Agility (basalt_rocks.rs2:24,42): a
        -- slip sweeps the player back to the shore it came from, so those two are retried as a pair
        -- with the jump before them (jump_pair below).
        local function jump(spot, at, src, dest)
            return { loc = spot, op_name = "Jump-to", at = { at[1], at[2], 0 }, loc_level = 1,
                src = src, dest = dest, attempts = 1, vitals = { eat = "shark", below = 30 } }
        end
        local function jump_pair(first, second, shore, tries)
            local slips = 0
            for i = 1, tries do
                local _, here = t.world.tile()
                if here.x ~= first.src[1] or here.z ~= first.src[2] then
                    t.player.walk_to(first.src[1], first.src[2], 20)
                end
                local r1, d1 = t.player.cross_trap(first)
                if r1 ~= "ok" then
                    return r1, "try " .. i .. " (" .. slips .. " slip(s) before): first jump: " .. tostring(d1)
                end
                local r2, d2 = t.player.cross_trap(second)
                if r2 == "ok" then
                    return "ok", slips .. " slip(s) swept back to " .. shore .. " before this pair; " .. d1 .. " || " .. d2
                end
                slips = slips + 1
                t.ticks(4)
                local _, after = t.world.tile()
                if i == tries then
                    return r2, "slipped " .. slips .. " time(s); last: " .. tostring(d2) .. " at " .. after.x .. "," .. after.z
                end
            end
        end
        local SPOT1 = jump("horror_jumping_spot1", { 2522, 3595 }, { 2522, 3594 }, { 2522, 3598 })
        local SPOT3 = jump("horror_jumping_spot3", { 2522, 3600 }, { 2522, 3598 }, { 2522, 3603 })
        local SPOT5 = jump("horror_jumping_spot5", { 2518, 3611 }, { 2518, 3610 }, { 2515, 3611 })
        local SPOT7 = jump("horror_jumping_spot7", { 2514, 3613 }, { 2515, 3611 }, { 2514, 3616 })
        local SPOT9 = jump("horror_jumping_spot9", { 2514, 3617 }, { 2514, 3616 }, { 2514, 3620 })
        local SPOT10 = jump("horror_jumping_spot10", { 2514, 3619 }, { 2514, 3620 }, { 2514, 3616 })
        local SPOT8 = jump("horror_jumping_spot8", { 2514, 3615 }, { 2514, 3616 }, { 2514, 3612 })
        local SPOT6 = jump("horror_jumping_spot6", { 2516, 3611 }, { 2514, 3612 }, { 2518, 3610 })
        local SPOT4 = jump("horror_jumping_spot4", { 2522, 3602 }, { 2522, 3603 }, { 2522, 3599 })
        local SPOT2 = jump("horror_jumping_spot2", { 2522, 3597 }, { 2522, 3599 }, { 2522, 3594 })
        local function rocks_north(step)
            t.exec(step .. ".walkToRocks", t.player.walk_to, 2522, 3594, 30)
            t.exec(step .. ".rocks1to3", jump_pair, SPOT1, SPOT3, "the beach", 30)
            t.exec(step .. ".walkToSpot5", t.player.walk_to, 2518, 3610, 20)
            t.exec(step .. ".rocks5", t.player.cross_trap, SPOT5)
            t.exec(step .. ".rocks7", t.player.cross_trap, SPOT7)
            t.exec(step .. ".rocks9", t.player.cross_trap, SPOT9)
        end
        local function rocks_south(step)
            t.exec(step .. ".walkToRocks", t.player.walk_to, 2514, 3620, 30)
            t.exec(step .. ".rocks10to8", jump_pair, SPOT10, SPOT8, "the north rocks", 30)
            t.exec(step .. ".rocks6", t.player.cross_trap, SPOT6)
            t.exec(step .. ".walkToSpot4", t.player.walk_to, 2522, 3603, 20)
            t.exec(step .. ".rocks4", t.player.cross_trap, SPOT4)
            t.exec(step .. ".rocks2", t.player.cross_trap, SPOT2)
        end
        -- The outpost's gate (doors_selfstage barbariangatel 2545,3570; scorpcatcher.lua) and the
        -- agility course's only entrance, the obstacle pipe (maplink_agility.dbrow:500-512,
        -- 2552,3561 <-> 2552,3558, Agility 35).
        local PIPE_IN = { loc = "agility_obstical_pipe_barbarian", op_name = "Squeeze-through",
            at = { 2552, 3559, 0 }, src = { 2552, 3561 }, dest = { 2552, 3558 } }
        local PIPE_OUT = { loc = "agility_obstical_pipe_barbarian", op_name = "Squeeze-through",
            at = { 2552, 3559, 0 }, src = { 2552, 3558 }, dest = { 2552, 3561 } }

        t.exec("goto-talkToLarrissa.memberGate", t.player.goto_tile, 2934, 3318, 0)
        t.exec("talkToLarrissa.memberGate", t.player.cross_gate, { loc = "membergatel", at = { 2934, 3320, 0 },
            near = { 2934, 3318 }, far_ok = function(tile) return tile.z >= 3320 and math.abs(tile.x - 2934) <= 2 end,
            far_desc = "north of the members' gate, z >= 3320" })
        t.exec("goto-talkToLarrissa", t.player.goto_tile, 2522, 3592, 0)
        rocks_north("talkToLarrissa")
        t.exec("talkToLarrissa.walk", t.player.walk_to, 2509, 3632, 30)
        t.exec("talkToLarrissa", t.player.talk_to, "horror_girlfriend_prequest", 1)
        t.exec("talkToLarrissa-dialog", t.chat.play, {
            "player:Hello there.",
            "npc:Oh, thank Armadyl!",
            "choose:With what?",
            "player:With what?",
            "npc:Oh... it is terrible",
            "npc:Look, you can see for yourself",
            "npc:With the light off",
            "player:Maybe he just went on holiday",
            "npc:That is terribly irresponsible",
            "npc:Please, I know something terrible",
            "choose:But how can I help?",
            "player:But how can I help?",
            "npc:Well, we have to do something",
            "npc:has trapped me on this causeway",
            "npc:as well as fix the bridge",
            "choose:Okay, I'll help!",
            "player:Okay, I'll help!",
            "npc:OH! THANK YOU SO MUCH!",
            "choose:I'll see what I can do",
            "player:I'll see what I can do.",
            "npc:Thank you so much!",
        })
        t.expect("quest.stage.started", t.quest.expect_stage("started"))

        t.exec("goto-usePlankOnBridge", t.player.goto_tile, 2595, 3608, 0)
        local left = t.player.by_symbol("loc", "horror_broken_bridge_left_spot")
        t.exec("usePlankOnBridge", t.player.use_on, "woodplank", left)
        t.exec("usePlankOnBridge-dialog", t.chat.drain, {max_pages = 3})
        -- Over the half-mended gap by the left spot's own Cross (horror_interactions.rs2:90-133):
        -- one half repaired is an Agility roll, a jump to 2599 on success, a dive to 2598 (and
        -- 1-5 damage) on a failure -- either is the far side.
        local function cross_half_mended(spec)
            local r, d = t.player.cross_trap(spec)
            local _, tile = t.world.tile()
            if r ~= "ok" and tile.x == 2598 and tile.z == 3608 and tile.level == 0 then
                return "ok", "dived (a failed roll) onto 2598,3608,0, the far side: " .. tostring(d)
            end
            return r, d
        end
        t.exec("useSecondPlank.crossBridge", cross_half_mended, { loc = "horror_broken_bridge_left_spot", op_name = "Cross",
            at = { 2596, 3608, 0 }, loc_level = 1, src = { 2595, 3608 }, dest = { 2599, 3608 }, attempts = 1 })
        local right = t.player.by_symbol("loc", "horror_broken_bridge_right_spot")
        t.exec("useSecondPlank", t.player.use_on, "woodplank", right)
        t.exec("useSecondPlank-dialog", t.chat.drain, {max_pages = 3})
        t.check("bridge.planks_used", select(2, t.inv.count("woodplank")) == 0, "planks left " .. tostring(select(2, t.inv.count("woodplank"))))

        -- Back over the mended bridge by the right spot (both halves: three steps west, 2598 ->
        -- 2595), back down the rocks, through the outpost gate and the pipe to Gunnjorn.
        t.exec("talkToGunnjorn.crossBridge", t.player.cross_trap, { loc = "horror_broken_bridge_right_spot",
            op_name = "Cross", at = { 2598, 3608, 0 }, loc_level = 1, src = { 2599, 3608 }, dest = { 2595, 3608 }, attempts = 1 })
        t.exec("goto-talkToGunnjorn.rocks", t.player.goto_tile, 2514, 3621, 0)
        rocks_south("talkToGunnjorn")
        t.exec("goto-talkToGunnjorn.gate", t.player.goto_tile, 2543, 3570, 0)
        t.exec("talkToGunnjorn.gateIn", t.player.pass_door, { closed = "barbariangatel", open = "barbariangatel",
            at = { 2545, 3570, 0 }, near = { 2545, 3570 }, far = { 2546, 3570 } })
        t.exec("talkToGunnjorn.walkToPipe", t.player.walk_to, 2552, 3561, 20)
        t.exec("talkToGunnjorn.pipeIn", t.player.cross_trap, PIPE_IN)
        t.exec("talkToGunnjorn", t.player.talk_to, "gunnjorn", 1)
        t.exec("talkToGunnjorn-dialog", t.chat.play, {
            "npc:Haha welcome to my obstacle course",
            "player:Hi, are you called Gunnjorn?",
            "npc:Why, indeed I am.",
            "player:Yeah, that's great.",
            "npc:Yes, she did!",
            "player:Well, something has happened",
            "npc:Sure. Here you go.",
        })
        t.expect("gunnjorn.key", t.inv.expect_has("horror_key", 1))

        t.exec("openLighthouse.walkToPipe", t.player.walk_to, 2552, 3558, 20)
        t.exec("openLighthouse.pipeOut", t.player.cross_trap, PIPE_OUT)
        t.exec("openLighthouse.walkToGate", t.player.walk_to, 2546, 3570, 20)
        t.exec("openLighthouse.gateOut", t.player.pass_door, { closed = "barbariangatel", open = "barbariangatel",
            at = { 2545, 3570, 0 }, near = { 2546, 3570 }, far = { 2545, 3570 } })
        t.exec("goto-openLighthouse.rocks", t.player.goto_tile, 2522, 3592, 0)
        rocks_north("openLighthouse")
        t.exec("openLighthouse.walk", t.player.walk_to, 2509, 3635, 30)
        t.exec("openLighthouse", t.player.click_loc, "horror_lighthouse_doorway", 1)
        t.exec("enterLighthouse", t.player.click_loc, "horror_lighthouse_doorway", 1)
        t.ticks(4)
        t.expect("quest.stage.entered_lighthouse", t.quest.expect_stage("entered_lighthouse"))
        t.exec("goToF1", t.player.click_loc, "horror_lighthouse_spiralstairs_base", 1)
        t.ticks(3)
        t.check("goToF1.level", select(2, t.world.level()) == 1, "level " .. tostring(select(2, t.world.level())))
        t.exec("goToF2", t.player.click_loc, "horror_lighthouse_spiralstairs_middle", 1)
        t.exec("goToF2-dialog", t.chat.play, {"choose:Climb Up."})
        t.ticks(3)
        t.check("goToF2.level", select(2, t.world.level()) == 2, "level " .. tostring(select(2, t.world.level())))
        local cog = t.player.by_symbol("loc", "horror_lighthouse_cog_broken")
        t.exec("useTar", t.player.use_on, "swamp_tar", cog)
        t.exec("useTinderbox", t.player.use_on, "tinderbox", cog)
        t.exec("useGlass", t.player.use_on, "molten_glass", cog)
        t.ticks(4)
        t.expect("quest.stage.repaired_lighthouse", t.quest.expect_stage("repaired_lighthouse"))
        local _, pos = t.world.tile()
        t.check("after_repair.tile", pos.level == 2, "tile " .. pos.x .. "," .. pos.z .. " level " .. pos.level)
        t.exec("goDownToF1", t.player.click_loc, "horror_lighthouse_spiralstairs_top", 1)
        t.ticks(3)
        _, pos = t.world.tile()
        t.check("goDownToF1.tile", pos.level == 1, "tile " .. pos.x .. "," .. pos.z .. " level " .. pos.level)
        t.exec("goDownToF0", t.player.click_loc, "horror_lighthouse_spiralstairs_middle", 3)
        t.ticks(3)
        _, pos = t.world.tile()
        t.check("goDownToF0.tile", pos.level == 0 and pos.x < 2450, "tile " .. pos.x .. "," .. pos.z .. " level " .. pos.level)
        t.exec("goDownToBasement", t.player.click_loc, "horror_ladder_top", 1)
        t.ticks(4)
        _, pos = t.world.tile()
        t.check("goDownToBasement.tile", pos.level == 0 and pos.z > 4500, "tile " .. pos.x .. "," .. pos.z .. " level " .. pos.level)
        local wall = t.player.by_symbol("loc", "horror_mid_right_door")
        t.exec("useAirRune", t.player.use_on, "airrune", wall)
        t.exec("useAirRune-dialog", t.chat.play, {"player:I don't think I'll get that back", "choose:Yes"})
        t.ticks(2)
        t.exec("useWaterRune", t.player.use_on, "waterrune", wall)
        t.exec("useWaterRune-dialog", t.chat.play, {"player:I don't think I'll get that back", "choose:Yes"})
        t.ticks(2)
        t.exec("useEarthRune", t.player.use_on, "earthrune", wall)
        t.exec("useEarthRune-dialog", t.chat.play, {"player:I don't think I'll get that back", "choose:Yes"})
        t.ticks(2)
        t.exec("useFireRune", t.player.use_on, "firerune", wall)
        t.exec("useFireRune-dialog", t.chat.play, {"player:I don't think I'll get that back", "choose:Yes"})
        t.ticks(2)
        t.exec("useArrow", t.player.use_on, "bronze_arrow", wall)
        t.exec("useArrow-dialog", t.chat.play, {"player:I don't think I'll get that back", "choose:Yes"})
        t.ticks(2)
        t.exec("useSword", t.player.use_on, "bronze_sword", wall)
        t.exec("useSword-dialog", t.chat.play, {"player:I don't think I'll get that back", "choose:Yes"})
        t.ticks(2)
        t.expect("wall.complete", t.msg.expect("You hear the sound of something moving within the wall."))
        t.exec("goThroughDoor", t.player.click_loc, "horror_far_right_door", 1)
        t.ticks(3)
        _, pos = t.world.tile()
        t.check("goThroughDoor.tile", pos.x >= 2516 and pos.level == 0, "tile " .. pos.x .. "," .. pos.z .. " level " .. pos.level)
        t.exec("climbDownToCavern", t.player.click_loc, "horror_ladder_top2_prequest", 1)
        t.ticks(3)
        _, pos = t.world.tile()
        t.check("climbDownToCavern.tile", pos.level == 0 and pos.z >= 4630, "tile " .. pos.x .. "," .. pos.z .. " level " .. pos.level)
        t.exec("talkToJossik", t.player.talk_to, "horror_lighthousekeeeper_injured", 1)
        t.exec("talkToJossik-dialog", t.chat.play, {
            "npc:*cough*",
            "player:I guess you're Jossik then",
            "npc:I... I do not know.",
            "npc:I was searching for information",
            "npc:came down here I was attacked",
            "npc:Well, I do not know what they are",
            "player:Don't worry, I'm here now.",
            "player:I'll go back upstairs",
            "npc:NO! No, you can't leave me now!",
        })
        t.exec("killDagannoth.cutscene", t.cutscene.await, "killDagannoth", { expect = {
            { op = "lookat" }, -- horror_encounter.rs2:61..88, expressions on $start
            { op = "reset" },  -- horror_encounter.rs2 cam_reset
        } })
        t.exec("killDagannoth.present", t.npc.await_present, "horror_dagannoth_jr4", 30, 60)
        t.ticks(8)
        t.exec("killDagannoth.settled", t.npc.await_present, "horror_dagannoth_jr4", 30, 20)
        t.cheat("::pray 18")
        t.exec("killDagannoth", t.player.cast, "wind_blast", "horror_dagannoth_jr4", 14)
        local _, sharks_before_jr = t.inv.count("shark")
        local _, jr_detail = t.exec("killDagannoth.dead", t.npc.await_dead_engaged, 400, 30, { eat = { item = "shark", below = 40 } })
        -- Margin (brief: lowest hp >= a quarter of max AND food left). No horror .rs2 or gunnjorn.rs2
        -- branches on the combat level the setup's Magic 60 / Defence 60 / Hitpoints 99 stage
        -- (grep combat_level quest_horror area_barbarian_outpost/scripts/gunnjorn.rs2 -> nothing).
        local jr_low = tonumber(string.match(tostring(jr_detail), "lowest hp (%d+)/") or "")
        local _, sharks_after_jr = t.inv.count("shark")
        t.check("killDagannoth.margin", jr_low ~= nil and jr_low >= 25 and sharks_after_jr >= 1,
            "lowest hp " .. tostring(jr_low) .. "/99, sharks " .. tostring(sharks_before_jr) .. " -> " .. tostring(sharks_after_jr)
                .. " (margin: lowest hp >= 25, a quarter of 99, AND food left)")
        t.ticks(3)
        t.expect("quest.stage.defeated_dagjr", t.quest.expect_stage("defeated_dagjr"))
        t.exec("killDagannoth-dialog", t.chat.play, {
            "player:Okay, now that the creature's dead",
            "npc:No... you do not understand...",
            "npc:That was not the creature that attacked me",
            "npc:That was one of its babies",
        })
        t.exec("killMother.cutscene", t.cutscene.await, "killMother", { expect = {
            { op = "moveto", coord = "0_39_72_18_37" }, -- horror_encounter.rs2:146
            { op = "lookat", coord = "0_39_72_13_36" }, -- horror_encounter.rs2:154
            { op = "reset" },
        } })
        t.ticks(10)
        local _, snap = t.skill.snapshot()
        local _, magic_row = t.skill.read("magic")
        local magic_before = magic_row.experience
        t.cheat("::pray 17")
        t.exec("killMother.present", t.npc.await_present, "horror_dagganoth_air", 30, 60)
        local colours = {
            {"horror_dagganoth_air", "wind_blast"},
            {"horror_dagganoth_water", "water_blast"},
            {"horror_dagganoth_earth", "earth_blast"},
            {"horror_dagganoth_fire", "fire_blast"},
        }
        local casts, landed, trace, eaten = 0, 0, "", 0
        local mother_low = nil
        for round = 1, 160 do
            local stage = select(2, t.quest.stage())
            if stage == 10 then break end
            local acted = false
            local _, hp_row = t.skill.read("hitpoints")
            if mother_low == nil or hp_row.level < mother_low then mother_low = hp_row.level end
            if hp_row.level < 55 then
                t.player.inv_op("shark", 1)
                eaten = eaten + 1
            end
            for _, c in ipairs(colours) do
                local found = t.npc.nearest(c[1], 25)
                if found == "ok" then
                    local r = t.player.cast(c[2], c[1], 8)
                    casts = casts + 1
                    if r == "ok" then landed = landed + 1 end
                    if casts <= 40 then trace = trace .. c[2] .. "=" .. tostring(r) .. " " end
                    acted = true
                    break
                end
            end
            if not acted then
                t.ticks(5)
                if round == 12 then
                    for _, sym in ipairs({"horror_dagganoth_melee", "horror_dagganoth_earth", "horror_dagganoth_fire", "horror_dagganoth_ranged", "horror_dagganoth_water", "horror_dagganoth_air"}) do
                        local r1, r2 = t.npc.nearest(sym, 40)
                        trace = trace .. sym .. "=" .. tostring(r1) .. ":" .. (type(r2) == "table" and (tostring(r2.x) .. "," .. tostring(r2.z)) or tostring(r2)) .. " "
                    end
                    local _, tp = t.world.tile()
                    trace = trace .. "me=" .. tp.x .. "," .. tp.z .. " "
                end
            end
        end
        t.check("killMother.casts", casts >= 1 and landed >= 1, casts .. " casts, " .. landed .. " ok, ate " .. eaten .. "; first: " .. trace)
        local _, sharks_after_mother = t.inv.count("shark")
        t.check("killMother.margin", mother_low ~= nil and mother_low >= 25 and sharks_after_mother >= 1,
            "lowest hp read between casts " .. tostring(mother_low) .. "/99, ate " .. eaten .. ", sharks left "
                .. tostring(sharks_after_mother) .. " (margin: lowest hp >= 25, a quarter of 99, AND food left)")
        t.ticks(10)
        t.exec("killMother-dialog", t.chat.drain, {max_pages = 8})
        t.expect("quest.stage.complete", t.quest.expect_stage("complete"))
        t.check("reward.strength", t.skill.expect_gain("strength", 4662, snap))
        t.check("reward.ranged", t.skill.expect_gain("ranged", 4662, snap))
        local _, magic_row_after = t.skill.read("magic")
        local magic_after = magic_row_after.experience
        t.check("reward.magic", magic_after - magic_before >= 4662.5, "magic xp " .. tostring(magic_before) .. " -> " .. tostring(magic_after) .. " (casts add some; reward is 4,662.5)")
        t.expect("reward.casket", t.inv.expect_has("horror_casket", 1))
        t.quest.expect_complete()
        t.finish(0)
    end,
}
