-- ROUND 5 (matthew-mbp-m4-b54), sent back by the sampler: green 208/0 with every guide step driven (Franklin's hammer,
-- trolls 52/60/52 ticks and the fishing troll 60 with the bow, Queen 200/200 read off the server), but killQueen-dead
-- ate ALL 15 sharks ("OUT OF shark", her bar 4/80 at t+147) and the player reached the scroll at 1 hp (shots 228, 236).
-- Next round: add "::give black_dragonhide_body 1" + "::wield black_dragonhide_body" (magic defence +45, not
-- quest-gated -- levelrequire.rs2:178 gates only green dragonhide_body), eat to full before killQueen-attack (the fight
-- opened at 72/99), drop the hammer after the walls for a 16th shark, then two runs with sharks to spare.
-- ROUND 4 (matthew-mbp-m4-b54), sent back by the sampler: green 202/0, every leg driven (hammer bought,
-- bones from trolls + chickens, pot and lid thrown and fired), but the Sea Troll Queen and the sea trolls
-- have no server .npc block, so they fight at the 10 hp default and the Queen dies to ONE fire blast
-- (play shot 215). Re-run unchanged once content gives swan_seatroll_queen / swan_troll_ambush their blocks.
-- Generated by tools/quest_gate/new_quest.py from Quest Helper's
-- helpers/quests/swansong/ -- docs/QUEST_SUITE_KIT.md phase 3.
-- phase to confirm against a live run before this counts as a passing
-- quest test. Tier (quest_inventory.tsv): 4.
-- Items from getItemRequirements(): 9 given in setup (::give), 0 left as '-- check gather' markers (Quest Helper canBeObtainedDuringQuest()).
-- Setup always starts with ::clearinv: the fresh character carries fourteen
-- slots of tutorial kit that block a non-stackable requirement fitting in the backpack.
-- Rewards from Quest Helper: 3 experience, 1 item, quest points 2 (QuestPointReward). Reward checks NOT emitted -- see the CHECK near boss_fight above.
--
-- Fixture start: fresh_lumbridge.ini stands the player at 3206,3233,0 (Lumbridge, beside
-- Hans). Every step below carries its own Quest Helper WorldPoint; the
-- FIRST emitted t.player.goto_tile is what actually leaves that tile.
--
-- Three rules the first pilot pass broke -- read before touching this file:
-- (a) "blocked" means a t.blocked("...") row followed by return -- a file
--     that runs on to expect_complete() after a failure is rejected.
-- (b) a talk_to/click answering screen_position or not_visible means you
--     are not standing near the target -- fix the goto, not the verb.
-- (c) never add a fixture or a helper file -- this quest file is the only
--     file you edit.

return {
    id = "swansong",
    fixture = "fresh_lumbridge.ini",
    setup = {
        "::clearinv",
        -- brought along (Quest Helper getItemRequirements): runes for the Wise Old Man, bones,
        -- pot + lid, iron bars, log, tinderbox, hammer, combat gear and food
        "::give mistrune 10",
        "::give lavarune 10",
        "::give bloodrune 5",
        "::give iron_bar 5",
        -- soft clay for the pot + lid (guide: make one from wet clay)
        "::give softclay 2",
        "::give logs 1",
        "::give tinderbox 1",
        -- SEAM b54-seam3 restaging: the trolls (100 hp, multicombat) and the Queen (200 hp, Water Wave 37)
        -- are fought with a bow from range; the Queen cannot be reached on foot (no route to a tile beside her)
        "::setlevel ranged 99",
        "::setlevel magic 99",
        "::setlevel cooking 62",
        "::setlevel fishing 62",
        "::setlevel smithing 45",
        "::setlevel crafting 40",
        "::setlevel firemaking 42",
        "::setlevel attack 80",
        "::setlevel strength 80",
        "::setlevel defence 99",
        "::setlevel hitpoints 99",
        "::setvar varp101_qp 100",
        "::complete quest_onesmallfavour",
        "::complete quest_gardenoftranquillity",
        "::give magic_shortbow 1",
        "::wield magic_shortbow",
        "::give rune_arrow 400",
        "::wield rune_arrow",
        "::give coif 1",
        "::wield coif",
        "::give black_dragonhide_chaps 1",
        "::wield black_dragonhide_chaps",
        "::give black_dragon_vambraces 1",
        "::wield black_dragon_vambraces",
        -- ROUND 6: black d'hide body (magic defence +45; levelrequire.rs2:178 gates only the green one), worn before the food
        "::give black_dragonhide_body 1",
        "::wield black_dragonhide_body",
        "::give shark 15",
    },

    run = function(t)
        t.quest.bind({
            varp = "varb2098_swansong",
            constants = {
                not_started = 0, agreed_to_help = 10, wom_told = 20, runes_given = 30,
                ready_to_fight = 40, trolls_beaten = 50, helping = 70, tasks_done = 80,
                frumscone_done = 95, malignius_first = 110, crafter_done = 120, pot_ready = 130,
                army_ready = 140, final_talk = 160, queen_fight = 170, queen_dead = 190,
                complete = 200,
            },
            row = "quest_swansong",
            display = "Swan Song",
            points = 2,
        })
        t.ticks(3)
        t.expect("quest.stage.not_started", t.quest.expect_stage("not_started"))

        -- closer b54-seam3: no store hammer; Franklin hands one over at the lit stage

        t.exec("goto-talkToHerman", t.player.goto_tile, 2345, 3649, 0)
        t.exec("talkToHerman", t.player.talk_to, "swan_multioutside", 1)
        t.exec("talkToHerman-dialog", t.chat.play, {
            "npc:Trolls! They're attacking",
            "player:Do you need any help",
            "npc:I might, at that",
            "choose:/brave adventurer/",
            "player:a brave adventurer",
            "npc:Very well",
        })
        t.ticks(2)
        t.expect("quest.stage.agreed_to_help", t.quest.expect_stage("agreed_to_help"))

        t.exec("goto-talkToWom", t.player.goto_tile, 3088, 3254, 0)
        t.exec("talkToWom", t.player.talk_to, "wom_multi", 1)
        t.exec("talkToWom-dialog", t.chat.play, {
            "npc:I shall bring my adventuring days",
            "player:You're going to sing",
            "npc:No, you ignoramus",
            "npc:I'm rather short of runes",
        })
        t.ticks(2)
        t.expect("quest.stage.wom_told", t.quest.expect_stage("wom_told"))
        t.exec("talkToWom-runes", t.player.talk_to, "wom_multi", 1)
        t.exec("talkToWom-runes-dialog", t.chat.play, {
            "player:I've brought the runes",
            "npc:Splendid",
        })
        t.ticks(2)
        t.expect("quest.stage.runes_given", t.quest.expect_stage("runes_given"))
        t.check("runes-handed-over", t.inv.expect_absent("mistrune"))

        t.exec("goto-talkToWomAtColony", t.player.goto_tile, 2345, 3649, 0)
        t.exec("talkToWomAtColony", t.player.talk_to, "swan_multioutside", 1)
        t.exec("talkToWomAtColony-dialog", t.chat.play, {
            "npc:I'm rather short of breath",
            "player:I'm ready to fight.",
            "npc:Then let's not waste",
        })
        t.ticks(2)
        t.expect("quest.stage.ready_to_fight", t.quest.expect_stage("ready_to_fight"))

        t.exec("enterColony", t.player.click_loc, "swan_hole", 1)
        t.ticks(4)
        t.check("enterColony-tile", t.world.tile())

        -- kill79Trolls: the three ambush trolls at the entrance (50 tick despawn: no pauses)
        t.ticks(2)
        t.check("kill79Trolls-present", t.npc.tiles("swan_troll_ambush", 25))
        t.cheat("::swansong_troll_hp")
        t.check("kill79Trolls-hp-server", t.msg.expect("Sea trolls 3: 100/100 100/100 100/100"))
        t.exec("kill79Trolls-attack-1", t.player.attack, "swan_troll_ambush", 2, 20)
        t.exec("kill79Trolls-dead-1", t.npc.await_dead_engaged, 120, 20, { eat = { item = "shark", below = 50 } })
        t.exec("kill79Trolls-attack-2", t.player.attack, "swan_troll_ambush", 2, 20)
        t.exec("kill79Trolls-dead-2", t.npc.await_dead_engaged, 120, 20, { eat = { item = "shark", below = 50 } })
        t.exec("kill79Trolls-attack-3", t.player.attack, "swan_troll_ambush", 2, 20)
        t.exec("kill79Trolls-dead-3", t.npc.await_dead_engaged, 120, 20, { eat = { item = "shark", below = 50 } })
        t.ticks(3)
        t.exec("pickUpBones-1", t.player.click_obj, "bones", 3)
        t.exec("pickUpBones-2", t.player.click_obj, "bones", 3)
        t.exec("pickUpBones-3", t.player.click_obj, "bones", 3)
        t.check("pickUpBones-3-count", t.inv.count("bones"))
        t.check("kill79Trolls-count", t.var.varbit("varb2107_swansong_trolls"))
        t.expect("quest.stage.trolls_beaten", t.quest.expect_stage("trolls_beaten"))

        t.exec("openColonyGate", t.player.click_loc, "swan_door_l", 1)
        t.ticks(3)
        t.exec("goto-talkToHermanInBuilding", t.player.goto_tile, 2354, 3682, 0)
        t.exec("talkToHermanInBuilding", t.player.talk_to, "swan_herman", 1)
        t.exec("talkToHermanInBuilding-dialog", t.chat.play, {
            "npc:You made it through",
            "npc:My brother Franklin needs help",
        })
        t.ticks(2)
        t.expect("quest.stage.helping", t.quest.expect_stage("helping"))

        t.exec("goto-talkToFranklin", t.player.goto_tile, 2341, 3668, 0)
        t.exec("talkToFranklin", t.player.talk_to, "swan_franklin", 1)
        t.exec("talkToFranklin-dialog", t.chat.play, {
            "player:Herman said you could use a hand",
            "npc:The trolls managed to smash",
        })
        t.ticks(2)
        t.check("talkToFranklin-var", t.var.varbit("varb2099_swansong_franklin"))

        local firebox = t.player.by_symbol("loc", "swan_firebox")
        t.check("firebox.found", firebox ~= nil, "swan_firebox resolved: " .. tostring(firebox and firebox.id))
        t.exec("goto-useLog", t.player.goto_tile, 2344, 3675, 0)
        t.exec("useLog", t.player.use_on, "logs", firebox)
        t.ticks(2)
        t.check("useLog-var", t.var.varbit("varb2099_swansong_franklin"))
        t.exec("useTinderbox", t.player.use_on, "tinderbox", firebox)
        t.ticks(2)
        t.check("useTinderbox-var", t.var.varbit("varb2099_swansong_franklin"))
        -- the firebox is lit: the leftover tinderbox and log only take backpack slots the Queen's food needs
        t.player.drop("tinderbox")
        t.player.drop("logs")
        t.ticks(3)
        t.check("dropFiremaking-slots", t.inv.expect_absent("tinderbox"), "tinderbox and log dropped to keep slots for food; logs left: " .. tostring(select(2, t.inv.count("logs"))))

        local press = t.player.by_symbol("loc", "swan_press")
        t.check("press.found", press ~= nil, "swan_press resolved: " .. tostring(press and press.id))
        for i = 1, 5 do
            t.exec("flattenBar-" .. i, t.player.use_on, "iron_bar", press)
            t.check("flattenBar-" .. i .. "-sheets", t.inv.await("iron_sheet", i, 20))
        end
        t.exec("goto-talkToFranklinHammer", t.player.goto_tile, 2341, 3668, 0)
        t.exec("talkToFranklinHammer", t.player.talk_to, "swan_franklin", 1)
        t.exec("talkToFranklinHammer-dialog", t.chat.play, {
            "npc:How are you getting on?",
            "player:the press is working now",
            "npc:At least you've got enough iron sheets",
            "player:Also I think I need a hammer",
            "npc:Hammer? Not a problem",
        })
        t.exec("talkToFranklinHammer-hammer", t.inv.await, "hammer", 1, 10)
        t.exec("goto-westWall", t.player.goto_tile, 2313, 3683, 0)
        for i = 1, 5 do
            local wall = t.player.by_symbol("loc", "swan_wall_" .. i)
            t.check("wall" .. i .. ".found", wall ~= nil, "swan_wall_" .. i .. " (2311," .. (3681 + (({[1]=1,[2]=0,[3]=2,[4]=4,[5]=3})[i])) .. ") resolved: " .. tostring(wall and wall.id))
            t.exec("repairWall-" .. i, t.player.use_on, "iron_sheet", wall)
            t.check("repairWall-" .. i .. "-var", t.var.await_server("varb" .. (2099 + i) .. "_swansong_wall_" .. i, 1, 30))
        end
        t.player.drop("hammer")
        t.ticks(2)
        local _, sharks_after_walls = t.inv.count("shark")
        t.check("dropHammer-slots", t.inv.expect_absent("hammer"), "hammer dropped after the fifth wall; sharks carried: " .. tostring(sharks_after_walls))
        t.exec("goto-talkToFranklinAgain", t.player.goto_tile, 2341, 3668, 0)
        t.exec("talkToFranklinAgain", t.player.talk_to, "swan_franklin", 1)
        t.exec("talkToFranklinAgain-dialog", t.chat.play, {
            "player:The wall's fully repaired",
            "npc:Excellent work",
        })
        t.ticks(2)
        t.check("talkToFranklinAgain-var", t.var.varbit("varb2099_swansong_franklin"))

        t.exec("goto-talkToArnold", t.player.goto_tile, 2329, 3687, 0)
        t.exec("talkToArnold", t.player.talk_to, "swan_arnold", 1)
        t.exec("talkToArnold-dialog", t.chat.play, {
            "player:Herman said you could use a hand",
            "npc:Our stores contain not a bit",
            "npc:Here, take this net",
        })
        t.ticks(2)
        t.check("talkToArnold-net", t.inv.has("net"))

        -- catch 5 monkfish at the fishing spot (the first cast wakes a troll), cook at the stove
        t.check("fishSpot", t.world.loc_near("swan_fish", 80))
        t.check("stove", t.world.loc_near("swan_stove", 80))
        t.exec("fish-cast-0", t.player.click_loc, "swan_fish", 1)
        t.ticks(3)
        t.check("fish-troll-present", t.npc.tiles("swan_troll_ambush", 15))
        t.exec("fish-troll-attack", t.player.attack, "swan_troll_ambush", 2, 20)
        t.exec("fish-troll-dead", t.npc.await_dead_engaged, 120, 20, { eat = { item = "shark", below = 50 } })
        t.exec("pickUpBones-4", t.player.click_obj, "bones", 3)
        t.check("pickUpBones-4-count", t.inv.count("bones"))
        t.ticks(2)
        for i = 1, 5 do
            t.exec("fish-cast-" .. i, t.player.click_loc, "swan_fish", 1)
            t.check("fish-cast-" .. i .. "-raw", t.inv.await("swan_raw_monkfish", i, 20))
        end
        -- the stove (2316,3668) sits in a walled building the west side cannot reach: stand inside
        t.exec("goto-stoveDoor", t.player.goto_tile, 2324, 3667, 0)
        t.exec("openSwanBuildingDoor", t.player.click_loc, "swan_building_door", 1)
        t.ticks(3)
        for i = 1, 5 do
            t.exec("cook-" .. i, t.player.click_loc, "swan_stove", 1)
            t.check("cook-" .. i .. "-cooked", t.inv.await("swan_monkfish", i, 20))
        end
        t.exec("goto-talkToArnoldFish", t.player.goto_tile, 2329, 3687, 0)
        t.exec("talkToArnoldFish", t.player.talk_to, "swan_arnold", 1)
        t.exec("talkToArnoldFish-dialog", t.chat.play, {
            "player:Here are some fresh monkfish",
            "npc:That's five now",
        })
        t.ticks(2)
        t.check("talkToArnoldFish-var", t.var.varbit("varb2105_swansong_arnold"))
        t.player.drop("net")
        t.ticks(3)
        t.check("dropNet-slots", t.inv.expect_absent("net"), "fishing net dropped after the five monkfish to keep slots for food")

        t.exec("goto-talkToHermanTasks", t.player.goto_tile, 2354, 3682, 0)
        t.exec("talkToHermanTasks", t.player.talk_to, "swan_herman", 1)
        t.exec("talkToHermanTasks-dialog", t.chat.play, {
            "npc:Franklin and Arnold both say",
        })
        t.ticks(2)
        t.expect("quest.stage.tasks_done", t.quest.expect_stage("tasks_done"))
        t.exec("talkToHermanAfterTasks", t.player.talk_to, "swan_herman", 1)
        t.exec("talkToHermanAfterTasks-dialog", t.chat.play, {
            "npc:Franklin and Arnold both speak well",
            "npc:I know of a wizard",
        })

        t.exec("goto-wizardsGuildDoor", t.player.goto_tile, 2583, 3088, 0)
        t.exec("wizardsGuildDoor", t.player.click_loc, "magicguild_door_l", 1)
        t.ticks(3)
        t.check("wizardsGuildDoor-tile", t.world.tile())
        t.exec("enterWizardsBasement", t.player.click_loc, "ladder_cellar", 1, { at = { 2594, 3085 } })
        t.ticks(3)
        t.check("enterWizardsBasement-tile", t.world.tile())
        t.exec("frumscone-present", t.npc.await_present, "wizard_frumscone", 15, 10)
        t.exec("talkToFruscone", t.player.talk_to, "wizard_frumscone", 1)
        t.exec("talkToFruscone-dialog", t.chat.play, {
            "player:I'm looking for a way to raise a defence",
            "npc:My magic zombies",
        })
        t.ticks(2)
        t.expect("quest.stage.frumscone_done", t.quest.expect_stage("frumscone_done"))

        -- Malignius wants 7 bones "from people and small monsters"; the sea trolls leave 4, so chickens give the rest
        t.exec("goto-chickenPen", t.player.goto_tile, 3228, 3298, 0)
        do
            local parts = {}
            for slot = 0, 27 do
                local _, row = t.inv.slot(slot)
                if row and row.count > 0 then
                    parts[#parts + 1] = row.name .. "x" .. tostring(row.count)
                end
            end
            t.check("pack-before-chickens", true, table.concat(parts, " "))
        end
        for i = 1, 3 do
            t.exec("chicken-attack-" .. i, t.player.attack, "chicken_brown", 2, 20)
            t.exec("chicken-dead-" .. i, t.npc.await_dead_engaged, 80, 20)
            t.exec("chicken-bones-" .. i, t.player.click_obj, "bones", 3)
        end
        t.check("bones-total", t.inv.count("bones"))
        t.exec("goto-talkToMalignius", t.player.goto_tile, 2993, 3270, 0)
        t.exec("talkToMalignius", t.player.talk_to, "elemental_wizard_boss", 1)
        t.exec("talkToMalignius-dialog", t.chat.play, {
            "player:I need help with saving a fishing colony",
            "npc:A fishing colony",
            "npc:You'll also need something airtight",
            "npc:Take this apron",
        })
        t.ticks(2)
        t.expect("quest.stage.malignius_first", t.quest.expect_stage("malignius_first"))
        t.exec("wear-apron", t.player.equip, "brown_apron")

        t.exec("goto-craftingGuildDoor", t.player.goto_tile, 2932, 3289, 0)
        t.exec("craftingGuildDoor", t.player.click_loc, "craftingguilddoor", 1)
        t.ticks(3)
        t.check("craftingGuildDoor-tile", t.world.tile())
        t.exec("talkToCrafter", t.player.talk_to, "master_crafter_3", 1)
        t.exec("talkToCrafter-dialog", t.chat.play, {
            "player:Swan Song",
            "npc:Ah, one of Malignius",
            "player:Not really, no",
            "npc:Throw soft clay",
        })
        t.ticks(2)
        t.expect("quest.stage.crafter_done", t.quest.expect_stage("crafter_done"))

        t.exec("goto-potteryWheel", t.player.goto_tile, 2936, 3285, 0)
        t.exec("throwPot", t.player.use_on, "softclay", t.player.by_symbol("loc", "potterywheel"))
        t.check("throwPot-menu", t.ui.await_open("skillmulti", 10))
        local pot_cell_r, pot_cell = t.ui.widget("skillmulti:a")
        t.check("throwPot-cell", pot_cell_r == "ok", "cell a -> " .. tostring(pot_cell_r) .. " " .. tostring(pot_cell))
        t.check("throwPot-press", t.ui.invoke(pot_cell, 1), "invoked pot cell")
        t.exec("throwPot.made", t.inv.await, "pot_unfired", 1, 15)
        t.ticks(4)
        -- the second throw settles on no new page (the wheel is already in reach), so read the menu itself
        local lid_use_r, lid_use_d = t.player.use_on("softclay", t.player.by_symbol("loc", "potterywheel"))
        t.check("throwLid-menu", t.ui.await_open("skillmulti", 10))
        local lid_cell_r, lid_cell = t.ui.widget("skillmulti:f")
        t.check("throwLid-cell", lid_cell_r == "ok", "cell f -> " .. tostring(lid_cell_r) .. " " .. tostring(lid_cell))
        t.check("throwLid-press", t.ui.invoke(lid_cell, 1), "invoked lid cell")
        t.exec("throwLid.made", t.inv.await, "potlid_unfired", 1, 15)
        t.exec("firePot", t.player.use_on, "pot_unfired", t.player.by_symbol("loc", "potteryoven"))
        t.exec("firePot.fired", t.inv.await, "pot_empty", 1, 15)
        t.exec("fireLid", t.player.use_on, "potlid_unfired", t.player.by_symbol("loc", "potteryoven"))
        t.exec("fireLid.fired", t.inv.await, "potlid", 1, 15)
        t.exec("makeAirtightPot", t.player.use_item_on_item, "pot_empty", "potlid")
        t.check("makeAirtightPot-item", t.inv.await("favour_airtight_pot", 1, 10))
        t.expect("quest.stage.pot_ready", t.quest.expect_stage("pot_ready"))

        t.exec("goto-talkToMaligniusWithPot", t.player.goto_tile, 2993, 3270, 0)
        t.exec("talkToMaligniusWithPot", t.player.talk_to, "elemental_wizard_boss", 1)
        t.exec("talkToMaligniusWithPot-dialog", t.chat.play, {
            "player:I've spoken to the master crafter",
            "npc:Excellent. Behold",
        })
        t.ticks(2)
        t.expect("quest.stage.army_ready", t.quest.expect_stage("army_ready"))
        t.exec("goto-talkToHermanWithPot", t.player.goto_tile, 2354, 3682, 0)
        t.exec("talkToHermanWithPot", t.player.talk_to, "swan_herman", 1)
        t.exec("talkToHermanWithPot-dialog", t.chat.play, {
            "player:I have the bone seeds",
            "npc:Then we have our army",
        })
        t.ticks(2)
        t.expect("quest.stage.final_talk", t.quest.expect_stage("final_talk"))
        t.exec("talkToHermanForFinalFight", t.player.talk_to, "swan_herman", 1)
        t.exec("talkToHermanForFinalFight-dialog", t.chat.play, {
            "npc:The Sea Troll Queen herself",
            "choose:I'm ready. Let's fight!",
            "player:I'm ready. Let's fight!",
            "npc:Then let's go",
        })
        t.ticks(2)
        t.expect("quest.stage.queen_fight", t.quest.expect_stage("queen_fight"))
        t.exec("goto-killQueen", t.player.goto_tile, 2347, 3701, 0)
        t.exec("killQueen-present", t.npc.await_present, "swan_seatroll_queen", 15, 10)
        t.cheat("::swansong_queen_hp")
        t.check("killQueen-hp-server", t.msg.expect("Sea Troll Queen hitpoints 200/200"))
        local _, food_at_queen = t.inv.count("shark")
        t.check("killQueen-food", true, "sharks carried to the Queen: " .. tostring(food_at_queen))
        local eaten_before = 0
        local lowest_hp = 99
        for _ = 1, 6 do
            local hr, hp = t.skill.read("hitpoints")
            local cur = hp and (hp.current or hp.level or hp.boosted)
            if hr ~= "ok" or not cur then break end
            if cur < lowest_hp then lowest_hp = cur end
            if cur > 79 then break end
            t.player.inv_op("shark", 1)
            eaten_before = eaten_before + 1
            t.ticks(3)
        end
        local _, hr_full = t.skill.read("hitpoints")
        local hp_full = hr_full and (hr_full.current or hr_full.level or hr_full.boosted)
        local _, food_after_topup = t.inv.count("shark")
        t.check("killQueen-eat-to-full", hp_full ~= nil and hp_full >= 80, "hp before the first Attack: " .. tostring(hp_full) .. "/99 after eating " .. eaten_before .. " shark(s); sharks left " .. tostring(food_after_topup))
        t.exec("killQueen-attack", t.player.attack, "swan_seatroll_queen", 2, 20)
        t.exec("killQueen-dead", t.npc.await_dead_engaged, 400, 40, { eat = { item = "shark", below = 60 } })
        local _, sharks_left = t.inv.count("shark")
        local _, hp_end = t.skill.read("hitpoints")
        local hp_now = hp_end and (hp_end.current or hp_end.level or hp_end.boosted)
        t.check("killQueen-margin", (sharks_left or 0) >= 2 or (hp_now or 0) > 25,
            "sharks staged 15, at the Queen " .. tostring(food_at_queen) .. ", eaten before attack " .. eaten_before .. ", left " .. tostring(sharks_left) .. ", hp after the kill " .. tostring(hp_now) .. "/99 (margin: sharks left >= 2 or hp > 25)")
        t.check("killQueen-stage", t.var.await("varb2098_swansong", 190, 20))
        t.ticks(3)
        t.expect("quest.stage.queen_dead", t.quest.expect_stage("queen_dead"))

        local _, xp_before = t.skill.snapshot()
        local _, coins_before = t.inv.count("coins")
        t.exec("goto-talkToHermanToFinish", t.player.goto_tile, 2354, 3682, 0)
        t.exec("talkToHermanToFinish", t.player.talk_to, "swan_herman", 1)
        t.exec("talkToHermanToFinish-dialog", t.chat.play, {
            "player:It's done",
            "npc:You have saved my Fishing Colony",
            "npc:You are hereby welcome",
        })
        t.ticks(3)
        t.quest.expect_complete()
        t.check("reward.magic_xp", t.skill.expect_gain("magic", 15000, xp_before))
        t.check("reward.prayer_xp", t.skill.expect_gain("prayer", 10000, xp_before))
        t.check("reward.fishing_xp", t.skill.expect_gain("fishing", 50000, xp_before))
        local _, coins_after = t.inv.count("coins")
        t.check("reward.coins", coins_after - coins_before == 25000, "coins " .. tostring(coins_before) .. " -> " .. tostring(coins_after) .. " (expected +25000)")
        t.finish(0)
    end,
}
