-- Generated by tools/quest_gate/new_quest.py from Quest Helper's
-- helpers/quests/lostcity/ -- docs/QUEST_SUITE_KIT.md phase 3.
-- Reviewed against the quest scripts. Tier (quest_inventory.tsv): 3.
-- Items from getItemRequirements(): 2 given in setup (::give), 0 left as gather markers (Quest Helper canBeObtainedDuringQuest()).
-- Setup always starts with ::clearinv: the fresh character carries fourteen
-- slots of tutorial kit that block a non-stackable requirement fitting in the backpack.
-- Rewards from Quest Helper: 0 experience, 0 item, quest points 3 (QuestPointReward).
--
-- Fixture start: fresh_lumbridge.ini stands the player at 3206,3233,0 (Lumbridge, beside
-- Hans). Every step below carries its own Quest Helper WorldPoint; the
-- FIRST emitted t.player.goto_tile is what actually leaves that tile.
--
-- Three rules the first pilot pass broke -- read before touching this file:
-- (a) "blocked" means a t.blocked("...") row followed by return -- a file
--     that runs on to expect_complete() after a failure is rejected.
-- (b) a talk_to/click answering screen_position or not_visible means you
--     are not standing near the target -- fix the goto, not the verb.
-- (c) never add a fixture or a helper file -- this quest file is the only
--     file you edit.

return {
    id = "zanaris",
    fixture = "fresh_lumbridge.ini",
    setup = {
        "::clearinv", -- the fixture's fourteen tutorial slots, so a requirement fits
        "::give bronze_axe 1",
        "::give knife 1",
        "::setlevel crafting 31",
        "::setlevel woodcutting 36",
        "::setlevel attack 99",
        "::setlevel strength 99",
        "::setlevel defence 99",
        "::setlevel hitpoints 99",
        "::give shark 20",
        "::setlevel magic 31",
        "::give lawrune 1",
        "::give airrune 3",
        "::give earthrune 1",
    },

    run = function(t)
        local bind_result, bind_detail = t.quest.bind({
            varp = "varp147_zanaris",
            constants = {
                complete = 6,
                not_started = 0,
                spirit_defeated = 3,
                spoken_shamus = 2,
                staff_made = 5,
                started = 1,
                tree_chopped = 4,
            },
            row = "quest_lostcity",
            display = "Lost City",
            points = 3,
        })
        t.step("quest.bind", bind_result == "ok" and "PASS" or "FAIL", bind_detail)

        t.ticks(3)
        t.expect("quest.stage.not_started", t.quest.expect_stage("not_started"))

        t.exec("goto-talkToWarrior", t.player.goto_tile, 3149, 3207, 0)
        t.exec("talkToWarrior", t.player.talk_to, "warrioradventurerpg", 1)
        t.exec("talkToWarrior-dialog", t.chat.play, {
            "npc:Hello there traveller.",
            "choose:What are you camped here for?",
            "player:What are you camped here for?",
            "npc:We're looking for Zanaris",
            "choose:What makes you think it's out here?",
            "player:What makes you think it's out here?",
            "npc:Don't you know of the legends",
            "choose:If it's hidden how are you planning to find it?",
            "player:If it's hidden how are you planning to find it?",
            "npc:Well, we don't want to tell anyone",
            "choose:Looks like you don't know either.",
            "player:Well, it looks to me like YOU",
            "npc:Of course we know!",
            "player:Leprechaun?",
            "npc:GAH! I didn't mean",
            "player:So a leprechaun knows",
            "npc:Ye.. uh, no.",
            "player:Thanks for the help!",
            "npc:Help? What help?",
        })
        t.ticks(2)
        t.expect("quest.stage.started", t.quest.expect_stage("started"))

        t.exec("goto-chopTree", t.player.goto_tile, 3140, 3213, 0)
        local chop_result, chop_detail = t.player.click_loc("leprechauntree", 1)
        t.check("chopTree-swing", chop_result == "ok" or chop_result == "timeout", "click_loc leprechauntree -> " .. tostring(chop_result) .. " " .. tostring(chop_detail))
        t.exec("chopTree", t.npc.await_present, "zanarisleprechaun", 15, 10)
        t.exec("talkToShamus", t.player.talk_to, "zanarisleprechaun", 1)
        t.exec("talkToShamus-dialog", t.chat.play, {
            "npc:Ay yer big elephant!",
            "player:I want to find Zanaris.",
            "npc:Zanaris is it now?",
            "player:...but... I thought",
            "npc:Aye that it is!",
            "choose:I've been in that shed, I didn't see a city.",
            "player:I've been in that shed.",
            "npc:Oh, was I fergetting to say?",
            "player:So where would I get a staff?",
            "npc:Dramenwood staffs are crafted",
            "npc:or some such.",
            "npc:The monks are running a ship",
            "mesbox:The leprechaun magically disappears.",
        })
        t.ticks(2)
        t.expect("quest.stage.spoken_shamus", t.quest.expect_stage("spoken_shamus"))

        -- Bank the axe (the guide banks weapons before Entrana): dropped here, the zombies give one back.
        t.exec("goToEntrana-bankAxe", t.player.drop, "bronze_axe")
        t.ticks(2)
        t.exec("goto-goToEntrana", t.player.goto_tile, 3049, 3236, 0)
        t.exec("goToEntrana", t.player.talk_to, "shipmonk1_c", 1)
        t.exec("goToEntrana-dialog", t.chat.play, {
            "npc:Do you seek passage to holy En",
            "choose:Yes, okay, I'm ready to go.",
            "player:Yes, okay, I'm ready to go.",
            "npc:Very well. One moment please.",
            "mesbox:The monk quickly searches you.",
        })
        t.ticks(3)
        local _, boat_tile = t.world.tile()
        t.check("goToEntrana-landed", boat_tile.x < 2900 and boat_tile.z < 3500, "tile after boat: " .. boat_tile.x .. "," .. boat_tile.z)
        t.exec("goto-goDownHole", t.player.goto_tile, 2820, 3374, 0)
        t.exec("goDownHole", t.player.click_loc, "entranaladdertop", 1)
        t.exec("goDownHole-dialog", t.chat.play, {
            "npc:Be careful going in there!",
            "npc:so our prayers seem",
            "npc:The only exit from the caves",
            "choose:Well that is a risk I will have to take.",
            "player:Well that is a risk I will have to take.",
        })
        t.ticks(3)
        local _, cave_tile = t.world.tile()
        t.check("goDownHole-landed", cave_tile.z > 9000, "tile after ladder: " .. cave_tile.x .. "," .. cave_tile.z)

        -- getAxe: kill zombies until one drops a bronze axe (50/128 per kill).
        local zombies = { "zombie_entranan", "zombie_entranan2", "zombie_entranan3", "zombie_entranan4", "zombie_entranan5" }
        local axe_found = false
        local hunt_log = {}
        for attempt = 1, 14 do
            local zombie = zombies[((attempt - 1) % 5) + 1]
            local attack_result, attack_detail = t.player.attack(zombie, 2, 20)
            if attack_result == "ok" then
                local kill_result, kill_detail = t.npc.await_dead_engaged(150, 8, { eat = { item = "shark", below = 30 } })
                hunt_log[#hunt_log + 1] = zombie .. ":" .. kill_result
                t.ticks(3)
                local obj_result = t.world.obj_near("bronze_axe", 8)
                if obj_result == "ok" then
                    axe_found = true
                    break
                end
            else
                hunt_log[#hunt_log + 1] = zombie .. ":attack " .. attack_result .. " " .. tostring(attack_detail)
            end
        end
        t.check("getAxe-hunt", axe_found, "hunt: " .. table.concat(hunt_log, "; "))
        t.exec("pickupAxe", t.player.click_obj, "bronze_axe", 3)
        t.exec("pickupAxe-count", t.inv.await, "bronze_axe", 1, 10)

        t.exec("goto-attemptToCutDramen", t.player.goto_tile, 2862, 9733, 0)
        local dramen_result, dramen_detail = t.player.click_loc("dramentree", 1)
        t.check("attemptToCutDramen-swing", dramen_result == "ok" or dramen_result == "timeout", "click_loc dramentree -> " .. tostring(dramen_result) .. " " .. tostring(dramen_detail))
        t.exec("attemptToCutDramen", t.npc.await_present, "tree_spirit", 15, 10)
        t.exec("killDramenSpirit-attack", t.player.attack, "tree_spirit", 2, 20)
        t.exec("killDramenSpirit", t.npc.await_dead_engaged, 400, 12, { eat = { item = "shark", below = 35 } })
        t.ticks(3)
        t.exec("killDramenSpirit-dialog", t.chat.drain, { max_pages = 8 })
        t.expect("quest.stage.spirit_defeated", t.quest.expect_stage("spirit_defeated"))

        local cut_result, cut_detail = t.player.click_loc("dramentree", 1)
        t.check("cutDramenBranch-swing", cut_result == "ok" or cut_result == "timeout", "click_loc dramentree -> " .. tostring(cut_result) .. " " .. tostring(cut_detail))
        t.exec("cutDramenBranch", t.inv.await, "dramen_branch", 1, 15)
        t.expect("quest.stage.tree_chopped", t.quest.expect_stage("tree_chopped"))

        t.exec("cast-teleportAway", t.player.cast, "lumbridge_teleport")
        t.ticks(3)
        t.exec("craftBranch", t.player.use_item_on_item, "knife", "dramen_branch")
        t.exec("craftBranch-count", t.inv.await, "dramen_staff", 1, 10)
        t.expect("quest.stage.staff_made", t.quest.expect_stage("staff_made"))
        t.exec("craftBranch-equip", t.player.equip, "dramen_staff")
        t.ticks(2)

        t.exec("goto-enterZanaris", t.player.goto_tile, 3202, 3171, 0)
        local door_result, door_detail = t.player.click_loc("zanarisdoor", 1)
        t.check("enterZanaris", door_result == "ok" or door_result == "timeout", "click_loc zanarisdoor -> " .. tostring(door_result) .. " " .. tostring(door_detail))
        t.ticks(6)
        local _, zanaris_tile = t.world.tile()
        t.check("enterZanaris-landed", zanaris_tile.x < 2600, "tile after the shed door: " .. zanaris_tile.x .. "," .. zanaris_tile.z)
        t.quest.expect_complete()
        t.finish(0)
        return
    end,
}
