#ifndef TORIRS_PLUGIN_HOST_TYPES_H
#define TORIRS_PLUGIN_HOST_TYPES_H

/*
 * Engine-facing values used by the plugin host implementation. They are not
 * part of the public plugin contract; V2 plugins address these through
 * ToriRS_Surface, named UI, frame builders, and placement areas.
 */

enum ToriRS_HostSurfaceSlot
{
    TORIRS_HOST_SURFACE_VIEWPORT = 0,
    TORIRS_HOST_SURFACE_MINIMAP,
    TORIRS_HOST_SURFACE_COMPASS,
    TORIRS_HOST_SURFACE_CHAT,
    TORIRS_HOST_SURFACE_SIDEBAR,
    TORIRS_HOST_SURFACE_MODAL,
    TORIRS_HOST_SURFACE_CHAT_BUTTONS,
    TORIRS_HOST_SURFACE_ORBS,
    TORIRS_HOST_SURFACE_PLACEABLE_COUNT,
    TORIRS_HOST_SURFACE_CANVAS = TORIRS_HOST_SURFACE_PLACEABLE_COUNT,
    TORIRS_HOST_SURFACE_COUNT
};

/*
 * Members of TORIRS_HOST_SURFACE_ORBS, spelled again from enum
 * ToriRS_OrbsMember. The tree needs the numbering -- the two kinds of member
 * mean different things by an unmentioned box -- and a headless uitree test
 * links no plugin contract to read it from. Kept true by the static asserts
 * in torirs_plugin_host.c, which sees both headers.
 */
enum ToriRS_HostOrbsMember
{
    TORIRS_HOST_ORBS_MEMBER_ACTIVITY_ADVISER = 0,
    TORIRS_HOST_ORBS_MEMBER_WORLD_MAP,
    TORIRS_HOST_ORBS_MEMBER_WIKI,
    TORIRS_HOST_ORBS_MEMBER_COUNT
};

#define TORIRS_HOST_LANE_CHROME_MAX 8
#define TORIRS_HOST_RESERVATION_NAME_MAX 64

enum ToriRS_HostPanelWidgetKind
{
    TORIRS_PANEL_WIDGET_LABEL = 0,
    TORIRS_PANEL_WIDGET_CHECKBOX,
    TORIRS_PANEL_WIDGET_INPUT,
    TORIRS_PANEL_WIDGET_DROPDOWN,
    TORIRS_PANEL_WIDGET_BUTTON,
    TORIRS_PANEL_WIDGET_SEPARATOR,
    TORIRS_PANEL_WIDGET_SECTION,
    TORIRS_PANEL_WIDGET_PARAGRAPH,
    TORIRS_PANEL_WIDGET_KEY_VALUE,
    TORIRS_PANEL_WIDGET_TOGGLE,
    TORIRS_PANEL_WIDGET_TEXTAREA,
    TORIRS_PANEL_WIDGET_LIST_ROW,
    TORIRS_PANEL_WIDGET_IMAGE,
    TORIRS_PANEL_WIDGET_PROGRESS,
    TORIRS_PANEL_WIDGET_ERROR,
    TORIRS_PANEL_WIDGET_CUSTOM,
    TORIRS_PANEL_WIDGET_ACTION_ROW,
    TORIRS_PANEL_WIDGET_COUNT
};

enum ToriRS_HostModelSource
{
    TORIRS_HOST_MODEL_CACHE = 0,
    TORIRS_HOST_MODEL_ASSET,
    TORIRS_HOST_MODEL_MESH,
    TORIRS_HOST_MODEL_SPOTANIM
};

#endif /* TORIRS_PLUGIN_HOST_TYPES_H */
