# Shared task object sources for Makefiles (paths relative to repo root via $(SRC2)).
TORIAUXLIB_TASK_SOURCES = \
	$(SRC2)/toriauxlib/core/tasks/instance_revconfig_context.c \
	$(SRC2)/toriauxlib/core/tasks/component_load_common.c \
	$(SRC2)/toriauxlib/core/tasks/task_cache_wrappers.c \
	$(SRC2)/toriauxlib/core/tasks/dat1/task_dat1_model_load.c \
	$(SRC2)/toriauxlib/core/tasks/dat1/task_dat1_animate.c \
	$(SRC2)/toriauxlib/core/tasks/dat1/task_dat1_npc_add.c \
	$(SRC2)/toriauxlib/core/tasks/dat1/task_dat1_player_add.c \
	$(SRC2)/toriauxlib/core/tasks/dat1/task_dat1_projectile_add.c \
	$(SRC2)/toriauxlib/core/tasks/dat1/task_dat1_world_rebuild_core.c \
	$(SRC2)/toriauxlib/core/tasks/dat1/task_dat1_world_rebuild_centerzone.c \
	$(SRC2)/toriauxlib/core/tasks/dat1/task_dat1_world_rebuild_chunk_list.c \
	$(SRC2)/toriauxlib/core/tasks/dat1/task_dat1_component_load.c \
	$(SRC2)/toriauxlib/core/tasks/dat1/task_dat1_inv_load.c \
	$(SRC2)/toriauxlib/core/tasks/dat1/task_dat1_sprite_load.c \
	$(SRC2)/toriauxlib/core/tasks/dat1/task_dat1_font_load.c \
	$(SRC2)/toriauxlib/core/tasks/dat1/task_dat1_td_model_load.c \
	$(SRC2)/toriauxlib/core/tasks/dat1/task_dat1_td_textures_load.c \
	$(SRC2)/toriauxlib/core/tasks/dat1/task_dat1_td_animations_load.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_model_load.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_animate.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_npc_add.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_player_add.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_projectile_add.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_world_rebuild_core.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_world_rebuild_centerzone.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_world_rebuild_chunk_list.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_anim_resolve.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_textures_load.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_config_entry_load.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_clientscript_load.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_cs2_run.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_component_load.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_inv_load.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_sprite_load.c \
	$(SRC2)/toriauxlib/core/tasks/dat2/task_dat2_font_load.c \
	$(SRC2)/toriauxlib/core/tasks/task_instance_on_rc.c \
	$(SRC2)/toriauxlib/core/tasks/task_instance_revconfig_load.c \
	$(SRC2)/toriauxlib/core/tasks/instance_revconfig_inv_bind.c
