/*
 * RSCache unity build anchor — compile this single file to build the library.
 */
#include "rscache.h"

// clang-format off
#include "../bzip/bzip.c"
#include "../miniz/miniz.c"
#include "../xteas/xteas.c"
#include "src/compression.c"
#include "src/rsbuffer.c"
#include "src/archive.c"
#include "src/reference_table.c"
#include "src/xtea_config.c"
#include "src/dat2disk.c"
#include "src/dat1disk.c"
#include "src/filelist.c"
#include "src/datatypes/mapsquares.c"
#include "src/datatypes/noise.c"
#include "src/datatypes/maps.c"
#include "src/datatypes/model.c"
#include "src/datatypes/dat2_component.c"
#include "src/datatypes/cs2_opcode_decode.c"
#include "src/datatypes/cs2_script.c"
#include "src/datatypes/clientscript.c"
#include "src/datatypes/dat1_config_obj.c"
#include "src/datatypes/dat1_config_idk.c"
#include "src/datatypes/dat1_config_npc.c"
#include "src/datatypes/dat2_config_obj.c"
#include "src/datatypes/dat2_config_idk.c"
#include "src/datatypes/dat2_config_npc.c"
#include "src/datatypes/dat2_config_loc.c"
#include "src/datatypes/dat2_config_flo.c"
#include "src/datatypes/dat2_texture.c"
#include "src/datatypes/dat2_sprites.c"
#include "src/datatypes/dat2_config_enum.c"
#include "src/datatypes/dat2_config_struct.c"
// clang-format on
