/*
 * RSCache unity build anchor — compile this single file to build the library.
 */
#include "rscache.h"

// clang-format off
#include "src/rscache_profile.c"
#include "src/checksum.c"
#include "src/whirlpool.c"
#include "src/compression.c"
#include "src/rsbuffer.c"
#include "src/archive.c"
#include "src/reference_table.c"
#include "src/xtea_config.c"
#include "src/dat2disk.c"
#include "src/cache_edit.c"
#include "src/dat1disk.c"
#include "src/filelist.c"
#include "src/datatypes/mapsquares.c"
#include "src/datatypes/noise.c"
#include "src/datatypes/maps.c"
#include "src/datatypes/model.c"
#include "src/datatypes/dat2_component.c"
#include "src/datatypes/cs2_opcode_decode.c"
#include "src/datatypes/cs2_script.c"
#include "src/datatypes/clientscript.c"
#include "src/datatypes/dat1_config_obj.c"
#include "src/datatypes/dat1_config_idk.c"
#include "src/datatypes/dat1_config_npc.c"
#include "src/datatypes/dat1_config_spotanim.c"
#include "src/datatypes/dat2_config_spotanim.c"
#include "src/datatypes/dat2_config_obj.c"
#include "src/datatypes/dat2_config_idk.c"
#include "src/datatypes/dat2_config_npc.c"
#include "src/datatypes/dat2_entity_ops.c"
#include "src/datatypes/dat2_config_bas.c"
#include "src/datatypes/dat2_config_loc.c"
#include "src/datatypes/dat2_config_flo.c"
#include "src/datatypes/dat2_texture.c"
#include "src/datatypes/dat2_proctexture.c"
#include "src/datatypes/dat2_sprites.c"
#include "src/datatypes/dat2_config_enum.c"
#include "src/datatypes/dat2_config_struct.c"
#include "src/datatypes/dat2_config_db.c"
#include "src/datatypes/dat2_config_param.c"
#include "src/datatypes/dat2_config_var.c"
#include "src/datatypes/dat2_config_inv.c"
#include "src/datatypes/dat2_config_healthbar.c"
#include "src/datatypes/dat2_config_hitsplat.c"
#include "src/datatypes/dat2_config_mapelement.c"
#include "src/datatypes/dat2_worldmap.c"
#include "src/datatypes/dat2_framemap.c"
#include "src/datatypes/dat2_frame.c"
#include "src/datatypes/dat2_config_sequence.c"
#include "src/datatypes/dat2_animaya.c"
#include "src/datatypes/dat2_skeletalbase.c"
#include "src/datatypes/dat1_anim_frame.c"
#include "src/datatypes/dat1_config_seq.c"
#include "src/datatypes/dat1_pix8.c"
#include "src/datatypes/dat1_pix32.c"
#include "src/datatypes/dat1_pix_font.c"
#include "src/datatypes/dat2_font_metrics.c"
#include "src/datatypes/dat1_config_component.c"
#include "src/datatypes/dat1_version_list.c"
/* Revision modules last: they sit above the datatypes and name the codecs they
 * bind, so they must see every datatype header. */
#include "src/revisions/revisions.c"
#include "src/revisions/rev_dat1_lc245_2.c"
#include "src/revisions/rev_dat1_lc254.c"
#include "src/revisions/rev_dat2_osrs184_kronos.c"
#include "src/revisions/rev_dat2_osrs230.c"
#include "src/revisions/rev_dat2_osrs231.c"
#include "src/revisions/rev_dat2_osrs232.c"
#include "src/revisions/rev_dat2_osrs233.c"
#include "src/revisions/rev_dat2_osrs234.c"
#include "src/revisions/rev_dat2_osrs235.c"
#include "src/revisions/rev_dat2_osrs236.c"
#include "src/revisions/rev_dat2_osrs237.c"
#include "src/revisions/rev_dat2_osrs238.c"
#include "src/revisions/rev_dat2_osrs239.c"
#include "src/revisions/rev_dat2_rs643.c"
// clang-format on
