/*
 * RSCache unity build anchor — compile this single file to build the library.
 */
#include "rscache.h"

// clang-format off
#include "src/compression.c"
#include "src/rsbuffer.c"
#include "src/archive.c"
#include "src/reference_table.c"
#include "src/xtea_config.c"
#include "src/dat2disk.c"
#include "src/dat1disk.c"
#include "src/filelist.c"
#include "src/datatypes/mapsquares.c"
#include "src/datatypes/noise.c"
#include "src/datatypes/maps.c"
#include "src/datatypes/model.c"
#include "src/datatypes/dat2_component.c"
#include "src/datatypes/cs2_opcode_decode.c"
#include "src/datatypes/cs2_script.c"
#include "src/datatypes/clientscript.c"
#include "src/datatypes/dat1_config_obj.c"
#include "src/datatypes/dat1_config_idk.c"
#include "src/datatypes/dat1_config_npc.c"
#include "src/datatypes/dat1_config_spotanim.c"
#include "src/datatypes/dat2_config_spotanim.c"
#include "src/datatypes/dat2_config_obj.c"
#include "src/datatypes/dat2_config_idk.c"
#include "src/datatypes/dat2_config_npc.c"
#include "src/datatypes/dat2_config_loc.c"
#include "src/datatypes/dat2_config_flo.c"
#include "src/datatypes/dat2_texture.c"
#include "src/datatypes/dat2_sprites.c"
#include "src/datatypes/dat2_config_enum.c"
#include "src/datatypes/dat2_config_struct.c"
#include "src/datatypes/dat2_config_param.c"
#include "src/datatypes/dat2_config_mapelement.c"
#include "src/datatypes/dat2_worldmap.c"
#include "src/datatypes/dat2_framemap.c"
#include "src/datatypes/dat2_frame.c"
#include "src/datatypes/dat2_config_sequence.c"
#include "src/datatypes/dat2_animaya.c"
#include "src/datatypes/dat1_anim_frame.c"
#include "src/datatypes/dat1_config_seq.c"
#include "src/datatypes/dat1_pix8.c"
#include "src/datatypes/dat1_pix32.c"
#include "src/datatypes/dat1_pix_font.c"
#include "src/datatypes/dat1_config_component.c"
// clang-format on
