#ifndef PACKETOUT_LC254_H
#define PACKETOUT_LC254_H

#include "net/rev/pktnames.h"

/* Client -> server wire opcodes of the authoritative LostCity_Server build
 * (engine/src/network/game/client/ClientGameProt.ts). */

#ifndef PACKET_OUT_DEFINITION
struct PacketOutDefinition
{
    int name; /* canonical GameProtoPktOutName */
    int code; /* wire opcode */
};
#define PACKET_OUT_DEFINITION(name, code) { name, code }
#endif

static const struct PacketOutDefinition g_packet_out_definitions_lc254[] = {
    PACKET_OUT_DEFINITION(PKTOUT_NAME_NO_TIMEOUT, 239),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_IDLE_TIMER, 144),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_EVENT_MOUSE_CLICK, 234),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_EVENT_MOUSE_MOVE, 232),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_EVENT_APPLET_FOCUS, 8),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_EVENT_TRACKING, 142),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_EVENT_CAMERA_POSITION, 91),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC1, 28),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC2, 77),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC3, 56),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC4, 121),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC5, 233),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC6, 131),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC7, 187),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC8, 206),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC9, 162),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_CYCLELOGIC1, 51),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_CYCLELOGIC2, 225),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_CYCLELOGIC3, 4),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_CYCLELOGIC4, 226),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_CYCLELOGIC5, 100),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_CYCLELOGIC6, 36),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_CYCLELOGIC7, 182),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPOBJ1, 141),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPOBJ2, 67),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPOBJ3, 178),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPOBJ4, 47),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPOBJ5, 97),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPOBJT, 202),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPOBJU, 245),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPNPC1, 143),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPNPC2, 195),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPNPC3, 69),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPNPC4, 122),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPNPC5, 118),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPNPCT, 231),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPNPCU, 119),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPLOC1, 33),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPLOC2, 213),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPLOC3, 98),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPLOC4, 87),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPLOC5, 147),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPLOCT, 26),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPLOCU, 240),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPPLAYER1, 192),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPPLAYER2, 17),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPPLAYER3, 18),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPPLAYER4, 72),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPPLAYER5, 230),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPPLAYERT, 68),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPPLAYERU, 113),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPHELD1, 243),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPHELD2, 228),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPHELD3, 80),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPHELD4, 163),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPHELD5, 74),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPHELDT, 102),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPHELDU, 200),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_INV_BUTTON1, 181),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_INV_BUTTON2, 70),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_INV_BUTTON3, 59),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_INV_BUTTON4, 160),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_INV_BUTTON5, 62),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_INV_BUTTOND, 176),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_IF_BUTTON, 244),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_RESUME_PAUSEBUTTON, 146),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_CLOSE_MODAL, 58),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_RESUME_P_COUNTDIALOG, 161),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_TUT_CLICKSIDE, 201),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_MAP_BUILD_COMPLETE, 134),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_MOVE_OPCLICK, 127),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_REPORT_ABUSE, 203),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_MOVE_MINIMAPCLICK, 220),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_MOVE_GAMECLICK, 6),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_IGNORELIST_DEL, 193),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_IGNORELIST_ADD, 189),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_FRIENDLIST_DEL, 84),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_FRIENDLIST_ADD, 9),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_IDK_SAVEDESIGN, 13),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_CHAT_SETMODE, 129),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_MESSAGE_PRIVATE, 214),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_MESSAGE_PUBLIC, 83),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_CLIENT_CHEAT, 86),
};

#define PACKET_OUT_DEFINITION_COUNT_LC254 \
    ((int)(sizeof(g_packet_out_definitions_lc254) / sizeof(g_packet_out_definitions_lc254[0])))

/** Canonical PKTOUT_NAME_* -> wire opcode; -1 = absent from this rev. */
static inline int
packetout_code_lc254(int pkt_out_name)
{
    for( int i = 0; i < PACKET_OUT_DEFINITION_COUNT_LC254; i++ )
    {
        if( g_packet_out_definitions_lc254[i].name == pkt_out_name )
        {
            return g_packet_out_definitions_lc254[i].code;
        }
    }
    return -1;
}

#endif
