#ifndef PACKETIN_LC254_H
#define PACKETIN_LC254_H

#include "net/rev/pktnames.h"

#include <assert.h>
#include <stdint.h>

#ifndef PKTIN_LENGTH_VARU8
#define PKTIN_LENGTH_VARU8 (-1)
#define PKTIN_LENGTH_VARU16 (-2)
#endif

/* Wire opcodes of the authoritative LostCity_Server build (Engine-TS branch
 * 254; engine/src/network/game/server/ServerGameProt.ts + zone sub-packets
 * from ServerGameZoneProt.ts). VARP_SYNC is that server's name for
 * RESET_CLIENT_VARCACHE and P_LOCMERGE for LOC_MERGE. */
enum PacketInType_LC254
{
    PKTIN_LC254_IF_OPENCHAT = 141,
    PKTIN_LC254_IF_OPENMAIN_SIDE = 249,
    PKTIN_LC254_IF_CLOSE = 174,
    PKTIN_LC254_IF_SETTAB = 91,
    PKTIN_LC254_IF_OPENMAIN = 197,
    PKTIN_LC254_IF_OPENSIDE = 187,
    PKTIN_LC254_IF_SETTAB_ACTIVE = 138,
    PKTIN_LC254_IF_OPENOVERLAY = 85,
    PKTIN_LC254_IF_SETCOLOUR = 38,
    PKTIN_LC254_IF_SETHIDE = 227,
    PKTIN_LC254_IF_SETOBJECT = 222,
    PKTIN_LC254_IF_SETMODEL = 211,
    PKTIN_LC254_IF_SETANIM = 95,
    PKTIN_LC254_IF_SETPLAYERHEAD = 161,
    PKTIN_LC254_IF_SETTEXT = 41,
    PKTIN_LC254_IF_SETNPCHEAD = 3,
    PKTIN_LC254_IF_SETPOSITION = 27,
    PKTIN_LC254_IF_SETSCROLLPOS = 14,
    PKTIN_LC254_TUT_FLASH = 58,
    PKTIN_LC254_TUT_OPEN = 239,
    PKTIN_LC254_UPDATE_INV_STOP_TRANSMIT = 168,
    PKTIN_LC254_UPDATE_INV_FULL = 28,
    PKTIN_LC254_UPDATE_INV_PARTIAL = 170,
    PKTIN_LC254_CAM_LOOKAT = 0,
    PKTIN_LC254_CAM_SHAKE = 225,
    PKTIN_LC254_CAM_MOVETO = 55,
    PKTIN_LC254_CAM_RESET = 167,
    PKTIN_LC254_NPC_INFO = 123,
    PKTIN_LC254_PLAYER_INFO = 87,
    PKTIN_LC254_FINISH_TRACKING = 29,
    PKTIN_LC254_ENABLE_TRACKING = 251,
    PKTIN_LC254_MESSAGE_GAME = 73,
    PKTIN_LC254_UPDATE_IGNORELIST = 63,
    PKTIN_LC254_CHAT_FILTER_SETTINGS = 24,
    PKTIN_LC254_MESSAGE_PRIVATE = 60,
    PKTIN_LC254_UPDATE_FRIENDLIST = 111,
    PKTIN_LC254_FRIENDLIST_LOADED = 255,
    PKTIN_LC254_UNSET_MAP_FLAG = 108,
    PKTIN_LC254_UPDATE_RUNWEIGHT = 164,
    PKTIN_LC254_HINT_ARROW = 64,
    PKTIN_LC254_UPDATE_REBOOT_TIMER = 143,
    PKTIN_LC254_UPDATE_STAT = 136,
    PKTIN_LC254_UPDATE_RUNENERGY = 94,
    PKTIN_LC254_RESET_ANIMS = 203,
    PKTIN_LC254_UPDATE_PID = 213,
    PKTIN_LC254_LAST_LOGIN_INFO = 146,
    PKTIN_LC254_LOGOUT = 21,
    PKTIN_LC254_P_COUNTDIALOG = 5,
    PKTIN_LC254_SET_MULTIWAY = 75,
    PKTIN_LC254_SET_PLAYER_OP = 204,
    PKTIN_LC254_REBUILD_NORMAL = 209,
    PKTIN_LC254_VARP_SMALL = 186,
    PKTIN_LC254_VARP_LARGE = 196,
    PKTIN_LC254_VARP_SYNC = 140,
    PKTIN_LC254_SYNTH_SOUND = 25,
    PKTIN_LC254_MIDI_SONG = 163,
    PKTIN_LC254_MIDI_JINGLE = 242,
    PKTIN_LC254_UPDATE_ZONE_PARTIAL_FOLLOWS = 173,
    PKTIN_LC254_UPDATE_ZONE_FULL_FOLLOWS = 159,
    PKTIN_LC254_UPDATE_ZONE_PARTIAL_ENCLOSED = 61,
    PKTIN_LC254_P_LOCMERGE = 218,
    PKTIN_LC254_LOC_ANIM = 30,
    PKTIN_LC254_OBJ_DEL = 115,
    PKTIN_LC254_OBJ_REVEAL = 8,
    PKTIN_LC254_LOC_ADD_CHANGE = 70,
    PKTIN_LC254_MAP_PROJANIM = 37,
    PKTIN_LC254_LOC_DEL = 88,
    PKTIN_LC254_OBJ_COUNT = 98,
    PKTIN_LC254_MAP_ANIM = 114,
    PKTIN_LC254_OBJ_ADD = 120
};

#ifndef PACKET_DEFINITION
struct PacketInDefinition
{
    int name; /* canonical GameProtoPktName */
    int code; /* wire opcode */
    int length;
};
#define PACKET_DEFINITION(name, code, length) { name, code, length }
#endif

static const struct PacketInDefinition g_packet_in_definitions_lc254[] = {
    PACKET_DEFINITION(PKT_NAME_IF_OPENCHAT, PKTIN_LC254_IF_OPENCHAT, 2),
    PACKET_DEFINITION(PKT_NAME_IF_OPENMAIN_SIDE, PKTIN_LC254_IF_OPENMAIN_SIDE, 4),
    PACKET_DEFINITION(PKT_NAME_IF_CLOSE, PKTIN_LC254_IF_CLOSE, 0),
    PACKET_DEFINITION(PKT_NAME_IF_SETTAB, PKTIN_LC254_IF_SETTAB, 3),
    PACKET_DEFINITION(PKT_NAME_IF_OPENMAIN, PKTIN_LC254_IF_OPENMAIN, 2),
    PACKET_DEFINITION(PKT_NAME_IF_OPENSIDE, PKTIN_LC254_IF_OPENSIDE, 2),
    PACKET_DEFINITION(PKT_NAME_IF_SETTAB_ACTIVE, PKTIN_LC254_IF_SETTAB_ACTIVE, 1),
    PACKET_DEFINITION(PKT_NAME_IF_OPENOVERLAY, PKTIN_LC254_IF_OPENOVERLAY, 2),
    PACKET_DEFINITION(PKT_NAME_IF_SETCOLOUR, PKTIN_LC254_IF_SETCOLOUR, 4),
    PACKET_DEFINITION(PKT_NAME_IF_SETHIDE, PKTIN_LC254_IF_SETHIDE, 3),
    PACKET_DEFINITION(PKT_NAME_IF_SETOBJECT, PKTIN_LC254_IF_SETOBJECT, 6),
    PACKET_DEFINITION(PKT_NAME_IF_SETMODEL, PKTIN_LC254_IF_SETMODEL, 4),
    PACKET_DEFINITION(PKT_NAME_IF_SETANIM, PKTIN_LC254_IF_SETANIM, 4),
    PACKET_DEFINITION(PKT_NAME_IF_SETPLAYERHEAD, PKTIN_LC254_IF_SETPLAYERHEAD, 2),
    PACKET_DEFINITION(PKT_NAME_IF_SETTEXT, PKTIN_LC254_IF_SETTEXT, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_IF_SETNPCHEAD, PKTIN_LC254_IF_SETNPCHEAD, 4),
    PACKET_DEFINITION(PKT_NAME_IF_SETPOSITION, PKTIN_LC254_IF_SETPOSITION, 6),
    PACKET_DEFINITION(PKT_NAME_IF_SETSCROLLPOS, PKTIN_LC254_IF_SETSCROLLPOS, 4),
    PACKET_DEFINITION(PKT_NAME_TUT_FLASH, PKTIN_LC254_TUT_FLASH, 1),
    PACKET_DEFINITION(PKT_NAME_TUT_OPEN, PKTIN_LC254_TUT_OPEN, 2),
    PACKET_DEFINITION(PKT_NAME_UPDATE_INV_STOP_TRANSMIT, PKTIN_LC254_UPDATE_INV_STOP_TRANSMIT, 2),
    PACKET_DEFINITION(PKT_NAME_UPDATE_INV_FULL, PKTIN_LC254_UPDATE_INV_FULL, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_UPDATE_INV_PARTIAL, PKTIN_LC254_UPDATE_INV_PARTIAL, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_CAM_LOOKAT, PKTIN_LC254_CAM_LOOKAT, 6),
    PACKET_DEFINITION(PKT_NAME_CAM_SHAKE, PKTIN_LC254_CAM_SHAKE, 4),
    PACKET_DEFINITION(PKT_NAME_CAM_MOVETO, PKTIN_LC254_CAM_MOVETO, 6),
    PACKET_DEFINITION(PKT_NAME_CAM_RESET, PKTIN_LC254_CAM_RESET, 0),
    PACKET_DEFINITION(PKT_NAME_NPC_INFO, PKTIN_LC254_NPC_INFO, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_PLAYER_INFO, PKTIN_LC254_PLAYER_INFO, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_FINISH_TRACKING, PKTIN_LC254_FINISH_TRACKING, 0),
    PACKET_DEFINITION(PKT_NAME_ENABLE_TRACKING, PKTIN_LC254_ENABLE_TRACKING, 0),
    PACKET_DEFINITION(PKT_NAME_MESSAGE_GAME, PKTIN_LC254_MESSAGE_GAME, PKTIN_LENGTH_VARU8),
    PACKET_DEFINITION(PKT_NAME_UPDATE_IGNORELIST, PKTIN_LC254_UPDATE_IGNORELIST, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_CHAT_FILTER_SETTINGS, PKTIN_LC254_CHAT_FILTER_SETTINGS, 3),
    PACKET_DEFINITION(PKT_NAME_MESSAGE_PRIVATE, PKTIN_LC254_MESSAGE_PRIVATE, PKTIN_LENGTH_VARU8),
    PACKET_DEFINITION(PKT_NAME_UPDATE_FRIENDLIST, PKTIN_LC254_UPDATE_FRIENDLIST, 9),
    PACKET_DEFINITION(PKT_NAME_FRIENDLIST_LOADED, PKTIN_LC254_FRIENDLIST_LOADED, 1),
    PACKET_DEFINITION(PKT_NAME_UNSET_MAP_FLAG, PKTIN_LC254_UNSET_MAP_FLAG, 0),
    PACKET_DEFINITION(PKT_NAME_UPDATE_RUNWEIGHT, PKTIN_LC254_UPDATE_RUNWEIGHT, 2),
    PACKET_DEFINITION(PKT_NAME_HINT_ARROW, PKTIN_LC254_HINT_ARROW, 6),
    PACKET_DEFINITION(PKT_NAME_UPDATE_REBOOT_TIMER, PKTIN_LC254_UPDATE_REBOOT_TIMER, 2),
    PACKET_DEFINITION(PKT_NAME_UPDATE_STAT, PKTIN_LC254_UPDATE_STAT, 6),
    PACKET_DEFINITION(PKT_NAME_UPDATE_RUNENERGY, PKTIN_LC254_UPDATE_RUNENERGY, 1),
    PACKET_DEFINITION(PKT_NAME_RESET_ANIMS, PKTIN_LC254_RESET_ANIMS, 0),
    PACKET_DEFINITION(PKT_NAME_UPDATE_PID, PKTIN_LC254_UPDATE_PID, 3),
    PACKET_DEFINITION(PKT_NAME_LAST_LOGIN_INFO, PKTIN_LC254_LAST_LOGIN_INFO, 10),
    PACKET_DEFINITION(PKT_NAME_LOGOUT, PKTIN_LC254_LOGOUT, 0),
    PACKET_DEFINITION(PKT_NAME_P_COUNTDIALOG, PKTIN_LC254_P_COUNTDIALOG, 0),
    PACKET_DEFINITION(PKT_NAME_SET_MULTIWAY, PKTIN_LC254_SET_MULTIWAY, 1),
    PACKET_DEFINITION(PKT_NAME_SET_PLAYER_OP, PKTIN_LC254_SET_PLAYER_OP, PKTIN_LENGTH_VARU8),
    PACKET_DEFINITION(PKT_NAME_REBUILD_NORMAL, PKTIN_LC254_REBUILD_NORMAL, 4),
    PACKET_DEFINITION(PKT_NAME_VARP_SMALL, PKTIN_LC254_VARP_SMALL, 3),
    PACKET_DEFINITION(PKT_NAME_VARP_LARGE, PKTIN_LC254_VARP_LARGE, 6),
    PACKET_DEFINITION(PKT_NAME_RESET_CLIENT_VARCACHE, PKTIN_LC254_VARP_SYNC, 0),
    PACKET_DEFINITION(PKT_NAME_SYNTH_SOUND, PKTIN_LC254_SYNTH_SOUND, 5),
    PACKET_DEFINITION(PKT_NAME_MIDI_SONG, PKTIN_LC254_MIDI_SONG, 2),
    PACKET_DEFINITION(PKT_NAME_MIDI_JINGLE, PKTIN_LC254_MIDI_JINGLE, 4),
    PACKET_DEFINITION(PKT_NAME_UPDATE_ZONE_PARTIAL_FOLLOWS, PKTIN_LC254_UPDATE_ZONE_PARTIAL_FOLLOWS, 2),
    PACKET_DEFINITION(PKT_NAME_UPDATE_ZONE_FULL_FOLLOWS, PKTIN_LC254_UPDATE_ZONE_FULL_FOLLOWS, 2),
    PACKET_DEFINITION(PKT_NAME_UPDATE_ZONE_PARTIAL_ENCLOSED, PKTIN_LC254_UPDATE_ZONE_PARTIAL_ENCLOSED, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_LOC_MERGE, PKTIN_LC254_P_LOCMERGE, 14),
    PACKET_DEFINITION(PKT_NAME_LOC_ANIM, PKTIN_LC254_LOC_ANIM, 4),
    PACKET_DEFINITION(PKT_NAME_OBJ_DEL, PKTIN_LC254_OBJ_DEL, 3),
    PACKET_DEFINITION(PKT_NAME_OBJ_REVEAL, PKTIN_LC254_OBJ_REVEAL, 7),
    PACKET_DEFINITION(PKT_NAME_LOC_ADD_CHANGE, PKTIN_LC254_LOC_ADD_CHANGE, 4),
    PACKET_DEFINITION(PKT_NAME_MAP_PROJANIM, PKTIN_LC254_MAP_PROJANIM, 15),
    PACKET_DEFINITION(PKT_NAME_LOC_DEL, PKTIN_LC254_LOC_DEL, 2),
    PACKET_DEFINITION(PKT_NAME_OBJ_COUNT, PKTIN_LC254_OBJ_COUNT, 7),
    PACKET_DEFINITION(PKT_NAME_MAP_ANIM, PKTIN_LC254_MAP_ANIM, 6),
    PACKET_DEFINITION(PKT_NAME_OBJ_ADD, PKTIN_LC254_OBJ_ADD, 5)
};

#define PACKET_IN_DEFINITION_COUNT_LC254 \
    ((int)(sizeof(g_packet_in_definitions_lc254) / sizeof(g_packet_in_definitions_lc254[0])))

/** Wire opcode -> payload length (>=0 fixed, -1 var-u8, -2 var-u16). */
static inline int
packetin_size_lc254(int wire_opcode)
{
    assert(wire_opcode >= 0 && wire_opcode < 256);
    for( int i = 0; i < PACKET_IN_DEFINITION_COUNT_LC254; i++ )
    {
        if( g_packet_in_definitions_lc254[i].code == wire_opcode )
        {
            return g_packet_in_definitions_lc254[i].length;
        }
    }
    return 0;
}

/** Wire opcode -> canonical PKT_NAME_*; PKT_NAME_NONE (0) = unknown. */
static inline int
packetin_code_lc254(int wire_opcode)
{
    assert(wire_opcode >= 0 && wire_opcode < 256);
    for( int i = 0; i < PACKET_IN_DEFINITION_COUNT_LC254; i++ )
    {
        if( g_packet_in_definitions_lc254[i].code == wire_opcode )
        {
            return g_packet_in_definitions_lc254[i].name;
        }
    }
    return PKT_NAME_NONE;
}

/** Canonical PKT_NAME_* -> wire opcode; -1 = packet absent from this rev. */
static inline int
packetin_wire_lc254(int pkt_name)
{
    for( int i = 0; i < PACKET_IN_DEFINITION_COUNT_LC254; i++ )
    {
        if( g_packet_in_definitions_lc254[i].name == pkt_name )
        {
            return g_packet_in_definitions_lc254[i].code;
        }
    }
    return -1;
}

#endif
