#ifndef PACKETIN_LC289_H
#define PACKETIN_LC289_H

#include "net/rev/pktnames.h"

#include <assert.h>
#include <stdint.h>

#ifndef PKTIN_LENGTH_VARU8
#define PKTIN_LENGTH_VARU8 (-1)
#define PKTIN_LENGTH_VARU16 (-2)
#endif

/*
 * Wire opcodes of the LostCity_Server Engine-TS branch 289 build
 * (engine/src/network/game/server/ServerGameProt.ts, plus the zone sub-packets
 * from ServerGameZoneProt.ts).
 *
 * EVERY opcode is renumbered from 254 -- not one survives -- so this table
 * shares nothing with lc254's but the canonical names and the payload sizes.
 * Two names moved with the build: VARP_SYNC became RESET_CLIENT_VARCACHE
 * (PKT_NAME_VARP_RESET, the same "drop the client copy" packet) and
 * MINIMAP_TOGGLE is new. The 254 tracking pair (ENABLE_TRACKING /
 * FINISH_TRACKING) is gone from the server, so it is absent here rather than
 * carried at a guessed opcode.
 */
enum PacketInType_LC289
{
    PKTIN_LC289_IF_OPENCHAT = 81,
    PKTIN_LC289_IF_OPENMAIN_SIDE = 55,
    PKTIN_LC289_IF_CLOSE = 23,
    PKTIN_LC289_IF_SETTAB = 63,
    PKTIN_LC289_IF_SETTAB_ACTIVE = 189,
    PKTIN_LC289_IF_OPENMAIN = 119,
    PKTIN_LC289_IF_OPENSIDE = 252,
    PKTIN_LC289_IF_OPENOVERLAY = 127,
    PKTIN_LC289_IF_SETCOLOUR = 160,
    PKTIN_LC289_IF_SETHIDE = 138,
    PKTIN_LC289_IF_SETOBJECT = 18,
    PKTIN_LC289_IF_SETMODEL = 222,
    PKTIN_LC289_IF_SETANIM = 211,
    PKTIN_LC289_IF_SETPLAYERHEAD = 30,
    PKTIN_LC289_IF_SETTEXT = 59,
    PKTIN_LC289_IF_SETNPCHEAD = 244,
    PKTIN_LC289_IF_SETPOSITION = 79,
    PKTIN_LC289_IF_SETSCROLLPOS = 184,
    PKTIN_LC289_TUT_FLASH = 181,
    PKTIN_LC289_TUT_OPEN = 12,
    PKTIN_LC289_UPDATE_INV_STOP_TRANSMIT = 28,
    PKTIN_LC289_UPDATE_INV_FULL = 107,
    PKTIN_LC289_UPDATE_INV_PARTIAL = 76,
    PKTIN_LC289_CAM_LOOKAT = 82,
    PKTIN_LC289_CAM_SHAKE = 208,
    PKTIN_LC289_CAM_MOVETO = 73,
    PKTIN_LC289_CAM_RESET = 133,
    PKTIN_LC289_NPC_INFO = 65,
    PKTIN_LC289_PLAYER_INFO = 188,
    PKTIN_LC289_FRIENDLIST_LOADED = 235,
    PKTIN_LC289_MESSAGE_GAME = 196,
    PKTIN_LC289_UPDATE_IGNORELIST = 47,
    PKTIN_LC289_CHAT_FILTER_SETTINGS = 13,
    PKTIN_LC289_MESSAGE_PRIVATE = 243,
    PKTIN_LC289_UPDATE_FRIENDLIST = 168,
    PKTIN_LC289_UNSET_MAP_FLAG = 164,
    PKTIN_LC289_UPDATE_RUNWEIGHT = 46,
    PKTIN_LC289_HINT_ARROW = 115,
    PKTIN_LC289_UPDATE_REBOOT_TIMER = 204,
    PKTIN_LC289_UPDATE_STAT = 154,
    PKTIN_LC289_UPDATE_RUNENERGY = 195,
    PKTIN_LC289_RESET_ANIMS = 201,
    PKTIN_LC289_UPDATE_PID = 120,
    PKTIN_LC289_LAST_LOGIN_INFO = 253,
    PKTIN_LC289_LOGOUT = 121,
    PKTIN_LC289_P_COUNTDIALOG = 35,
    PKTIN_LC289_SET_MULTIWAY = 247,
    PKTIN_LC289_SET_PLAYER_OP = 21,
    PKTIN_LC289_MINIMAP_TOGGLE = 136,
    PKTIN_LC289_REBUILD_NORMAL = 219,
    PKTIN_LC289_VARP_SMALL = 75,
    PKTIN_LC289_VARP_LARGE = 97,
    PKTIN_LC289_RESET_CLIENT_VARCACHE = 172,
    PKTIN_LC289_SYNTH_SOUND = 177,
    PKTIN_LC289_MIDI_SONG = 187,
    PKTIN_LC289_MIDI_JINGLE = 29,
    PKTIN_LC289_UPDATE_ZONE_PARTIAL_FOLLOWS = 155,
    PKTIN_LC289_UPDATE_ZONE_FULL_FOLLOWS = 144,
    PKTIN_LC289_UPDATE_ZONE_PARTIAL_ENCLOSED = 112,
    PKTIN_LC289_LOC_MERGE = 83,
    PKTIN_LC289_LOC_ANIM = 106,
    PKTIN_LC289_OBJ_DEL = 71,
    PKTIN_LC289_OBJ_REVEAL = 176,
    PKTIN_LC289_LOC_ADD_CHANGE = 90,
    PKTIN_LC289_MAP_PROJANIM = 87,
    PKTIN_LC289_LOC_DEL = 194,
    PKTIN_LC289_OBJ_COUNT = 117,
    PKTIN_LC289_MAP_ANIM = 233,
    PKTIN_LC289_OBJ_ADD = 60
};

#ifndef PACKET_DEFINITION
struct PacketInDefinition
{
    int name; /* canonical GameProtoPktName */
    int code; /* wire opcode */
    int length;
};
#define PACKET_DEFINITION(name, code, length) { name, code, length }
#endif

static const struct PacketInDefinition g_packet_in_definitions_lc289[] = {
    PACKET_DEFINITION(PKT_NAME_IF_OPENCHAT, PKTIN_LC289_IF_OPENCHAT, 2),
    PACKET_DEFINITION(PKT_NAME_IF_OPENMAIN_SIDE, PKTIN_LC289_IF_OPENMAIN_SIDE, 4),
    PACKET_DEFINITION(PKT_NAME_IF_CLOSE, PKTIN_LC289_IF_CLOSE, 0),
    PACKET_DEFINITION(PKT_NAME_IF_SETTAB, PKTIN_LC289_IF_SETTAB, 3),
    PACKET_DEFINITION(PKT_NAME_IF_SETTAB_ACTIVE, PKTIN_LC289_IF_SETTAB_ACTIVE, 1),
    PACKET_DEFINITION(PKT_NAME_IF_OPENMAIN, PKTIN_LC289_IF_OPENMAIN, 2),
    PACKET_DEFINITION(PKT_NAME_IF_OPENSIDE, PKTIN_LC289_IF_OPENSIDE, 2),
    PACKET_DEFINITION(PKT_NAME_IF_OPENOVERLAY, PKTIN_LC289_IF_OPENOVERLAY, 2),
    PACKET_DEFINITION(PKT_NAME_IF_SETCOLOUR, PKTIN_LC289_IF_SETCOLOUR, 4),
    PACKET_DEFINITION(PKT_NAME_IF_SETHIDE, PKTIN_LC289_IF_SETHIDE, 3),
    PACKET_DEFINITION(PKT_NAME_IF_SETOBJECT, PKTIN_LC289_IF_SETOBJECT, 6),
    PACKET_DEFINITION(PKT_NAME_IF_SETMODEL, PKTIN_LC289_IF_SETMODEL, 4),
    PACKET_DEFINITION(PKT_NAME_IF_SETANIM, PKTIN_LC289_IF_SETANIM, 4),
    PACKET_DEFINITION(PKT_NAME_IF_SETPLAYERHEAD, PKTIN_LC289_IF_SETPLAYERHEAD, 2),
    PACKET_DEFINITION(PKT_NAME_IF_SETTEXT, PKTIN_LC289_IF_SETTEXT, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_IF_SETNPCHEAD, PKTIN_LC289_IF_SETNPCHEAD, 4),
    PACKET_DEFINITION(PKT_NAME_IF_SETPOSITION, PKTIN_LC289_IF_SETPOSITION, 6),
    PACKET_DEFINITION(PKT_NAME_IF_SETSCROLLPOS, PKTIN_LC289_IF_SETSCROLLPOS, 4),
    PACKET_DEFINITION(PKT_NAME_TUT_FLASH, PKTIN_LC289_TUT_FLASH, 1),
    PACKET_DEFINITION(PKT_NAME_TUT_OPEN, PKTIN_LC289_TUT_OPEN, 2),
    PACKET_DEFINITION(PKT_NAME_UPDATE_INV_STOP_TRANSMIT, PKTIN_LC289_UPDATE_INV_STOP_TRANSMIT, 2),
    PACKET_DEFINITION(PKT_NAME_UPDATE_INV_FULL, PKTIN_LC289_UPDATE_INV_FULL, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_UPDATE_INV_PARTIAL, PKTIN_LC289_UPDATE_INV_PARTIAL, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_CAM_LOOKAT, PKTIN_LC289_CAM_LOOKAT, 6),
    PACKET_DEFINITION(PKT_NAME_CAM_SHAKE, PKTIN_LC289_CAM_SHAKE, 4),
    PACKET_DEFINITION(PKT_NAME_CAM_MOVETO, PKTIN_LC289_CAM_MOVETO, 6),
    PACKET_DEFINITION(PKT_NAME_CAM_RESET, PKTIN_LC289_CAM_RESET, 0),
    PACKET_DEFINITION(PKT_NAME_NPC_INFO, PKTIN_LC289_NPC_INFO, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_PLAYER_INFO, PKTIN_LC289_PLAYER_INFO, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_FRIENDLIST_LOADED, PKTIN_LC289_FRIENDLIST_LOADED, 1),
    PACKET_DEFINITION(PKT_NAME_MESSAGE_GAME, PKTIN_LC289_MESSAGE_GAME, PKTIN_LENGTH_VARU8),
    PACKET_DEFINITION(PKT_NAME_UPDATE_IGNORELIST, PKTIN_LC289_UPDATE_IGNORELIST, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_CHAT_FILTER_SETTINGS, PKTIN_LC289_CHAT_FILTER_SETTINGS, 3),
    PACKET_DEFINITION(PKT_NAME_MESSAGE_PRIVATE, PKTIN_LC289_MESSAGE_PRIVATE, PKTIN_LENGTH_VARU8),
    PACKET_DEFINITION(PKT_NAME_UPDATE_FRIENDLIST, PKTIN_LC289_UPDATE_FRIENDLIST, 9),
    PACKET_DEFINITION(PKT_NAME_UNSET_MAP_FLAG, PKTIN_LC289_UNSET_MAP_FLAG, 0),
    PACKET_DEFINITION(PKT_NAME_UPDATE_RUNWEIGHT, PKTIN_LC289_UPDATE_RUNWEIGHT, 2),
    PACKET_DEFINITION(PKT_NAME_HINT_ARROW, PKTIN_LC289_HINT_ARROW, 6),
    PACKET_DEFINITION(PKT_NAME_UPDATE_REBOOT_TIMER, PKTIN_LC289_UPDATE_REBOOT_TIMER, 2),
    PACKET_DEFINITION(PKT_NAME_UPDATE_STAT, PKTIN_LC289_UPDATE_STAT, 6),
    PACKET_DEFINITION(PKT_NAME_UPDATE_RUNENERGY, PKTIN_LC289_UPDATE_RUNENERGY, 1),
    PACKET_DEFINITION(PKT_NAME_RESET_ANIMS, PKTIN_LC289_RESET_ANIMS, 0),
    PACKET_DEFINITION(PKT_NAME_UPDATE_PID, PKTIN_LC289_UPDATE_PID, 3),
    PACKET_DEFINITION(PKT_NAME_LAST_LOGIN_INFO, PKTIN_LC289_LAST_LOGIN_INFO, 10),
    PACKET_DEFINITION(PKT_NAME_LOGOUT, PKTIN_LC289_LOGOUT, 0),
    PACKET_DEFINITION(PKT_NAME_P_COUNTDIALOG, PKTIN_LC289_P_COUNTDIALOG, 0),
    PACKET_DEFINITION(PKT_NAME_SET_MULTIWAY, PKTIN_LC289_SET_MULTIWAY, 1),
    PACKET_DEFINITION(PKT_NAME_SET_PLAYER_OP, PKTIN_LC289_SET_PLAYER_OP, PKTIN_LENGTH_VARU8),
    PACKET_DEFINITION(PKT_NAME_MINIMAP_TOGGLE, PKTIN_LC289_MINIMAP_TOGGLE, 1),
    PACKET_DEFINITION(PKT_NAME_REBUILD_NORMAL, PKTIN_LC289_REBUILD_NORMAL, 4),
    PACKET_DEFINITION(PKT_NAME_VARP_SMALL, PKTIN_LC289_VARP_SMALL, 3),
    PACKET_DEFINITION(PKT_NAME_VARP_LARGE, PKTIN_LC289_VARP_LARGE, 6),
    PACKET_DEFINITION(PKT_NAME_VARP_RESET, PKTIN_LC289_RESET_CLIENT_VARCACHE, 0),
    PACKET_DEFINITION(PKT_NAME_SYNTH_SOUND, PKTIN_LC289_SYNTH_SOUND, 5),
    PACKET_DEFINITION(PKT_NAME_MIDI_SONG, PKTIN_LC289_MIDI_SONG, 2),
    PACKET_DEFINITION(PKT_NAME_MIDI_JINGLE, PKTIN_LC289_MIDI_JINGLE, 4),
    PACKET_DEFINITION(PKT_NAME_UPDATE_ZONE_PARTIAL_FOLLOWS, PKTIN_LC289_UPDATE_ZONE_PARTIAL_FOLLOWS, 2),
    PACKET_DEFINITION(PKT_NAME_UPDATE_ZONE_FULL_FOLLOWS, PKTIN_LC289_UPDATE_ZONE_FULL_FOLLOWS, 2),
    PACKET_DEFINITION(PKT_NAME_UPDATE_ZONE_PARTIAL_ENCLOSED, PKTIN_LC289_UPDATE_ZONE_PARTIAL_ENCLOSED, PKTIN_LENGTH_VARU16),
    PACKET_DEFINITION(PKT_NAME_LOC_MERGE, PKTIN_LC289_LOC_MERGE, 14),
    PACKET_DEFINITION(PKT_NAME_LOC_ANIM, PKTIN_LC289_LOC_ANIM, 4),
    PACKET_DEFINITION(PKT_NAME_OBJ_DEL, PKTIN_LC289_OBJ_DEL, 3),
    PACKET_DEFINITION(PKT_NAME_OBJ_REVEAL, PKTIN_LC289_OBJ_REVEAL, 7),
    PACKET_DEFINITION(PKT_NAME_LOC_ADD_CHANGE, PKTIN_LC289_LOC_ADD_CHANGE, 4),
    PACKET_DEFINITION(PKT_NAME_MAP_PROJANIM, PKTIN_LC289_MAP_PROJANIM, 15),
    PACKET_DEFINITION(PKT_NAME_LOC_DEL, PKTIN_LC289_LOC_DEL, 2),
    PACKET_DEFINITION(PKT_NAME_OBJ_COUNT, PKTIN_LC289_OBJ_COUNT, 7),
    PACKET_DEFINITION(PKT_NAME_MAP_ANIM, PKTIN_LC289_MAP_ANIM, 6),
    PACKET_DEFINITION(PKT_NAME_OBJ_ADD, PKTIN_LC289_OBJ_ADD, 5),
};

#define PACKET_IN_DEFINITION_COUNT_LC289 \
    ((int)(sizeof(g_packet_in_definitions_lc289) / sizeof(g_packet_in_definitions_lc289[0])))

/** Wire opcode -> payload length (>=0 fixed, -1 var-u8, -2 var-u16). */
static inline int
packetin_size_lc289(int wire_opcode)
{
    assert(wire_opcode >= 0 && wire_opcode < 256);
    for( int i = 0; i < PACKET_IN_DEFINITION_COUNT_LC289; i++ )
    {
        if( g_packet_in_definitions_lc289[i].code == wire_opcode )
        {
            return g_packet_in_definitions_lc289[i].length;
        }
    }
    return 0;
}

/** Wire opcode -> canonical PKT_NAME_*; PKT_NAME_NONE (0) = unknown. */
static inline int
packetin_code_lc289(int wire_opcode)
{
    assert(wire_opcode >= 0 && wire_opcode < 256);
    for( int i = 0; i < PACKET_IN_DEFINITION_COUNT_LC289; i++ )
    {
        if( g_packet_in_definitions_lc289[i].code == wire_opcode )
        {
            return g_packet_in_definitions_lc289[i].name;
        }
    }
    return PKT_NAME_NONE;
}

/** Canonical PKT_NAME_* -> wire opcode; -1 = packet absent from this rev. */
static inline int
packetin_wire_lc289(int pkt_name)
{
    for( int i = 0; i < PACKET_IN_DEFINITION_COUNT_LC289; i++ )
    {
        if( g_packet_in_definitions_lc289[i].name == pkt_name )
        {
            return g_packet_in_definitions_lc289[i].code;
        }
    }
    return -1;
}

#endif
