#ifndef PACKETOUT_LC289_H
#define PACKETOUT_LC289_H

#include "net/rev/pktnames.h"

/* Client -> server wire opcodes of the LostCity_Server Engine-TS branch 289
 * build (engine/src/network/game/client/ClientGameProt.ts).
 *
 * Renumbered wholesale from 254, like the inbound table. EVENT_TRACKING is
 * absent: 289 dropped the tracking pair, and a name with no opcode here
 * resolves to -1, which is how net_out declines to send it. */

#ifndef PACKET_OUT_DEFINITION
struct PacketOutDefinition
{
    int name; /* canonical GameProtoPktOutName */
    int code; /* wire opcode */
};
#define PACKET_OUT_DEFINITION(name, code) { name, code }
#endif

static const struct PacketOutDefinition g_packet_out_definitions_lc289[] = {
    PACKET_OUT_DEFINITION(PKTOUT_NAME_NO_TIMEOUT, 181),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_IDLE_TIMER, 145),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_EVENT_MOUSE_CLICK, 224),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_EVENT_MOUSE_MOVE, 229),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_EVENT_APPLET_FOCUS, 149),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_EVENT_CAMERA_POSITION, 193),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC1, 195),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC2, 81),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC3, 122),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC4, 49),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC5, 46),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC6, 73),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC7, 133),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC8, 168),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_OPLOGIC9, 88),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_CYCLELOGIC1, 130),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_CYCLELOGIC2, 154),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_CYCLELOGIC3, 125),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_CYCLELOGIC4, 137),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_CYCLELOGIC5, 85),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_CYCLELOGIC6, 255),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_ANTICHEAT_CYCLELOGIC7, 232),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPOBJ1, 97),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPOBJ2, 4),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPOBJ3, 110),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPOBJ4, 147),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPOBJ5, 22),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPOBJT, 241),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPOBJU, 55),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPNPC1, 252),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPNPC2, 21),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPNPC3, 178),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPNPC4, 30),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPNPC5, 247),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPNPCT, 108),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPNPCU, 160),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPLOC1, 10),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPLOC2, 45),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPLOC3, 196),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPLOC4, 53),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPLOC5, 126),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPLOCT, 218),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPLOCU, 184),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPPLAYER1, 220),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPPLAYER2, 51),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPPLAYER3, 13),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPPLAYER4, 189),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPPLAYER5, 69),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPPLAYERT, 138),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPPLAYERU, 16),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPHELD1, 76),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPHELD2, 177),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPHELD3, 40),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPHELD4, 191),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPHELD5, 79),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPHELDT, 112),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_OPHELDU, 200),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_INV_BUTTON1, 44),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_INV_BUTTON2, 111),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_INV_BUTTON3, 124),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_INV_BUTTON4, 248),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_INV_BUTTON5, 227),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_IF_BUTTON, 86),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_RESUME_PAUSEBUTTON, 166),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_CLOSE_MODAL, 93),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_RESUME_P_COUNTDIALOG, 180),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_TUT_CLICKSIDE, 146),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_MAP_BUILD_COMPLETE, 214),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_MOVE_OPCLICK, 67),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_REPORT_ABUSE, 94),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_MOVE_MINIMAPCLICK, 236),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_INV_BUTTOND, 253),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_IGNORELIST_DEL, 251),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_IGNORELIST_ADD, 192),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_IDK_SAVEDESIGN, 27),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_CHAT_SETMODE, 161),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_MESSAGE_PRIVATE, 107),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_FRIENDLIST_DEL, 203),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_FRIENDLIST_ADD, 235),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_CLIENT_CHEAT, 34),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_MESSAGE_PUBLIC, 156),
    PACKET_OUT_DEFINITION(PKTOUT_NAME_MOVE_GAMECLICK, 234),
};

#define PACKET_OUT_DEFINITION_COUNT_LC289 \
    ((int)(sizeof(g_packet_out_definitions_lc289) / sizeof(g_packet_out_definitions_lc289[0])))

/** Canonical PKTOUT_NAME_* -> wire opcode; -1 = absent from this rev. */
static inline int
packetout_code_lc289(int pkt_out_name)
{
    for( int i = 0; i < PACKET_OUT_DEFINITION_COUNT_LC289; i++ )
    {
        if( g_packet_out_definitions_lc289[i].name == pkt_out_name )
        {
            return g_packet_out_definitions_lc289[i].code;
        }
    }
    return -1;
}

#endif
