#ifndef GAMETASK_STATUS_H
#define GAMETASK_STATUS_H

enum GameTaskStatus
{
    GAMETASK_STATUS_PENDING,
    GAMETASK_STATUS_RUNNING,
    GAMETASK_STATUS_COMPLETED,
    GAMETASK_STATUS_FAILED,
};

#endif