#ifndef MINIMENU_ACTION_H
#define MINIMENU_ACTION_H

#include <stdint.h>
// Taken from Client-TS Lostcity rev 254
// These are just randomized numbers.
// They are converted to serverprot codes before being sent to the network

enum MinimenuAction
{
    MINIMENU_ACTION_CANCEL = 1106,

    MINIMENU_ACTION_OPOBJ1 = 139,
    MINIMENU_ACTION_OPOBJ2 = 778,
    MINIMENU_ACTION_OPOBJ3 = 617,
    MINIMENU_ACTION_OPOBJ4 = 224,
    MINIMENU_ACTION_OPOBJ5 = 662,
    MINIMENU_ACTION_OPOBJ6 = 1152,
    MINIMENU_ACTION_OPOBJT = 370,
    MINIMENU_ACTION_OPOBJU = 111,

    MINIMENU_ACTION_OPNPC1 = 242,
    MINIMENU_ACTION_OPNPC2 = 209,
    MINIMENU_ACTION_OPNPC3 = 309,
    MINIMENU_ACTION_OPNPC4 = 852,
    MINIMENU_ACTION_OPNPC5 = 793,
    MINIMENU_ACTION_OPNPC6 = 1714,
    MINIMENU_ACTION_OPNPCT = 240,
    MINIMENU_ACTION_OPNPCU = 829,

    MINIMENU_ACTION_OPLOC1 = 625,
    MINIMENU_ACTION_OPLOC2 = 721,
    MINIMENU_ACTION_OPLOC3 = 743,
    MINIMENU_ACTION_OPLOC4 = 357,
    MINIMENU_ACTION_OPLOC5 = 1071,
    MINIMENU_ACTION_OPLOC6 = 1381,
    MINIMENU_ACTION_OPLOCT = 899,
    MINIMENU_ACTION_OPLOCU = 810,

    MINIMENU_ACTION_OPPLAYER1 = 639,
    MINIMENU_ACTION_OPPLAYER2 = 499,
    MINIMENU_ACTION_OPPLAYER3 = 27,
    MINIMENU_ACTION_OPPLAYER4 = 387,
    MINIMENU_ACTION_OPPLAYER5 = 185,
    MINIMENU_ACTION_OPPLAYER_TRADEREQ = 507,
    MINIMENU_ACTION_OPPLAYER_DUELREQ = 957,
    MINIMENU_ACTION_OPPLAYERT = 131,
    MINIMENU_ACTION_OPPLAYERU = 275,

    MINIMENU_ACTION_OPHELD1 = 694,
    MINIMENU_ACTION_OPHELD2 = 962,
    MINIMENU_ACTION_OPHELD3 = 795,
    MINIMENU_ACTION_OPHELD4 = 681,
    MINIMENU_ACTION_OPHELD5 = 100,
    MINIMENU_ACTION_OPHELD6 = 1328,
    MINIMENU_ACTION_OPHELDT_START = 102,
    MINIMENU_ACTION_OPHELDT_SELECT = 274,
    MINIMENU_ACTION_OPHELDT = 563,
    MINIMENU_ACTION_OPHELDU = 398,

    MINIMENU_ACTION_INV_BUTTON1 = 582,
    MINIMENU_ACTION_INV_BUTTON2 = 113,
    MINIMENU_ACTION_INV_BUTTON3 = 555,
    MINIMENU_ACTION_INV_BUTTON4 = 331,
    MINIMENU_ACTION_INV_BUTTON5 = 354,

    MINIMENU_ACTION_IF_BUTTON = 231,
    MINIMENU_ACTION_IF_BUTTON_TOGGLE = 435,
    MINIMENU_ACTION_IF_BUTTON_SELECT = 225,

    MINIMENU_ACTION_RESUME_PAUSEBUTTON = 997,
    MINIMENU_ACTION_CLOSE_MODAL = 737,

    MINIMENU_ACTION_REPORT_ABUSE = 524,

    MINIMENU_ACTION_WALK = 718,

    MINIMENU_ACTION_FRIENDLIST_ADD = 605,
    MINIMENU_ACTION_IGNORELIST_ADD = 47,
    MINIMENU_ACTION_FRIENDLIST_DEL = 513,
    MINIMENU_ACTION_IGNORELIST_DEL = 884,

    MINIMENU_ACTION_MESSAGE_PRIVATE = 902,
};

#define MINIMENU_ACTION_PRIORITY_OFFSET 2000

#define MINIMENU_ACTION_PRIORITY 1

static inline int
minimenu_action_priority(
    enum MinimenuAction action,
    int is_priority)
{
    if( is_priority )
    {
        return action + MINIMENU_ACTION_PRIORITY_OFFSET;
    }
    else
    {
        return action;
    }
}

#endif