/* AFFINEDCLANSETTINGS_ADDBANNED_FROMCHANNEL. GENERATED by tools/rsprot_gen_codec.py -- do not edit. */
#include "affinedclansettings_addbanned_fromchannel.h"

/*
 * Transcribed from RSProt:
 *   protocol/osrs-<N>/osrs-<N>-desktop/src/main/kotlin/net/rsprot/protocol/
 *       game/incoming/codec/clan/AffinedClanSettingsAddBannedFromChannelDecoder.kt
 *
 * One function per layout, running in whichever direction the executor is in --
 * so a server's writer and a client's reader are the same transcription and
 * cannot drift apart.
 */

/* v1 -- revs 221-239. */
void
packet_affinedclansettings_addbanned_fromchannel_v1_in(RsprotExec *x, MsgAffinedClanSettingsAddBannedFromChannel *m)
{
    RSPROT_U1(x, m->clan_id);
    RSPROT_U2(x, m->member_index);
    RSPROT_JSTR(x, m->name);
}

/*
 * 1 row(s) for 1 layout(s), complete over revisions 221-239.
 * A complete table makes rsprot_version_pick's NULL mean exactly one thing: a
 * revision outside that span. An incomplete one would conflate "not
 * transcribed" with "no such packet", and those are different facts.
 */
const RsprotVersionRange rsprot_affinedclansettings_addbanned_fromchannel_in[] = {
    { 221, 239, (RsprotCodecFn)packet_affinedclansettings_addbanned_fromchannel_v1_in },
};

const int rsprot_affinedclansettings_addbanned_fromchannel_in_count =
    (int)(sizeof(rsprot_affinedclansettings_addbanned_fromchannel_in) / sizeof(rsprot_affinedclansettings_addbanned_fromchannel_in[0]));
