/* CAM_UNLOCK. GENERATED by tools/rsprot_gen_codec.py -- do not edit. */
#include "cam_unlock.h"

/*
 * Transcribed from RSProt:
 *   protocol/osrs-<N>/osrs-<N>-desktop/src/main/kotlin/net/rsprot/protocol/
 *       game/outgoing/codec/camera/CamUnlockEncoder.kt
 *
 * One function per layout, running in whichever direction the executor is in --
 * so a server's writer and a client's reader are the same transcription and
 * cannot drift apart.
 */

/* v2 -- revs 239. */
void
packet_cam_unlock_v2_out(RsprotExec *x, MsgCamUnlock *m)
{
    RSPROT_BOOL(x, m->unlock);
}

/*
 * 1 row(s) for 1 layout(s), complete over revisions 221-239.
 * A complete table makes rsprot_version_pick's NULL mean exactly one thing: a
 * revision outside that span. An incomplete one would conflate "not
 * transcribed" with "no such packet", and those are different facts.
 */
const RsprotVersionRange rsprot_cam_unlock_out[] = {
    { 239, 239, (RsprotCodecFn)packet_cam_unlock_v2_out },
};

const int rsprot_cam_unlock_out_count =
    (int)(sizeof(rsprot_cam_unlock_out) / sizeof(rsprot_cam_unlock_out[0]));
