/* CAM_SHAKE. GENERATED by tools/rsprot_gen_codec.py -- do not edit. */
#include "cam_shake.h"

/*
 * Transcribed from RSProt:
 *   protocol/osrs-<N>/osrs-<N>-desktop/src/main/kotlin/net/rsprot/protocol/
 *       game/outgoing/codec/camera/CamShakeEncoder.kt
 *
 * One function per layout, running in whichever direction the executor is in --
 * so a server's writer and a client's reader are the same transcription and
 * cannot drift apart.
 */

/* v1 -- revs 221-222. */
void
packet_cam_shake_v1_out(RsprotExec *x, MsgCamShake *m)
{
    RSPROT_U1(x, m->type);
    RSPROT_U1(x, m->random_amount);
    RSPROT_U1(x, m->sine_amount);
    RSPROT_U1(x, m->sine_frequency);
}

/* v2 -- revs 223-239. */
void
packet_cam_shake_v2_out(RsprotExec *x, MsgCamShake *m)
{
    RSPROT_U1(x, m->axis);
    RSPROT_U1(x, m->random);
    RSPROT_U1(x, m->amplitude);
    RSPROT_U1(x, m->rate);
}

/*
 * 2 row(s) for 2 layout(s), complete over revisions 221-239.
 * A complete table makes rsprot_version_pick's NULL mean exactly one thing: a
 * revision outside that span. An incomplete one would conflate "not
 * transcribed" with "no such packet", and those are different facts.
 */
const RsprotVersionRange rsprot_cam_shake_out[] = {
    { 221, 222, (RsprotCodecFn)packet_cam_shake_v1_out },
    { 223, 239, (RsprotCodecFn)packet_cam_shake_v2_out },
};

const int rsprot_cam_shake_out_count =
    (int)(sizeof(rsprot_cam_shake_out) / sizeof(rsprot_cam_shake_out[0]));
