#ifndef RSPROT_PACKET_CAM_MOVETO_ARC_V2_H
#define RSPROT_PACKET_CAM_MOVETO_ARC_V2_H

/*
 * CAM_MOVETO_ARC_V2 -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : CamMoveToArcV2Encoder
 * Layouts      : 1 distinct, over 1 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^CamMoveToArcV2Encoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgCamMoveToArcV2 {
	int32_t ignore_terrain;
	int32_t destination_z;
	int32_t cycles;
	int32_t height;
	int32_t center_x;
	int32_t destination_x;
	int32_t center_z;
	int32_t easing_id;
} MsgCamMoveToArcV2;

/* v3 -- revs 238. */
void packet_cam_moveto_arc_v2_v3_out(RsprotExec *x, MsgCamMoveToArcV2 *m);

/* Per-revision aliases: `packet_cam_moveto_arc_v2_rev239_out` is greppable, which is the
 * point -- "what does 239 do for CAM_MOVETO_ARC_V2" without reading a table. */
#define packet_cam_moveto_arc_v2_rev238_out packet_cam_moveto_arc_v2_v3_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_cam_moveto_arc_v2_out[];
extern const int rsprot_cam_moveto_arc_v2_out_count;

#endif
