#ifndef RSPROT_PACKET_CAM_LOOKAT_V3_H
#define RSPROT_PACKET_CAM_LOOKAT_V3_H

/*
 * CAM_LOOKAT_V3 -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : CamLookAtV3Encoder
 * Layouts      : 1 distinct, over 1 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^CamLookAtV3Encoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgCamLookAtV3 {
	int32_t height_relative;
	int32_t rate;
	int32_t height;
	int32_t z;
	int32_t x;
	int32_t rate2;
} MsgCamLookAtV3;

/* v1 -- revs 239. */
void packet_cam_lookat_v3_v1_out(RsprotExec *x, MsgCamLookAtV3 *m);

/* Per-revision aliases: `packet_cam_lookat_v3_rev239_out` is greppable, which is the
 * point -- "what does 239 do for CAM_LOOKAT_V3" without reading a table. */
#define packet_cam_lookat_v3_rev239_out packet_cam_lookat_v3_v1_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_cam_lookat_v3_out[];
extern const int rsprot_cam_lookat_v3_out_count;

#endif
