#ifndef RSPROT_PACKET_CAM_ROTATETO_H
#define RSPROT_PACKET_CAM_ROTATETO_H

/*
 * CAM_ROTATETO -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : CamRotateToEncoder
 * Layouts      : 1 distinct, over 1 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^CamRotateToEncoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgCamRotateTo {
	int32_t yaw;
	int32_t pitch;
	int32_t cycles;
	int32_t easing_id;
} MsgCamRotateTo;

/* v1 -- revs 223-239. */
void packet_cam_rotateto_v1_out(RsprotExec *x, MsgCamRotateTo *m);

/* Per-revision aliases: `packet_cam_rotateto_rev239_out` is greppable, which is the
 * point -- "what does 239 do for CAM_ROTATETO" without reading a table. */
#define packet_cam_rotateto_rev223_out packet_cam_rotateto_v1_out
#define packet_cam_rotateto_rev224_out packet_cam_rotateto_v1_out
#define packet_cam_rotateto_rev225_out packet_cam_rotateto_v1_out
#define packet_cam_rotateto_rev226_out packet_cam_rotateto_v1_out
#define packet_cam_rotateto_rev227_out packet_cam_rotateto_v1_out
#define packet_cam_rotateto_rev228_out packet_cam_rotateto_v1_out
#define packet_cam_rotateto_rev229_out packet_cam_rotateto_v1_out
#define packet_cam_rotateto_rev230_out packet_cam_rotateto_v1_out
#define packet_cam_rotateto_rev231_out packet_cam_rotateto_v1_out
#define packet_cam_rotateto_rev232_out packet_cam_rotateto_v1_out
#define packet_cam_rotateto_rev233_out packet_cam_rotateto_v1_out
#define packet_cam_rotateto_rev234_out packet_cam_rotateto_v1_out
#define packet_cam_rotateto_rev235_out packet_cam_rotateto_v1_out
#define packet_cam_rotateto_rev236_out packet_cam_rotateto_v1_out
#define packet_cam_rotateto_rev237_out packet_cam_rotateto_v1_out
#define packet_cam_rotateto_rev238_out packet_cam_rotateto_v1_out
#define packet_cam_rotateto_rev239_out packet_cam_rotateto_v1_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_cam_rotateto_out[];
extern const int rsprot_cam_rotateto_out_count;

#endif
