/* CAM_ROTATEBY. GENERATED by tools/rsprot_gen_codec.py -- do not edit. */
#include "cam_rotateby.h"

/*
 * Transcribed from RSProt:
 *   protocol/osrs-<N>/osrs-<N>-desktop/src/main/kotlin/net/rsprot/protocol/
 *       game/outgoing/codec/camera/CamRotateByEncoder.kt
 *
 * One function per layout, running in whichever direction the executor is in --
 * so a server's writer and a client's reader are the same transcription and
 * cannot drift apart.
 */

/* v1 -- revs 223-239. */
void
packet_cam_rotateby_v1_out(RsprotExec *x, MsgCamRotateBy *m)
{
    RSPROT_U2(x, m->yaw);
    RSPROT_U2(x, m->pitch);
    RSPROT_U2(x, m->cycles);
    RSPROT_U1(x, m->easing_id);
}

/*
 * 1 row(s) for 1 layout(s), complete over revisions 221-239.
 * A complete table makes rsprot_version_pick's NULL mean exactly one thing: a
 * revision outside that span. An incomplete one would conflate "not
 * transcribed" with "no such packet", and those are different facts.
 */
const RsprotVersionRange rsprot_cam_rotateby_out[] = {
    { 223, 239, (RsprotCodecFn)packet_cam_rotateby_v1_out },
};

const int rsprot_cam_rotateby_out_count =
    (int)(sizeof(rsprot_cam_rotateby_out) / sizeof(rsprot_cam_rotateby_out[0]));
