#ifndef RSPROT_PACKET_CAM_ROTATEBY_H
#define RSPROT_PACKET_CAM_ROTATEBY_H

/*
 * CAM_ROTATEBY -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : CamRotateByEncoder
 * Layouts      : 1 distinct, over 1 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^CamRotateByEncoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgCamRotateBy {
	int32_t yaw;
	int32_t pitch;
	int32_t cycles;
	int32_t easing_id;
} MsgCamRotateBy;

/* v1 -- revs 223-239. */
void packet_cam_rotateby_v1_out(RsprotExec *x, MsgCamRotateBy *m);

/* Per-revision aliases: `packet_cam_rotateby_rev239_out` is greppable, which is the
 * point -- "what does 239 do for CAM_ROTATEBY" without reading a table. */
#define packet_cam_rotateby_rev223_out packet_cam_rotateby_v1_out
#define packet_cam_rotateby_rev224_out packet_cam_rotateby_v1_out
#define packet_cam_rotateby_rev225_out packet_cam_rotateby_v1_out
#define packet_cam_rotateby_rev226_out packet_cam_rotateby_v1_out
#define packet_cam_rotateby_rev227_out packet_cam_rotateby_v1_out
#define packet_cam_rotateby_rev228_out packet_cam_rotateby_v1_out
#define packet_cam_rotateby_rev229_out packet_cam_rotateby_v1_out
#define packet_cam_rotateby_rev230_out packet_cam_rotateby_v1_out
#define packet_cam_rotateby_rev231_out packet_cam_rotateby_v1_out
#define packet_cam_rotateby_rev232_out packet_cam_rotateby_v1_out
#define packet_cam_rotateby_rev233_out packet_cam_rotateby_v1_out
#define packet_cam_rotateby_rev234_out packet_cam_rotateby_v1_out
#define packet_cam_rotateby_rev235_out packet_cam_rotateby_v1_out
#define packet_cam_rotateby_rev236_out packet_cam_rotateby_v1_out
#define packet_cam_rotateby_rev237_out packet_cam_rotateby_v1_out
#define packet_cam_rotateby_rev238_out packet_cam_rotateby_v1_out
#define packet_cam_rotateby_rev239_out packet_cam_rotateby_v1_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_cam_rotateby_out[];
extern const int rsprot_cam_rotateby_out_count;

#endif
