#ifndef RSPROT_PACKET_CHAT_FILTER_SETTINGS_H
#define RSPROT_PACKET_CHAT_FILTER_SETTINGS_H

/*
 * CHAT_FILTER_SETTINGS -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : ChatFilterSettingsEncoder
 * Layouts      : 15 distinct, over 19 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^ChatFilterSettingsEncoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgChatFilterSettings {
	int32_t public_chat_filter;
	int32_t trade_chat_filter;
} MsgChatFilterSettings;

/* v1 -- revs 221. */
void packet_chat_filter_settings_v1_out(RsprotExec *x, MsgChatFilterSettings *m);
/* v2 -- revs 222. */
void packet_chat_filter_settings_v2_out(RsprotExec *x, MsgChatFilterSettings *m);
/* v3 -- revs 223. */
void packet_chat_filter_settings_v3_out(RsprotExec *x, MsgChatFilterSettings *m);
/* v4 -- revs 224. */
void packet_chat_filter_settings_v4_out(RsprotExec *x, MsgChatFilterSettings *m);
/* v5 -- revs 225, 237. */
void packet_chat_filter_settings_v5_out(RsprotExec *x, MsgChatFilterSettings *m);
/* v6 -- revs 226. */
void packet_chat_filter_settings_v6_out(RsprotExec *x, MsgChatFilterSettings *m);
/* v7 -- revs 227, 234. */
void packet_chat_filter_settings_v7_out(RsprotExec *x, MsgChatFilterSettings *m);
/* v8 -- revs 228, 238. */
void packet_chat_filter_settings_v8_out(RsprotExec *x, MsgChatFilterSettings *m);
/* v9 -- revs 229, 232. */
void packet_chat_filter_settings_v9_out(RsprotExec *x, MsgChatFilterSettings *m);
/* v10 -- revs 230. */
void packet_chat_filter_settings_v10_out(RsprotExec *x, MsgChatFilterSettings *m);
/* v11 -- revs 231. */
void packet_chat_filter_settings_v11_out(RsprotExec *x, MsgChatFilterSettings *m);
/* v12 -- revs 233. */
void packet_chat_filter_settings_v12_out(RsprotExec *x, MsgChatFilterSettings *m);
/* v13 -- revs 235. */
void packet_chat_filter_settings_v13_out(RsprotExec *x, MsgChatFilterSettings *m);
/* v14 -- revs 236. */
void packet_chat_filter_settings_v14_out(RsprotExec *x, MsgChatFilterSettings *m);
/* v15 -- revs 239. */
void packet_chat_filter_settings_v15_out(RsprotExec *x, MsgChatFilterSettings *m);

/* Per-revision aliases: `packet_chat_filter_settings_rev239_out` is greppable, which is the
 * point -- "what does 239 do for CHAT_FILTER_SETTINGS" without reading a table. */
#define packet_chat_filter_settings_rev221_out packet_chat_filter_settings_v1_out
#define packet_chat_filter_settings_rev222_out packet_chat_filter_settings_v2_out
#define packet_chat_filter_settings_rev223_out packet_chat_filter_settings_v3_out
#define packet_chat_filter_settings_rev224_out packet_chat_filter_settings_v4_out
#define packet_chat_filter_settings_rev225_out packet_chat_filter_settings_v5_out
#define packet_chat_filter_settings_rev226_out packet_chat_filter_settings_v6_out
#define packet_chat_filter_settings_rev227_out packet_chat_filter_settings_v7_out
#define packet_chat_filter_settings_rev228_out packet_chat_filter_settings_v8_out
#define packet_chat_filter_settings_rev229_out packet_chat_filter_settings_v9_out
#define packet_chat_filter_settings_rev230_out packet_chat_filter_settings_v10_out
#define packet_chat_filter_settings_rev231_out packet_chat_filter_settings_v11_out
#define packet_chat_filter_settings_rev232_out packet_chat_filter_settings_v9_out
#define packet_chat_filter_settings_rev233_out packet_chat_filter_settings_v12_out
#define packet_chat_filter_settings_rev234_out packet_chat_filter_settings_v7_out
#define packet_chat_filter_settings_rev235_out packet_chat_filter_settings_v13_out
#define packet_chat_filter_settings_rev236_out packet_chat_filter_settings_v14_out
#define packet_chat_filter_settings_rev237_out packet_chat_filter_settings_v5_out
#define packet_chat_filter_settings_rev238_out packet_chat_filter_settings_v8_out
#define packet_chat_filter_settings_rev239_out packet_chat_filter_settings_v15_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_chat_filter_settings_out[];
extern const int rsprot_chat_filter_settings_out_count;

#endif
