#ifndef RSPROT_PACKET_CLANCHANNEL_KICKUSER_H
#define RSPROT_PACKET_CLANCHANNEL_KICKUSER_H

/*
 * CLANCHANNEL_KICKUSER -- client -> server.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : ClanChannelKickUserDecoder
 * Layouts      : 1 distinct, over 1 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^ClanChannelKickUserDecoder\tin\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgClanChannelKickUser {
	int32_t clan_id;
	int32_t member_index;
	const char *name;
} MsgClanChannelKickUser;

/* v1 -- revs 221-239. */
void packet_clanchannel_kickuser_v1_in(RsprotExec *x, MsgClanChannelKickUser *m);

/* Per-revision aliases: `packet_clanchannel_kickuser_rev239_in` is greppable, which is the
 * point -- "what does 239 do for CLANCHANNEL_KICKUSER" without reading a table. */
#define packet_clanchannel_kickuser_rev221_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev222_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev223_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev224_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev225_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev226_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev227_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev228_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev229_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev230_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev231_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev232_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev233_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev234_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev235_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev236_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev237_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev238_in packet_clanchannel_kickuser_v1_in
#define packet_clanchannel_kickuser_rev239_in packet_clanchannel_kickuser_v1_in

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_clanchannel_kickuser_in[];
extern const int rsprot_clanchannel_kickuser_in_count;

#endif
