/* EVENT_MOUSE_SCROLL. GENERATED by tools/rsprot_gen_codec.py -- do not edit. */
#include "event_mouse_scroll.h"

/*
 * Transcribed from RSProt:
 *   protocol/osrs-<N>/osrs-<N>-desktop/src/main/kotlin/net/rsprot/protocol/
 *       game/incoming/codec/events/EventMouseScrollDecoder.kt
 *
 * One function per layout, running in whichever direction the executor is in --
 * so a server's writer and a client's reader are the same transcription and
 * cannot drift apart.
 */

/* v1 -- revs 221-239. */
void
packet_event_mouse_scroll_v1_in(RsprotExec *x, MsgEventMouseScroll *m)
{
    RSPROT_I2(x, m->rotation);
}

/*
 * 1 row(s) for 1 layout(s), complete over revisions 221-239.
 * A complete table makes rsprot_version_pick's NULL mean exactly one thing: a
 * revision outside that span. An incomplete one would conflate "not
 * transcribed" with "no such packet", and those are different facts.
 */
const RsprotVersionRange rsprot_event_mouse_scroll_in[] = {
    { 221, 239, (RsprotCodecFn)packet_event_mouse_scroll_v1_in },
};

const int rsprot_event_mouse_scroll_in_count =
    (int)(sizeof(rsprot_event_mouse_scroll_in) / sizeof(rsprot_event_mouse_scroll_in[0]));
