#ifndef RSPROT_PACKET_EVENT_NATIVE_MOUSE_CLICK_H
#define RSPROT_PACKET_EVENT_NATIVE_MOUSE_CLICK_H

/*
 * EVENT_NATIVE_MOUSE_CLICK -- client -> server.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : EventNativeMouseClickDecoder
 * Layouts      : 10 distinct, over 10 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^EventNativeMouseClickDecoder\tin\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgEventNativeMouseClick {
	int32_t last_transmitted_mouse_click;
	int32_t packed_coord;
	int32_t code;
} MsgEventNativeMouseClick;

/* v1 -- revs 222. */
void packet_event_native_mouse_click_v1_in(RsprotExec *x, MsgEventNativeMouseClick *m);
/* v2 -- revs 223. */
void packet_event_native_mouse_click_v2_in(RsprotExec *x, MsgEventNativeMouseClick *m);
/* v3 -- revs 224. */
void packet_event_native_mouse_click_v3_in(RsprotExec *x, MsgEventNativeMouseClick *m);
/* v4 -- revs 225. */
void packet_event_native_mouse_click_v4_in(RsprotExec *x, MsgEventNativeMouseClick *m);
/* v5 -- revs 226. */
void packet_event_native_mouse_click_v5_in(RsprotExec *x, MsgEventNativeMouseClick *m);
/* v6 -- revs 227. */
void packet_event_native_mouse_click_v6_in(RsprotExec *x, MsgEventNativeMouseClick *m);
/* v7 -- revs 228. */
void packet_event_native_mouse_click_v7_in(RsprotExec *x, MsgEventNativeMouseClick *m);
/* v8 -- revs 229. */
void packet_event_native_mouse_click_v8_in(RsprotExec *x, MsgEventNativeMouseClick *m);
/* v9 -- revs 230. */
void packet_event_native_mouse_click_v9_in(RsprotExec *x, MsgEventNativeMouseClick *m);
/* v10 -- revs 231. */
void packet_event_native_mouse_click_v10_in(RsprotExec *x, MsgEventNativeMouseClick *m);

/* Per-revision aliases: `packet_event_native_mouse_click_rev239_in` is greppable, which is the
 * point -- "what does 239 do for EVENT_NATIVE_MOUSE_CLICK" without reading a table. */
#define packet_event_native_mouse_click_rev222_in packet_event_native_mouse_click_v1_in
#define packet_event_native_mouse_click_rev223_in packet_event_native_mouse_click_v2_in
#define packet_event_native_mouse_click_rev224_in packet_event_native_mouse_click_v3_in
#define packet_event_native_mouse_click_rev225_in packet_event_native_mouse_click_v4_in
#define packet_event_native_mouse_click_rev226_in packet_event_native_mouse_click_v5_in
#define packet_event_native_mouse_click_rev227_in packet_event_native_mouse_click_v6_in
#define packet_event_native_mouse_click_rev228_in packet_event_native_mouse_click_v7_in
#define packet_event_native_mouse_click_rev229_in packet_event_native_mouse_click_v8_in
#define packet_event_native_mouse_click_rev230_in packet_event_native_mouse_click_v9_in
#define packet_event_native_mouse_click_rev231_in packet_event_native_mouse_click_v10_in

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_event_native_mouse_click_in[];
extern const int rsprot_event_native_mouse_click_in_count;

#endif
