#ifndef RSPROT_PACKET_EVENT_MOUSE_SCROLL_H
#define RSPROT_PACKET_EVENT_MOUSE_SCROLL_H

/*
 * EVENT_MOUSE_SCROLL -- client -> server.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : EventMouseScrollDecoder
 * Layouts      : 1 distinct, over 1 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^EventMouseScrollDecoder\tin\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgEventMouseScroll {
	int32_t rotation;
} MsgEventMouseScroll;

/* v1 -- revs 221-239. */
void packet_event_mouse_scroll_v1_in(RsprotExec *x, MsgEventMouseScroll *m);

/* Per-revision aliases: `packet_event_mouse_scroll_rev239_in` is greppable, which is the
 * point -- "what does 239 do for EVENT_MOUSE_SCROLL" without reading a table. */
#define packet_event_mouse_scroll_rev221_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev222_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev223_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev224_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev225_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev226_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev227_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev228_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev229_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev230_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev231_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev232_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev233_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev234_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev235_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev236_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev237_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev238_in packet_event_mouse_scroll_v1_in
#define packet_event_mouse_scroll_rev239_in packet_event_mouse_scroll_v1_in

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_event_mouse_scroll_in[];
extern const int rsprot_event_mouse_scroll_in_count;

#endif
