/* FRIENDCHAT_KICK. GENERATED by tools/rsprot_gen_codec.py -- do not edit. */
#include "friendchat_kick.h"

/*
 * Transcribed from RSProt:
 *   protocol/osrs-<N>/osrs-<N>-desktop/src/main/kotlin/net/rsprot/protocol/
 *       game/incoming/codec/friendchat/FriendChatKickDecoder.kt
 *
 * One function per layout, running in whichever direction the executor is in --
 * so a server's writer and a client's reader are the same transcription and
 * cannot drift apart.
 */

/* v1 -- revs 221-239. */
void
packet_friendchat_kick_v1_in(RsprotExec *x, MsgFriendChatKick *m)
{
    RSPROT_JSTR(x, m->name);
}

/*
 * 1 row(s) for 1 layout(s), complete over revisions 221-239.
 * A complete table makes rsprot_version_pick's NULL mean exactly one thing: a
 * revision outside that span. An incomplete one would conflate "not
 * transcribed" with "no such packet", and those are different facts.
 */
const RsprotVersionRange rsprot_friendchat_kick_in[] = {
    { 221, 239, (RsprotCodecFn)packet_friendchat_kick_v1_in },
};

const int rsprot_friendchat_kick_in_count =
    (int)(sizeof(rsprot_friendchat_kick_in) / sizeof(rsprot_friendchat_kick_in[0]));
