/* IF_CRMVIEW_OP. GENERATED by tools/rsprot_gen_codec.py -- do not edit. */
#include "if_crmview_op.h"

/*
 * Transcribed from RSProt:
 *   protocol/osrs-<N>/osrs-<N>-desktop/src/main/kotlin/net/rsprot/protocol/
 *       game/incoming/codec/misc/user/IfCrmViewOpDecoder.kt
 *
 * One function per layout, running in whichever direction the executor is in --
 * so a server's writer and a client's reader are the same transcription and
 * cannot drift apart.
 */

/* v1 -- revs 221. */
void
packet_if_crmview_op_v1_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_U4_ALT1(x, m->server_target);
    RSPROT_U2(x, m->sub);
    RSPROT_U4(x, m->behaviour2);
    RSPROT_U4_ALT2(x, m->behaviour3);
    RSPROT_COM_ALT1(x, m->combined_id);
    RSPROT_U4_ALT2(x, m->behaviour1);
}

/* v2 -- revs 222. */
void
packet_if_crmview_op_v2_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_U4_ALT2(x, m->server_target);
    RSPROT_U4_ALT2(x, m->behaviour2);
    RSPROT_U4_ALT3(x, m->behaviour3);
    RSPROT_U2_ALT2(x, m->sub);
    RSPROT_COM_ALT3(x, m->combined_id);
    RSPROT_U4_ALT1(x, m->behaviour1);
}

/* v3 -- revs 223. */
void
packet_if_crmview_op_v3_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_COM_ALT1(x, m->combined_id);
    RSPROT_U2_ALT1(x, m->sub);
    RSPROT_U4_ALT3(x, m->behaviour2);
    RSPROT_U4_ALT3(x, m->server_target);
    RSPROT_U4_ALT1(x, m->behaviour1);
    RSPROT_U4_ALT1(x, m->behaviour3);
}

/* v4 -- revs 224. */
void
packet_if_crmview_op_v4_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_U2_ALT1(x, m->sub);
    RSPROT_U4(x, m->behaviour2);
    RSPROT_U4_ALT3(x, m->server_target);
    RSPROT_U4_ALT2(x, m->behaviour1);
    RSPROT_COM_ALT1(x, m->combined_id);
    RSPROT_U4_ALT1(x, m->behaviour3);
}

/* v5 -- revs 225. */
void
packet_if_crmview_op_v5_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_U2(x, m->sub);
    RSPROT_U4(x, m->behaviour1);
    RSPROT_U4_ALT1(x, m->behaviour2);
    RSPROT_COM(x, m->combined_id);
    RSPROT_U4(x, m->behaviour3);
    RSPROT_U4_ALT1(x, m->server_target);
}

/* v6 -- revs 226. */
void
packet_if_crmview_op_v6_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_U4_ALT1(x, m->server_target);
    RSPROT_U4(x, m->behaviour1);
    RSPROT_U2(x, m->sub);
    RSPROT_COM_ALT2(x, m->combined_id);
    RSPROT_U4_ALT2(x, m->behaviour2);
    RSPROT_U4_ALT1(x, m->behaviour3);
}

/* v7 -- revs 227. */
void
packet_if_crmview_op_v7_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_U4_ALT3(x, m->behaviour1);
    RSPROT_U2_ALT2(x, m->sub);
    RSPROT_COM_ALT3(x, m->combined_id);
    RSPROT_U4_ALT2(x, m->behaviour3);
    RSPROT_U4_ALT3(x, m->behaviour2);
    RSPROT_U4_ALT2(x, m->server_target);
}

/* v8 -- revs 228. */
void
packet_if_crmview_op_v8_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_U4_ALT1(x, m->behaviour3);
    RSPROT_U4(x, m->server_target);
    RSPROT_U4_ALT2(x, m->behaviour2);
    RSPROT_U4_ALT1(x, m->behaviour1);
    RSPROT_U2(x, m->sub);
    RSPROT_COM_ALT2(x, m->combined_id);
}

/* v9 -- revs 229. */
void
packet_if_crmview_op_v9_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_U4_ALT3(x, m->behaviour2);
    RSPROT_U4_ALT1(x, m->behaviour1);
    RSPROT_U4_ALT1(x, m->server_target);
    RSPROT_U4_ALT2(x, m->behaviour3);
    RSPROT_U2(x, m->sub);
    RSPROT_COM_ALT2(x, m->combined_id);
}

/* v10 -- revs 230. */
void
packet_if_crmview_op_v10_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_U4_ALT1(x, m->behaviour1);
    RSPROT_COM_ALT2(x, m->combined_id);
    RSPROT_U4_ALT2(x, m->behaviour3);
    RSPROT_U4(x, m->server_target);
    RSPROT_U2_ALT2(x, m->sub);
    RSPROT_U4_ALT2(x, m->behaviour2);
}

/* v11 -- revs 231. */
void
packet_if_crmview_op_v11_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_U4_ALT3(x, m->server_target);
    RSPROT_U4(x, m->behaviour3);
    RSPROT_COM_ALT3(x, m->combined_id);
    RSPROT_U2(x, m->sub);
    RSPROT_U4_ALT1(x, m->behaviour1);
    RSPROT_U4_ALT2(x, m->behaviour2);
}

/* v12 -- revs 232. */
void
packet_if_crmview_op_v12_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_COM_ALT3(x, m->combined_id);
    RSPROT_U4_ALT1(x, m->server_target);
    RSPROT_U4(x, m->behaviour1);
    RSPROT_U4_ALT1(x, m->behaviour3);
    RSPROT_U4(x, m->behaviour2);
    RSPROT_U2(x, m->sub);
}

/* v13 -- revs 233. */
void
packet_if_crmview_op_v13_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_U4_ALT3(x, m->behaviour1);
    RSPROT_U4_ALT1(x, m->behaviour3);
    RSPROT_U4_ALT2(x, m->behaviour2);
    RSPROT_U2_ALT3(x, m->sub);
    RSPROT_COM(x, m->combined_id);
    RSPROT_U4_ALT1(x, m->server_target);
}

/* v14 -- revs 234. */
void
packet_if_crmview_op_v14_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_U2_ALT2(x, m->sub);
    RSPROT_COM_ALT3(x, m->combined_id);
    RSPROT_U4_ALT2(x, m->server_target);
    RSPROT_U4_ALT1(x, m->behaviour2);
    RSPROT_U4_ALT3(x, m->behaviour1);
    RSPROT_U4(x, m->behaviour3);
}

/* v15 -- revs 235. */
void
packet_if_crmview_op_v15_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_U4_ALT1(x, m->server_target);
    RSPROT_U2_ALT1(x, m->sub);
    RSPROT_U4_ALT3(x, m->behaviour3);
    RSPROT_U4_ALT1(x, m->behaviour2);
    RSPROT_U4_ALT3(x, m->behaviour1);
    RSPROT_COM_ALT1(x, m->combined_id);
}

/* v16 -- revs 236. */
void
packet_if_crmview_op_v16_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_U4_ALT1(x, m->server_target);
    RSPROT_U2_ALT2(x, m->sub);
    RSPROT_U4_ALT2(x, m->behaviour3);
    RSPROT_U4(x, m->behaviour2);
    RSPROT_U4_ALT1(x, m->behaviour1);
    RSPROT_COM_ALT2(x, m->combined_id);
}

/* v17 -- revs 237. */
void
packet_if_crmview_op_v17_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_U2_ALT3(x, m->sub);
    RSPROT_COM_ALT3(x, m->combined_id);
    RSPROT_U4_ALT2(x, m->behaviour1);
    RSPROT_U4(x, m->behaviour2);
    RSPROT_U4_ALT3(x, m->behaviour3);
    RSPROT_U4(x, m->server_target);
}

/* v18 -- revs 238. */
void
packet_if_crmview_op_v18_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_U4_ALT1(x, m->behaviour2);
    RSPROT_U4_ALT3(x, m->server_target);
    RSPROT_U4(x, m->behaviour3);
    RSPROT_U2_ALT1(x, m->sub);
    RSPROT_COM_ALT3(x, m->combined_id);
    RSPROT_U4(x, m->behaviour1);
}

/* v19 -- revs 239. */
void
packet_if_crmview_op_v19_in(RsprotExec *x, MsgIfCrmViewOp *m)
{
    RSPROT_COM_ALT2(x, m->combined_id);
    RSPROT_U4(x, m->server_target);
    RSPROT_U4_ALT2(x, m->behaviour1);
    RSPROT_U4_ALT2(x, m->behaviour3);
    RSPROT_U4_ALT1(x, m->behaviour2);
    RSPROT_U2_ALT1(x, m->sub);
}

/*
 * 19 row(s) for 19 layout(s), complete over revisions 221-239.
 * A complete table makes rsprot_version_pick's NULL mean exactly one thing: a
 * revision outside that span. An incomplete one would conflate "not
 * transcribed" with "no such packet", and those are different facts.
 */
const RsprotVersionRange rsprot_if_crmview_op_in[] = {
    { 221, 221, (RsprotCodecFn)packet_if_crmview_op_v1_in },
    { 222, 222, (RsprotCodecFn)packet_if_crmview_op_v2_in },
    { 223, 223, (RsprotCodecFn)packet_if_crmview_op_v3_in },
    { 224, 224, (RsprotCodecFn)packet_if_crmview_op_v4_in },
    { 225, 225, (RsprotCodecFn)packet_if_crmview_op_v5_in },
    { 226, 226, (RsprotCodecFn)packet_if_crmview_op_v6_in },
    { 227, 227, (RsprotCodecFn)packet_if_crmview_op_v7_in },
    { 228, 228, (RsprotCodecFn)packet_if_crmview_op_v8_in },
    { 229, 229, (RsprotCodecFn)packet_if_crmview_op_v9_in },
    { 230, 230, (RsprotCodecFn)packet_if_crmview_op_v10_in },
    { 231, 231, (RsprotCodecFn)packet_if_crmview_op_v11_in },
    { 232, 232, (RsprotCodecFn)packet_if_crmview_op_v12_in },
    { 233, 233, (RsprotCodecFn)packet_if_crmview_op_v13_in },
    { 234, 234, (RsprotCodecFn)packet_if_crmview_op_v14_in },
    { 235, 235, (RsprotCodecFn)packet_if_crmview_op_v15_in },
    { 236, 236, (RsprotCodecFn)packet_if_crmview_op_v16_in },
    { 237, 237, (RsprotCodecFn)packet_if_crmview_op_v17_in },
    { 238, 238, (RsprotCodecFn)packet_if_crmview_op_v18_in },
    { 239, 239, (RsprotCodecFn)packet_if_crmview_op_v19_in },
};

const int rsprot_if_crmview_op_in_count =
    (int)(sizeof(rsprot_if_crmview_op_in) / sizeof(rsprot_if_crmview_op_in[0]));
