/* IF_CLOSESUB. GENERATED by tools/rsprot_gen_codec.py -- do not edit. */
#include "if_closesub.h"

/*
 * Transcribed from RSProt:
 *   protocol/osrs-<N>/osrs-<N>-desktop/src/main/kotlin/net/rsprot/protocol/
 *       game/outgoing/codec/interfaces/IfCloseSubEncoder.kt
 *
 * One function per layout, running in whichever direction the executor is in --
 * so a server's writer and a client's reader are the same transcription and
 * cannot drift apart.
 */

/* v1 -- revs 221. */
void
packet_if_closesub_v1_out(RsprotExec *x, MsgIfCloseSub *m)
{
    RSPROT_U4(x, m->combined_id);
}

/* v2 -- revs 222-239. */
void
packet_if_closesub_v2_out(RsprotExec *x, MsgIfCloseSub *m)
{
    RSPROT_COM(x, m->combined_id);
}

/*
 * 2 row(s) for 2 layout(s), complete over revisions 221-239.
 * A complete table makes rsprot_version_pick's NULL mean exactly one thing: a
 * revision outside that span. An incomplete one would conflate "not
 * transcribed" with "no such packet", and those are different facts.
 */
const RsprotVersionRange rsprot_if_closesub_out[] = {
    { 221, 221, (RsprotCodecFn)packet_if_closesub_v1_out },
    { 222, 239, (RsprotCodecFn)packet_if_closesub_v2_out },
};

const int rsprot_if_closesub_out_count =
    (int)(sizeof(rsprot_if_closesub_out) / sizeof(rsprot_if_closesub_out[0]));
