#ifndef RSPROT_PACKET_IF_SETTEXT_H
#define RSPROT_PACKET_IF_SETTEXT_H

/*
 * IF_SETTEXT -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : IfSetTextEncoder
 * Layouts      : 8 distinct, over 17 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^IfSetTextEncoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgIfSetText {
	int32_t combined_id;
	const char *text;
} MsgIfSetText;

/* v1 -- revs 221. */
void packet_if_settext_v1_out(RsprotExec *x, MsgIfSetText *m);
/* v2 -- revs 222, 227, 231. */
void packet_if_settext_v2_out(RsprotExec *x, MsgIfSetText *m);
/* v3 -- revs 223, 228. */
void packet_if_settext_v3_out(RsprotExec *x, MsgIfSetText *m);
/* v4 -- revs 224, 237-238. */
void packet_if_settext_v4_out(RsprotExec *x, MsgIfSetText *m);
/* v5 -- revs 225, 229, 234. */
void packet_if_settext_v5_out(RsprotExec *x, MsgIfSetText *m);
/* v6 -- revs 226, 230, 235-236, 239. */
void packet_if_settext_v6_out(RsprotExec *x, MsgIfSetText *m);
/* v7 -- revs 232. */
void packet_if_settext_v7_out(RsprotExec *x, MsgIfSetText *m);
/* v8 -- revs 233. */
void packet_if_settext_v8_out(RsprotExec *x, MsgIfSetText *m);

/* Per-revision aliases: `packet_if_settext_rev239_out` is greppable, which is the
 * point -- "what does 239 do for IF_SETTEXT" without reading a table. */
#define packet_if_settext_rev221_out packet_if_settext_v1_out
#define packet_if_settext_rev222_out packet_if_settext_v2_out
#define packet_if_settext_rev223_out packet_if_settext_v3_out
#define packet_if_settext_rev224_out packet_if_settext_v4_out
#define packet_if_settext_rev225_out packet_if_settext_v5_out
#define packet_if_settext_rev226_out packet_if_settext_v6_out
#define packet_if_settext_rev227_out packet_if_settext_v2_out
#define packet_if_settext_rev228_out packet_if_settext_v3_out
#define packet_if_settext_rev229_out packet_if_settext_v5_out
#define packet_if_settext_rev230_out packet_if_settext_v6_out
#define packet_if_settext_rev231_out packet_if_settext_v2_out
#define packet_if_settext_rev232_out packet_if_settext_v7_out
#define packet_if_settext_rev233_out packet_if_settext_v8_out
#define packet_if_settext_rev234_out packet_if_settext_v5_out
#define packet_if_settext_rev235_out packet_if_settext_v6_out
#define packet_if_settext_rev236_out packet_if_settext_v6_out
#define packet_if_settext_rev237_out packet_if_settext_v4_out
#define packet_if_settext_rev238_out packet_if_settext_v4_out
#define packet_if_settext_rev239_out packet_if_settext_v6_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_if_settext_out[];
extern const int rsprot_if_settext_out_count;

#endif
