/* IF_SETSCROLLPOS. GENERATED by tools/rsprot_gen_codec.py -- do not edit. */
#include "if_setscrollpos.h"

/*
 * Transcribed from RSProt:
 *   protocol/osrs-<N>/osrs-<N>-desktop/src/main/kotlin/net/rsprot/protocol/
 *       game/outgoing/codec/interfaces/IfSetScrollPosEncoder.kt
 *
 * One function per layout, running in whichever direction the executor is in --
 * so a server's writer and a client's reader are the same transcription and
 * cannot drift apart.
 */

/* v1 -- revs 221. */
void
packet_if_setscrollpos_v1_out(RsprotExec *x, MsgIfSetScrollPos *m)
{
    RSPROT_U2_ALT2(x, m->scroll_pos);
    RSPROT_U4_ALT3(x, m->combined_id);
}

/* v2 -- revs 222. */
void
packet_if_setscrollpos_v2_out(RsprotExec *x, MsgIfSetScrollPos *m)
{
    RSPROT_U2_ALT1(x, m->scroll_pos);
    RSPROT_COM(x, m->combined_id);
}

/* v3 -- revs 223, 234. */
void
packet_if_setscrollpos_v3_out(RsprotExec *x, MsgIfSetScrollPos *m)
{
    RSPROT_U2(x, m->scroll_pos);
    RSPROT_COM_ALT2(x, m->combined_id);
}

/* v4 -- revs 224, 233. */
void
packet_if_setscrollpos_v4_out(RsprotExec *x, MsgIfSetScrollPos *m)
{
    RSPROT_COM_ALT3(x, m->combined_id);
    RSPROT_U2_ALT3(x, m->scroll_pos);
}

/* v5 -- revs 225. */
void
packet_if_setscrollpos_v5_out(RsprotExec *x, MsgIfSetScrollPos *m)
{
    RSPROT_COM_ALT1(x, m->combined_id);
    RSPROT_U2_ALT2(x, m->scroll_pos);
}

/* v6 -- revs 226. */
void
packet_if_setscrollpos_v6_out(RsprotExec *x, MsgIfSetScrollPos *m)
{
    RSPROT_COM(x, m->combined_id);
    RSPROT_U2_ALT2(x, m->scroll_pos);
}

/* v7 -- revs 227. */
void
packet_if_setscrollpos_v7_out(RsprotExec *x, MsgIfSetScrollPos *m)
{
    RSPROT_U2(x, m->scroll_pos);
    RSPROT_COM_ALT1(x, m->combined_id);
}

/* v8 -- revs 228. */
void
packet_if_setscrollpos_v8_out(RsprotExec *x, MsgIfSetScrollPos *m)
{
    RSPROT_COM(x, m->combined_id);
    RSPROT_U2_ALT3(x, m->scroll_pos);
}

/* v9 -- revs 229. */
void
packet_if_setscrollpos_v9_out(RsprotExec *x, MsgIfSetScrollPos *m)
{
    RSPROT_COM_ALT1(x, m->combined_id);
    RSPROT_U2(x, m->scroll_pos);
}

/* v10 -- revs 230, 239. */
void
packet_if_setscrollpos_v10_out(RsprotExec *x, MsgIfSetScrollPos *m)
{
    RSPROT_COM_ALT3(x, m->combined_id);
    RSPROT_U2(x, m->scroll_pos);
}

/* v11 -- revs 231. */
void
packet_if_setscrollpos_v11_out(RsprotExec *x, MsgIfSetScrollPos *m)
{
    RSPROT_COM(x, m->combined_id);
    RSPROT_U2(x, m->scroll_pos);
}

/* v12 -- revs 232. */
void
packet_if_setscrollpos_v12_out(RsprotExec *x, MsgIfSetScrollPos *m)
{
    RSPROT_COM(x, m->combined_id);
    RSPROT_U2_ALT1(x, m->scroll_pos);
}

/* v13 -- revs 235. */
void
packet_if_setscrollpos_v13_out(RsprotExec *x, MsgIfSetScrollPos *m)
{
    RSPROT_COM_ALT2(x, m->combined_id);
    RSPROT_U2(x, m->scroll_pos);
}

/* v14 -- revs 236-237. */
void
packet_if_setscrollpos_v14_out(RsprotExec *x, MsgIfSetScrollPos *m)
{
    RSPROT_COM_ALT3(x, m->combined_id);
    RSPROT_U2_ALT1(x, m->scroll_pos);
}

/* v15 -- revs 238. */
void
packet_if_setscrollpos_v15_out(RsprotExec *x, MsgIfSetScrollPos *m)
{
    RSPROT_COM_ALT3(x, m->combined_id);
    RSPROT_U2_ALT2(x, m->scroll_pos);
}

/*
 * 18 row(s) for 15 layout(s), complete over revisions 221-239.
 * A complete table makes rsprot_version_pick's NULL mean exactly one thing: a
 * revision outside that span. An incomplete one would conflate "not
 * transcribed" with "no such packet", and those are different facts.
 */
const RsprotVersionRange rsprot_if_setscrollpos_out[] = {
    { 221, 221, (RsprotCodecFn)packet_if_setscrollpos_v1_out },
    { 222, 222, (RsprotCodecFn)packet_if_setscrollpos_v2_out },
    { 223, 223, (RsprotCodecFn)packet_if_setscrollpos_v3_out },
    { 224, 224, (RsprotCodecFn)packet_if_setscrollpos_v4_out },
    { 225, 225, (RsprotCodecFn)packet_if_setscrollpos_v5_out },
    { 226, 226, (RsprotCodecFn)packet_if_setscrollpos_v6_out },
    { 227, 227, (RsprotCodecFn)packet_if_setscrollpos_v7_out },
    { 228, 228, (RsprotCodecFn)packet_if_setscrollpos_v8_out },
    { 229, 229, (RsprotCodecFn)packet_if_setscrollpos_v9_out },
    { 230, 230, (RsprotCodecFn)packet_if_setscrollpos_v10_out },
    { 231, 231, (RsprotCodecFn)packet_if_setscrollpos_v11_out },
    { 232, 232, (RsprotCodecFn)packet_if_setscrollpos_v12_out },
    { 233, 233, (RsprotCodecFn)packet_if_setscrollpos_v4_out },
    { 234, 234, (RsprotCodecFn)packet_if_setscrollpos_v3_out },
    { 235, 235, (RsprotCodecFn)packet_if_setscrollpos_v13_out },
    { 236, 237, (RsprotCodecFn)packet_if_setscrollpos_v14_out },
    { 238, 238, (RsprotCodecFn)packet_if_setscrollpos_v15_out },
    { 239, 239, (RsprotCodecFn)packet_if_setscrollpos_v10_out },
};

const int rsprot_if_setscrollpos_out_count =
    (int)(sizeof(rsprot_if_setscrollpos_out) / sizeof(rsprot_if_setscrollpos_out[0]));
