#ifndef RSPROT_PACKET_IF_SETANIM_H
#define RSPROT_PACKET_IF_SETANIM_H

/*
 * IF_SETANIM -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : IfSetAnimEncoder
 * Layouts      : 14 distinct, over 19 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^IfSetAnimEncoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgIfSetAnim {
	int32_t anim;
	int32_t combined_id;
} MsgIfSetAnim;

/* v1 -- revs 221. */
void packet_if_setanim_v1_out(RsprotExec *x, MsgIfSetAnim *m);
/* v2 -- revs 222, 230. */
void packet_if_setanim_v2_out(RsprotExec *x, MsgIfSetAnim *m);
/* v3 -- revs 223, 228, 235. */
void packet_if_setanim_v3_out(RsprotExec *x, MsgIfSetAnim *m);
/* v4 -- revs 224. */
void packet_if_setanim_v4_out(RsprotExec *x, MsgIfSetAnim *m);
/* v5 -- revs 225. */
void packet_if_setanim_v5_out(RsprotExec *x, MsgIfSetAnim *m);
/* v6 -- revs 226, 238. */
void packet_if_setanim_v6_out(RsprotExec *x, MsgIfSetAnim *m);
/* v7 -- revs 227. */
void packet_if_setanim_v7_out(RsprotExec *x, MsgIfSetAnim *m);
/* v8 -- revs 229. */
void packet_if_setanim_v8_out(RsprotExec *x, MsgIfSetAnim *m);
/* v9 -- revs 231. */
void packet_if_setanim_v9_out(RsprotExec *x, MsgIfSetAnim *m);
/* v10 -- revs 232. */
void packet_if_setanim_v10_out(RsprotExec *x, MsgIfSetAnim *m);
/* v11 -- revs 233, 239. */
void packet_if_setanim_v11_out(RsprotExec *x, MsgIfSetAnim *m);
/* v12 -- revs 234. */
void packet_if_setanim_v12_out(RsprotExec *x, MsgIfSetAnim *m);
/* v13 -- revs 236. */
void packet_if_setanim_v13_out(RsprotExec *x, MsgIfSetAnim *m);
/* v14 -- revs 237. */
void packet_if_setanim_v14_out(RsprotExec *x, MsgIfSetAnim *m);

/* Per-revision aliases: `packet_if_setanim_rev239_out` is greppable, which is the
 * point -- "what does 239 do for IF_SETANIM" without reading a table. */
#define packet_if_setanim_rev221_out packet_if_setanim_v1_out
#define packet_if_setanim_rev222_out packet_if_setanim_v2_out
#define packet_if_setanim_rev223_out packet_if_setanim_v3_out
#define packet_if_setanim_rev224_out packet_if_setanim_v4_out
#define packet_if_setanim_rev225_out packet_if_setanim_v5_out
#define packet_if_setanim_rev226_out packet_if_setanim_v6_out
#define packet_if_setanim_rev227_out packet_if_setanim_v7_out
#define packet_if_setanim_rev228_out packet_if_setanim_v3_out
#define packet_if_setanim_rev229_out packet_if_setanim_v8_out
#define packet_if_setanim_rev230_out packet_if_setanim_v2_out
#define packet_if_setanim_rev231_out packet_if_setanim_v9_out
#define packet_if_setanim_rev232_out packet_if_setanim_v10_out
#define packet_if_setanim_rev233_out packet_if_setanim_v11_out
#define packet_if_setanim_rev234_out packet_if_setanim_v12_out
#define packet_if_setanim_rev235_out packet_if_setanim_v3_out
#define packet_if_setanim_rev236_out packet_if_setanim_v13_out
#define packet_if_setanim_rev237_out packet_if_setanim_v14_out
#define packet_if_setanim_rev238_out packet_if_setanim_v6_out
#define packet_if_setanim_rev239_out packet_if_setanim_v11_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_if_setanim_out[];
extern const int rsprot_if_setanim_out_count;

#endif
