/* IF_SETANGLE. GENERATED by tools/rsprot_gen_codec.py -- do not edit. */
#include "if_setangle.h"

/*
 * Transcribed from RSProt:
 *   protocol/osrs-<N>/osrs-<N>-desktop/src/main/kotlin/net/rsprot/protocol/
 *       game/outgoing/codec/interfaces/IfSetAngleEncoder.kt
 *
 * One function per layout, running in whichever direction the executor is in --
 * so a server's writer and a client's reader are the same transcription and
 * cannot drift apart.
 */

/* v1 -- revs 221. */
void
packet_if_setangle_v1_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_U2_ALT2(x, m->angle_x);
    RSPROT_U2_ALT1(x, m->zoom);
    RSPROT_U2(x, m->angle_y);
    RSPROT_U4(x, m->combined_id);
}

/* v2 -- revs 222. */
void
packet_if_setangle_v2_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_U2_ALT1(x, m->zoom);
    RSPROT_U2_ALT3(x, m->angle_y);
    RSPROT_U2(x, m->angle_x);
    RSPROT_COM_ALT2(x, m->combined_id);
}

/* v3 -- revs 223. */
void
packet_if_setangle_v3_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_COM(x, m->combined_id);
    RSPROT_U2_ALT3(x, m->angle_x);
    RSPROT_U2(x, m->angle_y);
    RSPROT_U2(x, m->zoom);
}

/* v4 -- revs 224. */
void
packet_if_setangle_v4_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_COM_ALT1(x, m->combined_id);
    RSPROT_U2_ALT3(x, m->angle_y);
    RSPROT_U2(x, m->zoom);
    RSPROT_U2_ALT3(x, m->angle_x);
}

/* v5 -- revs 225. */
void
packet_if_setangle_v5_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_U2_ALT2(x, m->angle_y);
    RSPROT_U2_ALT1(x, m->zoom);
    RSPROT_U2(x, m->angle_x);
    RSPROT_COM_ALT2(x, m->combined_id);
}

/* v6 -- revs 226. */
void
packet_if_setangle_v6_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_U2(x, m->zoom);
    RSPROT_U2_ALT1(x, m->angle_x);
    RSPROT_U2_ALT1(x, m->angle_y);
    RSPROT_COM_ALT2(x, m->combined_id);
}

/* v7 -- revs 227. */
void
packet_if_setangle_v7_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_U2_ALT2(x, m->angle_y);
    RSPROT_U2_ALT3(x, m->angle_x);
    RSPROT_U2_ALT3(x, m->zoom);
    RSPROT_COM(x, m->combined_id);
}

/* v8 -- revs 228. */
void
packet_if_setangle_v8_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_COM_ALT3(x, m->combined_id);
    RSPROT_U2_ALT3(x, m->angle_y);
    RSPROT_U2_ALT2(x, m->zoom);
    RSPROT_U2_ALT3(x, m->angle_x);
}

/* v9 -- revs 229. */
void
packet_if_setangle_v9_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_U2_ALT1(x, m->angle_y);
    RSPROT_U2_ALT2(x, m->zoom);
    RSPROT_COM_ALT2(x, m->combined_id);
    RSPROT_U2(x, m->angle_x);
}

/* v10 -- revs 230. */
void
packet_if_setangle_v10_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_U2_ALT3(x, m->angle_x);
    RSPROT_U2_ALT2(x, m->zoom);
    RSPROT_U2_ALT1(x, m->angle_y);
    RSPROT_COM(x, m->combined_id);
}

/* v11 -- revs 231. */
void
packet_if_setangle_v11_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_U2_ALT3(x, m->zoom);
    RSPROT_U2_ALT3(x, m->angle_y);
    RSPROT_U2_ALT2(x, m->angle_x);
    RSPROT_COM_ALT2(x, m->combined_id);
}

/* v12 -- revs 232. */
void
packet_if_setangle_v12_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_COM(x, m->combined_id);
    RSPROT_U2_ALT3(x, m->angle_y);
    RSPROT_U2(x, m->zoom);
    RSPROT_U2(x, m->angle_x);
}

/* v13 -- revs 233. */
void
packet_if_setangle_v13_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_U2_ALT1(x, m->angle_x);
    RSPROT_U2_ALT3(x, m->angle_y);
    RSPROT_U2_ALT2(x, m->zoom);
    RSPROT_COM(x, m->combined_id);
}

/* v14 -- revs 234. */
void
packet_if_setangle_v14_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_U2_ALT1(x, m->angle_y);
    RSPROT_COM(x, m->combined_id);
    RSPROT_U2_ALT1(x, m->angle_x);
    RSPROT_U2_ALT3(x, m->zoom);
}

/* v15 -- revs 235. */
void
packet_if_setangle_v15_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_U2_ALT1(x, m->zoom);
    RSPROT_U2_ALT2(x, m->angle_y);
    RSPROT_U2_ALT1(x, m->angle_x);
    RSPROT_COM_ALT3(x, m->combined_id);
}

/* v16 -- revs 236. */
void
packet_if_setangle_v16_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_U2_ALT2(x, m->angle_y);
    RSPROT_U2(x, m->angle_x);
    RSPROT_U2_ALT1(x, m->zoom);
    RSPROT_COM_ALT3(x, m->combined_id);
}

/* v17 -- revs 237. */
void
packet_if_setangle_v17_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_U2_ALT2(x, m->angle_y);
    RSPROT_U2_ALT2(x, m->zoom);
    RSPROT_COM(x, m->combined_id);
    RSPROT_U2_ALT2(x, m->angle_x);
}

/* v18 -- revs 238. */
void
packet_if_setangle_v18_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_COM_ALT2(x, m->combined_id);
    RSPROT_U2(x, m->zoom);
    RSPROT_U2_ALT3(x, m->angle_y);
    RSPROT_U2(x, m->angle_x);
}

/* v19 -- revs 239. */
void
packet_if_setangle_v19_out(RsprotExec *x, MsgIfSetAngle *m)
{
    RSPROT_COM_ALT3(x, m->combined_id);
    RSPROT_U2(x, m->zoom);
    RSPROT_U2(x, m->angle_x);
    RSPROT_U2_ALT3(x, m->angle_y);
}

/*
 * 19 row(s) for 19 layout(s), complete over revisions 221-239.
 * A complete table makes rsprot_version_pick's NULL mean exactly one thing: a
 * revision outside that span. An incomplete one would conflate "not
 * transcribed" with "no such packet", and those are different facts.
 */
const RsprotVersionRange rsprot_if_setangle_out[] = {
    { 221, 221, (RsprotCodecFn)packet_if_setangle_v1_out },
    { 222, 222, (RsprotCodecFn)packet_if_setangle_v2_out },
    { 223, 223, (RsprotCodecFn)packet_if_setangle_v3_out },
    { 224, 224, (RsprotCodecFn)packet_if_setangle_v4_out },
    { 225, 225, (RsprotCodecFn)packet_if_setangle_v5_out },
    { 226, 226, (RsprotCodecFn)packet_if_setangle_v6_out },
    { 227, 227, (RsprotCodecFn)packet_if_setangle_v7_out },
    { 228, 228, (RsprotCodecFn)packet_if_setangle_v8_out },
    { 229, 229, (RsprotCodecFn)packet_if_setangle_v9_out },
    { 230, 230, (RsprotCodecFn)packet_if_setangle_v10_out },
    { 231, 231, (RsprotCodecFn)packet_if_setangle_v11_out },
    { 232, 232, (RsprotCodecFn)packet_if_setangle_v12_out },
    { 233, 233, (RsprotCodecFn)packet_if_setangle_v13_out },
    { 234, 234, (RsprotCodecFn)packet_if_setangle_v14_out },
    { 235, 235, (RsprotCodecFn)packet_if_setangle_v15_out },
    { 236, 236, (RsprotCodecFn)packet_if_setangle_v16_out },
    { 237, 237, (RsprotCodecFn)packet_if_setangle_v17_out },
    { 238, 238, (RsprotCodecFn)packet_if_setangle_v18_out },
    { 239, 239, (RsprotCodecFn)packet_if_setangle_v19_out },
};

const int rsprot_if_setangle_out_count =
    (int)(sizeof(rsprot_if_setangle_out) / sizeof(rsprot_if_setangle_out[0]));
