#ifndef RSPROT_PACKET_IF_SETSCROLLPOS_H
#define RSPROT_PACKET_IF_SETSCROLLPOS_H

/*
 * IF_SETSCROLLPOS -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : IfSetScrollPosEncoder
 * Layouts      : 15 distinct, over 18 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^IfSetScrollPosEncoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgIfSetScrollPos {
	int32_t scroll_pos;
	int32_t combined_id;
} MsgIfSetScrollPos;

/* v1 -- revs 221. */
void packet_if_setscrollpos_v1_out(RsprotExec *x, MsgIfSetScrollPos *m);
/* v2 -- revs 222. */
void packet_if_setscrollpos_v2_out(RsprotExec *x, MsgIfSetScrollPos *m);
/* v3 -- revs 223, 234. */
void packet_if_setscrollpos_v3_out(RsprotExec *x, MsgIfSetScrollPos *m);
/* v4 -- revs 224, 233. */
void packet_if_setscrollpos_v4_out(RsprotExec *x, MsgIfSetScrollPos *m);
/* v5 -- revs 225. */
void packet_if_setscrollpos_v5_out(RsprotExec *x, MsgIfSetScrollPos *m);
/* v6 -- revs 226. */
void packet_if_setscrollpos_v6_out(RsprotExec *x, MsgIfSetScrollPos *m);
/* v7 -- revs 227. */
void packet_if_setscrollpos_v7_out(RsprotExec *x, MsgIfSetScrollPos *m);
/* v8 -- revs 228. */
void packet_if_setscrollpos_v8_out(RsprotExec *x, MsgIfSetScrollPos *m);
/* v9 -- revs 229. */
void packet_if_setscrollpos_v9_out(RsprotExec *x, MsgIfSetScrollPos *m);
/* v10 -- revs 230, 239. */
void packet_if_setscrollpos_v10_out(RsprotExec *x, MsgIfSetScrollPos *m);
/* v11 -- revs 231. */
void packet_if_setscrollpos_v11_out(RsprotExec *x, MsgIfSetScrollPos *m);
/* v12 -- revs 232. */
void packet_if_setscrollpos_v12_out(RsprotExec *x, MsgIfSetScrollPos *m);
/* v13 -- revs 235. */
void packet_if_setscrollpos_v13_out(RsprotExec *x, MsgIfSetScrollPos *m);
/* v14 -- revs 236-237. */
void packet_if_setscrollpos_v14_out(RsprotExec *x, MsgIfSetScrollPos *m);
/* v15 -- revs 238. */
void packet_if_setscrollpos_v15_out(RsprotExec *x, MsgIfSetScrollPos *m);

/* Per-revision aliases: `packet_if_setscrollpos_rev239_out` is greppable, which is the
 * point -- "what does 239 do for IF_SETSCROLLPOS" without reading a table. */
#define packet_if_setscrollpos_rev221_out packet_if_setscrollpos_v1_out
#define packet_if_setscrollpos_rev222_out packet_if_setscrollpos_v2_out
#define packet_if_setscrollpos_rev223_out packet_if_setscrollpos_v3_out
#define packet_if_setscrollpos_rev224_out packet_if_setscrollpos_v4_out
#define packet_if_setscrollpos_rev225_out packet_if_setscrollpos_v5_out
#define packet_if_setscrollpos_rev226_out packet_if_setscrollpos_v6_out
#define packet_if_setscrollpos_rev227_out packet_if_setscrollpos_v7_out
#define packet_if_setscrollpos_rev228_out packet_if_setscrollpos_v8_out
#define packet_if_setscrollpos_rev229_out packet_if_setscrollpos_v9_out
#define packet_if_setscrollpos_rev230_out packet_if_setscrollpos_v10_out
#define packet_if_setscrollpos_rev231_out packet_if_setscrollpos_v11_out
#define packet_if_setscrollpos_rev232_out packet_if_setscrollpos_v12_out
#define packet_if_setscrollpos_rev233_out packet_if_setscrollpos_v4_out
#define packet_if_setscrollpos_rev234_out packet_if_setscrollpos_v3_out
#define packet_if_setscrollpos_rev235_out packet_if_setscrollpos_v13_out
#define packet_if_setscrollpos_rev236_out packet_if_setscrollpos_v14_out
#define packet_if_setscrollpos_rev237_out packet_if_setscrollpos_v14_out
#define packet_if_setscrollpos_rev238_out packet_if_setscrollpos_v15_out
#define packet_if_setscrollpos_rev239_out packet_if_setscrollpos_v10_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_if_setscrollpos_out[];
extern const int rsprot_if_setscrollpos_out_count;

#endif
