#ifndef RSPROT_PACKET_IF_SETHIDE_H
#define RSPROT_PACKET_IF_SETHIDE_H

/*
 * IF_SETHIDE -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : IfSetHideEncoder
 * Layouts      : 4 distinct, over 4 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^IfSetHideEncoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgIfSetHide {
	int32_t combined_id;
	int32_t hidden;
} MsgIfSetHide;

/* v1 -- revs 221. */
void packet_if_sethide_v1_out(RsprotExec *x, MsgIfSetHide *m);
/* v3 -- revs 223. */
void packet_if_sethide_v3_out(RsprotExec *x, MsgIfSetHide *m);
/* v6 -- revs 226. */
void packet_if_sethide_v6_out(RsprotExec *x, MsgIfSetHide *m);
/* v16 -- revs 238. */
void packet_if_sethide_v16_out(RsprotExec *x, MsgIfSetHide *m);

/* Per-revision aliases: `packet_if_sethide_rev239_out` is greppable, which is the
 * point -- "what does 239 do for IF_SETHIDE" without reading a table. */
#define packet_if_sethide_rev221_out packet_if_sethide_v1_out
#define packet_if_sethide_rev223_out packet_if_sethide_v3_out
#define packet_if_sethide_rev226_out packet_if_sethide_v6_out
#define packet_if_sethide_rev238_out packet_if_sethide_v16_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_if_sethide_out[];
extern const int rsprot_if_sethide_out_count;

#endif
