/* LOC_ADD_CHANGE_V2. GENERATED by tools/rsprot_gen_codec.py -- do not edit. */
#include "loc_add_change_v2.h"

/*
 * Transcribed from RSProt:
 *   protocol/osrs-<N>/osrs-<N>-desktop/src/main/kotlin/net/rsprot/protocol/
 *       game/outgoing/codec/zone/payload/LocAddChangeV2Encoder.kt
 *
 * One function per layout, running in whichever direction the executor is in --
 * so a server's writer and a client's reader are the same transcription and
 * cannot drift apart.
 */

/* v1 -- revs 228. */
void
packet_loc_add_change_v2_v1_out(RsprotExec *x, MsgLocAddChangeV2 *m)
{
    RSPROT_U1(x, m->coord_in_zone_packed);
    RSPROT_U1_ALT2(x, m->loc_properties_packed);
    RSPROT_U1_ALT2(x, m->ops_count);
    if ((!(m->ops_count == 0))) {
        for (int32_t rs_i_ops = 0; rs_i_ops < m->ops_count; rs_i_ops++) {
            Rsprot_MsgLocAddChangeV2_opsElem *elem = &m->ops[rs_i_ops];
            RSPROT_XFORM(x, U1_ALT1, elem->key, -1);
            RSPROT_JSTR(x, elem->value);
        }
    }
    RSPROT_U1_ALT2(x, m->op_flags);
    RSPROT_U2(x, m->id);
}

/* v2 -- revs 229. */
void
packet_loc_add_change_v2_v2_out(RsprotExec *x, MsgLocAddChangeV2 *m)
{
    RSPROT_U2(x, m->id);
    RSPROT_U1(x, m->coord_in_zone_packed);
    RSPROT_U1(x, m->op_flags);
    RSPROT_U1_ALT3(x, m->loc_properties_packed);
    RSPROT_U1_ALT2(x, m->ops_count);
    if ((!(m->ops_count == 0))) {
        for (int32_t rs_i_ops = 0; rs_i_ops < m->ops_count; rs_i_ops++) {
            Rsprot_MsgLocAddChangeV2_opsElem *elem = &m->ops[rs_i_ops];
            RSPROT_XFORM(x, U1_ALT3, elem->key, -1);
            RSPROT_JSTR(x, elem->value);
        }
    }
}

/* v3 -- revs 230. */
void
packet_loc_add_change_v2_v3_out(RsprotExec *x, MsgLocAddChangeV2 *m)
{
    RSPROT_U1_ALT2(x, m->op_flags);
    RSPROT_U1_ALT2(x, m->ops_count);
    if ((!(m->ops_count == 0))) {
        for (int32_t rs_i_ops = 0; rs_i_ops < m->ops_count; rs_i_ops++) {
            Rsprot_MsgLocAddChangeV2_opsElem *elem = &m->ops[rs_i_ops];
            RSPROT_XFORM(x, U1_ALT2, elem->key, -1);
            RSPROT_JSTR(x, elem->value);
        }
    }
    RSPROT_U2_ALT2(x, m->id);
    RSPROT_U1_ALT2(x, m->loc_properties_packed);
    RSPROT_U1_ALT2(x, m->coord_in_zone_packed);
}

/* v4 -- revs 231. */
void
packet_loc_add_change_v2_v4_out(RsprotExec *x, MsgLocAddChangeV2 *m)
{
    RSPROT_U2_ALT3(x, m->id);
    RSPROT_U1_ALT3(x, m->op_flags);
    RSPROT_U1_ALT1(x, m->loc_properties_packed);
    RSPROT_U1(x, m->coord_in_zone_packed);
    RSPROT_U1_ALT2(x, m->ops_count);
    if ((!(m->ops_count == 0))) {
        for (int32_t rs_i_ops = 0; rs_i_ops < m->ops_count; rs_i_ops++) {
            Rsprot_MsgLocAddChangeV2_opsElem *elem = &m->ops[rs_i_ops];
            RSPROT_XFORM(x, U1_ALT3, elem->key, -1);
            RSPROT_JSTR(x, elem->value);
        }
    }
}

/* v5 -- revs 232. */
void
packet_loc_add_change_v2_v5_out(RsprotExec *x, MsgLocAddChangeV2 *m)
{
    RSPROT_U1_ALT3(x, m->op_flags);
    RSPROT_U1_ALT1(x, m->ops_count);
    if ((!(m->ops_count == 0))) {
        for (int32_t rs_i_ops = 0; rs_i_ops < m->ops_count; rs_i_ops++) {
            Rsprot_MsgLocAddChangeV2_opsElem *elem = &m->ops[rs_i_ops];
            RSPROT_XFORM(x, U1_ALT3, elem->key, -1);
            RSPROT_JSTR(x, elem->value);
        }
    }
    RSPROT_U1_ALT3(x, m->coord_in_zone_packed);
    RSPROT_U2_ALT3(x, m->id);
    RSPROT_U1_ALT3(x, m->loc_properties_packed);
}

/* v6 -- revs 233. */
void
packet_loc_add_change_v2_v6_out(RsprotExec *x, MsgLocAddChangeV2 *m)
{
    RSPROT_U1_ALT2(x, m->ops_count);
    if ((!(m->ops_count == 0))) {
        for (int32_t rs_i_ops = 0; rs_i_ops < m->ops_count; rs_i_ops++) {
            Rsprot_MsgLocAddChangeV2_opsElem *elem = &m->ops[rs_i_ops];
            RSPROT_XFORM(x, U1_ALT3, elem->key, -1);
            RSPROT_JSTR(x, elem->value);
        }
    }
    RSPROT_U1_ALT2(x, m->coord_in_zone_packed);
    RSPROT_U1_ALT2(x, m->loc_properties_packed);
    RSPROT_U2_ALT1(x, m->id);
    RSPROT_U1(x, m->op_flags);
}

/* v7 -- revs 234. */
void
packet_loc_add_change_v2_v7_out(RsprotExec *x, MsgLocAddChangeV2 *m)
{
    RSPROT_U1_ALT2(x, m->op_flags);
    RSPROT_U2(x, m->id);
    RSPROT_U1_ALT2(x, m->ops_count);
    if ((!(m->ops_count == 0))) {
        for (int32_t rs_i_ops = 0; rs_i_ops < m->ops_count; rs_i_ops++) {
            Rsprot_MsgLocAddChangeV2_opsElem *elem = &m->ops[rs_i_ops];
            RSPROT_XFORM(x, U1, elem->key, -1);
            RSPROT_JSTR(x, elem->value);
        }
    }
    RSPROT_U1_ALT3(x, m->loc_properties_packed);
    RSPROT_U1_ALT1(x, m->coord_in_zone_packed);
}

/* v8 -- revs 235. */
void
packet_loc_add_change_v2_v8_out(RsprotExec *x, MsgLocAddChangeV2 *m)
{
    RSPROT_U1_ALT2(x, m->ops_count);
    if ((!(m->ops_count == 0))) {
        for (int32_t rs_i_ops = 0; rs_i_ops < m->ops_count; rs_i_ops++) {
            Rsprot_MsgLocAddChangeV2_opsElem *elem = &m->ops[rs_i_ops];
            RSPROT_XFORM(x, U1_ALT3, elem->key, -1);
            RSPROT_JSTR(x, elem->value);
        }
    }
    RSPROT_U1_ALT2(x, m->loc_properties_packed);
    RSPROT_U1_ALT1(x, m->op_flags);
    RSPROT_U2_ALT2(x, m->id);
    RSPROT_U1_ALT1(x, m->coord_in_zone_packed);
}

/* v9 -- revs 236. */
void
packet_loc_add_change_v2_v9_out(RsprotExec *x, MsgLocAddChangeV2 *m)
{
    RSPROT_U1_ALT1(x, m->op_flags);
    RSPROT_U1_ALT1(x, m->loc_properties_packed);
    RSPROT_U1_ALT3(x, m->ops_count);
    if ((!(m->ops_count == 0))) {
        for (int32_t rs_i_ops = 0; rs_i_ops < m->ops_count; rs_i_ops++) {
            Rsprot_MsgLocAddChangeV2_opsElem *elem = &m->ops[rs_i_ops];
            RSPROT_XFORM(x, U1, elem->key, -1);
            RSPROT_JSTR(x, elem->value);
        }
    }
    RSPROT_U1(x, m->coord_in_zone_packed);
    RSPROT_U2_ALT1(x, m->id);
}

/* v10 -- revs 237. */
void
packet_loc_add_change_v2_v10_out(RsprotExec *x, MsgLocAddChangeV2 *m)
{
    RSPROT_U1(x, m->coord_in_zone_packed);
    RSPROT_U1_ALT2(x, m->op_flags);
    RSPROT_U1(x, m->loc_properties_packed);
    RSPROT_U2(x, m->id);
    RSPROT_U1(x, m->ops_count);
    if ((!(m->ops_count == 0))) {
        for (int32_t rs_i_ops = 0; rs_i_ops < m->ops_count; rs_i_ops++) {
            Rsprot_MsgLocAddChangeV2_opsElem *elem = &m->ops[rs_i_ops];
            RSPROT_XFORM(x, U1, elem->key, -1);
            RSPROT_JSTR(x, elem->value);
        }
    }
}

/* v11 -- revs 238. */
void
packet_loc_add_change_v2_v11_out(RsprotExec *x, MsgLocAddChangeV2 *m)
{
    RSPROT_U1(x, m->loc_properties_packed);
    RSPROT_U1_ALT1(x, m->op_flags);
    RSPROT_U2_ALT2(x, m->id);
    RSPROT_U1_ALT1(x, m->ops_count);
    if ((!(m->ops_count == 0))) {
        for (int32_t rs_i_ops = 0; rs_i_ops < m->ops_count; rs_i_ops++) {
            Rsprot_MsgLocAddChangeV2_opsElem *elem = &m->ops[rs_i_ops];
            RSPROT_XFORM(x, U1_ALT1, elem->key, -1);
            RSPROT_JSTR(x, elem->value);
        }
    }
    RSPROT_U1_ALT1(x, m->coord_in_zone_packed);
}

/* v12 -- revs 239. */
void
packet_loc_add_change_v2_v12_out(RsprotExec *x, MsgLocAddChangeV2 *m)
{
    RSPROT_U1_ALT1(x, m->ops_count);
    if ((!(m->ops_count == 0))) {
        for (int32_t rs_i_ops = 0; rs_i_ops < m->ops_count; rs_i_ops++) {
            Rsprot_MsgLocAddChangeV2_opsElem *elem = &m->ops[rs_i_ops];
            RSPROT_XFORM(x, U1, elem->key, -1);
            RSPROT_JSTR(x, elem->value);
        }
    }
    RSPROT_U1_ALT3(x, m->op_flags);
    RSPROT_U1_ALT1(x, m->loc_properties_packed);
    RSPROT_U1_ALT2(x, m->coord_in_zone_packed);
    RSPROT_U2_ALT3(x, m->id);
}

/*
 * 12 row(s) for 12 layout(s), complete over revisions 221-239.
 * A complete table makes rsprot_version_pick's NULL mean exactly one thing: a
 * revision outside that span. An incomplete one would conflate "not
 * transcribed" with "no such packet", and those are different facts.
 */
const RsprotVersionRange rsprot_loc_add_change_v2_out[] = {
    { 228, 228, (RsprotCodecFn)packet_loc_add_change_v2_v1_out },
    { 229, 229, (RsprotCodecFn)packet_loc_add_change_v2_v2_out },
    { 230, 230, (RsprotCodecFn)packet_loc_add_change_v2_v3_out },
    { 231, 231, (RsprotCodecFn)packet_loc_add_change_v2_v4_out },
    { 232, 232, (RsprotCodecFn)packet_loc_add_change_v2_v5_out },
    { 233, 233, (RsprotCodecFn)packet_loc_add_change_v2_v6_out },
    { 234, 234, (RsprotCodecFn)packet_loc_add_change_v2_v7_out },
    { 235, 235, (RsprotCodecFn)packet_loc_add_change_v2_v8_out },
    { 236, 236, (RsprotCodecFn)packet_loc_add_change_v2_v9_out },
    { 237, 237, (RsprotCodecFn)packet_loc_add_change_v2_v10_out },
    { 238, 238, (RsprotCodecFn)packet_loc_add_change_v2_v11_out },
    { 239, 239, (RsprotCodecFn)packet_loc_add_change_v2_v12_out },
};

const int rsprot_loc_add_change_v2_out_count =
    (int)(sizeof(rsprot_loc_add_change_v2_out) / sizeof(rsprot_loc_add_change_v2_out[0]));
