/* MAP_PROJANIM. GENERATED by tools/rsprot_gen_codec.py -- do not edit. */
#include "map_projanim.h"

/*
 * Transcribed from RSProt:
 *   protocol/osrs-<N>/osrs-<N>-desktop/src/main/kotlin/net/rsprot/protocol/
 *       game/outgoing/codec/zone/payload/MapProjAnimEncoder.kt
 *
 * One function per layout, running in whichever direction the executor is in --
 * so a server's writer and a client's reader are the same transcription and
 * cannot drift apart.
 */

/* v1 -- revs 221. */
void
packet_map_projanim_v1_out(RsprotExec *x, MsgMapProjAnim *m)
{
    RSPROT_U1_ALT2(x, m->end_height);
    RSPROT_U1_ALT2(x, m->delta_z);
    RSPROT_U2_ALT1(x, m->progress);
    RSPROT_U2_ALT1(x, m->end_time);
    RSPROT_U1_ALT1(x, m->start_height);
    RSPROT_U3_ALT1(x, m->target_index);
    RSPROT_U3_ALT2(x, m->source_index);
    RSPROT_U1_ALT3(x, m->coord_in_zone_packed);
    RSPROT_U1_ALT1(x, m->delta_x);
    RSPROT_U1(x, m->angle);
    RSPROT_U2_ALT2(x, m->id);
    RSPROT_U2_ALT1(x, m->start_time);
}

/* v2 -- revs 222. */
void
packet_map_projanim_v2_out(RsprotExec *x, MsgMapProjAnim *m)
{
    RSPROT_U2_ALT1(x, m->progress);
    RSPROT_U2(x, m->id);
    RSPROT_U3_ALT2(x, m->target_index);
    RSPROT_U1_ALT3(x, m->angle);
    RSPROT_U1_ALT3(x, m->start_height);
    RSPROT_U1_ALT2(x, m->delta_x);
    RSPROT_U3_ALT2(x, m->source_index);
    RSPROT_U1_ALT2(x, m->coord_in_zone_packed);
    RSPROT_U1_ALT2(x, m->end_height);
    RSPROT_U2(x, m->end_time);
    RSPROT_U2(x, m->start_time);
    RSPROT_U1(x, m->delta_z);
}

/* v3 -- revs 223. */
void
packet_map_projanim_v3_out(RsprotExec *x, MsgMapProjAnim *m)
{
    RSPROT_U1(x, m->delta_x);
    RSPROT_U2_ALT1(x, m->end_time);
    RSPROT_U1_ALT2(x, m->delta_z);
    RSPROT_U3(x, m->target_index);
    RSPROT_U1(x, m->angle);
    RSPROT_U1_ALT3(x, m->coord_in_zone_packed);
    RSPROT_U1(x, m->start_height);
    RSPROT_U2_ALT3(x, m->id);
    RSPROT_U2_ALT2(x, m->start_time);
    RSPROT_U2(x, m->progress);
    RSPROT_U1_ALT2(x, m->end_height);
    RSPROT_U3_ALT1(x, m->source_index);
}

/* v4 -- revs 224. */
void
packet_map_projanim_v4_out(RsprotExec *x, MsgMapProjAnim *m)
{
    RSPROT_U1(x, m->angle);
    RSPROT_U2_ALT1(x, m->end_time);
    RSPROT_U3_ALT3(x, m->target_index);
    RSPROT_U1_ALT2(x, m->coord_in_zone_packed);
    RSPROT_U1_ALT1(x, m->end_height);
    RSPROT_U1_ALT3(x, m->start_height);
    RSPROT_U2(x, m->progress);
    RSPROT_U2_ALT3(x, m->start_time);
    RSPROT_U3_ALT2(x, m->source_index);
    RSPROT_U1(x, m->delta_x);
    RSPROT_U1_ALT1(x, m->delta_z);
    RSPROT_U2_ALT3(x, m->id);
}

/* v5 -- revs 225. */
void
packet_map_projanim_v5_out(RsprotExec *x, MsgMapProjAnim *m)
{
    RSPROT_U2(x, m->id);
    RSPROT_U1_ALT2(x, m->end_height);
    RSPROT_U3_ALT1(x, m->target_index);
    RSPROT_U2_ALT2(x, m->progress);
    RSPROT_U2(x, m->end_time);
    RSPROT_U1(x, m->coord_in_zone_packed);
    RSPROT_U3_ALT2(x, m->source_index);
    RSPROT_U1_ALT1(x, m->angle);
    RSPROT_U1(x, m->start_height);
    RSPROT_U1_ALT3(x, m->delta_x);
    RSPROT_U2_ALT2(x, m->start_time);
    RSPROT_U1(x, m->delta_z);
}

/* v6 -- revs 226. */
void
packet_map_projanim_v6_out(RsprotExec *x, MsgMapProjAnim *m)
{
    RSPROT_U2_ALT2(x, m->end_time);
    RSPROT_U3(x, m->source_index);
    RSPROT_U2_ALT2(x, m->start_time);
    RSPROT_U2_ALT3(x, m->progress);
    RSPROT_U3_ALT1(x, m->target_index);
    RSPROT_U1(x, m->start_height);
    RSPROT_U1_ALT3(x, m->coord_in_zone_packed);
    RSPROT_U1_ALT1(x, m->end_height);
    RSPROT_U2_ALT2(x, m->id);
    RSPROT_U1_ALT2(x, m->delta_z);
    RSPROT_U1_ALT2(x, m->angle);
    RSPROT_U1_ALT1(x, m->delta_x);
}

/* v7 -- revs 227. */
void
packet_map_projanim_v7_out(RsprotExec *x, MsgMapProjAnim *m)
{
    RSPROT_U3_ALT3(x, m->source_index);
    RSPROT_U2_ALT2(x, m->end_time);
    RSPROT_U2(x, m->id);
    RSPROT_U2_ALT2(x, m->start_time);
    RSPROT_U1_ALT2(x, m->coord_in_zone_packed);
    RSPROT_U2_ALT2(x, m->progress);
    RSPROT_U3_ALT2(x, m->target_index);
    RSPROT_U1(x, m->start_height);
    RSPROT_U1_ALT3(x, m->delta_x);
    RSPROT_U1_ALT3(x, m->end_height);
    RSPROT_U1_ALT3(x, m->delta_z);
    RSPROT_U1_ALT3(x, m->angle);
}

/* v8 -- revs 228. */
void
packet_map_projanim_v8_out(RsprotExec *x, MsgMapProjAnim *m)
{
    RSPROT_U1_ALT2(x, m->end_height);
    RSPROT_U1(x, m->angle);
    RSPROT_U2(x, m->progress);
    RSPROT_U3_ALT2(x, m->target_index);
    RSPROT_U1(x, m->start_height);
    RSPROT_U1(x, m->coord_in_zone_packed);
    RSPROT_U1_ALT2(x, m->delta_x);
    RSPROT_U2_ALT2(x, m->id);
    RSPROT_U2_ALT1(x, m->end_time);
    RSPROT_U2_ALT1(x, m->start_time);
    RSPROT_U1(x, m->delta_z);
    RSPROT_U3_ALT2(x, m->source_index);
}

/* v9 -- revs 229. */
void
packet_map_projanim_v9_out(RsprotExec *x, MsgMapProjAnim *m)
{
    RSPROT_U3_ALT3(x, m->target_index);
    RSPROT_U2(x, m->end_time);
    RSPROT_U1_ALT1(x, m->delta_x);
    RSPROT_U1_ALT3(x, m->end_height);
    RSPROT_U1(x, m->angle);
    RSPROT_U2_ALT1(x, m->start_time);
    RSPROT_U3_ALT2(x, m->source_index);
    RSPROT_U2_ALT1(x, m->progress);
    RSPROT_U1_ALT1(x, m->delta_z);
    RSPROT_U2(x, m->id);
    RSPROT_U1_ALT3(x, m->start_height);
    RSPROT_U1_ALT1(x, m->coord_in_zone_packed);
}

/* v10 -- revs 230. */
void
packet_map_projanim_v10_out(RsprotExec *x, MsgMapProjAnim *m)
{
    RSPROT_U3_ALT2(x, m->target_index);
    RSPROT_U2(x, m->end_time);
    RSPROT_U3_ALT1(x, m->source_index);
    RSPROT_U1_ALT2(x, m->start_height);
    RSPROT_U2_ALT1(x, m->progress);
    RSPROT_U2_ALT3(x, m->id);
    RSPROT_U1_ALT3(x, m->delta_x);
    RSPROT_U1_ALT2(x, m->delta_z);
    RSPROT_U1_ALT1(x, m->angle);
    RSPROT_U1_ALT2(x, m->end_height);
    RSPROT_U1(x, m->coord_in_zone_packed);
    RSPROT_U2_ALT1(x, m->start_time);
}

/*
 * 10 row(s) for 10 layout(s), complete over revisions 221-239.
 * A complete table makes rsprot_version_pick's NULL mean exactly one thing: a
 * revision outside that span. An incomplete one would conflate "not
 * transcribed" with "no such packet", and those are different facts.
 */
const RsprotVersionRange rsprot_map_projanim_out[] = {
    { 221, 221, (RsprotCodecFn)packet_map_projanim_v1_out },
    { 222, 222, (RsprotCodecFn)packet_map_projanim_v2_out },
    { 223, 223, (RsprotCodecFn)packet_map_projanim_v3_out },
    { 224, 224, (RsprotCodecFn)packet_map_projanim_v4_out },
    { 225, 225, (RsprotCodecFn)packet_map_projanim_v5_out },
    { 226, 226, (RsprotCodecFn)packet_map_projanim_v6_out },
    { 227, 227, (RsprotCodecFn)packet_map_projanim_v7_out },
    { 228, 228, (RsprotCodecFn)packet_map_projanim_v8_out },
    { 229, 229, (RsprotCodecFn)packet_map_projanim_v9_out },
    { 230, 230, (RsprotCodecFn)packet_map_projanim_v10_out },
};

const int rsprot_map_projanim_out_count =
    (int)(sizeof(rsprot_map_projanim_out) / sizeof(rsprot_map_projanim_out[0]));
