#ifndef RSPROT_PACKET_MESSAGE_GAME_H
#define RSPROT_PACKET_MESSAGE_GAME_H

/*
 * MESSAGE_GAME -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : MessageGameEncoder
 * Layouts      : 1 distinct, over 1 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^MessageGameEncoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgMessageGame {
	int32_t type;
	int32_t name_present;
	const char *name;
	const char *message;
} MsgMessageGame;

/* v1 -- revs 221-239. */
void packet_message_game_v1_out(RsprotExec *x, MsgMessageGame *m);

/* Per-revision aliases: `packet_message_game_rev239_out` is greppable, which is the
 * point -- "what does 239 do for MESSAGE_GAME" without reading a table. */
#define packet_message_game_rev221_out packet_message_game_v1_out
#define packet_message_game_rev222_out packet_message_game_v1_out
#define packet_message_game_rev223_out packet_message_game_v1_out
#define packet_message_game_rev224_out packet_message_game_v1_out
#define packet_message_game_rev225_out packet_message_game_v1_out
#define packet_message_game_rev226_out packet_message_game_v1_out
#define packet_message_game_rev227_out packet_message_game_v1_out
#define packet_message_game_rev228_out packet_message_game_v1_out
#define packet_message_game_rev229_out packet_message_game_v1_out
#define packet_message_game_rev230_out packet_message_game_v1_out
#define packet_message_game_rev231_out packet_message_game_v1_out
#define packet_message_game_rev232_out packet_message_game_v1_out
#define packet_message_game_rev233_out packet_message_game_v1_out
#define packet_message_game_rev234_out packet_message_game_v1_out
#define packet_message_game_rev235_out packet_message_game_v1_out
#define packet_message_game_rev236_out packet_message_game_v1_out
#define packet_message_game_rev237_out packet_message_game_v1_out
#define packet_message_game_rev238_out packet_message_game_v1_out
#define packet_message_game_rev239_out packet_message_game_v1_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_message_game_out[];
extern const int rsprot_message_game_out_count;

#endif
