/* MIDI_SONG_V2. GENERATED by tools/rsprot_gen_codec.py -- do not edit. */
#include "midi_song_v2.h"

/*
 * Transcribed from RSProt:
 *   protocol/osrs-<N>/osrs-<N>-desktop/src/main/kotlin/net/rsprot/protocol/
 *       game/outgoing/codec/sound/MidiSongV2Encoder.kt
 *
 * One function per layout, running in whichever direction the executor is in --
 * so a server's writer and a client's reader are the same transcription and
 * cannot drift apart.
 */

/* v1 -- revs 226. */
void
packet_midi_song_v2_v1_out(RsprotExec *x, MsgMidiSongV2 *m)
{
    RSPROT_U2_ALT1(x, m->fade_out_delay);
    RSPROT_U2(x, m->fade_in_delay);
    RSPROT_U2_ALT2(x, m->id);
    RSPROT_U2_ALT3(x, m->fade_in_speed);
    RSPROT_U2(x, m->fade_out_speed);
}

/* v2 -- revs 227. */
void
packet_midi_song_v2_v2_out(RsprotExec *x, MsgMidiSongV2 *m)
{
    RSPROT_U2_ALT1(x, m->fade_out_speed);
    RSPROT_U2_ALT2(x, m->fade_out_delay);
    RSPROT_U2_ALT1(x, m->id);
    RSPROT_U2_ALT1(x, m->fade_in_speed);
    RSPROT_U2_ALT1(x, m->fade_in_delay);
}

/* v3 -- revs 228. */
void
packet_midi_song_v2_v3_out(RsprotExec *x, MsgMidiSongV2 *m)
{
    RSPROT_U2(x, m->fade_out_speed);
    RSPROT_U2(x, m->fade_out_delay);
    RSPROT_U2(x, m->fade_in_speed);
    RSPROT_U2_ALT3(x, m->fade_in_delay);
    RSPROT_U2_ALT1(x, m->id);
}

/* v4 -- revs 229. */
void
packet_midi_song_v2_v4_out(RsprotExec *x, MsgMidiSongV2 *m)
{
    RSPROT_U2_ALT2(x, m->fade_out_speed);
    RSPROT_U2_ALT1(x, m->fade_out_delay);
    RSPROT_U2_ALT2(x, m->id);
    RSPROT_U2_ALT2(x, m->fade_in_speed);
    RSPROT_U2_ALT3(x, m->fade_in_delay);
}

/* v5 -- revs 230. */
void
packet_midi_song_v2_v5_out(RsprotExec *x, MsgMidiSongV2 *m)
{
    RSPROT_U2_ALT2(x, m->fade_out_delay);
    RSPROT_U2_ALT2(x, m->fade_out_speed);
    RSPROT_U2(x, m->fade_in_delay);
    RSPROT_U2(x, m->id);
    RSPROT_U2_ALT3(x, m->fade_in_speed);
}

/* v6 -- revs 231. */
void
packet_midi_song_v2_v6_out(RsprotExec *x, MsgMidiSongV2 *m)
{
    RSPROT_U2(x, m->fade_out_speed);
    RSPROT_U2_ALT2(x, m->id);
    RSPROT_U2_ALT2(x, m->fade_in_speed);
    RSPROT_U2(x, m->fade_out_delay);
    RSPROT_U2(x, m->fade_in_delay);
}

/* v7 -- revs 232. */
void
packet_midi_song_v2_v7_out(RsprotExec *x, MsgMidiSongV2 *m)
{
    RSPROT_U2_ALT2(x, m->fade_in_delay);
    RSPROT_U2(x, m->id);
    RSPROT_U2(x, m->fade_out_speed);
    RSPROT_U2(x, m->fade_in_speed);
    RSPROT_U2_ALT2(x, m->fade_out_delay);
}

/* v8 -- revs 233. */
void
packet_midi_song_v2_v8_out(RsprotExec *x, MsgMidiSongV2 *m)
{
    RSPROT_U2(x, m->fade_out_speed);
    RSPROT_U2_ALT1(x, m->fade_in_delay);
    RSPROT_U2_ALT3(x, m->fade_in_speed);
    RSPROT_U2_ALT3(x, m->id);
    RSPROT_U2(x, m->fade_out_delay);
}

/* v9 -- revs 234. */
void
packet_midi_song_v2_v9_out(RsprotExec *x, MsgMidiSongV2 *m)
{
    RSPROT_U2_ALT1(x, m->fade_in_delay);
    RSPROT_U2_ALT1(x, m->fade_out_delay);
    RSPROT_U2(x, m->fade_in_speed);
    RSPROT_U2(x, m->fade_out_speed);
    RSPROT_U2_ALT3(x, m->id);
}

/* v10 -- revs 235. */
void
packet_midi_song_v2_v10_out(RsprotExec *x, MsgMidiSongV2 *m)
{
    RSPROT_U2_ALT3(x, m->fade_out_speed);
    RSPROT_U2_ALT1(x, m->fade_out_delay);
    RSPROT_U2(x, m->fade_in_speed);
    RSPROT_U2_ALT2(x, m->id);
    RSPROT_U2_ALT1(x, m->fade_in_delay);
}

/* v11 -- revs 236. */
void
packet_midi_song_v2_v11_out(RsprotExec *x, MsgMidiSongV2 *m)
{
    RSPROT_U2_ALT1(x, m->fade_out_delay);
    RSPROT_U2_ALT3(x, m->fade_out_speed);
    RSPROT_U2_ALT2(x, m->fade_in_delay);
    RSPROT_U2(x, m->fade_in_speed);
    RSPROT_U2_ALT3(x, m->id);
}

/* v12 -- revs 237. */
void
packet_midi_song_v2_v12_out(RsprotExec *x, MsgMidiSongV2 *m)
{
    RSPROT_U2(x, m->fade_in_speed);
    RSPROT_U2_ALT3(x, m->fade_out_delay);
    RSPROT_U2_ALT2(x, m->fade_out_speed);
    RSPROT_U2_ALT1(x, m->fade_in_delay);
    RSPROT_U2(x, m->id);
}

/* v13 -- revs 238. */
void
packet_midi_song_v2_v13_out(RsprotExec *x, MsgMidiSongV2 *m)
{
    RSPROT_U2(x, m->fade_out_delay);
    RSPROT_U2_ALT2(x, m->fade_in_speed);
    RSPROT_U2_ALT2(x, m->id);
    RSPROT_U2_ALT3(x, m->fade_in_delay);
    RSPROT_U2(x, m->fade_out_speed);
}

/* v14 -- revs 239. */
void
packet_midi_song_v2_v14_out(RsprotExec *x, MsgMidiSongV2 *m)
{
    RSPROT_U2_ALT1(x, m->fade_in_delay);
    RSPROT_U2(x, m->fade_out_delay);
    RSPROT_U2_ALT3(x, m->id);
    RSPROT_U2(x, m->fade_in_speed);
    RSPROT_U2_ALT3(x, m->fade_out_speed);
}

/*
 * 14 row(s) for 14 layout(s), complete over revisions 221-239.
 * A complete table makes rsprot_version_pick's NULL mean exactly one thing: a
 * revision outside that span. An incomplete one would conflate "not
 * transcribed" with "no such packet", and those are different facts.
 */
const RsprotVersionRange rsprot_midi_song_v2_out[] = {
    { 226, 226, (RsprotCodecFn)packet_midi_song_v2_v1_out },
    { 227, 227, (RsprotCodecFn)packet_midi_song_v2_v2_out },
    { 228, 228, (RsprotCodecFn)packet_midi_song_v2_v3_out },
    { 229, 229, (RsprotCodecFn)packet_midi_song_v2_v4_out },
    { 230, 230, (RsprotCodecFn)packet_midi_song_v2_v5_out },
    { 231, 231, (RsprotCodecFn)packet_midi_song_v2_v6_out },
    { 232, 232, (RsprotCodecFn)packet_midi_song_v2_v7_out },
    { 233, 233, (RsprotCodecFn)packet_midi_song_v2_v8_out },
    { 234, 234, (RsprotCodecFn)packet_midi_song_v2_v9_out },
    { 235, 235, (RsprotCodecFn)packet_midi_song_v2_v10_out },
    { 236, 236, (RsprotCodecFn)packet_midi_song_v2_v11_out },
    { 237, 237, (RsprotCodecFn)packet_midi_song_v2_v12_out },
    { 238, 238, (RsprotCodecFn)packet_midi_song_v2_v13_out },
    { 239, 239, (RsprotCodecFn)packet_midi_song_v2_v14_out },
};

const int rsprot_midi_song_v2_out_count =
    (int)(sizeof(rsprot_midi_song_v2_out) / sizeof(rsprot_midi_song_v2_out[0]));
