/* MIDI_SONG_WITHSECONDARY. GENERATED by tools/rsprot_gen_codec.py -- do not edit. */
#include "midi_song_withsecondary.h"

/*
 * Transcribed from RSProt:
 *   protocol/osrs-<N>/osrs-<N>-desktop/src/main/kotlin/net/rsprot/protocol/
 *       game/outgoing/codec/sound/MidiSongWithSecondaryEncoder.kt
 *
 * One function per layout, running in whichever direction the executor is in --
 * so a server's writer and a client's reader are the same transcription and
 * cannot drift apart.
 */

/* v1 -- revs 221. */
void
packet_midi_song_withsecondary_v1_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2_ALT2(x, m->primary_id);
    RSPROT_U2_ALT1(x, m->fade_in_speed);
    RSPROT_U2(x, m->secondary_id);
    RSPROT_U2(x, m->fade_in_delay);
    RSPROT_U2_ALT3(x, m->fade_out_speed);
    RSPROT_U2_ALT1(x, m->fade_out_delay);
}

/* v2 -- revs 222. */
void
packet_midi_song_withsecondary_v2_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2_ALT3(x, m->fade_in_delay);
    RSPROT_U2_ALT1(x, m->fade_out_delay);
    RSPROT_U2_ALT1(x, m->fade_in_speed);
    RSPROT_U2_ALT2(x, m->secondary_id);
    RSPROT_U2_ALT1(x, m->primary_id);
    RSPROT_U2(x, m->fade_out_speed);
}

/* v3 -- revs 223. */
void
packet_midi_song_withsecondary_v3_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2(x, m->fade_out_delay);
    RSPROT_U2_ALT2(x, m->secondary_id);
    RSPROT_U2_ALT3(x, m->fade_out_speed);
    RSPROT_U2(x, m->fade_in_speed);
    RSPROT_U2_ALT3(x, m->fade_in_delay);
    RSPROT_U2_ALT2(x, m->primary_id);
}

/* v4 -- revs 224. */
void
packet_midi_song_withsecondary_v4_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2_ALT3(x, m->primary_id);
    RSPROT_U2_ALT2(x, m->fade_in_delay);
    RSPROT_U2_ALT1(x, m->fade_in_speed);
    RSPROT_U2(x, m->fade_out_speed);
    RSPROT_U2(x, m->fade_out_delay);
    RSPROT_U2_ALT1(x, m->secondary_id);
}

/* v5 -- revs 225. */
void
packet_midi_song_withsecondary_v5_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2(x, m->fade_out_speed);
    RSPROT_U2_ALT3(x, m->fade_in_speed);
    RSPROT_U2_ALT1(x, m->fade_out_delay);
    RSPROT_U2_ALT3(x, m->secondary_id);
    RSPROT_U2_ALT2(x, m->fade_in_delay);
    RSPROT_U2(x, m->primary_id);
}

/* v6 -- revs 226. */
void
packet_midi_song_withsecondary_v6_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2_ALT3(x, m->fade_in_delay);
    RSPROT_U2_ALT1(x, m->fade_out_delay);
    RSPROT_U2(x, m->primary_id);
    RSPROT_U2_ALT1(x, m->secondary_id);
    RSPROT_U2_ALT2(x, m->fade_out_speed);
    RSPROT_U2_ALT2(x, m->fade_in_speed);
}

/* v7 -- revs 227. */
void
packet_midi_song_withsecondary_v7_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2_ALT2(x, m->fade_in_delay);
    RSPROT_U2_ALT3(x, m->fade_in_speed);
    RSPROT_U2_ALT1(x, m->fade_out_speed);
    RSPROT_U2_ALT2(x, m->primary_id);
    RSPROT_U2(x, m->secondary_id);
    RSPROT_U2_ALT1(x, m->fade_out_delay);
}

/* v8 -- revs 228. */
void
packet_midi_song_withsecondary_v8_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2_ALT3(x, m->fade_out_speed);
    RSPROT_U2_ALT3(x, m->secondary_id);
    RSPROT_U2_ALT3(x, m->fade_out_delay);
    RSPROT_U2_ALT3(x, m->fade_in_delay);
    RSPROT_U2_ALT3(x, m->fade_in_speed);
    RSPROT_U2_ALT2(x, m->primary_id);
}

/* v9 -- revs 229. */
void
packet_midi_song_withsecondary_v9_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2_ALT3(x, m->fade_out_delay);
    RSPROT_U2_ALT3(x, m->secondary_id);
    RSPROT_U2_ALT1(x, m->fade_out_speed);
    RSPROT_U2_ALT3(x, m->fade_in_speed);
    RSPROT_U2_ALT2(x, m->fade_in_delay);
    RSPROT_U2_ALT1(x, m->primary_id);
}

/* v10 -- revs 230. */
void
packet_midi_song_withsecondary_v10_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2_ALT1(x, m->fade_in_delay);
    RSPROT_U2_ALT2(x, m->primary_id);
    RSPROT_U2(x, m->fade_out_delay);
    RSPROT_U2_ALT3(x, m->fade_in_speed);
    RSPROT_U2(x, m->secondary_id);
    RSPROT_U2_ALT2(x, m->fade_out_speed);
}

/* v11 -- revs 231. */
void
packet_midi_song_withsecondary_v11_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2_ALT2(x, m->primary_id);
    RSPROT_U2(x, m->fade_out_speed);
    RSPROT_U2_ALT1(x, m->fade_in_delay);
    RSPROT_U2(x, m->secondary_id);
    RSPROT_U2_ALT1(x, m->fade_out_delay);
    RSPROT_U2_ALT1(x, m->fade_in_speed);
}

/* v12 -- revs 232. */
void
packet_midi_song_withsecondary_v12_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2_ALT1(x, m->fade_out_speed);
    RSPROT_U2(x, m->fade_out_delay);
    RSPROT_U2(x, m->primary_id);
    RSPROT_U2(x, m->fade_in_delay);
    RSPROT_U2_ALT1(x, m->fade_in_speed);
    RSPROT_U2_ALT1(x, m->secondary_id);
}

/* v13 -- revs 233. */
void
packet_midi_song_withsecondary_v13_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2_ALT2(x, m->fade_out_delay);
    RSPROT_U2_ALT1(x, m->fade_in_delay);
    RSPROT_U2_ALT2(x, m->fade_out_speed);
    RSPROT_U2_ALT1(x, m->primary_id);
    RSPROT_U2(x, m->fade_in_speed);
    RSPROT_U2(x, m->secondary_id);
}

/* v14 -- revs 234. */
void
packet_midi_song_withsecondary_v14_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2_ALT3(x, m->secondary_id);
    RSPROT_U2_ALT1(x, m->fade_in_delay);
    RSPROT_U2(x, m->primary_id);
    RSPROT_U2_ALT3(x, m->fade_out_delay);
    RSPROT_U2_ALT2(x, m->fade_out_speed);
    RSPROT_U2_ALT2(x, m->fade_in_speed);
}

/* v15 -- revs 235. */
void
packet_midi_song_withsecondary_v15_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2_ALT1(x, m->fade_out_delay);
    RSPROT_U2_ALT3(x, m->secondary_id);
    RSPROT_U2_ALT3(x, m->fade_in_speed);
    RSPROT_U2_ALT1(x, m->fade_in_delay);
    RSPROT_U2(x, m->fade_out_speed);
    RSPROT_U2(x, m->primary_id);
}

/* v16 -- revs 236. */
void
packet_midi_song_withsecondary_v16_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2_ALT1(x, m->fade_in_speed);
    RSPROT_U2(x, m->secondary_id);
    RSPROT_U2_ALT1(x, m->fade_in_delay);
    RSPROT_U2_ALT1(x, m->primary_id);
    RSPROT_U2_ALT1(x, m->fade_out_speed);
    RSPROT_U2_ALT1(x, m->fade_out_delay);
}

/* v17 -- revs 237. */
void
packet_midi_song_withsecondary_v17_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2_ALT3(x, m->fade_out_speed);
    RSPROT_U2_ALT2(x, m->fade_in_speed);
    RSPROT_U2_ALT2(x, m->secondary_id);
    RSPROT_U2_ALT1(x, m->fade_in_delay);
    RSPROT_U2_ALT1(x, m->primary_id);
    RSPROT_U2_ALT2(x, m->fade_out_delay);
}

/* v18 -- revs 238. */
void
packet_midi_song_withsecondary_v18_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2_ALT3(x, m->primary_id);
    RSPROT_U2_ALT1(x, m->fade_out_delay);
    RSPROT_U2(x, m->fade_out_speed);
    RSPROT_U2_ALT2(x, m->fade_in_speed);
    RSPROT_U2_ALT3(x, m->fade_in_delay);
    RSPROT_U2(x, m->secondary_id);
}

/* v19 -- revs 239. */
void
packet_midi_song_withsecondary_v19_out(RsprotExec *x, MsgMidiSongWithSecondary *m)
{
    RSPROT_U2(x, m->primary_id);
    RSPROT_U2_ALT3(x, m->fade_in_delay);
    RSPROT_U2_ALT1(x, m->secondary_id);
    RSPROT_U2(x, m->fade_out_speed);
    RSPROT_U2_ALT1(x, m->fade_out_delay);
    RSPROT_U2_ALT3(x, m->fade_in_speed);
}

/*
 * 19 row(s) for 19 layout(s), complete over revisions 221-239.
 * A complete table makes rsprot_version_pick's NULL mean exactly one thing: a
 * revision outside that span. An incomplete one would conflate "not
 * transcribed" with "no such packet", and those are different facts.
 */
const RsprotVersionRange rsprot_midi_song_withsecondary_out[] = {
    { 221, 221, (RsprotCodecFn)packet_midi_song_withsecondary_v1_out },
    { 222, 222, (RsprotCodecFn)packet_midi_song_withsecondary_v2_out },
    { 223, 223, (RsprotCodecFn)packet_midi_song_withsecondary_v3_out },
    { 224, 224, (RsprotCodecFn)packet_midi_song_withsecondary_v4_out },
    { 225, 225, (RsprotCodecFn)packet_midi_song_withsecondary_v5_out },
    { 226, 226, (RsprotCodecFn)packet_midi_song_withsecondary_v6_out },
    { 227, 227, (RsprotCodecFn)packet_midi_song_withsecondary_v7_out },
    { 228, 228, (RsprotCodecFn)packet_midi_song_withsecondary_v8_out },
    { 229, 229, (RsprotCodecFn)packet_midi_song_withsecondary_v9_out },
    { 230, 230, (RsprotCodecFn)packet_midi_song_withsecondary_v10_out },
    { 231, 231, (RsprotCodecFn)packet_midi_song_withsecondary_v11_out },
    { 232, 232, (RsprotCodecFn)packet_midi_song_withsecondary_v12_out },
    { 233, 233, (RsprotCodecFn)packet_midi_song_withsecondary_v13_out },
    { 234, 234, (RsprotCodecFn)packet_midi_song_withsecondary_v14_out },
    { 235, 235, (RsprotCodecFn)packet_midi_song_withsecondary_v15_out },
    { 236, 236, (RsprotCodecFn)packet_midi_song_withsecondary_v16_out },
    { 237, 237, (RsprotCodecFn)packet_midi_song_withsecondary_v17_out },
    { 238, 238, (RsprotCodecFn)packet_midi_song_withsecondary_v18_out },
    { 239, 239, (RsprotCodecFn)packet_midi_song_withsecondary_v19_out },
};

const int rsprot_midi_song_withsecondary_out_count =
    (int)(sizeof(rsprot_midi_song_withsecondary_out) / sizeof(rsprot_midi_song_withsecondary_out[0]));
