#ifndef RSPROT_PACKET_MIDI_SONG_V2_H
#define RSPROT_PACKET_MIDI_SONG_V2_H

/*
 * MIDI_SONG_V2 -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : MidiSongV2Encoder
 * Layouts      : 14 distinct, over 14 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^MidiSongV2Encoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgMidiSongV2 {
	int32_t fade_out_delay;
	int32_t fade_in_delay;
	int32_t id;
	int32_t fade_in_speed;
	int32_t fade_out_speed;
} MsgMidiSongV2;

/* v1 -- revs 226. */
void packet_midi_song_v2_v1_out(RsprotExec *x, MsgMidiSongV2 *m);
/* v2 -- revs 227. */
void packet_midi_song_v2_v2_out(RsprotExec *x, MsgMidiSongV2 *m);
/* v3 -- revs 228. */
void packet_midi_song_v2_v3_out(RsprotExec *x, MsgMidiSongV2 *m);
/* v4 -- revs 229. */
void packet_midi_song_v2_v4_out(RsprotExec *x, MsgMidiSongV2 *m);
/* v5 -- revs 230. */
void packet_midi_song_v2_v5_out(RsprotExec *x, MsgMidiSongV2 *m);
/* v6 -- revs 231. */
void packet_midi_song_v2_v6_out(RsprotExec *x, MsgMidiSongV2 *m);
/* v7 -- revs 232. */
void packet_midi_song_v2_v7_out(RsprotExec *x, MsgMidiSongV2 *m);
/* v8 -- revs 233. */
void packet_midi_song_v2_v8_out(RsprotExec *x, MsgMidiSongV2 *m);
/* v9 -- revs 234. */
void packet_midi_song_v2_v9_out(RsprotExec *x, MsgMidiSongV2 *m);
/* v10 -- revs 235. */
void packet_midi_song_v2_v10_out(RsprotExec *x, MsgMidiSongV2 *m);
/* v11 -- revs 236. */
void packet_midi_song_v2_v11_out(RsprotExec *x, MsgMidiSongV2 *m);
/* v12 -- revs 237. */
void packet_midi_song_v2_v12_out(RsprotExec *x, MsgMidiSongV2 *m);
/* v13 -- revs 238. */
void packet_midi_song_v2_v13_out(RsprotExec *x, MsgMidiSongV2 *m);
/* v14 -- revs 239. */
void packet_midi_song_v2_v14_out(RsprotExec *x, MsgMidiSongV2 *m);

/* Per-revision aliases: `packet_midi_song_v2_rev239_out` is greppable, which is the
 * point -- "what does 239 do for MIDI_SONG_V2" without reading a table. */
#define packet_midi_song_v2_rev226_out packet_midi_song_v2_v1_out
#define packet_midi_song_v2_rev227_out packet_midi_song_v2_v2_out
#define packet_midi_song_v2_rev228_out packet_midi_song_v2_v3_out
#define packet_midi_song_v2_rev229_out packet_midi_song_v2_v4_out
#define packet_midi_song_v2_rev230_out packet_midi_song_v2_v5_out
#define packet_midi_song_v2_rev231_out packet_midi_song_v2_v6_out
#define packet_midi_song_v2_rev232_out packet_midi_song_v2_v7_out
#define packet_midi_song_v2_rev233_out packet_midi_song_v2_v8_out
#define packet_midi_song_v2_rev234_out packet_midi_song_v2_v9_out
#define packet_midi_song_v2_rev235_out packet_midi_song_v2_v10_out
#define packet_midi_song_v2_rev236_out packet_midi_song_v2_v11_out
#define packet_midi_song_v2_rev237_out packet_midi_song_v2_v12_out
#define packet_midi_song_v2_rev238_out packet_midi_song_v2_v13_out
#define packet_midi_song_v2_rev239_out packet_midi_song_v2_v14_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_midi_song_v2_out[];
extern const int rsprot_midi_song_v2_out_count;

#endif
