#ifndef RSPROT_PACKET_MINIMAP_TOGGLE_H
#define RSPROT_PACKET_MINIMAP_TOGGLE_H

/*
 * MINIMAP_TOGGLE -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : MinimapToggleEncoder
 * Layouts      : 1 distinct, over 1 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^MinimapToggleEncoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgMinimapToggle {
	int32_t minimap_state;
} MsgMinimapToggle;

/* v1 -- revs 221-239. */
void packet_minimap_toggle_v1_out(RsprotExec *x, MsgMinimapToggle *m);

/* Per-revision aliases: `packet_minimap_toggle_rev239_out` is greppable, which is the
 * point -- "what does 239 do for MINIMAP_TOGGLE" without reading a table. */
#define packet_minimap_toggle_rev221_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev222_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev223_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev224_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev225_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev226_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev227_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev228_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev229_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev230_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev231_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev232_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev233_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev234_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev235_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev236_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev237_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev238_out packet_minimap_toggle_v1_out
#define packet_minimap_toggle_rev239_out packet_minimap_toggle_v1_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_minimap_toggle_out[];
extern const int rsprot_minimap_toggle_out_count;

#endif
