/* PROJANIM_SPECIFIC_V4. GENERATED by tools/rsprot_gen_codec.py -- do not edit. */
#include "projanim_specific_v4.h"

/*
 * Transcribed from RSProt:
 *   protocol/osrs-<N>/osrs-<N>-desktop/src/main/kotlin/net/rsprot/protocol/
 *       game/outgoing/codec/specific/ProjAnimSpecificV4Encoder.kt
 *
 * One function per layout, running in whichever direction the executor is in --
 * so a server's writer and a client's reader are the same transcription and
 * cannot drift apart.
 */

/* v1 -- revs 231. */
void
packet_projanim_specific_v4_v1_out(RsprotExec *x, MsgProjAnimSpecificV4 *m)
{
    RSPROT_U4_ALT1(x, m->start_packed);
    RSPROT_U3_ALT1(x, m->target_index);
    RSPROT_U2_ALT1(x, m->start_height);
    RSPROT_U4_ALT3(x, m->end_packed);
    RSPROT_U1_ALT3(x, m->angle);
    RSPROT_U3_ALT1(x, m->source_index);
    RSPROT_U2_ALT1(x, m->start_time);
    RSPROT_U2_ALT1(x, m->id);
    RSPROT_U2(x, m->end_height);
    RSPROT_U2_ALT1(x, m->end_time);
    RSPROT_U2_ALT1(x, m->progress);
}

/* v2 -- revs 232. */
void
packet_projanim_specific_v4_v2_out(RsprotExec *x, MsgProjAnimSpecificV4 *m)
{
    RSPROT_U2_ALT1(x, m->start_time);
    RSPROT_U2_ALT2(x, m->id);
    RSPROT_U3_ALT2(x, m->source_index);
    RSPROT_U2(x, m->end_time);
    RSPROT_U4_ALT2(x, m->start_packed);
    RSPROT_U1_ALT1(x, m->angle);
    RSPROT_U2_ALT3(x, m->end_height);
    RSPROT_U3_ALT3(x, m->target_index);
    RSPROT_U2(x, m->progress);
    RSPROT_U2_ALT1(x, m->start_height);
    RSPROT_U4_ALT2(x, m->end_packed);
}

/* v3 -- revs 233. */
void
packet_projanim_specific_v4_v3_out(RsprotExec *x, MsgProjAnimSpecificV4 *m)
{
    RSPROT_U4_ALT1(x, m->start_packed);
    RSPROT_U2_ALT2(x, m->start_height);
    RSPROT_U2(x, m->end_height);
    RSPROT_U2_ALT3(x, m->id);
    RSPROT_U4_ALT2(x, m->end_packed);
    RSPROT_U1_ALT2(x, m->angle);
    RSPROT_U2_ALT2(x, m->start_time);
    RSPROT_U3_ALT2(x, m->source_index);
    RSPROT_U3_ALT3(x, m->target_index);
    RSPROT_U2(x, m->progress);
    RSPROT_U2_ALT3(x, m->end_time);
}

/* v4 -- revs 234. */
void
packet_projanim_specific_v4_v4_out(RsprotExec *x, MsgProjAnimSpecificV4 *m)
{
    RSPROT_U3_ALT2(x, m->source_index);
    RSPROT_U2_ALT3(x, m->start_time);
    RSPROT_U2(x, m->progress);
    RSPROT_U2_ALT1(x, m->end_time);
    RSPROT_U2_ALT1(x, m->end_height);
    RSPROT_U2_ALT1(x, m->start_height);
    RSPROT_U1_ALT3(x, m->angle);
    RSPROT_U3_ALT1(x, m->target_index);
    RSPROT_U2_ALT2(x, m->id);
    RSPROT_U4_ALT2(x, m->start_packed);
    RSPROT_U4_ALT1(x, m->end_packed);
}

/* v5 -- revs 235. */
void
packet_projanim_specific_v4_v5_out(RsprotExec *x, MsgProjAnimSpecificV4 *m)
{
    RSPROT_U2(x, m->start_time);
    RSPROT_U2_ALT2(x, m->end_time);
    RSPROT_U4_ALT1(x, m->end_packed);
    RSPROT_U2_ALT1(x, m->end_height);
    RSPROT_U4_ALT2(x, m->start_packed);
    RSPROT_U3_ALT1(x, m->target_index);
    RSPROT_U2_ALT3(x, m->start_height);
    RSPROT_U3_ALT2(x, m->source_index);
    RSPROT_U1_ALT2(x, m->angle);
    RSPROT_U2_ALT2(x, m->id);
    RSPROT_U2_ALT1(x, m->progress);
}

/* v6 -- revs 236. */
void
packet_projanim_specific_v4_v6_out(RsprotExec *x, MsgProjAnimSpecificV4 *m)
{
    RSPROT_U2_ALT3(x, m->start_height);
    RSPROT_U2_ALT2(x, m->id);
    RSPROT_U2_ALT3(x, m->end_height);
    RSPROT_U2_ALT1(x, m->start_time);
    RSPROT_U2_ALT3(x, m->end_time);
    RSPROT_U4(x, m->start_packed);
    RSPROT_U2_ALT1(x, m->progress);
    RSPROT_U3_ALT3(x, m->source_index);
    RSPROT_U1_ALT1(x, m->angle);
    RSPROT_U3_ALT1(x, m->target_index);
    RSPROT_U4(x, m->end_packed);
}

/* v7 -- revs 237. */
void
packet_projanim_specific_v4_v7_out(RsprotExec *x, MsgProjAnimSpecificV4 *m)
{
    RSPROT_U4_ALT2(x, m->end_packed);
    RSPROT_U4_ALT2(x, m->start_packed);
    RSPROT_U2_ALT3(x, m->end_height);
    RSPROT_U2_ALT2(x, m->start_height);
    RSPROT_U2(x, m->start_time);
    RSPROT_U2_ALT2(x, m->end_time);
    RSPROT_U3_ALT1(x, m->source_index);
    RSPROT_U3(x, m->target_index);
    RSPROT_U2(x, m->id);
    RSPROT_U2(x, m->progress);
    RSPROT_U1_ALT1(x, m->angle);
}

/* v8 -- revs 238. */
void
packet_projanim_specific_v4_v8_out(RsprotExec *x, MsgProjAnimSpecificV4 *m)
{
    RSPROT_U1(x, m->angle);
    RSPROT_U2_ALT1(x, m->start_time);
    RSPROT_U2_ALT1(x, m->end_time);
    RSPROT_U2_ALT1(x, m->start_height);
    RSPROT_U4_ALT1(x, m->end_packed);
    RSPROT_U4_ALT2(x, m->start_packed);
    RSPROT_U2_ALT3(x, m->end_height);
    RSPROT_U3_ALT2(x, m->source_index);
    RSPROT_U2_ALT1(x, m->progress);
    RSPROT_U2(x, m->id);
    RSPROT_U3_ALT2(x, m->target_index);
}

/* v9 -- revs 239. */
void
packet_projanim_specific_v4_v9_out(RsprotExec *x, MsgProjAnimSpecificV4 *m)
{
    RSPROT_U2_ALT2(x, m->start_time);
    RSPROT_U2_ALT2(x, m->end_time);
    RSPROT_U2_ALT3(x, m->start_height);
    RSPROT_U2_ALT3(x, m->end_height);
    RSPROT_U1_ALT3(x, m->angle);
    RSPROT_U4_ALT1(x, m->start_packed);
    RSPROT_U2_ALT3(x, m->progress);
    RSPROT_U2_ALT1(x, m->id);
    RSPROT_U4_ALT1(x, m->end_packed);
    RSPROT_U3_ALT3(x, m->source_index);
    RSPROT_U3(x, m->target_index);
}

/*
 * 9 row(s) for 9 layout(s), complete over revisions 221-239.
 * A complete table makes rsprot_version_pick's NULL mean exactly one thing: a
 * revision outside that span. An incomplete one would conflate "not
 * transcribed" with "no such packet", and those are different facts.
 */
const RsprotVersionRange rsprot_projanim_specific_v4_out[] = {
    { 231, 231, (RsprotCodecFn)packet_projanim_specific_v4_v1_out },
    { 232, 232, (RsprotCodecFn)packet_projanim_specific_v4_v2_out },
    { 233, 233, (RsprotCodecFn)packet_projanim_specific_v4_v3_out },
    { 234, 234, (RsprotCodecFn)packet_projanim_specific_v4_v4_out },
    { 235, 235, (RsprotCodecFn)packet_projanim_specific_v4_v5_out },
    { 236, 236, (RsprotCodecFn)packet_projanim_specific_v4_v6_out },
    { 237, 237, (RsprotCodecFn)packet_projanim_specific_v4_v7_out },
    { 238, 238, (RsprotCodecFn)packet_projanim_specific_v4_v8_out },
    { 239, 239, (RsprotCodecFn)packet_projanim_specific_v4_v9_out },
};

const int rsprot_projanim_specific_v4_out_count =
    (int)(sizeof(rsprot_projanim_specific_v4_out) / sizeof(rsprot_projanim_specific_v4_out[0]));
