#ifndef RSPROT_PACKET_REBUILD_WORLDENTITY_V3_H
#define RSPROT_PACKET_REBUILD_WORLDENTITY_V3_H

/*
 * REBUILD_WORLDENTITY_V3 -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : RebuildWorldEntityV3Encoder
 * Layouts      : 2 distinct, over 2 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^RebuildWorldEntityV3Encoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgRebuildWorldEntityV3 {
	int32_t base_x;
	int32_t base_z;
} MsgRebuildWorldEntityV3;

/* v1 -- revs 229-236. */
void packet_rebuild_worldentity_v3_v1_out(RsprotExec *x, MsgRebuildWorldEntityV3 *m);
/* v2 -- revs 237. */
void packet_rebuild_worldentity_v3_v2_out(RsprotExec *x, MsgRebuildWorldEntityV3 *m);

/* Per-revision aliases: `packet_rebuild_worldentity_v3_rev239_out` is greppable, which is the
 * point -- "what does 239 do for REBUILD_WORLDENTITY_V3" without reading a table. */
#define packet_rebuild_worldentity_v3_rev229_out packet_rebuild_worldentity_v3_v1_out
#define packet_rebuild_worldentity_v3_rev230_out packet_rebuild_worldentity_v3_v1_out
#define packet_rebuild_worldentity_v3_rev231_out packet_rebuild_worldentity_v3_v1_out
#define packet_rebuild_worldentity_v3_rev232_out packet_rebuild_worldentity_v3_v1_out
#define packet_rebuild_worldentity_v3_rev233_out packet_rebuild_worldentity_v3_v1_out
#define packet_rebuild_worldentity_v3_rev234_out packet_rebuild_worldentity_v3_v1_out
#define packet_rebuild_worldentity_v3_rev235_out packet_rebuild_worldentity_v3_v1_out
#define packet_rebuild_worldentity_v3_rev236_out packet_rebuild_worldentity_v3_v1_out
#define packet_rebuild_worldentity_v3_rev237_out packet_rebuild_worldentity_v3_v2_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_rebuild_worldentity_v3_out[];
extern const int rsprot_rebuild_worldentity_v3_out_count;

#endif
