#ifndef RSPROT_PACKET_RESUME_P_COUNTDIALOG_LONG_H
#define RSPROT_PACKET_RESUME_P_COUNTDIALOG_LONG_H

/*
 * RESUME_P_COUNTDIALOG_LONG -- client -> server.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : ResumePCountDialogLongDecoder
 * Layouts      : 1 distinct, over 1 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^ResumePCountDialogLongDecoder\tin\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgResumePCountDialogLong {
	int64_t count;
} MsgResumePCountDialogLong;

/* v1 -- revs 237-239. */
void packet_resume_p_countdialog_long_v1_in(RsprotExec *x, MsgResumePCountDialogLong *m);

/* Per-revision aliases: `packet_resume_p_countdialog_long_rev239_in` is greppable, which is the
 * point -- "what does 239 do for RESUME_P_COUNTDIALOG_LONG" without reading a table. */
#define packet_resume_p_countdialog_long_rev237_in packet_resume_p_countdialog_long_v1_in
#define packet_resume_p_countdialog_long_rev238_in packet_resume_p_countdialog_long_v1_in
#define packet_resume_p_countdialog_long_rev239_in packet_resume_p_countdialog_long_v1_in

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_resume_p_countdialog_long_in[];
extern const int rsprot_resume_p_countdialog_long_in_count;

#endif
