#ifndef RSPROT_PACKET_SCRIPTEDPROJ_CHANGE_H
#define RSPROT_PACKET_SCRIPTEDPROJ_CHANGE_H

/*
 * SCRIPTEDPROJ_CHANGE -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : ScriptedProjChangeEncoder
 * Layouts      : 1 distinct, over 1 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^ScriptedProjChangeEncoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgScriptedProjChange {
	int32_t target_offset_z;
	int32_t target_height;
	int32_t target_coord_packed;
	int32_t target_offset_x;
	int32_t target_index;
	int32_t freeze_duration;
	int32_t slot;
	int32_t delete_on_freeze_end;
} MsgScriptedProjChange;

/* v1 -- revs 239. */
void packet_scriptedproj_change_v1_out(RsprotExec *x, MsgScriptedProjChange *m);

/* Per-revision aliases: `packet_scriptedproj_change_rev239_out` is greppable, which is the
 * point -- "what does 239 do for SCRIPTEDPROJ_CHANGE" without reading a table. */
#define packet_scriptedproj_change_rev239_out packet_scriptedproj_change_v1_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_scriptedproj_change_out[];
extern const int rsprot_scriptedproj_change_out_count;

#endif
