#ifndef RSPROT_PACKET_SET_NPC_UPDATE_ORIGIN_H
#define RSPROT_PACKET_SET_NPC_UPDATE_ORIGIN_H

/*
 * SET_NPC_UPDATE_ORIGIN -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : SetNpcUpdateOriginEncoder
 * Layouts      : 1 distinct, over 1 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^SetNpcUpdateOriginEncoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgSetNpcUpdateOrigin {
	int32_t origin_x;
	int32_t origin_z;
} MsgSetNpcUpdateOrigin;

/* v1 -- revs 222-239. */
void packet_set_npc_update_origin_v1_out(RsprotExec *x, MsgSetNpcUpdateOrigin *m);

/* Per-revision aliases: `packet_set_npc_update_origin_rev239_out` is greppable, which is the
 * point -- "what does 239 do for SET_NPC_UPDATE_ORIGIN" without reading a table. */
#define packet_set_npc_update_origin_rev222_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev223_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev224_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev225_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev226_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev227_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev228_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev229_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev230_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev231_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev232_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev233_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev234_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev235_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev236_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev237_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev238_out packet_set_npc_update_origin_v1_out
#define packet_set_npc_update_origin_rev239_out packet_set_npc_update_origin_v1_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_set_npc_update_origin_out[];
extern const int rsprot_set_npc_update_origin_out_count;

#endif
