#ifndef RSPROT_PACKET_SYNTH_SOUND_H
#define RSPROT_PACKET_SYNTH_SOUND_H

/*
 * SYNTH_SOUND -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : SynthSoundEncoder
 * Layouts      : 1 distinct, over 1 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^SynthSoundEncoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgSynthSound {
	int32_t id;
	int32_t loops;
	int32_t delay;
} MsgSynthSound;

/* v1 -- revs 221-239. */
void packet_synth_sound_v1_out(RsprotExec *x, MsgSynthSound *m);

/* Per-revision aliases: `packet_synth_sound_rev239_out` is greppable, which is the
 * point -- "what does 239 do for SYNTH_SOUND" without reading a table. */
#define packet_synth_sound_rev221_out packet_synth_sound_v1_out
#define packet_synth_sound_rev222_out packet_synth_sound_v1_out
#define packet_synth_sound_rev223_out packet_synth_sound_v1_out
#define packet_synth_sound_rev224_out packet_synth_sound_v1_out
#define packet_synth_sound_rev225_out packet_synth_sound_v1_out
#define packet_synth_sound_rev226_out packet_synth_sound_v1_out
#define packet_synth_sound_rev227_out packet_synth_sound_v1_out
#define packet_synth_sound_rev228_out packet_synth_sound_v1_out
#define packet_synth_sound_rev229_out packet_synth_sound_v1_out
#define packet_synth_sound_rev230_out packet_synth_sound_v1_out
#define packet_synth_sound_rev231_out packet_synth_sound_v1_out
#define packet_synth_sound_rev232_out packet_synth_sound_v1_out
#define packet_synth_sound_rev233_out packet_synth_sound_v1_out
#define packet_synth_sound_rev234_out packet_synth_sound_v1_out
#define packet_synth_sound_rev235_out packet_synth_sound_v1_out
#define packet_synth_sound_rev236_out packet_synth_sound_v1_out
#define packet_synth_sound_rev237_out packet_synth_sound_v1_out
#define packet_synth_sound_rev238_out packet_synth_sound_v1_out
#define packet_synth_sound_rev239_out packet_synth_sound_v1_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_synth_sound_out[];
extern const int rsprot_synth_sound_out_count;

#endif
