#ifndef RSPROT_PACKET_UPDATE_ZONE_PARTIAL_FOLLOWS_H
#define RSPROT_PACKET_UPDATE_ZONE_PARTIAL_FOLLOWS_H

/*
 * UPDATE_ZONE_PARTIAL_FOLLOWS -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : UpdateZonePartialFollowsEncoder
 * Layouts      : 19 distinct, over 19 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^UpdateZonePartialFollowsEncoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgUpdateZonePartialFollows {
	int32_t zone_x;
	int32_t zone_z;
	int32_t level;
} MsgUpdateZonePartialFollows;

/* v1 -- revs 221. */
void packet_update_zone_partial_follows_v1_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v2 -- revs 222. */
void packet_update_zone_partial_follows_v2_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v3 -- revs 223. */
void packet_update_zone_partial_follows_v3_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v4 -- revs 224. */
void packet_update_zone_partial_follows_v4_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v5 -- revs 225. */
void packet_update_zone_partial_follows_v5_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v6 -- revs 226. */
void packet_update_zone_partial_follows_v6_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v7 -- revs 227. */
void packet_update_zone_partial_follows_v7_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v8 -- revs 228. */
void packet_update_zone_partial_follows_v8_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v9 -- revs 229. */
void packet_update_zone_partial_follows_v9_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v10 -- revs 230. */
void packet_update_zone_partial_follows_v10_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v11 -- revs 231. */
void packet_update_zone_partial_follows_v11_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v12 -- revs 232. */
void packet_update_zone_partial_follows_v12_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v13 -- revs 233. */
void packet_update_zone_partial_follows_v13_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v14 -- revs 234. */
void packet_update_zone_partial_follows_v14_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v15 -- revs 235. */
void packet_update_zone_partial_follows_v15_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v16 -- revs 236. */
void packet_update_zone_partial_follows_v16_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v17 -- revs 237. */
void packet_update_zone_partial_follows_v17_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v18 -- revs 238. */
void packet_update_zone_partial_follows_v18_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);
/* v19 -- revs 239. */
void packet_update_zone_partial_follows_v19_out(RsprotExec *x, MsgUpdateZonePartialFollows *m);

/* Per-revision aliases: `packet_update_zone_partial_follows_rev239_out` is greppable, which is the
 * point -- "what does 239 do for UPDATE_ZONE_PARTIAL_FOLLOWS" without reading a table. */
#define packet_update_zone_partial_follows_rev221_out packet_update_zone_partial_follows_v1_out
#define packet_update_zone_partial_follows_rev222_out packet_update_zone_partial_follows_v2_out
#define packet_update_zone_partial_follows_rev223_out packet_update_zone_partial_follows_v3_out
#define packet_update_zone_partial_follows_rev224_out packet_update_zone_partial_follows_v4_out
#define packet_update_zone_partial_follows_rev225_out packet_update_zone_partial_follows_v5_out
#define packet_update_zone_partial_follows_rev226_out packet_update_zone_partial_follows_v6_out
#define packet_update_zone_partial_follows_rev227_out packet_update_zone_partial_follows_v7_out
#define packet_update_zone_partial_follows_rev228_out packet_update_zone_partial_follows_v8_out
#define packet_update_zone_partial_follows_rev229_out packet_update_zone_partial_follows_v9_out
#define packet_update_zone_partial_follows_rev230_out packet_update_zone_partial_follows_v10_out
#define packet_update_zone_partial_follows_rev231_out packet_update_zone_partial_follows_v11_out
#define packet_update_zone_partial_follows_rev232_out packet_update_zone_partial_follows_v12_out
#define packet_update_zone_partial_follows_rev233_out packet_update_zone_partial_follows_v13_out
#define packet_update_zone_partial_follows_rev234_out packet_update_zone_partial_follows_v14_out
#define packet_update_zone_partial_follows_rev235_out packet_update_zone_partial_follows_v15_out
#define packet_update_zone_partial_follows_rev236_out packet_update_zone_partial_follows_v16_out
#define packet_update_zone_partial_follows_rev237_out packet_update_zone_partial_follows_v17_out
#define packet_update_zone_partial_follows_rev238_out packet_update_zone_partial_follows_v18_out
#define packet_update_zone_partial_follows_rev239_out packet_update_zone_partial_follows_v19_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_update_zone_partial_follows_out[];
extern const int rsprot_update_zone_partial_follows_out_count;

#endif
