#ifndef RSPROT_PACKET_UPDATE_STAT_H
#define RSPROT_PACKET_UPDATE_STAT_H

/*
 * UPDATE_STAT -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : UpdateStatEncoder
 * Layouts      : 5 distinct, over 5 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^UpdateStatEncoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgUpdateStat {
	int32_t stat;
	int32_t current_level;
	int32_t invisible_boosted_level;
	int32_t experience;
} MsgUpdateStat;

/* v1 -- revs 221. */
void packet_update_stat_v1_out(RsprotExec *x, MsgUpdateStat *m);
/* v2 -- revs 222. */
void packet_update_stat_v2_out(RsprotExec *x, MsgUpdateStat *m);
/* v3 -- revs 223. */
void packet_update_stat_v3_out(RsprotExec *x, MsgUpdateStat *m);
/* v4 -- revs 224. */
void packet_update_stat_v4_out(RsprotExec *x, MsgUpdateStat *m);
/* v5 -- revs 225. */
void packet_update_stat_v5_out(RsprotExec *x, MsgUpdateStat *m);

/* Per-revision aliases: `packet_update_stat_rev239_out` is greppable, which is the
 * point -- "what does 239 do for UPDATE_STAT" without reading a table. */
#define packet_update_stat_rev221_out packet_update_stat_v1_out
#define packet_update_stat_rev222_out packet_update_stat_v2_out
#define packet_update_stat_rev223_out packet_update_stat_v3_out
#define packet_update_stat_rev224_out packet_update_stat_v4_out
#define packet_update_stat_rev225_out packet_update_stat_v5_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_update_stat_out[];
extern const int rsprot_update_stat_out_count;

#endif
