#ifndef RSPROT_PACKET_VARP_SYNC_H
#define RSPROT_PACKET_VARP_SYNC_H

/*
 * VARP_SYNC -- server -> client.
 *
 * GENERATED by tools/rsprot_gen_codec.py -- do not edit. Hand edits are lost on
 * the next run; change the generator, or the RSProt source it reads.
 *
 * Shape and rationale: 3rd/rsprot/packets/if_opentop.h, which is hand-written
 * and is the pattern this file is generated into. Read that one first.
 *
 * RSProt class : VarpSyncEncoder
 * Layouts      : 1 distinct, over 1 contiguous revision run(s)
 * Version nos. : from gen/packet_versions.txt (append-only; never allocated
 *                here). Cross-check with:
 *                    grep '^VarpSyncEncoder\tout\t' 3rd/rsprot/gen/packet_versions.txt
 */

#include "../include/rsprot_exec.h"

/**
 * One struct for every version -- the union of all their fields.
 *
 * A field a version does not carry is simply not transferred, which is what
 * keeps the layer above revision-free: fill the struct, and the wire picks the
 * codec.
 */
typedef struct MsgVarpSync {
	/* No payload at any version. C has no empty
	 * struct; nothing reads this. */
	int32_t _unused;
} MsgVarpSync;

/* v1 -- revs 221-239. */
void packet_varp_sync_v1_out(RsprotExec *x, MsgVarpSync *m);

/* Per-revision aliases: `packet_varp_sync_rev239_out` is greppable, which is the
 * point -- "what does 239 do for VARP_SYNC" without reading a table. */
#define packet_varp_sync_rev221_out packet_varp_sync_v1_out
#define packet_varp_sync_rev222_out packet_varp_sync_v1_out
#define packet_varp_sync_rev223_out packet_varp_sync_v1_out
#define packet_varp_sync_rev224_out packet_varp_sync_v1_out
#define packet_varp_sync_rev225_out packet_varp_sync_v1_out
#define packet_varp_sync_rev226_out packet_varp_sync_v1_out
#define packet_varp_sync_rev227_out packet_varp_sync_v1_out
#define packet_varp_sync_rev228_out packet_varp_sync_v1_out
#define packet_varp_sync_rev229_out packet_varp_sync_v1_out
#define packet_varp_sync_rev230_out packet_varp_sync_v1_out
#define packet_varp_sync_rev231_out packet_varp_sync_v1_out
#define packet_varp_sync_rev232_out packet_varp_sync_v1_out
#define packet_varp_sync_rev233_out packet_varp_sync_v1_out
#define packet_varp_sync_rev234_out packet_varp_sync_v1_out
#define packet_varp_sync_rev235_out packet_varp_sync_v1_out
#define packet_varp_sync_rev236_out packet_varp_sync_v1_out
#define packet_varp_sync_rev237_out packet_varp_sync_v1_out
#define packet_varp_sync_rev238_out packet_varp_sync_v1_out
#define packet_varp_sync_rev239_out packet_varp_sync_v1_out

/** Revision -> layout. See the .c for the rows. */
extern const RsprotVersionRange rsprot_varp_sync_out[];
extern const int rsprot_varp_sync_out_count;

#endif
