/* ZBUF. GENERATED by tools/rsprot_gen_codec.py -- do not edit. */
#include "zbuf.h"

/*
 * Transcribed from RSProt:
 *   protocol/osrs-<N>/osrs-<N>-desktop/src/main/kotlin/net/rsprot/protocol/
 *       game/outgoing/codec/misc/client/ZBufEncoder.kt
 *
 * One function per layout, running in whichever direction the executor is in --
 * so a server's writer and a client's reader are the same transcription and
 * cannot drift apart.
 */

/* v1 -- revs 234-237. */
void
packet_zbuf_v1_out(RsprotExec *x, MsgZBuf *m)
{
    RSPROT_BOOL(x, m->enabled);
}

/*
 * 1 row(s) for 1 layout(s), complete over revisions 221-239.
 * A complete table makes rsprot_version_pick's NULL mean exactly one thing: a
 * revision outside that span. An incomplete one would conflate "not
 * transcribed" with "no such packet", and those are different facts.
 */
const RsprotVersionRange rsprot_zbuf_out[] = {
    { 234, 237, (RsprotCodecFn)packet_zbuf_v1_out },
};

const int rsprot_zbuf_out_count =
    (int)(sizeof(rsprot_zbuf_out) / sizeof(rsprot_zbuf_out[0]));
