  WIPED = 3,
  ABANDONED = 4,
}

export enum Stage {
  UNKNOWN = StageProto.UNKNOWN_STAGE,

  TOB_MAIDEN = StageProto.TOB_MAIDEN,
  TOB_BLOAT = StageProto.TOB_BLOAT,
  TOB_NYLOCAS = StageProto.TOB_NYLOCAS,
  TOB_SOTETSEG = StageProto.TOB_SOTETSEG,
  TOB_XARPUS = StageProto.TOB_XARPUS,
  TOB_VERZIK = StageProto.TOB_VERZIK,

  COX_TEKTON = StageProto.COX_TEKTON,
  COX_CRABS = StageProto.COX_CRABS,
  COX_ICE_DEMON = StageProto.COX_ICE_DEMON,
  COX_SHAMANS = StageProto.COX_SHAMANS,
  COX_VANGUARDS = StageProto.COX_VANGUARDS,
  COX_THIEVING = StageProto.COX_THIEVING,
  COX_VESPULA = StageProto.COX_VESPULA,
  COX_TIGHTROPE = StageProto.COX_TIGHTROPE,
  COX_GUARDIANS = StageProto.COX_GUARDIANS,
  COX_VASA = StageProto.COX_VASA,
  COX_MYSTICS = StageProto.COX_MYSTICS,
  COX_MUTTADILE = StageProto.COX_MUTTADILE,
  COX_OLM = StageProto.COX_OLM,

  TOA_APMEKEN = StageProto.TOA_APMEKEN,
  TOA_BABA = StageProto.TOA_BABA,
  TOA_SCABARAS = StageProto.TOA_SCABARAS,
  TOA_KEPHRI = StageProto.TOA_KEPHRI,
  TOA_HET = StageProto.TOA_HET,
  TOA_AKKHA = StageProto.TOA_AKKHA,
  TOA_CRONDIS = StageProto.TOA_CRONDIS,
  TOA_ZEBAK = StageProto.TOA_ZEBAK,
  TOA_WARDENS = StageProto.TOA_WARDENS,

