#ifndef SRC_NET_REV_PKTNAMES_H
#define SRC_NET_REV_PKTNAMES_H

/*
 * Canonical (revision-independent) packet names.
 *
 * Wire opcodes differ per server build (lc245_2 vs lc254) but the payload
 * layout of a given packet NAME is identical across the builds this client
 * targets. The parser, exec layer, and outbound builders all key on these
 * names; only the per-revision tables (net/rev/<rev>/packetin.h,
 * packetout.h) know wire numbers. GameProtoRevTable.packetin_code maps
 * wire -> name, .packetin_wire / .packetout_code map name -> wire.
 *
 * The inbound set is the authoritative LostCity_Server (rev 254)
 * ServerGameProt list plus its zone sub-packets; lc245_2 covers a subset
 * (its table simply has no row for names it lacks).
 */

enum GameProtoPktName
{
    PKT_NAME_NONE = 0,

    /* interfaces */
    PKT_NAME_IF_OPENCHAT,
    PKT_NAME_IF_OPENMAIN_SIDE,
    PKT_NAME_IF_CLOSE,
    PKT_NAME_IF_SETTAB,
    PKT_NAME_IF_SETTAB_ACTIVE,
    PKT_NAME_IF_OPENMAIN,
    PKT_NAME_IF_OPENSIDE,
    PKT_NAME_IF_OPENOVERLAY,

    /* interface mutators */
    PKT_NAME_IF_SETCOLOUR,
    PKT_NAME_IF_SETHIDE,
    PKT_NAME_IF_SETOBJECT,
    PKT_NAME_IF_SETMODEL,
    PKT_NAME_IF_SETANIM,
    PKT_NAME_IF_SETPLAYERHEAD,
    PKT_NAME_IF_SETTEXT,
    PKT_NAME_IF_SETNPCHEAD,
    PKT_NAME_IF_SETPOSITION,
    PKT_NAME_IF_SETSCROLLPOS,

    /* tutorial */
    PKT_NAME_TUT_FLASH,
    PKT_NAME_TUT_OPEN,

    /* inventory */
    PKT_NAME_UPDATE_INV_STOP_TRANSMIT,
    PKT_NAME_UPDATE_INV_FULL,
    PKT_NAME_UPDATE_INV_PARTIAL,

    /* camera */
    PKT_NAME_CAM_LOOKAT,
    PKT_NAME_CAM_SHAKE,
    PKT_NAME_CAM_MOVETO,
    PKT_NAME_CAM_RESET,

    /* entity info command streams */
    PKT_NAME_NPC_INFO,
    PKT_NAME_PLAYER_INFO,

    /* tracking */
    PKT_NAME_FINISH_TRACKING,
    PKT_NAME_ENABLE_TRACKING,

    /* social / chat */
    PKT_NAME_MESSAGE_GAME,
    PKT_NAME_UPDATE_IGNORELIST,
    PKT_NAME_CHAT_FILTER_SETTINGS,
    PKT_NAME_MESSAGE_PRIVATE,
    PKT_NAME_UPDATE_FRIENDLIST,
    PKT_NAME_FRIENDLIST_LOADED,

    /* misc */
    PKT_NAME_UNSET_MAP_FLAG,
    PKT_NAME_UPDATE_RUNWEIGHT,
    PKT_NAME_HINT_ARROW,
    PKT_NAME_UPDATE_REBOOT_TIMER,
    PKT_NAME_UPDATE_STAT,
    PKT_NAME_UPDATE_RUNENERGY,
    PKT_NAME_RESET_ANIMS,
    PKT_NAME_UPDATE_PID,
    PKT_NAME_LAST_LOGIN_INFO,
    PKT_NAME_LOGOUT,
    PKT_NAME_P_COUNTDIALOG,
    PKT_NAME_SET_MULTIWAY,
    PKT_NAME_SET_PLAYER_OP,

    /* maps / vars / audio */
    PKT_NAME_REBUILD_NORMAL,
    PKT_NAME_VARP_SMALL,
    PKT_NAME_VARP_LARGE,
    PKT_NAME_RESET_CLIENT_VARCACHE, /* aka VARP_SYNC */
    PKT_NAME_SYNTH_SOUND,
    PKT_NAME_MIDI_SONG,
    PKT_NAME_MIDI_JINGLE,

    /* zones + zone sub-packets (sub-packet opcodes share the wire space) */
    PKT_NAME_UPDATE_ZONE_PARTIAL_FOLLOWS,
    PKT_NAME_UPDATE_ZONE_FULL_FOLLOWS,
    PKT_NAME_UPDATE_ZONE_PARTIAL_ENCLOSED,
    PKT_NAME_LOC_MERGE, /* aka P_LOCMERGE */
    PKT_NAME_LOC_ANIM,
    PKT_NAME_OBJ_DEL,
    PKT_NAME_OBJ_REVEAL,
    PKT_NAME_LOC_ADD_CHANGE,
    PKT_NAME_MAP_PROJANIM,
    PKT_NAME_LOC_DEL,
    PKT_NAME_OBJ_COUNT,
    PKT_NAME_MAP_ANIM,
    PKT_NAME_OBJ_ADD,

    PKT_NAME_COUNT
};

/* Canonical client -> server packet names (authoritative rev-254 ClientProt
 * set; lc245_2 maps the subset it supports). */
enum GameProtoPktOutName
{
    PKTOUT_NAME_NONE = 0,

    PKTOUT_NAME_NO_TIMEOUT,
    PKTOUT_NAME_IDLE_TIMER,

    PKTOUT_NAME_EVENT_MOUSE_CLICK,
    PKTOUT_NAME_EVENT_MOUSE_MOVE,
    PKTOUT_NAME_EVENT_APPLET_FOCUS,
    PKTOUT_NAME_EVENT_TRACKING,
    PKTOUT_NAME_EVENT_CAMERA_POSITION,

    PKTOUT_NAME_ANTICHEAT_OPLOGIC1,
    PKTOUT_NAME_ANTICHEAT_OPLOGIC2,
    PKTOUT_NAME_ANTICHEAT_OPLOGIC3,
    PKTOUT_NAME_ANTICHEAT_OPLOGIC4,
    PKTOUT_NAME_ANTICHEAT_OPLOGIC5,
    PKTOUT_NAME_ANTICHEAT_OPLOGIC6,
    PKTOUT_NAME_ANTICHEAT_OPLOGIC7,
    PKTOUT_NAME_ANTICHEAT_OPLOGIC8,
    PKTOUT_NAME_ANTICHEAT_OPLOGIC9,
    PKTOUT_NAME_ANTICHEAT_CYCLELOGIC1,
    PKTOUT_NAME_ANTICHEAT_CYCLELOGIC2,
    PKTOUT_NAME_ANTICHEAT_CYCLELOGIC3,
    PKTOUT_NAME_ANTICHEAT_CYCLELOGIC4,
    PKTOUT_NAME_ANTICHEAT_CYCLELOGIC5,
    PKTOUT_NAME_ANTICHEAT_CYCLELOGIC6,
    PKTOUT_NAME_ANTICHEAT_CYCLELOGIC7,

    PKTOUT_NAME_OPOBJ1,
    PKTOUT_NAME_OPOBJ2,
    PKTOUT_NAME_OPOBJ3,
    PKTOUT_NAME_OPOBJ4,
    PKTOUT_NAME_OPOBJ5,
    PKTOUT_NAME_OPOBJT,
    PKTOUT_NAME_OPOBJU,

    PKTOUT_NAME_OPNPC1,
    PKTOUT_NAME_OPNPC2,
    PKTOUT_NAME_OPNPC3,
    PKTOUT_NAME_OPNPC4,
    PKTOUT_NAME_OPNPC5,
    PKTOUT_NAME_OPNPCT,
    PKTOUT_NAME_OPNPCU,

    PKTOUT_NAME_OPLOC1,
    PKTOUT_NAME_OPLOC2,
    PKTOUT_NAME_OPLOC3,
    PKTOUT_NAME_OPLOC4,
    PKTOUT_NAME_OPLOC5,
    PKTOUT_NAME_OPLOCT,
    PKTOUT_NAME_OPLOCU,

    PKTOUT_NAME_OPPLAYER1,
    PKTOUT_NAME_OPPLAYER2,
    PKTOUT_NAME_OPPLAYER3,
    PKTOUT_NAME_OPPLAYER4,
    PKTOUT_NAME_OPPLAYER5,
    PKTOUT_NAME_OPPLAYERT,
    PKTOUT_NAME_OPPLAYERU,

    PKTOUT_NAME_OPHELD1,
    PKTOUT_NAME_OPHELD2,
    PKTOUT_NAME_OPHELD3,
    PKTOUT_NAME_OPHELD4,
    PKTOUT_NAME_OPHELD5,
    PKTOUT_NAME_OPHELDT,
    PKTOUT_NAME_OPHELDU,

    PKTOUT_NAME_INV_BUTTON1,
    PKTOUT_NAME_INV_BUTTON2,
    PKTOUT_NAME_INV_BUTTON3,
    PKTOUT_NAME_INV_BUTTON4,
    PKTOUT_NAME_INV_BUTTON5,
    PKTOUT_NAME_INV_BUTTOND,

    PKTOUT_NAME_IF_BUTTON,
    PKTOUT_NAME_RESUME_PAUSEBUTTON,
    PKTOUT_NAME_CLOSE_MODAL,
    PKTOUT_NAME_RESUME_P_COUNTDIALOG,
    PKTOUT_NAME_TUT_CLICKSIDE,

    PKTOUT_NAME_MAP_BUILD_COMPLETE,
    PKTOUT_NAME_MOVE_OPCLICK,
    PKTOUT_NAME_REPORT_ABUSE,
    PKTOUT_NAME_MOVE_MINIMAPCLICK,
    PKTOUT_NAME_MOVE_GAMECLICK,

    PKTOUT_NAME_IGNORELIST_DEL,
    PKTOUT_NAME_IGNORELIST_ADD,
    PKTOUT_NAME_FRIENDLIST_DEL,
    PKTOUT_NAME_FRIENDLIST_ADD,
    PKTOUT_NAME_IDK_SAVEDESIGN,
    PKTOUT_NAME_CHAT_SETMODE,
    PKTOUT_NAME_MESSAGE_PRIVATE,
    PKTOUT_NAME_MESSAGE_PUBLIC,
    PKTOUT_NAME_CLIENT_CHEAT,

    PKTOUT_NAME_COUNT
};

#endif
