/*
 * Resolving the engine's ids out of the content tree.
 *
 * One table, read top to bottom. The point of keeping it in a single file is
 * that it is the complete list: if a number the engine sends is not derived
 * from something the player did, it is one of these, and it is here beside the
 * name the cache knows it by.
 */

#include "mock230_ids.h"

#include "mock230_content.h"

#include <stdio.h>

static struct Mock230Ids g_ids;

const struct Mock230Ids*
mock230_ids(void)
{
    return &g_ids;
}

int
mock230_ids_resolve(void)
{
    /* Written out rather than generated by a macro so that grepping for a
     * symbol name finds both the pack line and the field it lands in. */
    const struct Mock230SymbolRef k_refs[] = {
        { MOCK230_PACK_INTERFACE, "gameframe", &g_ids.iface_gameframe },
        { MOCK230_PACK_INTERFACE, "inventory", &g_ids.iface_inventory },
        { MOCK230_PACK_INTERFACE, "worn_equipment", &g_ids.iface_wornitems },
        { MOCK230_PACK_INTERFACE, "bankmain", &g_ids.iface_bankmain },
        { MOCK230_PACK_INTERFACE, "bankside", &g_ids.iface_bankside },
        { MOCK230_PACK_INTERFACE, "equipment_stats", &g_ids.iface_equipment_stats },
        { MOCK230_PACK_INTERFACE, "equipment_stats_side", &g_ids.iface_equipment_stats_side },
        { MOCK230_PACK_INTERFACE, "prayerbook", &g_ids.iface_prayerbook },
        { MOCK230_PACK_INTERFACE, "worldmap", &g_ids.iface_worldmap },

        { MOCK230_PACK_INV, "inv", &g_ids.inv_backpack },
        { MOCK230_PACK_INV, "worn", &g_ids.inv_worn },
        { MOCK230_PACK_INV, "bank", &g_ids.inv_bank },

        { MOCK230_PACK_COMPONENT, "gameframe_mainmodal", &g_ids.com_gameframe_mainmodal },
        { MOCK230_PACK_COMPONENT, "gameframe_sidemodal", &g_ids.com_gameframe_sidemodal },
        { MOCK230_PACK_COMPONENT, "gameframe_floater", &g_ids.com_gameframe_floater },
        { MOCK230_PACK_COMPONENT, "worldmap_esckey", &g_ids.com_worldmap_esckey },
        { MOCK230_PACK_COMPONENT, "worldmap_close", &g_ids.com_worldmap_close },
        { MOCK230_PACK_COMPONENT, "inventory_items", &g_ids.com_inventory_items },
        { MOCK230_PACK_COMPONENT, "worn_equipment_stats", &g_ids.com_worn_equipment_stats },

        { MOCK230_PACK_COMPONENT, "bankmain_items", &g_ids.com_bankmain_items },
        { MOCK230_PACK_COMPONENT, "bankmain_swap", &g_ids.com_bankmain_swap },
        { MOCK230_PACK_COMPONENT, "bankmain_insert", &g_ids.com_bankmain_insert },
        { MOCK230_PACK_COMPONENT, "bankmain_item_mode", &g_ids.com_bankmain_item_mode },
        { MOCK230_PACK_COMPONENT, "bankmain_note_mode", &g_ids.com_bankmain_note_mode },
        { MOCK230_PACK_COMPONENT, "bankmain_qty_1", &g_ids.com_bankmain_qty_1 },
        { MOCK230_PACK_COMPONENT, "bankmain_qty_5", &g_ids.com_bankmain_qty_5 },
        { MOCK230_PACK_COMPONENT, "bankmain_qty_10", &g_ids.com_bankmain_qty_10 },
        { MOCK230_PACK_COMPONENT, "bankmain_qty_x", &g_ids.com_bankmain_qty_x },
        { MOCK230_PACK_COMPONENT, "bankmain_qty_all", &g_ids.com_bankmain_qty_all },
        { MOCK230_PACK_COMPONENT, "bankmain_deposit_inv", &g_ids.com_bankmain_deposit_inv },
        { MOCK230_PACK_COMPONENT, "bankmain_deposit_worn", &g_ids.com_bankmain_deposit_worn },
        { MOCK230_PACK_COMPONENT, "bankside_items", &g_ids.com_bankside_items },

        { MOCK230_PACK_COMPONENT, "equipment_stats_container",
          &g_ids.com_equipment_stats_container },
        { MOCK230_PACK_COMPONENT, "equipment_stats_stabatt",
          &g_ids.com_equipment_stats_stabatt },
        { MOCK230_PACK_COMPONENT, "equipment_stats_slashatt",
          &g_ids.com_equipment_stats_slashatt },
        { MOCK230_PACK_COMPONENT, "equipment_stats_crushatt",
          &g_ids.com_equipment_stats_crushatt },
        { MOCK230_PACK_COMPONENT, "equipment_stats_magicatt",
          &g_ids.com_equipment_stats_magicatt },
        { MOCK230_PACK_COMPONENT, "equipment_stats_rangeatt",
          &g_ids.com_equipment_stats_rangeatt },
        { MOCK230_PACK_COMPONENT, "equipment_stats_stabdef",
          &g_ids.com_equipment_stats_stabdef },
        { MOCK230_PACK_COMPONENT, "equipment_stats_slashdef",
          &g_ids.com_equipment_stats_slashdef },
        { MOCK230_PACK_COMPONENT, "equipment_stats_crushdef",
          &g_ids.com_equipment_stats_crushdef },
        { MOCK230_PACK_COMPONENT, "equipment_stats_magicdef",
          &g_ids.com_equipment_stats_magicdef },
        { MOCK230_PACK_COMPONENT, "equipment_stats_rangedef",
          &g_ids.com_equipment_stats_rangedef },
        { MOCK230_PACK_COMPONENT, "equipment_stats_meleestrength",
          &g_ids.com_equipment_stats_meleestrength },
        { MOCK230_PACK_COMPONENT, "equipment_stats_rangestrength",
          &g_ids.com_equipment_stats_rangestrength },
        { MOCK230_PACK_COMPONENT, "equipment_stats_magicdamage",
          &g_ids.com_equipment_stats_magicdamage },
        { MOCK230_PACK_COMPONENT, "equipment_stats_prayer",
          &g_ids.com_equipment_stats_prayer },
        { MOCK230_PACK_COMPONENT, "equipment_stats_typemultiplier",
          &g_ids.com_equipment_stats_typemultiplier },
        { MOCK230_PACK_COMPONENT, "equipment_stats_slayermultiplier",
          &g_ids.com_equipment_stats_slayermultiplier },
        { MOCK230_PACK_COMPONENT, "equipment_stats_attackspeedbase",
          &g_ids.com_equipment_stats_attackspeedbase },
        { MOCK230_PACK_COMPONENT, "equipment_stats_attackspeedactual",
          &g_ids.com_equipment_stats_attackspeedactual },

        { MOCK230_PACK_VARBIT, "bank_withdrawnotes", &g_ids.varbit_bank_withdrawnotes },
        { MOCK230_PACK_VARBIT, "bank_insertmode", &g_ids.varbit_bank_insertmode },
        { MOCK230_PACK_VARBIT, "bank_requestedquantity",
          &g_ids.varbit_bank_requestedquantity },
        { MOCK230_PACK_VARBIT, "bank_quantity_type", &g_ids.varbit_bank_quantity_type },
        { MOCK230_PACK_VARBIT, "bank_currenttab", &g_ids.varbit_bank_currenttab },
        { MOCK230_PACK_VARBIT, "bank_tab_display", &g_ids.varbit_bank_tab_display },
        { MOCK230_PACK_VARBIT, "bank_leaveplaceholders",
          &g_ids.varbit_bank_leaveplaceholders },
        { MOCK230_PACK_VARBIT, "bank_showincinerator", &g_ids.varbit_bank_showincinerator },
        { MOCK230_PACK_VARBIT, "bank_hidedepositworn", &g_ids.varbit_bank_hidedepositworn },
        { MOCK230_PACK_VARBIT, "bank_side_slot_ignore", &g_ids.varbit_bank_side_slot_ignore },
    };
    static const struct
    {
        const char* name;
        int* out;
    } k_constants[] = {
        { "bank_qty_1", &g_ids.bank_qty_1 },     { "bank_qty_5", &g_ids.bank_qty_5 },
        { "bank_qty_10", &g_ids.bank_qty_10 },   { "bank_qty_x", &g_ids.bank_qty_x },
        { "bank_qty_all", &g_ids.bank_qty_all },
    };
    int failed;

    failed = mock230_content_resolve("ids", k_refs, (int)(sizeof(k_refs) / sizeof(k_refs[0])));

    for( size_t i = 0; i < sizeof(k_constants) / sizeof(k_constants[0]); i++ )
    {
        /* -1 rather than 0 for a missing one: a quantity mode of 0 is
         * "withdraw 1", so the fallback would be a working bank with the wrong
         * button lit. mock230_content_constant_int does the reporting. */
        *k_constants[i].out = mock230_content_constant_int(k_constants[i].name, -1);
        if( *k_constants[i].out < 0 )
            failed++;
    }

    if( failed )
        fprintf(stderr,
                "mock230: %d id(s) did not resolve — the content tree and the packs "
                "disagree\n",
                failed);
    return failed;
}
