#ifndef OSRS_CORE_PACKETIN_SHARED_H
#define OSRS_CORE_PACKETIN_SHARED_H

#include <assert.h>
#include <stdint.h>

#define PKTIN_LENGTH_VARU8 (-1)
#define PKTIN_LENGTH_VARU16 (-2)

enum PacketInType_Dane317
{
    PKTIN_CAM_LOOKAT = 177,
    PKTIN_CAM_RESET = 107,
    PKTIN_CAM_SETPOS = 166,
    PKTIN_CAM_SHAKE = 35,
    PKTIN_IF_CHAT = 164,
    PKTIN_IF_CHAT_STICKY = 218,
    PKTIN_CHAT_FILTER_SETTINGS = 206,
    PKTIN_CLEAR_MAP_FLAG = 78,
    PKTIN_FRIENDLIST_LOADED = 221,
    PKTIN_FRIEND_STATUS = 50,
    PKTIN_HINT_ARROW = 254,
    PKTIN_IF_CLOSE = 219,
    PKTIN_IF_SETANGLE = 230,
    PKTIN_IF_SETANIM = 200,
    PKTIN_IF_SETCOLOR = 122,
    PKTIN_IF_SETHIDE = 171,
    PKTIN_IF_SETMODEL = 8,
    PKTIN_IF_SETNPCHEAD = 75,
    PKTIN_IF_SETOBJECT = 246,
    PKTIN_IF_SETPLAYERHEAD = 185,
    PKTIN_IF_SETPOSITION = 70,
    PKTIN_IF_SETSCROLLPOS = 79,
    PKTIN_IF_SETTEXT = 126,
    PKTIN_IF_STOPANIM = 142,
    PKTIN_IF_VIEWPORT = 97,
    PKTIN_IF_VIEWPORT_AND_SIDEBAR = 248,
    PKTIN_IF_VIEWPORT_OVERLAY = 208,
    PKTIN_IGNORE_LIST = 214,
    PKTIN_INPUT_AMOUNT = 27,
    PKTIN_INPUT_NAME = 187,
    PKTIN_INV_CLEAR = 72,
    PKTIN_LAST_LOGIN_INFO = 176,
    PKTIN_LOCAL_PLAYER = 249,
    PKTIN_LOC_ADD = 151,
    PKTIN_LOC_CHANGE = 160,
    PKTIN_LOC_DEL = 101,
    PKTIN_LOGOUT = 109,
    PKTIN_MESSAGE_GAME = 253,
    PKTIN_MESSAGE_PUBLIC = 196,
    PKTIN_MIDI_JINGLE = 121,
    PKTIN_MIDI_SONG = 74,
    PKTIN_MINIMAP_TOGGLE = 99,
    PKTIN_MULTIZONE = 61,
    PKTIN_OBJ_ADD = 44,
    PKTIN_OBJ_COUNT = 84,
    PKTIN_OBJ_DEL = 156,
    PKTIN_OBJ_REVEAL = 215,
    PKTIN_LOC_PLAYER = 147,
    PKTIN_MAP_PROJECTILE = 117,
    PKTIN_REBUILD_REGION = 73,
    PKTIN_REBUILD_REGION_INSTANCE = 241,
    PKTIN_RESET_ANIMS = 1,
    PKTIN_RESET_CLIENT_VARCACHE = 68,
    PKTIN_SET_PLAYER_OP = 104,
    PKTIN_MAP_SOUND = 105,
    PKTIN_MAP_ANIM = 4,
    PKTIN_SYNC_NPCS = 65,
    PKTIN_SYNC_PLAYERS = 81,
    PKTIN_SYNTH_SOUND = 174,
    PKTIN_IF_TAB = 71,
    PKTIN_TAB_HINT = 24,
    PKTIN_TAB_SELECTED = 106,
    PKTIN_UPDATE_INV_FULL = 53,
    PKTIN_UPDATE_INV_PARTIAL = 34,
    PKTIN_UPDATE_REBOOT_TIMER = 114,
    PKTIN_UPDATE_RUNENERGY = 110,
    PKTIN_UPDATE_RUNWEIGHT = 240,
    PKTIN_UPDATE_STAT = 134,
    PKTIN_VARP_LARGE = 87,
    PKTIN_VARP_SMALL = 36,
    PKTIN_ZONE_BASE = 85,
    PKTIN_ZONE_CLEAR = 64,
    PKTIN_ZONE_UPDATE = 60,
};

struct PacketInDefinition
{
    int name;
    int code;
    int length;
};

#define PACKET_DEFINITION(name, code, length) { name, code, length }

static inline int
packetin_size_dane317(int packet_type)
{
    assert(packet_type >= 0 && packet_type < 256);
    return 0;
}

#endif
