; Static UI layout: each section is an element id.
; Keys: sprite (game struct path), x, y; optional: state_handler, draw_type.
; Position: integer or expression: chat_y, bind_x, bind_y, bind_bottom_x, bind_bottom_y.

[compass]
sprite=sprite_compass
x=550
y=4
state_handler=compass
draw_type=sprite_rotated

[invback]
sprite=sprite_invback
x=553
y=205

[backleft1]
sprite=sprite_backleft1
x=0
y=4

[backleft2]
sprite=sprite_backleft2
x=0
y=chat_y

[backright1]
sprite=sprite_backright1
x=722
y=4

[backright2]
sprite=sprite_backright2
x=743
y=205

[backtop1]
sprite=sprite_backtop1
x=0
y=0

[backvmid1]
sprite=sprite_backvmid1
x=516
y=4

[backvmid2]
sprite=sprite_backvmid2
x=516
y=205

[backvmid3]
sprite=sprite_backvmid3
x=496
y=chat_y

[backhmid2]
sprite=sprite_backhmid2
x=0
y=chat_y_m19

[mapback]
sprite=sprite_mapback
x=550
y=4

[backhmid1]
sprite=sprite_backhmid1
x=516
y=160

[tab_redstone_top]
sprite=sprite_redstone1
x=0
y=0
state_handler=tab_redstone_top

[sideicon0]
sprite=sprite_sideicons[0]
x=545
y=173

[sideicon1]
sprite=sprite_sideicons[1]
x=569
y=171

[sideicon2]
sprite=sprite_sideicons[2]
x=598
y=171

[sideicon3]
sprite=sprite_sideicons[3]
x=631
y=172

[sideicon4]
sprite=sprite_sideicons[4]
x=669
y=173

[sideicon5]
sprite=sprite_sideicons[5]
x=696
y=171

[sideicon6]
sprite=sprite_sideicons[6]
x=724
y=173

[backbase2]
sprite=sprite_backbase2
x=496
y=466

[tab_redstone_bottom]
sprite=sprite_redstone1v
x=0
y=0
state_handler=tab_redstone_bottom

[sideicon7]
sprite=sprite_sideicons[7]
x=570
y=468

[sideicon8]
sprite=sprite_sideicons[8]
x=598
y=469

[sideicon9]
sprite=sprite_sideicons[9]
x=633
y=470

[sideicon10]
sprite=sprite_sideicons[10]
x=670
y=468

[sideicon11]
sprite=sprite_sideicons[11]
x=697
y=468

[sideicon12]
sprite=sprite_sideicons[12]
x=722
y=468

[chatback]
sprite=sprite_chatback
x=17
y=chat_y