/*
 * Host tool: build a PaintersCullMap with painters_cullmap_build and emit a standalone .c file
 * with the packed visibility blob and a loader compatible with painters_cullmap_free.
 */

#include <errno.h>
#include <limits.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "graphics/shared_tables.h"

/* Resolves nested includes from src/osrs (projection.u.c, etc.). */
#include "../../src/osrs/painters_cullmap.u.c"

static void
usage(const char* argv0)
{
    fprintf(
        stderr,
        "usage: %s --radius R --near Z --width W --height H [--blob] [-o outpath]\n"
        "  Builds cullmap with painters_cullmap_build.\n"
        "  Default: C source (.c). With --blob: raw visibility bytes (.bin).\n"
        "  Default output: painters_cullmap_baked_r{R}_f{Z}_w{W}_h{H}.c or .bin\n",
        argv0);
}

static int
parse_int(const char* s, const char* name)
{
    char* end = NULL;
    long v = strtol(s, &end, 10);
    if( end == s || *end != '\0' || v < INT_MIN || v > INT_MAX )
    {
        fprintf(stderr, "gen_painters_cullmap: invalid integer for %s: %s\n", name, s);
        exit(1);
    }
    return (int)v;
}

static bool
streq(const char* a, const char* b)
{
    return strcmp(a, b) == 0;
}

static void
near_filename_part(
    char* buf,
    size_t cap,
    int ne)
{
    snprintf(buf, cap, "f%d", ne);
}

static void
suffix_ident(
    char* buf,
    size_t cap,
    int radius,
    int ne,
    int w,
    int h)
{
    char fpart[48];
    if( ne >= 0 )
        snprintf(fpart, sizeof fpart, "f%u", (unsigned)ne);
    else
        snprintf(fpart, sizeof fpart, "fm%u", (unsigned)(-ne));
    snprintf(
        buf,
        cap,
        "r%u_%s_w%u_h%u",
        (unsigned)radius,
        fpart,
        (unsigned)w,
        (unsigned)h);
}

static void
emit_c_file(
    FILE* f,
    const char* suffix,
    const struct PaintersCullMap* cm,
    int radius,
    int near_z,
    int width,
    int height)
{
    size_t nbits = (size_t)cm->pitch_levels * (size_t)cm->yaw_levels * (size_t)cm->grid_side *
                   (size_t)cm->grid_side;
    size_t nbytes = (nbits + 7u) / 8u;

    fprintf(f, "/*\n");
    fprintf(f, " * Auto-generated by gen_painters_cullmap — do not edit.\n");
    fprintf(f, " *\n");
    fprintf(f, " * Runtime params: radius=%d near_clip_z=%d width=%d height=%d\n", radius, near_z, width, height);
    fprintf(f, " * Derived: pitch_levels=%d yaw_levels=%d grid_side=%d nbytes=%zu\n",
        cm->pitch_levels, cm->yaw_levels, cm->grid_side, nbytes);
    fprintf(f, " *\n");
    fprintf(f, " * PCULL_* values used when the generator was built (must match game build):\n");
    fprintf(f, " *   PCULL_PITCH_MIN %d\n", PCULL_PITCH_MIN);
    fprintf(f, " *   PCULL_PITCH_MAX %d\n", PCULL_PITCH_MAX);
    fprintf(f, " *   PCULL_PITCH_STEP %d\n", PCULL_PITCH_STEP);
    fprintf(f, " *   PCULL_YAW_STEP %d\n", PCULL_YAW_STEP);
    fprintf(f, " *   PCULL_FRUSTUM_Y_START %d\n", PCULL_FRUSTUM_Y_START);
    fprintf(f, " *   PCULL_FRUSTUM_Y_END %d\n", PCULL_FRUSTUM_Y_END);
    fprintf(f, " *   PCULL_Y_STEP %d\n", PCULL_Y_STEP);
    fprintf(f, " *   PCULL_Y_GRANULARITY %d\n", PCULL_Y_GRANULARITY);
    fprintf(f, " */\n\n");

    fprintf(f, "#include <stdint.h>\n");
    fprintf(f, "#include <stdlib.h>\n");
    fprintf(f, "#include <string.h>\n\n");
    fprintf(f, "#include \"osrs/painters.h\"\n\n");
    fprintf(f, "/* Must match struct PaintersCullMap in painters_cullmap.u.c */\n");
    fprintf(f, "struct PaintersCullMap {\n");
    fprintf(f, "    uint8_t* visibility;\n");
    fprintf(f, "    int radius;\n");
    fprintf(f, "    int pitch_levels;\n");
    fprintf(f, "    int yaw_levels;\n");
    fprintf(f, "    int grid_side;\n");
    fprintf(f, "    int all_visible;\n");
    fprintf(f, "};\n\n");

    fprintf(f, "static const uint8_t painters_cullmap_baked_bytes_%s[] = {\n", suffix);
    for( size_t i = 0; i < nbytes; i++ )
    {
        if( i % 12u == 0u )
            fprintf(f, "    ");
        fprintf(f, "0x%02x", cm->visibility[i]);
        if( i + 1u < nbytes )
            fprintf(f, ",");
        if( i % 12u == 11u || i + 1u == nbytes )
            fprintf(f, "\n");
        else
            fprintf(f, " ");
    }
    fprintf(f, "};\n\n");

    fprintf(
        f,
        "struct PaintersCullMap*\n"
        "painters_cullmap_baked_open_%s(void)\n"
        "{\n"
        "    size_t nbytes = sizeof painters_cullmap_baked_bytes_%s;\n"
        "    uint8_t* vis = (uint8_t*)malloc(nbytes);\n"
        "    if( !vis )\n"
        "        return NULL;\n"
        "    memcpy(vis, painters_cullmap_baked_bytes_%s, nbytes);\n"
        "    struct PaintersCullMap* cm =\n"
        "        (struct PaintersCullMap*)malloc(sizeof(struct PaintersCullMap));\n"
        "    if( !cm )\n"
        "    {\n"
        "        free(vis);\n"
        "        return NULL;\n"
        "    }\n"
        "    cm->visibility = vis;\n"
        "    cm->radius = %d;\n"
        "    cm->pitch_levels = %d;\n"
        "    cm->yaw_levels = %d;\n"
        "    cm->grid_side = %d;\n"
        "    cm->all_visible = 0;\n"
        "    return cm;\n"
        "}\n",
        suffix,
        suffix,
        suffix,
        cm->radius,
        cm->pitch_levels,
        cm->yaw_levels,
        cm->grid_side);
}

static void
emit_blob_file(
    FILE* f,
    const struct PaintersCullMap* cm)
{
    size_t nbits = (size_t)cm->pitch_levels * (size_t)cm->yaw_levels * (size_t)cm->grid_side *
                   (size_t)cm->grid_side;
    size_t nbytes = (nbits + 7u) / 8u;
    if( fwrite(cm->visibility, 1, nbytes, f) != nbytes )
    {
        fprintf(stderr, "gen_painters_cullmap: short write (binary)\n");
        exit(1);
    }
}

int
main(int argc, char** argv)
{
    int radius = -1;
    int near_z = 0;
    bool have_near = false;
    int width = -1;
    int height = -1;
    const char* out_path = NULL;
    bool blob_mode = false;

    for( int i = 1; i < argc; i++ )
    {
        if( streq(argv[i], "-h") || streq(argv[i], "--help") )
        {
            usage(argv[0]);
            return 0;
        }
        if( streq(argv[i], "--radius") && i + 1 < argc )
        {
            radius = parse_int(argv[++i], "--radius");
            continue;
        }
        if( streq(argv[i], "--near") && i + 1 < argc )
        {
            near_z = parse_int(argv[++i], "--near");
            have_near = true;
            continue;
        }
        if( streq(argv[i], "--width") && i + 1 < argc )
        {
            width = parse_int(argv[++i], "--width");
            continue;
        }
        if( streq(argv[i], "--height") && i + 1 < argc )
        {
            height = parse_int(argv[++i], "--height");
            continue;
        }
        if( streq(argv[i], "-o") && i + 1 < argc )
        {
            out_path = argv[++i];
            continue;
        }
        if( streq(argv[i], "--blob") )
        {
            blob_mode = true;
            continue;
        }
        fprintf(stderr, "gen_painters_cullmap: unknown argument: %s\n", argv[i]);
        usage(argv[0]);
        return 1;
    }

    if( radius < 1 || !have_near || width < 1 || height < 1 )
    {
        fprintf(stderr, "gen_painters_cullmap: --radius, --near, --width, --height are required.\n");
        usage(argv[0]);
        return 1;
    }

    init_sin_table();
    init_cos_table();
    init_tan_table();

    struct PaintersCullMap* cm = painters_cullmap_build(radius, near_z, width, height);
    if( !cm )
    {
        fprintf(stderr, "gen_painters_cullmap: painters_cullmap_build failed\n");
        return 1;
    }

    char fpart[64];
    near_filename_part(fpart, sizeof fpart, near_z);
    char defname[256];
    snprintf(
        defname,
        sizeof defname,
        "painters_cullmap_baked_r%u_%s_w%u_h%u.%s",
        (unsigned)radius,
        fpart,
        (unsigned)width,
        (unsigned)height,
        blob_mode ? "bin" : "c");

    char suffix[160];
    suffix_ident(suffix, sizeof suffix, radius, near_z, width, height);

    const char* path = out_path ? out_path : defname;
    FILE* f = fopen(path, blob_mode ? "wb" : "w");
    if( !f )
    {
        fprintf(stderr, "gen_painters_cullmap: fopen %s: %s\n", path, strerror(errno));
        painters_cullmap_free(cm);
        return 1;
    }

    if( blob_mode )
        emit_blob_file(f, cm);
    else
        emit_c_file(f, suffix, cm, radius, near_z, width, height);
    fclose(f);
    painters_cullmap_free(cm);

    fprintf(stderr, "gen_painters_cullmap: wrote %s\n", path);
    return 0;
}
