-- Generated by tools/quest_gate/new_quest.py from Quest Helper's
-- helpers/quests/taibwowannaitrio/ -- docs/QUEST_SUITE_KIT.md phase 3.
-- UNREVIEWED: every '-- CHECK' marker below needs a human or a later
-- phase to confirm against a live run before this counts as a passing
-- quest test. Tier (quest_inventory.tsv): 3.
-- Items from getItemRequirements(): 0 given in setup (::give), 0 left as '-- CHECK gather' markers (Quest Helper canBeObtainedDuringQuest()).
-- Setup always starts with ::clearinv: the fresh character carries fourteen
-- slots of tutorial kit that block a non-stackable requirement fitting in the backpack.
-- Rewards from Quest Helper: 4 experience, 1 item, quest points 2 (QuestPointReward).
--
-- Fixture start: fresh_lumbridge.ini stands the player at 3206,3233,0 (Lumbridge, beside
-- Hans). Every step below carries its own Quest Helper WorldPoint; the
-- FIRST emitted t.player.goto_tile is what actually leaves that tile.
--
-- Three rules the first pilot pass broke -- read before touching this file:
-- (a) "blocked" means a t.blocked("...") row followed by return -- a file
--     that runs on to expect_complete() after a failure is rejected.
-- (b) a talk_to/click answering screen_position or not_visible means you
--     are not standing near the target -- fix the goto, not the verb.
-- (c) never add a fixture or a helper file -- this quest file is the only
--     file you edit.

return {
    id = "tbwt",
    fixture = "fresh_lumbridge.ini",
    setup = {
        "::clearinv", -- the fixture's fourteen tutorial slots, so a requirement fits
        "::setlevel firemaking 30",
        "::setlevel agility 15",
        "::setlevel cooking 30",
        "::setlevel fishing 5", -- fishing_spots/tbwt.rs2:fish_karambwanji needs 5 to net karambwanji
        "::complete quest_junglepotion", -- guide requirement: Jungle Potion complete (tbwt_timfraku.rs2 gate)
        "::give net 1", -- guide item: small fishing net (fishKarambwaji)
        "::give coins 500", -- guide item: coins for Zembo's Karamjan rum (getRum)
    },
    bind = {
        varp = "varp320_tbwt_main",
        constants = {
            not_started = 0,
            spoke_to_timfraku = 1,
            asked_for_help = 2,
            started = 3,
            complete = 6,
        },
        row = "quest_taibwowannaitrio",
        display = "Tai Bwo Wannai Trio",
        points = 2,
    },

    legs = {
        { name = "timfraku_to_rum", run = function(t)
            -- LEG 1 BEGIN: goToTimfrakuLadder
            t.ticks(3) -- a setup cheat's effect is not client-side yet
            t.expect("quest.stage.not_started", t.quest.expect_stage("not_started"))

            t.exec("goto-goToTimfrakuLadder", t.player.goto_tile, 2781, 3089, 0)
            t.exec("goToTimfrakuLadder", t.player.click_loc, "ladder", 1)
            t.ticks(4)
            local _, up_level = t.world.level()
            t.check("goToTimfrakuLadder.level", up_level == 1, "after the ladder the player is on level " .. tostring(up_level))

            t.exec("talkToTimfrakuStart", t.player.talk_to, "tbwt_timfraku", 1)
            t.exec("talkToTimfrakuStart-dialog", t.chat.play, {
                "npc:I am the Chief of Tai Bwo Wann",
                "choose:I am a roving adventurer.",
                "player:I am a roving adventurer",
                "npc:Well then adventurer",
                "choose:Trufitus sent me.",
                "player:Trufitus sent me",
                "npc:Trufitus Shakaya",
                "player:Trufitus has communed",
                "npc:Bwana, do you speak",
                "player:Yes, I helped",
                "npc:Then it must be true",
            })
            -- tbwt_timfraku.rs2 closes the dialogue (if_close), mes() + p_delay(4), then reopens it
            t.ticks(6)
            t.exec("talkToTimfrakuStart-dialog2", t.chat.play, {
                "npc:I cannot thank you",
                "choose:Your gratitude is all I deserve.",
                "player:Your gratitude",
                "npc:No, Bwana",
                "npc:I now ask you",
                "player:And what is that",
                "npc:I ask you to deliver",
                "choose:Yes",
                "player:Ok, I'll do it.",
                "npc:Thank you very much",
                "player:If I succeed",
                "npc:We shall see",
            })
            t.ticks(2)
            t.expect("quest.stage.started", t.quest.expect_stage("started"))

            local jr, jd = t.ui.journal_open("Tai Bwo Wannai Trio")
            t.check("syncStep", jr == "ok", "quest journal opened: " .. tostring(jd))
            t.ui.journal_close()

            t.exec("goto-fishKarambwaji", t.player.goto_tile, 2791, 3019, 0)
            t.exec("fishKarambwaji", t.player.press, "0_43_47_karambwanji", 1, 200)
            local fr, fd = t.inv.await("tbwt_raw_karambwanji", 23, 400)
            t.check("fishKarambwaji.caught", fr == "ok", "raw karambwanji in the backpack: " .. tostring(fd))

            -- goToLubufu: tbwt_lubufu.rs2 -- first talk is the whippersnapper brush-off (var 0 -> intro),
            -- then the ask-twice-what-he-does chain (-> offered_to_help -> fetch_karambwanji).
            t.exec("goto-goToLubufu", t.player.goto_tile, 2771, 3169, 0)
            t.exec("goToLubufu-brushoff", t.player.talk_to, "tbwt_lubufu", 1)
            t.exec("goToLubufu-brushoff-dialog", t.chat.play, {
                "npc:Watch where you're going",
                "choose:I wasn't going anywhere...",
                "player:I wasn't going anywhere",
                "npc:Well then go away",
            })
            t.ticks(2)
            local _, lub = t.var.server("varp6052_tbwt_lubufu")
            t.check("goToLubufu-brushoff.var", lub == 1, "varp6052_tbwt_lubufu = " .. tostring(lub) .. " (intro)")
            t.exec("goToLubufu-ask", t.player.talk_to, "tbwt_lubufu", 1)
            t.exec("goToLubufu-ask-dialog", t.chat.play, {
                "npc:You again!",
                "player:You did.",
                "npc:So I see.",
                "choose:Talk about him...",
                "choose:What do you do?",
                "player:What do you do?",
                "npc:Nowadays I mostly",
                "choose:What do you use for bait?",
                "player:What do you use for bait?",
                "npc:That is part of the secret",
                "choose:Talk about him...",
                "choose:What do you do?",
                "player:What do you do?",
                "npc:Nowadays I mostly",
                "choose:I could help collect the bait.",
                "player:I could help collect the bait.",
                "npc:And why would you help me?",
                "choose:You sound like you could do with the help.",
                "player:You sound like you could do",
                "npc:Well perhaps you're right",
                "npc:I have a fair amount of bait",
                "player:Ok. Where can I find the bait?",
                "npc:Patience.",
                "npc:You must therefore",
                "player:I understand.",
                "npc:Very well.",
                "npc:Karambwanji congregate",
                "player:Where is the Holy Lake?",
                "npc:Just to the south",
                "player:And what do I use",
                "npc:Any small net will do",
            })
            t.ticks(2)
            _, lub = t.var.server("varp6052_tbwt_lubufu")
            t.check("goToLubufu-ask.var", lub == 5, "varp6052_tbwt_lubufu = " .. tostring(lub) .. " (fetch_karambwanji)")

            t.exec("goToLubufu-give", t.player.talk_to, "tbwt_lubufu", 1)
            t.exec("goToLubufu-give-dialog", t.chat.play, {
                "npc:Have you retrieved the Karambwanji yet?",
                "player:Yes, I have some here.",
                "mesbox:You hand Lubufu 20 raw Karambwanji.",
                "npc:Thank you! This should tide me over",
            })
            t.ticks(2)
            _, lub = t.var.server("varp6052_tbwt_lubufu")
            t.check("goToLubufu-give.var", lub == 25, "varp6052_tbwt_lubufu = " .. tostring(lub) .. " (given_karambwanji), raw karambwanji left: " .. tostring(select(2, t.inv.count("tbwt_raw_karambwanji"))))

            -- getMoreVessel (tbwt_lubufu.rs2 given_karambwanji_ops): three of the four questions each add
            -- one to the lubufu var (25 -> 28); the third makes him offer the apprenticeship + a vessel.
            t.exec("getMoreVessel-q1", t.player.talk_to, "tbwt_lubufu", 1)
            t.exec("getMoreVessel-q1-dialog", t.chat.play, {
                "choose:What is a Karambwan?",
                "player:What is a Karambwan?",
                "npc:A species of octopus",
                "npc:You should really",
            })
            t.exec("getMoreVessel-q2", t.player.talk_to, "tbwt_lubufu", 1)
            t.exec("getMoreVessel-q2-dialog", t.chat.play, {
                "choose:What do you do with your Karambwan?",
                "player:What do you do with your Karambwan?",
                "npc:I eat what I need",
                "npc:Before you ask",
            })
            t.exec("getMoreVessel-q3", t.player.talk_to, "tbwt_lubufu", 1)
            t.exec("getMoreVessel-q3-dialog", t.chat.play, {
                "choose:What do you use to catch Karambwan?",
                "player:What do you use to catch Karambwan?",
                "npc:Well ... since you ask",
                "npc:My, you're keen",
            })
            t.ticks(4) -- mes() + p_delay(2) before the offer
            t.exec("getMoreVessel-apprentice-dialog", t.chat.play, {
                "npc:How would you feel about becoming my apprentice?",
                "player:That's a slight change",
                "npc:As much as I need",
                "npc:You seem a trustworthy",
                "choose:Yes!",
                "player:Yes!",
                "npc:I'm glad to hear it",
                "mesbox:Lubufu teaches you a new fishing technique.",
                "npc:In our language",
                "npc:There are two aspects",
                "npc:You already know",
                "player:But what kind of equipment",
                "npc:It is futile",
                "npc:I have spent many years",
                "npc:If this vessel is loaded",
                "npc:I will now give you",
                "player:Yes, I understand.",
                "mesbox:Lubufu hands you a Karambwan vessel.",
                "npc:Feel free to practise",
            })
            t.ticks(2)
            _, lub = t.var.server("varp6052_tbwt_lubufu")
            t.check("getMoreVessel-apprentice.var", lub == 31, "varp6052_tbwt_lubufu = " .. tostring(lub) .. " (complete: apprentice)")
            t.exec("getMoreVessel-first", t.inv.expect_has, "tbwt_karambwan_vessel", 1)

            -- dropVessel: drop the vessel so the lost-vessel option appears, then ask for another.
            t.exec("dropVessel", t.player.drop, "tbwt_karambwan_vessel")
            t.ticks(2)
            t.exec("getAnotherVessel", t.player.talk_to, "tbwt_lubufu", 1)
            t.exec("getAnotherVessel-dialog", t.chat.play, {
                "npc:How fares my apprentice?",
                "choose:Actually, I've lost my Karambwan vessel.",
                "player:Actually, I've lost",
                "npc:You did what",
                "player:Don't worry",
                "choose:... a shark ate it!",
                "player:... a shark ate it!",
                "npc:Well you'd better hope",
                "npc:In the meantime",
                "mesbox:Lubufu hands you a Karambwan vessel.",
                "player:Thank you so much.",
                "npc:Don't mention it",
            })
            t.ticks(2)
            t.exec("pickupVessel", t.player.click_obj, "tbwt_karambwan_vessel", 3)
            t.ticks(2)
            local _, vessels = t.inv.count("tbwt_karambwan_vessel")
            t.check("getMoreVessel", vessels == 2, "karambwan vessels in the backpack: " .. tostring(vessels))

            -- fillVessel: tbwt_load_karambwan_vessel (quest_tbwt.rs2:96) swaps vessel + karambwanji for a loaded vessel
            t.exec("fillVessel", t.player.use_item_on_item, "tbwt_raw_karambwanji", "tbwt_karambwan_vessel")
            t.ticks(2)
            t.exec("fillVessel.loaded", t.inv.expect_has, "tbwt_karambwan_vessel_loaded_with_karambwanji", 1)

            -- getRum: Zembo, Musa Point
            t.exec("goto-getRum", t.player.goto_tile, 2925, 3143, 0)
            local zr, zd = t.npc.nearest("zembo", 15)
            t.check("getRum.zembo", zr == "not_found" or zr == "no_row", "zembo lookup within 15 tiles of Musa Point 2925,3143: " .. tostring(zr) .. " " .. tostring(zd))
            t.blocked("content_bug: Zembo (the Karamjan rum seller, guide step getRum, 2925,3143) has no placement and no shop: areas/world/configs/m45_49.spawn (Musa Point, 16 npcs) has no zembo row, no .spawn/.rs2/.inv anywhere under OSRS-Content/osrs239-content/server/scripts mentions zembo, and karamja_rum is referenced only by quests/quest_tbwt/scripts/quest_tbwt.rs2:188; the rum cannot be bought, so makeBananaRum (leg 2) is unreachable")
            return
        end },
    },
}
