#ifndef BUILDCACHE_LUA_C_H
#define BUILDCACHE_LUA_C_H

enum LuaBuildCacheFunctionNo
{
    FUNC_LOAD_ARCHIVE = 1,
    FUNC_STORE_CONTAINER_JAGFILE = 2,
    FUNC_STORE_CONTAINER_JAGFILEPACK = 4,
    FUNC_STORE_CONTAINER_JAGFILEPACK_INDEXED = 5,
    FUNC_STORE_CONTAINER_JAGFILEPACK_FROM_JAGFILE = 6,
    FUNC_STORE_CONTAINER_JAGFILEPACK_INDEXED_FROM_JAGFILE = 7,
    FUNC_STORE_DATA_RAW = 8,
    FUNC_STORE_DATA_FROM_CONTAINER_WITH_ID = 9,
    FUNC_STORE_DATA_FROM_CONTAINER_WITH_IDS = 10,
    FUNC_STORE_DATA_FROM_CONTAINER_WITH_NAME = 11,
    FUNC_STORE_DATA_FROM_CONTAINER_ALL = 12,
    FUNC_HAS_DATA = 13,
    FUNC_HAS_CONT = 14,
    FUNC_LIST_IDS = 15,
    FUNC_LIST_FIELD = 16,
    FUNC_LOAD_ARCHIVES = 17,
};

#endif