-- Stable versioned packet type identifiers.
--
-- Values mirror enum ServerProt in src/osrs/core/serverprot.h.
-- The protocol itself has no version; each individual packet type carries
-- its own version suffix (_v1, _v2, ...).  If a future revision changes the
-- wire layout of a packet a new _v2 entry is added here and in the C header
-- while the existing _v1 entry remains unchanged.
--
-- These are NOT wire opcodes.  Wire opcodes change revision to revision and
-- are only visible inside serverprot_netrev*_parse.c.

return {
    REBUILD_NORMAL_V1               =  1,
    NPC_INFO_V1                     =  2,
    PLAYER_INFO_V1                  =  3,
    UPDATE_INV_FULL_V1              =  4,
    UPDATE_INV_PARTIAL_V1           =  5,
    UPDATE_INV_STOP_TRANSMIT_V1     =  6,
    IF_SETTAB_V1                    =  7,
    IF_SETTAB_ACTIVE_V1             =  8,
    IF_SETCOLOUR_V1                 =  9,
    IF_SETHIDE_V1                   = 10,
    IF_SETOBJECT_V1                 = 11,
    IF_SETMODEL_V1                  = 12,
    IF_SETANIM_V1                   = 13,
    IF_SETPLAYERHEAD_V1             = 14,
    IF_SETTEXT_V1                   = 15,
    IF_SETNPCHEAD_V1                = 16,
    IF_SETPOSITION_V1               = 17,
    IF_SETSCROLLPOS_V1              = 18,
    IF_OPENCHAT_V1                  = 19,
    IF_OPENMAIN_V1                  = 20,
    IF_OPENSIDE_V1                  = 21,
    IF_OPENMAIN_SIDE_V1             = 22,
    IF_CLOSE_V1                     = 23,
    CAM_LOOKAT_V1                   = 24,
    CAM_MOVETO_V1                   = 25,
    CAM_SHAKE_V1                    = 26,
    CAM_RESET_V1                    = 27,
    VARP_SMALL_V1                   = 28,
    VARP_LARGE_V1                   = 29,
    VARP_SYNC_V1                    = 30,
    UPDATE_ZONE_PARTIAL_FOLLOWS_V1  = 31,
    UPDATE_ZONE_FULL_FOLLOWS_V1     = 32,
    UPDATE_ZONE_PARTIAL_ENCLOSED_V1 = 33,
    LOC_ADD_CHANGE_V1               = 34,
    LOC_DEL_V1                      = 35,
    LOC_ANIM_V1                     = 36,
    LOC_MERGE_V1                    = 37,
    OBJ_ADD_V1                      = 38,
    OBJ_DEL_V1                      = 39,
    OBJ_REVEAL_V1                   = 40,
    OBJ_COUNT_V1                    = 41,
    MAP_ANIM_V1                     = 42,
    MAP_PROJANIM_V1                 = 43,
    UNSET_MAP_FLAG_V1               = 44,
    UPDATE_RUNWEIGHT_V1             = 45,
    UPDATE_RUNENERGY_V1             = 46,
    UPDATE_STAT_V1                  = 47,
    HINT_ARROW_V1                   = 48,
    RESET_ANIMS_V1                  = 49,
    UPDATE_PID_V1                   = 50,
    SET_MULTIWAY_V1                 = 51,
    SET_PLAYER_OP_V1                = 52,
    MESSAGE_GAME_V1                 = 53,
    MESSAGE_PRIVATE_V1              = 54,
    CHAT_FILTER_SETTINGS_V1         = 55,
    TUT_FLASH_V1                    = 56,
    TUT_OPEN_V1                     = 57,
    LOGOUT_V1                       = 58,
    P_COUNTDIALOG_V1                = 59,
    UPDATE_REBOOT_TIMER_V1          = 60,
    UPDATE_FRIENDLIST_V1            = 61,
    UPDATE_IGNORELIST_V1            = 62,
    SYNTH_SOUND_V1                  = 63,
    MIDI_SONG_V1                    = 64,
    MIDI_JINGLE_V1                  = 65,
    FINISH_TRACKING_V1              = 66,
    ENABLE_TRACKING_V1              = 67,
    LAST_LOGIN_INFO_V1              = 68,
}
