/*
 * Resolving the engine's ids out of the content tree.
 *
 * One table, read top to bottom. The point of keeping it in a single file is
 * that it is the complete list: if a number the engine sends is not derived
 * from something the player did, it is one of these, and it is here beside the
 * name the cache knows it by.
 */

#include "mock230_ids.h"

#include "mock230_content.h"

#include <stdio.h>

static struct Mock230Ids g_ids;

const struct Mock230Ids*
mock230_ids(void)
{
    return &g_ids;
}

/* Written out rather than generated by a macro so that grepping for a symbol
 * name finds both the pack line and the field it lands in.
 *
 * At file scope so `mock230_ids_symbols` can hand it to the pin writer. These
 * are the only names in the whole system that no content file mentions — the
 * engine addresses them from C — so a symbol closure computed by reading
 * `server/` as text would miss every one, and they are exactly the ones a cache
 * bump is most likely to move. */
static const struct Mock230SymbolRef k_refs[] = {
        { MOCK230_PACK_INTERFACE, "toplevel_osrs_stretch", &g_ids.iface_gameframe },
        { MOCK230_PACK_INTERFACE, "toplevel", &g_ids.iface_toplevel },
        { MOCK230_PACK_INTERFACE, "toplevel_pre_eoc", &g_ids.iface_toplevel_pre_eoc },
        { MOCK230_PACK_INTERFACE, "inventory", &g_ids.iface_inventory },
        { MOCK230_PACK_INTERFACE, "wornitems", &g_ids.iface_wornitems },
        { MOCK230_PACK_INTERFACE, "bankmain", &g_ids.iface_bankmain },
        { MOCK230_PACK_INTERFACE, "bankside", &g_ids.iface_bankside },
        { MOCK230_PACK_INTERFACE, "equipment", &g_ids.iface_equipment_stats },
        { MOCK230_PACK_INTERFACE, "equipment_side", &g_ids.iface_equipment_stats_side },
        { MOCK230_PACK_INTERFACE, "prayerbook", &g_ids.iface_prayerbook },
        { MOCK230_PACK_INTERFACE, "worldmap", &g_ids.iface_worldmap },

        { MOCK230_PACK_INV, "inv", &g_ids.inv_backpack },
        { MOCK230_PACK_INV, "worn", &g_ids.inv_worn },
        { MOCK230_PACK_INV, "bank", &g_ids.inv_bank },
        { MOCK230_PACK_INV, "collection_transmit", &g_ids.inv_collection_log },
        /* The standard-health family, one per footprint band. The BAND is the
         * engine's convention (`healthbar_for_size`); the NAMES are the
         * cache's, so the mapping is readable at both ends. */
        { MOCK230_PACK_HEALTHBAR, "healthbar_standard_30", &g_ids.healthbar_standard },
        { MOCK230_PACK_HEALTHBAR, "healthbar_standard_60", &g_ids.healthbar_size4 },
        { MOCK230_PACK_HEALTHBAR, "healthbar_standard_80", &g_ids.healthbar_size5 },
        { MOCK230_PACK_HEALTHBAR, "healthbar_standard_120", &g_ids.healthbar_size67 },
        { MOCK230_PACK_HEALTHBAR, "healthbar_standard_160", &g_ids.healthbar_size89 },

        { MOCK230_PACK_ENUM, "worn_slots", &g_ids.enum_worn_slots },

        { MOCK230_PACK_COMPONENT, "toplevel_osrs_stretch:mainmodal", &g_ids.com_gameframe_mainmodal },
        { MOCK230_PACK_COMPONENT, "toplevel_osrs_stretch:sidemodal", &g_ids.com_gameframe_sidemodal },
        { MOCK230_PACK_COMPONENT, "toplevel_osrs_stretch:floater", &g_ids.com_gameframe_floater },
        { MOCK230_PACK_COMPONENT, "chatbox:chatmodal", &g_ids.com_chatbox_modal },
        { MOCK230_PACK_COMPONENT, "music:now_playing_text",
          &g_ids.com_music_now_playing_text },
        { MOCK230_PACK_COMPONENT, "worldmap:esckey", &g_ids.com_worldmap_esckey },
        { MOCK230_PACK_COMPONENT, "worldmap:close", &g_ids.com_worldmap_close },
        { MOCK230_PACK_COMPONENT, "inventory:items", &g_ids.com_inventory_items },
        { MOCK230_PACK_COMPONENT, "wornitems:equipment", &g_ids.com_worn_equipment_stats },

        { MOCK230_PACK_COMPONENT, "bankmain:items", &g_ids.com_bankmain_items },
        { MOCK230_PACK_COMPONENT, "bankmain:capacity", &g_ids.com_bankmain_capacity },
        { MOCK230_PACK_COMPONENT, "bankmain:tabs", &g_ids.com_bankmain_tabs },
        { MOCK230_PACK_COMPONENT, "bankmain:swap_insert", &g_ids.com_bankmain_swap_insert },
        { MOCK230_PACK_COMPONENT, "bankmain:note", &g_ids.com_bankmain_note },
        { MOCK230_PACK_COMPONENT, "bankmain:quantity1", &g_ids.com_bankmain_qty_1 },
        { MOCK230_PACK_COMPONENT, "bankmain:quantity5", &g_ids.com_bankmain_qty_5 },
        { MOCK230_PACK_COMPONENT, "bankmain:quantity10", &g_ids.com_bankmain_qty_10 },
        { MOCK230_PACK_COMPONENT, "bankmain:quantityx", &g_ids.com_bankmain_qty_x },
        { MOCK230_PACK_COMPONENT, "bankmain:quantityall", &g_ids.com_bankmain_qty_all },
        { MOCK230_PACK_COMPONENT, "bankmain:depositinv", &g_ids.com_bankmain_deposit_inv },
        { MOCK230_PACK_COMPONENT, "bankmain:depositworn", &g_ids.com_bankmain_deposit_worn },
        { MOCK230_PACK_COMPONENT, "bankside:items", &g_ids.com_bankside_items },

        { MOCK230_PACK_COMPONENT, "equipment:universe",
          &g_ids.com_equipment_stats_container },
        { MOCK230_PACK_COMPONENT, "equipment:stabatt",
          &g_ids.com_equipment_stats_stabatt },
        { MOCK230_PACK_COMPONENT, "equipment:slashatt",
          &g_ids.com_equipment_stats_slashatt },
        { MOCK230_PACK_COMPONENT, "equipment:crushatt",
          &g_ids.com_equipment_stats_crushatt },
        { MOCK230_PACK_COMPONENT, "equipment:magicatt",
          &g_ids.com_equipment_stats_magicatt },
        { MOCK230_PACK_COMPONENT, "equipment:rangeatt",
          &g_ids.com_equipment_stats_rangeatt },
        { MOCK230_PACK_COMPONENT, "equipment:stabdef",
          &g_ids.com_equipment_stats_stabdef },
        { MOCK230_PACK_COMPONENT, "equipment:slashdef",
          &g_ids.com_equipment_stats_slashdef },
        { MOCK230_PACK_COMPONENT, "equipment:crushdef",
          &g_ids.com_equipment_stats_crushdef },
        { MOCK230_PACK_COMPONENT, "equipment:magicdef",
          &g_ids.com_equipment_stats_magicdef },
        { MOCK230_PACK_COMPONENT, "equipment:rangedef",
          &g_ids.com_equipment_stats_rangedef },
        { MOCK230_PACK_COMPONENT, "equipment:meleestrength",
          &g_ids.com_equipment_stats_meleestrength },
        { MOCK230_PACK_COMPONENT, "equipment:rangestrength",
          &g_ids.com_equipment_stats_rangestrength },
        { MOCK230_PACK_COMPONENT, "equipment:magicdamage",
          &g_ids.com_equipment_stats_magicdamage },
        { MOCK230_PACK_COMPONENT, "equipment:prayer",
          &g_ids.com_equipment_stats_prayer },
        { MOCK230_PACK_COMPONENT, "equipment:typemultiplier",
          &g_ids.com_equipment_stats_typemultiplier },
        { MOCK230_PACK_COMPONENT, "equipment:slayermultiplier",
          &g_ids.com_equipment_stats_slayermultiplier },
        { MOCK230_PACK_COMPONENT, "equipment:attackspeedbase",
          &g_ids.com_equipment_stats_attackspeedbase },
        { MOCK230_PACK_COMPONENT, "equipment:attackspeedactual",
          &g_ids.com_equipment_stats_attackspeedactual },

        { MOCK230_PACK_VARBIT, "bank_withdrawnotes", &g_ids.varbit_bank_withdrawnotes },
        { MOCK230_PACK_VARBIT, "bank_insertmode", &g_ids.varbit_bank_insertmode },
        { MOCK230_PACK_VARBIT, "bank_requestedquantity",
          &g_ids.varbit_bank_requestedquantity },
        { MOCK230_PACK_VARBIT, "bank_quantity_type", &g_ids.varbit_bank_quantity_type },
        { MOCK230_PACK_VARBIT, "bank_currenttab", &g_ids.varbit_bank_currenttab },
        { MOCK230_PACK_VARBIT, "bank_tab_display", &g_ids.varbit_bank_tab_display },
        { MOCK230_PACK_VARBIT, "bank_leaveplaceholders",
          &g_ids.varbit_bank_leaveplaceholders },
        { MOCK230_PACK_VARBIT, "bank_showincinerator", &g_ids.varbit_bank_showincinerator },
        { MOCK230_PACK_VARBIT, "bank_hidedepositworn", &g_ids.varbit_bank_hidedepositworn },
        { MOCK230_PACK_VARBIT, "bank_side_slot_ignoreinvlocks", &g_ids.varbit_bank_side_slot_ignore },
        { MOCK230_PACK_VARBIT, "stamina_active", &g_ids.varbit_stamina_active },
};

const struct Mock230SymbolRef*
mock230_ids_symbols(int* out_count)
{
    *out_count = (int)(sizeof(k_refs) / sizeof(k_refs[0]));
    return k_refs;
}

int
mock230_ids_resolve(void)
{
    static const struct
    {
        const char* name;
        int* out;
    } k_constants[] = {
        { "bank_qty_1", &g_ids.bank_qty_1 },     { "bank_qty_5", &g_ids.bank_qty_5 },
        { "bank_qty_10", &g_ids.bank_qty_10 },   { "bank_qty_x", &g_ids.bank_qty_x },
        { "bank_qty_all", &g_ids.bank_qty_all },
        { "lootdrop_duration", &g_ids.lootdrop_duration },
    };
    int failed;

    failed = mock230_content_resolve("ids", k_refs, (int)(sizeof(k_refs) / sizeof(k_refs[0])));

    for( size_t i = 0; i < sizeof(k_constants) / sizeof(k_constants[0]); i++ )
    {
        /* -1 rather than 0 for a missing one: a quantity mode of 0 is
         * "withdraw 1", so the fallback would be a working bank with the wrong
         * button lit. mock230_content_constant_int does the reporting. */
        *k_constants[i].out = mock230_content_constant_int(k_constants[i].name, -1);
        if( *k_constants[i].out < 0 )
            failed++;
    }

    if( failed )
        fprintf(stderr,
                "mock230: %d id(s) did not resolve — the content tree and the packs "
                "disagree\n",
                failed);
    return failed;
}
