/*
 * cache.gen.ts — the cache, as TypeScript constants.
 *
 * This is the half of "integrated with the cache" that shows up while writing a
 * component: `sprites.orb_run_on` autocompletes, and a sprite that is not in the
 * tree is a type error rather than a wrong number that renders as nothing. Names
 * and ids both come from the content tree's own pack files, which are the same
 * authority cachepack uses, so the bindings cannot drift from what a bake will
 * produce — and because the tree is read rather than a built cache, an asset added
 * this morning is already here.
 *
 * Names are normalised only where TypeScript forces it: an identifier cannot start
 * with a digit, so `2x_standard_spells_on_0` is reachable as `sprites["2x_..."]`
 * through the index signature and gets no dotted alias.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

import { readCompack, readNamedConfig } from './build.js';

/** Which pack file feeds which exported table. */
const PACKS = [
    { export: 'sprites', pack: 'pack/8_sprites.pack', what: 'sprite ids' },
    { export: 'fonts', pack: 'pack/13_fonts.pack', what: 'font ids' },
    { export: 'models', pack: 'pack/7_models.pack', what: 'model ids' },
    { export: 'interfaces', pack: 'pack/3_interfaces.pack', what: 'interface ids' },
    { export: 'scripts', pack: 'pack/12_clientscripts.pack', what: 'clientscript ids' },
];

const CONFIGS = [
    { export: 'varps', compack: 'configs/all.varp.compack', what: 'server variables' },
    { export: 'varbits', compack: 'configs/all.varbit.compack', what: 'packed variable fields' },
    { export: 'varcs', compack: 'configs/all.varc.compack', what: 'client variables' },
    { export: 'invs', compack: 'configs/all.inv.compack', what: 'inventories' },
    { export: 'objs', compack: 'configs/all.obj.compack', what: 'items' },
    { export: 'seqs', compack: 'configs/all.seq.compack', what: 'animations' },
    { export: 'enums', compack: 'configs/all.enum.compack', what: 'enums' },
];

/** The stats, which the cache does not name — this order is the client's. */
const STATS = [
    'attack', 'defence', 'strength', 'hitpoints', 'ranged', 'prayer', 'magic', 'cooking',
    'woodcutting', 'fletching', 'fishing', 'firemaking', 'crafting', 'smithing', 'mining',
    'herblore', 'agility', 'thieving', 'slayer', 'farming', 'runecraft', 'hunter',
    'construction',
];

/**
 * What a build generates unless the project says otherwise.
 *
 * Everything the cache names would be 160,000 lines, most of it models and items
 * that a component never mentions — and a file that size is a slow type-check on
 * every keystroke. So the default is the tables a component actually reaches for,
 * and `"cachegen"` in cs2dom.json widens it: `["sprites", "fonts", "objs", ...]`,
 * or `["all"]` for the lot.
 */
export const DEFAULT_TABLES =
    ['sprites', 'fonts', 'interfaces', 'varps', 'varbits', 'varcs', 'invs', 'stats'];

export const ALL_TABLES =
    [...PACKS.map((p) => p.export), ...CONFIGS.map((c) => c.export), 'stats'];

export function generate(contentDir, tables = DEFAULT_TABLES) {
    const wanted = new Set(tables.includes('all') ? ALL_TABLES : tables);
    const sections = [];

    for( const source of PACKS ) {
        if( !wanted.has(source.export) ) continue;
        const path = join(contentDir, source.pack);
        sections.push(table(source.export, source.what, existsSync(path) ? readCompack(path) : new Map()));
    }
    for( const source of CONFIGS ) {
        if( !wanted.has(source.export) ) continue;
        const path = join(contentDir, source.compack);
        sections.push(table(source.export, source.what, existsSync(path) ? readCompack(path) : new Map()));
    }

    if( wanted.has('stats') ) {
        const stats = new Map(STATS.map((name, id) => [name, id]));
        sections.push(table('stats', 'skills, in client order', stats));
    }

    /* The varbit -> varp mapping, so useVarbit can find the trigger to bind to. */
    if( wanted.has('varbits') ) {
        const varbitVarp = varbitVarps(contentDir);
        sections.push(
            `/** Which varp each varbit is packed into — the transmit a varbit binds to. */\n` +
            `export const varbitVarp: Record<number, number> = ${JSON.stringify(varbitVarp)};\n`);
    }

    return (
        `/*\n` +
        ` * Generated by cs2dom from the content tree. Do not edit.\n` +
        ` * Rebuild with: node tools/cs2dom/bin/cs2dom.js cachegen\n` +
        ` */\n\n` +
        sections.join('\n')
    );
}

function table(name, what, entries) {
    const lines = [`/** ${what[0].toUpperCase()}${what.slice(1)}, by name. */`];
    lines.push(`export const ${name} = {`);
    for( const [entryName, id] of [...entries].sort((a, b) => a[1] - b[1]) )
        lines.push(`    ${key(entryName)}: ${id},`);
    lines.push(`} as const;`);
    return lines.join('\n') + '\n';
}

function key(name) {
    return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function varbitVarps(contentDir) {
    const varbits = readNamedConfig(join(contentDir, 'configs', 'all.varbit'));
    const varbitIds = readCompack(join(contentDir, 'configs', 'all.varbit.compack'));
    const varpIds = readCompack(join(contentDir, 'configs', 'all.varp.compack'));
    const out = {};
    for( const [name, fields] of varbits ) {
        const id = varbitIds.get(name);
        const varp = varpIds.get(fields.basevar);
        if( id !== undefined && varp !== undefined ) out[id] = varp;
    }
    return out;
}

export function writeCacheGen(contentDir, outPath) {
    writeFileSync(outPath, generate(contentDir));
    return outPath;
}
