/*
 * Writing the interface: one `.if` of `[block]`s and the `.compack` beside it.
 *
 * The format is cachepack's, exactly — `interfaces/<name>.if` is read by
 * `interface_read` in tools/cachepack/cp_decode.c and encoded with
 * RSCache_Dat2ComponentEncodeIf3, which is the same encoder that round-trips all
 * 968 of osrs239's interfaces byte for byte. Nothing here is a private
 * intermediate: the output sits in the content tree beside hand-authored
 * interfaces and bakes the same way.
 *
 * The `.compack` is not optional and not derivable. It maps block name to file id,
 * and cachepack refuses an interface without one, because the id is data — a
 * component's uid is `(interface << 16) | file id` and scripts reference it, so an
 * invented id would move a component every time the tree changed.
 */

import { TRANSMIT } from './components.js';
import { ELEMENTS } from './components.js';

/** Fields written on every IF3 block, whatever the component is. */
function header(component) {
    const lines = [`if3=yes`, `type=${component.type}`];
    if( component.layer !== null ) lines.push(`layer=${component.layer}`);
    return lines;
}

/**
 * Emit the .if text.
 *
 * Only non-default fields are written, the way cachepack's own writer does it: a
 * block carries what someone chose, so a diff shows decisions rather than the
 * whole field set.
 */
export function emitInterface(ir) {
    const out = [
        `// ${ir.name} — ${ir.components.length} components, interface ${ir.interfaceId}.`,
        `// Generated by cs2dom from the .tsx of the same name. Edits here are`,
        `// overwritten on the next build; change the component and rebuild.`,
        '',
    ];

    for( const component of ir.components ) {
        out.push(`[${component.name}]`);
        out.push(...header(component));

        const schema = ELEMENTS[component.kind].props;
        for( const [prop, value] of Object.entries(component.static) ) {
            const field = schema[prop];
            if( !field ) continue;
            /* A prop bound to state keeps its field at the default; the update
             * script owns it from the first paint onward. */
            if( isDefault(value, field.default) && !isBoundElsewhere(component, prop) ) continue;
            out.push(`${field.field}=${fieldValue(value)}`);
        }

        for( const op of component.ops )
            out.push(`op${op.index}=${op.text}`);

        for( const [hook, binding] of Object.entries(component.hooks) ) {
            const args = [`i:${binding.script.id}`, ...binding.args.map((a) => `i:${a}`)];
            out.push(`${hook}=${args.join(',')}`);
        }

        for( const [key, ids] of Object.entries(component.triggers) )
            out.push(`${key}=${ids.join(',')}`);

        out.push('');
    }

    return out.join('\n');
}

function isDefault(value, fallback) {
    return value === fallback;
}

/* A default-valued prop is still written when something else in its command group
 * moved, so the .if and the first if_set* call agree about the starting state. */
function isBoundElsewhere(component, prop) {
    return component.dynamic.some((binding) => binding.prop === prop);
}

function fieldValue(value) {
    if( typeof value === 'boolean' ) return value ? 'yes' : 'no';
    return String(value);
}

/** `<file id>=<block name>` — the member list cachepack needs beside the .if. */
export function emitCompack(ir) {
    return ir.components.map((c) => `${c.fileId}=${c.name}`).join('\n') + '\n';
}

export { TRANSMIT };
