#!/usr/bin/env python3
"""Bind `~openbank` to every loc this cache puts a "Bank" op on.

Why this exists
---------------
`interaction_engine_loc` in `src/torirsserver/torirs_server_world.c` opened the bank by
`strcmp`ing the loc's *cache menu verb* against "Bank" (and against
"Use-quickly", which matches zero records in this cache). That is content's job:
LostCity binds every booth by name in
`content/scripts/interface_bank/scripts/bank_booth.rs2`
(`[oploc1,bankbooth]`, `[oploc2,bankbooth]`) and in the area scripts that own a
particular one — `tut_bank_booth.rs2`, `shantay_chest.rs2`, `misc_locs.rs2`,
`gundai.rs2`. Not one line of it is in that tree's engine, and not one of those
bindings is by category: the reference names the booth.

Names, not a category — and that was measured, not assumed
----------------------------------------------------------
The obvious alternative is a category binding, the way
`tools/ladder_import.py` handles the 1,445 climb records. It was tried against
this cache and it **over-reaches**, which is why this file emits names:

  cache category 684  63 members, 58 say "Bank".  The other five include
                      `exchange_bank_wall_exchange`, whose op1 is "Exchange" —
                      the Grand Exchange, not the bank.
  cache category 237  44 members, 11 say "Bank".  The other 33 say "Use", and
                      one of them is `chest_alchemist01_closed01`.
  cache category 1929  1 member,  1 says "Bank".

So binding those three ids would open the bank on 38 records whose menu never
offered it, on the strength of a grouping nobody in either tree has named. An
*authored* category (`category=bank_booth` on exactly the 78) has no
over-reach, but it is the same 78 generated blocks moved from a `.rs2` to a
`.loc`, plus a `pack/category.pack` row, plus overwriting the cache's own
category on 70 of them. The name rung costs less and is what the reference
does.

That leaves the objection the C's own comment raised — "OldSchool has dozens of
bank booths and an id list would be a second copy kept by hand, wrong for
whichever booth nobody added". It is answered by *generated* and by `--check`,
not by disagreeing with it: this list is derived from the cache on every run and
`test-port` fails when the file and the cache disagree. And it is a list of
**names**, which is what a trigger subject is; no id is copied anywhere.

Usage
-----
    python3 tools/bank_import.py [--content <dir>] [--check] [--report]

`--check` writes nothing and exits non-zero if the file on disk differs, which
is what makes "generated, do not edit" enforceable.
"""

import argparse
import collections
import os
import re
import sys

# The cache menu verb the engine used to answer. It is spelled here, in the
# tool that reads the cache, and nowhere in C — that is the whole point of the
# move.
BANK_VERB = "Bank"

# The other half of the deleted branch. Kept as a measurement rather than a
# rule: `interaction_engine_loc` treated it as a synonym for "Bank", and it
# matches nothing, so the generator reports the count and emits nothing for it.
DEAD_VERB = "Use-quickly"

HEADER = """\
// Every loc in this cache whose menu says "{verb}".
//
// Generated by tools/bank_import.py — do not edit, re-run the importer.
// `python3 tools/bank_import.py --check` fails when this file and the cache
// disagree.
//
// Where LostCity puts it: content. `interface_bank/scripts/bank_booth.rs2`
// binds `[oploc1,bankbooth]` and `[oploc2,bankbooth]`; the booths that belong
// to an area or a tutorial are bound in that area's own file
// (`tut_bank_booth.rs2`, `shantay_chest.rs2`, `misc_locs.rs2`, `gundai.rs2`).
// Every one of them is a NAME. There is no bank category in either tree.
//
// This tree answered it in C instead — `interaction_engine_loc` compared the
// loc's cache menu verb to "{verb}" and called `ToriRSServer_BankOpen` — which
// covered all {total} records without content saying anything, and was the last
// thing keeping `TORIRSSERVER_FALLBACK_OPLOC` alive. A script cannot read a menu
// verb (no opcode exposes one; a trigger's subject is a name or a category), so
// the verb is restated here as the list of records that carry it, derived from
// the cache rather than typed.
//
// Names, not a category: cache category 684 has 63 members and only 58 say
// "{verb}" (one of the others is the Grand Exchange wall), 237 has 44 members
// and only 11 do (33 say "Use"). Binding those ids would open the bank on 38
// records that never offered it. See the importer's docstring.
//
// {total} records, on the slot the cache puts the verb on: {slots}.
// "{dead}" — the other verb the C treated as a synonym — matches {dead_count}
// records in this cache and is emitted nowhere.
"""


def read_configs(path):
    records = {}
    current = None
    with open(path) as handle:
        for raw in handle:
            line = raw.rstrip("\n")
            match = re.match(r"^\[([^\]]+)\]$", line)
            if match:
                current = match.group(1)
                records[current] = {}
                continue
            if current is None or "=" not in line or line.startswith("//"):
                continue
            key, _, value = line.partition("=")
            records[current].setdefault(key, value)
    return records


def collect(records, verb):
    """name -> sorted list of op slots stating `verb`."""
    out = {}
    for name, record in records.items():
        slots = [s for s in range(1, 6) if record.get("op%d" % s) == verb]
        if slots:
            out[name] = slots
    return out


def render(booths, dead_count):
    slots = collections.Counter()
    for name in booths:
        for slot in booths[name]:
            slots[slot] += 1
    total = len(booths)
    body = [
        HEADER.format(
            verb=BANK_VERB,
            total=total,
            dead=DEAD_VERB,
            dead_count=dead_count,
            slots=", ".join("op%d %d" % (s, slots[s]) for s in sorted(slots)),
        )
    ]
    for name in sorted(booths):
        for slot in booths[name]:
            body.append("\n[oploc%d,%s] ~openbank;\n" % (slot, name))
    return "".join(body)


def main():
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    parser = argparse.ArgumentParser()
    parser.add_argument("--content", default=os.path.join(here, "OSRS-Content", "osrs239-content"))
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--report", action="store_true")
    args = parser.parse_args()

    records = read_configs(os.path.join(args.content, "configs", "all.loc"))
    booths = collect(records, BANK_VERB)
    dead = collect(records, DEAD_VERB)

    # A nameless record cannot be a trigger subject. `cachepack` writes
    # `loc_<id>` for one, and resolving that by id is the forbidden move, so it
    # would have to be reported and dropped. Measured today: none of them.
    nameless = sorted(n for n in booths if re.fullmatch(r"loc_\d+", n))
    if nameless:
        print(
            "bank_import: %d bank record(s) have no symbol and cannot be bound: %s"
            % (len(nameless), ", ".join(nameless)),
            file=sys.stderr,
        )
        return 1

    text = render(booths, len(dead))
    out_path = os.path.join(
        args.content, "server", "scripts", "interface_bank", "scripts", "bank_booths.rs2"
    )

    if args.report:
        print("bank_import: %d records say %r" % (len(booths), BANK_VERB))
        print("bank_import: %d records say %r" % (len(dead), DEAD_VERB))
        counts = collections.Counter()
        for name in booths:
            for slot in booths[name]:
                counts[slot] += 1
        print("bank_import: slots %s" % dict(sorted(counts.items())))
        categories = collections.Counter(records[n].get("category", "-1") for n in booths)
        print("bank_import: cache categories %s" % categories.most_common())
        return 0
    if args.check:
        try:
            with open(out_path) as handle:
                on_disk = handle.read()
        except OSError:
            print("bank_import: %s is missing" % out_path, file=sys.stderr)
            return 1
        if on_disk != text:
            print(
                "bank_import: %s does not match the cache — re-run tools/bank_import.py"
                % out_path,
                file=sys.stderr,
            )
            return 1
        return 0

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as handle:
        handle.write(text)
    print("bank_import: wrote %d bindings over %d records to %s"
          % (sum(len(v) for v in booths.values()), len(booths), out_path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
