#!/usr/bin/env python3
"""
Import door / gate pairings as a LostCity `.loc` config plus its pack file.

    tools/door_import.py --content OSRS-Content/osrs239-content

Two loc ids look identical to a cache reader — one closed, one open — and
nothing in the cache says which pairs with which. LostCity records the pairing
as a config overlay:

    [poordoor]
    category=door_closed
    param=next_loc_stage,poordooropen

    [poordooropen]
    category=door_opened
    param=next_loc_stage,poordoor

so the engine's door handler is one generic rule and every door in the game is
data. This emits exactly that, from two sources:

  * OpenRune's hand-curated tables (`data/cfg/doors/*.json`,
    `data/cfg/gates/gates.json`) — 13 pairs, and the only ones anybody checked.
  * The rest proposed from OpenRune's gameval names by the transforms below.

The proposed ones are guesswork and are marked as such in the output. What
makes the guess safe is that `mock230_pack` checks every pair against
cache.osrs230: both halves must be real locs, the closed half must carry an
Open-family action and the open half must not. A wrong pair fails that and
never reaches the game.

Writes `<content>/scripts/doors/configs/doors.loc` and
`<content>/pack/door.pack` — a pack of its own rather than lines appended to
loc.pack, because two generators writing one file is how a generated file gets
edited by hand.
"""

import argparse
import importlib.util
import json
import os

DEFAULT_CFG = os.path.expanduser("~/Documents/git_repos/OpenRune-Server/data/cfg")

PACK_HEADER = """\
// Generated by tools/door_import.py. Symbols for both halves of every door and
// gate pair, so doors.loc can name them. Kept out of loc.pack because that file
// is generated from tools/gameval_import.names and this one is not.
"""

LOC_HEADER = """\
// Door and gate pairings, in LostCity's own form: `category=door_closed` plus
// `param=next_loc_stage,<the other half>`, which is all the engine's generic
// door handler reads.
//
// Generated by tools/door_import.py — do not edit, re-run the importer.
//
// The first section is OpenRune's curated table (data/cfg/doors,
// data/cfg/gates). The second is proposed from OpenRune's gameval names and is
// only as good as the naming conventions; `mock230_pack` validates every pair
// against cache.osrs230 and drops the ones that do not hold up.
"""

# Closed-name -> open-name transforms, tried in order. Each is a real pattern in
# OpenRune's name table: `poordoor`/`poordooropen`,
# `castledoubledoorl`/`opencastledoubledoorl`, `zanarisdoor`/`zanarisdoor_open`,
# `desertdoorclosed`/`desertdooropen`.
TRANSFORMS = (
    lambda n: n + "open",
    lambda n: n + "_open",
    lambda n: "open" + n,
    lambda n: n.replace("closed", "open") if "closed" in n else None,
    lambda n: n.replace("_shut", "_open") if "_shut" in n else None,
)


def load_gamevals(path):
    spec = importlib.util.spec_from_file_location(
        "gameval_import", os.path.join(os.path.dirname(__file__), "gameval_import.py")
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.read_gamevals(path)


def curated_pairs(cfg):
    """[(closed_id, opened_id)] from OpenRune's JSON, doors then gates."""

    def load(*parts):
        with open(os.path.join(cfg, *parts), "r", encoding="utf-8") as handle:
            return json.load(handle)

    pairs = []
    for entry in load("doors", "single-doors.json"):
        pairs.append((entry["closed"], entry["opened"]))
    for entry in load("doors", "double-doors.json"):
        pairs.append((entry["closed"]["left"], entry["opened"]["left"]))
        pairs.append((entry["closed"]["right"], entry["opened"]["right"]))
    for entry in load("gates", "gates.json"):
        pairs.append((entry["closed"]["hinge"], entry["opened"]["hinge"]))
        pairs.append((entry["closed"]["extension"], entry["opened"]["extension"]))
    return pairs


def derived_pairs(objects, already):
    pairs = []
    for name, ident in sorted(objects.items(), key=lambda kv: kv[1]):
        if ident in already:
            continue
        # Only door-shaped names. Without this the transforms pair things like
        # `bank_booth` with `bank_boothopen` on the strength of a coincidence.
        if ("door" not in name and "gate" not in name) or "open" in name:
            continue
        for transform in TRANSFORMS:
            candidate = transform(name)
            if candidate and candidate in objects and objects[candidate] != ident:
                pairs.append((ident, objects[candidate]))
                break
    return pairs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cfg", default=DEFAULT_CFG)
    parser.add_argument("--content", required=True, help="the mock's content root")
    parser.add_argument(
        "--gamevals",
        default=os.path.join(DEFAULT_CFG, "gamevals-binary", "gamevals.dat"),
    )
    parser.add_argument("--no-derive", action="store_true")
    args = parser.parse_args()

    objects = load_gamevals(args.gamevals)["objects"]
    names = {ident: name for name, ident in objects.items()}

    curated = curated_pairs(args.cfg)
    seen = {ident for pair in curated for ident in pair}
    derived = [] if args.no_derive else derived_pairs(objects, seen)

    # A loc can only be one half of one pair. Whichever section claimed it first
    # wins, so curation always beats derivation.
    claimed = set()
    symbols = {}
    sections = []

    for label, pairs in (("curated", curated), ("derived", derived)):
        blocks = []
        for closed, opened in pairs:
            if closed in claimed or opened in claimed:
                continue
            if closed not in names or opened not in names:
                continue
            claimed.update((closed, opened))
            symbols[names[closed]] = closed
            symbols[names[opened]] = opened
            blocks.append(
                f"[{names[closed]}]\n"
                f"category=door_closed\n"
                f"param=next_loc_stage,{names[opened]}\n\n"
                f"[{names[opened]}]\n"
                f"category=door_opened\n"
                f"param=next_loc_stage,{names[closed]}\n"
            )
        sections.append((label, blocks))

    pack_path = os.path.join(args.content, "pack", "door.pack")
    loc_path = os.path.join(args.content, "scripts", "doors", "configs", "doors.loc")
    os.makedirs(os.path.dirname(pack_path), exist_ok=True)
    os.makedirs(os.path.dirname(loc_path), exist_ok=True)

    with open(pack_path, "w", encoding="utf-8") as handle:
        handle.write(PACK_HEADER)
        for name, ident in sorted(symbols.items(), key=lambda kv: kv[1]):
            handle.write(f"{ident}={name}\n")

    with open(loc_path, "w", encoding="utf-8") as handle:
        handle.write(LOC_HEADER)
        for label, blocks in sections:
            if not blocks:
                continue
            handle.write(
                f"\n// ------------------------------------------------------------------\n"
                f"// {label}\n"
                f"// ------------------------------------------------------------------\n\n"
            )
            handle.write("\n".join(blocks))

    print(
        f"wrote {loc_path} and {pack_path} "
        f"({len(sections[0][1])} curated pairs, "
        f"{len(sections[1][1]) if len(sections) > 1 else 0} derived, "
        f"{len(symbols)} symbols)"
    )


if __name__ == "__main__":
    main()
