#!/usr/bin/env bash
# Capture one named BMP per Nature Spirit interaction.
# Plugins off. Player unkillable. Each shot must show the mesbox/journal/reward.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/OSRS-Content/osrs239-content/server/scripts/selftest/quest_druidspirit"
MANIFEST="${NS_MANIFEST:-$ROOT/manifests/manifest_osrs239_sailing.ini}"
if [[ ! -f "$MANIFEST" ]]; then
  MANIFEST="$ROOT/manifests/manifest_osrs239.ini"
fi
mkdir -p "$OUT"
export TORIRS_PLUGINS=0
export TORIRSSERVER_GOD=1
export SDL_VIDEODRIVER=dummy
export PLATFORM_OBJ_BASE="${PLATFORM_OBJ_BASE:-/tmp/gp-spirit-img-obj}"

shots=(
  "001_drezel_offer:nsbmp_001_drezel_offer"
  "002_drezel_offer_choice:nsbmp_002_drezel_offer_choice"
  "003_drezel_decline:nsbmp_003_drezel_decline"
  "004_drezel_accept:nsbmp_004_drezel_accept"
  "005_drezel_prereq_fail:nsbmp_005_drezel_prereq_fail"
  "006_drezel_thanks:nsbmp_006_drezel_thanks"
  "007_gate_warning:nsbmp_007_gate_warning"
  "008_gate_walk_in:nsbmp_008_gate_walk_in"
  "009_gate_walk_out:nsbmp_009_gate_walk_out"
  "010_gate_guard_blocked:nsbmp_010_gate_guard_blocked"
  "011_gate_guard_not_started:nsbmp_011_gate_guard_not_started"
  "012_gate_guard_quest:nsbmp_012_gate_guard_quest"
  "013_gate_guard_complete:nsbmp_013_gate_guard_complete"
  "014_filliman_apparition:nsbmp_014_filliman_apparition"
  "015_filliman_failed_talk:nsbmp_015_filliman_failed_talk"
  "016_filliman_failed_sense:nsbmp_016_filliman_failed_sense"
  "017_filliman_ghostspeak_hello:nsbmp_017_filliman_ghostspeak_hello"
  "018_filliman_first_choice:nsbmp_018_filliman_first_choice"
  "019_filliman_ghostspeak:nsbmp_019_filliman_ghostspeak"
  "020_filliman_longghost:nsbmp_020_filliman_longghost"
  "021_filliman_likeghost:nsbmp_021_filliman_likeghost"
  "022_filliman_ok:nsbmp_022_filliman_ok"
  "023_filliman_ghost_no_amulet:nsbmp_023_filliman_ghost_no_amulet"
  "024_filliman_spoken_again:nsbmp_024_filliman_spoken_again"
  "025_bowl_mirror:nsbmp_025_bowl_mirror"
  "026_filliman_mirror:nsbmp_026_filliman_mirror"
  "027_filliman_mirror_take:nsbmp_027_filliman_mirror_take"
  "028_filliman_mirror_dead:nsbmp_028_filliman_mirror_dead"
  "029_filliman_mirror_already:nsbmp_029_filliman_mirror_already"
  "030_grotto_search_journal:nsbmp_030_grotto_search_journal"
  "031_grotto_search_empty:nsbmp_031_grotto_search_empty"
  "032_journal_read:nsbmp_032_journal_read"
  "033_journal_read_vague:nsbmp_033_journal_read_vague"
  "034_filliman_journal_early:nsbmp_034_filliman_journal_early"
  "035_filliman_journal:nsbmp_035_filliman_journal"
  "036_filliman_journal_leaf:nsbmp_036_filliman_journal_leaf"
  "037_filliman_after_journal_choice:nsbmp_037_filliman_after_journal_choice"
  "038_filliman_bedead:nsbmp_038_filliman_bedead"
  "039_filliman_plan:nsbmp_039_filliman_plan"
  "040_filliman_goodluck:nsbmp_040_filliman_goodluck"
  "041_filliman_howhelp:nsbmp_041_filliman_howhelp"
  "042_filliman_spell_papyrus:nsbmp_042_filliman_spell_papyrus"
  "043_filliman_need_bless:nsbmp_043_filliman_need_bless"
  "044_filliman_another_bloom:nsbmp_044_filliman_another_bloom"
  "045_filliman_already_bloom:nsbmp_045_filliman_already_bloom"
  "046_filliman_ok2:nsbmp_046_filliman_ok2"
  "047_bloom_need_bless:nsbmp_047_bloom_need_bless"
  "048_bloom_outside:nsbmp_048_bloom_outside"
  "049_bloom_cast:nsbmp_049_bloom_cast"
  "050_bloom_no_material:nsbmp_050_bloom_no_material"
  "051_fungi_pick:nsbmp_051_fungi_pick"
  "052_filliman_show_fungus:nsbmp_052_filliman_show_fungus"
  "053_filliman_whatneed:nsbmp_053_filliman_whatneed"
  "054_filliman_whatdo:nsbmp_054_filliman_whatdo"
  "055_filliman_puzzle_fail:nsbmp_055_filliman_puzzle_fail"
  "056_faith_stone:nsbmp_056_faith_stone"
  "057_faith_stone_complete:nsbmp_057_faith_stone_complete"
  "058_nature_stone:nsbmp_058_nature_stone"
  "059_nature_stone_old:nsbmp_059_nature_stone_old"
  "060_nature_stone_use:nsbmp_060_nature_stone_use"
  "061_nature_stone_done:nsbmp_061_nature_stone_done"
  "062_spirit_stone:nsbmp_062_spirit_stone"
  "063_spirit_stone_use:nsbmp_063_spirit_stone_use"
  "064_spirit_stone_used:nsbmp_064_spirit_stone_used"
  "065_spirit_stone_done:nsbmp_065_spirit_stone_done"
  "066_stone_wrong_item:nsbmp_066_stone_wrong_item"
  "067_filliman_puzzle_ok:nsbmp_067_filliman_puzzle_ok"
  "068_grotto_look:nsbmp_068_grotto_look"
  "069_grotto_door_before:nsbmp_069_grotto_door_before"
  "070_grotto_enter:nsbmp_070_grotto_enter"
  "071_grotto_leave:nsbmp_071_grotto_leave"
  "072_grotto_leave_crawl:nsbmp_072_grotto_leave_crawl"
  "073_filliman_grotto_meet:nsbmp_073_filliman_grotto_meet"
  "074_filliman_transform:nsbmp_074_filliman_transform"
  "075_filliman_ask_sickle:nsbmp_075_filliman_ask_sickle"
  "076_filliman_where_sickle:nsbmp_076_filliman_where_sickle"
  "077_filliman_what_sickle:nsbmp_077_filliman_what_sickle"
  "078_filliman_defeat_ghasts:nsbmp_078_filliman_defeat_ghasts"
  "079_filliman_no_sickle:nsbmp_079_filliman_no_sickle"
  "080_filliman_bless_sickle:nsbmp_080_filliman_bless_sickle"
  "081_filliman_pouch_give:nsbmp_081_filliman_pouch_give"
  "082_filliman_pouch_noroom:nsbmp_082_filliman_pouch_noroom"
  "083_sickle_need_pray:nsbmp_083_sickle_need_pray"
  "084_sickle_bloom:nsbmp_084_sickle_bloom"
  "085_stem_pick:nsbmp_085_stem_pick"
  "086_pear_pick:nsbmp_086_pear_pick"
  "087_pouch_not_told:nsbmp_087_pouch_not_told"
  "088_pouch_need_three:nsbmp_088_pouch_need_three"
  "089_pouch_add:nsbmp_089_pouch_add"
  "090_altar_recharge:nsbmp_090_altar_recharge"
  "091_altar_boosted:nsbmp_091_altar_boosted"
  "092_sickle_dip:nsbmp_092_sickle_dip"
  "093_sickle_already:nsbmp_093_sickle_already"
  "094_inv_full_fungi:nsbmp_094_inv_full_fungi"
  "095_ghast_need_pouch:nsbmp_095_ghast_need_pouch"
  "096_ghast_reveal:nsbmp_096_ghast_reveal"
  "097_ghast_pouch_empty:nsbmp_097_ghast_pouch_empty"
  "098_ghast_kill1:nsbmp_098_ghast_kill1"
  "099_ghast_kill2:nsbmp_099_ghast_kill2"
  "100_ghast_kill3:nsbmp_100_ghast_kill3"
  "101_filliman_not_yet:nsbmp_101_filliman_not_yet"
  "102_ns_attackghasts:nsbmp_102_ns_attackghasts"
  "103_ns_whatpouch:nsbmp_103_ns_whatpouch"
  "104_ns_whatsickle2:nsbmp_104_ns_whatsickle2"
  "105_ns_lostsickle:nsbmp_105_ns_lostsickle"
  "106_ns_occupied:nsbmp_106_ns_occupied"
  "107_ns_busy:nsbmp_107_ns_busy"
  "108_filliman_three_killed:nsbmp_108_filliman_three_killed"
  "109_complete_scroll:nsbmp_109_complete_scroll"
  "110_complete_postquest:nsbmp_110_complete_postquest"
  "111_grotto_tended:nsbmp_111_grotto_tended"
  "112_journal_not_started:nsbmp_112_journal_not_started"
  "113_journal_started:nsbmp_113_journal_started"
  "114_journal_failed:nsbmp_114_journal_failed"
  "115_journal_spoken:nsbmp_115_journal_spoken"
  "116_journal_mirror:nsbmp_116_journal_mirror"
  "117_journal_spell:nsbmp_117_journal_spell"
  "118_journal_mid:nsbmp_118_journal_mid"
  "119_journal_grotto:nsbmp_119_journal_grotto"
  "120_journal_ghasts:nsbmp_120_journal_ghasts"
  "121_journal_complete:nsbmp_121_journal_complete"
  "122_jump_drown:nsbmp_122_jump_drown"
  "123_swamp_decay:nsbmp_123_swamp_decay"
  "124_swamp_camp:nsbmp_124_swamp_camp"
  "125_swamp_sickle:nsbmp_125_swamp_sickle"
  "126_filliman_casted_spell:nsbmp_126_filliman_casted_spell"
  "127_filliman_blessed:nsbmp_127_filliman_blessed"
  "128_another_bloom_give:nsbmp_128_another_bloom_give"
)

CLIENT="${NS_CLIENT:-$ROOT/src/torirs}"
if [[ ! -x "$CLIENT" ]]; then
  CLIENT="$ROOT/src/torirs"
fi

only="${1:-}"
for shot in "${shots[@]}"; do
  name="${shot%%:*}"
  cheat="${shot##*:}"
  if [[ -n "$only" && "$name" != *"$only"* && "$cheat" != *"$only"* ]]; then
    continue
  fi
  dest="$OUT/${name}.bmp"
  echo "CAPTURING $name via ::$cheat -> $dest"
  TORIRS_PLUGINS=0 \
  TORIRSSERVER_GOD=1 \
  TORIRS_PAINTER_NOCULL=1 \
  TORIRS_NET_CHEAT="god 1;maxstats;$cheat" \
  TORIRS_EXIT_BMP="$dest" \
  TORIRS_MAX_FRAMES="${TORIRS_MAX_FRAMES:-240}" \
  SDL_VIDEODRIVER=dummy \
  "$CLIENT" --manifest "$MANIFEST" --user testc --pass test --soft3d || true
  if [[ ! -f "$dest" ]]; then
    echo "MISSING $dest" >&2
  else
    echo "WROTE $dest ($(wc -c < "$dest") bytes)"
  fi
done
echo "done. count=$(ls -1 "$OUT"/*.bmp 2>/dev/null | wc -l)"
