#!/usr/bin/env python3
"""gen_toa_invocations — the Tombs of Amascut invocation table, out of the cache.

    tools/gen_toa_invocations.py --write

The 44 raid invocations are not content: every one of them is a `struct` in the
rev239 cache carrying its own index, name, category, raid-level modifier,
numeric argument and prerequisite. Hand-keeping that table would be the same
mistake as hand-keeping any other exported config -- it drifts, silently, and the
only symptom is a raid that is the wrong difficulty.

So this reads `configs/all.struct` and writes

    server/scripts/minigames/minigame_toa/configs/toa_invocation.dbtable
    server/scripts/minigames/minigame_toa/configs/toa_invocation.dbrow

Selection rule: a struct is an invocation if it carries **both** param 1159 (its
index) and param 1160 (its name). That finds all 46 and nothing else, so there is
no id list here to fall out of date -- a struct added by a later cache is picked
up on the next run.

Leagues rows (category 15, `Blazing Tombs I/II`) are dropped: they are +200 each
and exist only inside a Leagues world, and including them would break the
ceiling check below.

The check that the read is right is arithmetic, and it runs on every invocation
of this tool: one invocation from each of the four exclusive categories plus
every non-exclusive toggle must sum to exactly 600, the documented raid-level
ceiling. If it does not, the tool refuses to write.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTENT = ROOT / "OSRS-Content/osrs239-content"
OUT = CONTENT / "server/scripts/minigames/minigame_toa/configs"

STRUCT_INDEX = "param_1159"
STRUCT_NAME = "param_1160"
STRUCT_CATEGORY = "param_1161"
STRUCT_RAID_LEVEL = "param_1162"
STRUCT_ARG = "param_1299"
STRUCT_PREREQ = "param_1346"

# param_1161 values. 3-6 are exclusive: the interface lets one member of each be
# active at a time, which is also what makes the 600 ceiling computable.
CATEGORY_NAMES = {
    3: "attempts", 4: "timelimit", 5: "spirit", 6: "pathlevel",
    7: "prayer", 8: "restoration", 9: "paths", 10: "akkha", 11: "kephri",
    12: "zebak", 13: "baba", 14: "wardens", 15: "leagues",
}
EXCLUSIVE = {3, 4, 5, 6}
LEAGUES = 15
RAID_LEVEL_CEILING = 600

HEADER = """// GENERATED by tools/gen_toa_invocations.py from cache.osrs239 `all.struct`.
// Re-run the tool; do not hand-edit.
//
// The Tombs of Amascut invocation table. Every row is a cache struct: `struct`
// is its id, `index` is param 1159 (which is also the invocation's bit position
// in the party's selection), `category` is param 1161, `raidlevel` is param
// 1162, `arg` is param 1299 (attempt count, time limit in ticks, supply
// percentage) and `prereq` is param 1346 -- the invocation that must also be
// active, 0 for none.
//
// Leagues invocations (category 15) are deliberately absent; see the tool.
//
// Spec: docs/minigames/tombs_of_amascut/TOMBS_OF_AMASCUT_PLAN.md section 3.
"""


def symbol(name: str) -> str:
    """`Need Some Help?` -> `toa_inv_need_some_help`."""
    slug = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    return f"toa_inv_{slug}"


def read_structs() -> list:
    text = (CONTENT / "configs/all.struct").read_text(encoding="cp1252",
                                                      errors="replace")
    rows = []
    for block in re.split(r"\n(?=\[)", text):
        m = re.match(r"\[struct_(\d+)\]", block)
        if not m:
            continue
        params = dict(re.findall(r"^param=(param_\d+),(?:int|str),(.*)$",
                                 block, re.M))
        if STRUCT_INDEX not in params or STRUCT_NAME not in params:
            continue
        rows.append({
            "struct": int(m.group(1)),
            "index": int(params[STRUCT_INDEX]),
            "name": params[STRUCT_NAME],
            "category": int(params.get(STRUCT_CATEGORY, 0)),
            "raidlevel": int(params.get(STRUCT_RAID_LEVEL, 0)),
            "arg": int(params.get(STRUCT_ARG, 0) or 0),
            "prereq": int(params.get(STRUCT_PREREQ, 0) or 0),
        })
    rows.sort(key=lambda r: r["index"])
    return rows


def ceiling(rows: list) -> int:
    """The highest raid level the interface can actually produce."""
    best = {}
    rest = 0
    for r in rows:
        if r["category"] in EXCLUSIVE:
            best[r["category"]] = max(best.get(r["category"], 0), r["raidlevel"])
        else:
            rest += r["raidlevel"]
    return rest + sum(best.values())


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true",
                    help="write the two config files; otherwise report only")
    args = ap.parse_args()

    rows = [r for r in read_structs() if r["category"] != LEAGUES]
    if not rows:
        print("no invocation structs found -- wrong cache?", file=sys.stderr)
        return 1

    reachable = ceiling(rows)
    if reachable != RAID_LEVEL_CEILING:
        print(f"raid-level ceiling is {reachable}, wanted {RAID_LEVEL_CEILING}; "
              "refusing to write", file=sys.stderr)
        return 1

    structs = {r["struct"] for r in rows}
    dangling = {r["prereq"] for r in rows if r["prereq"]} - structs
    if dangling:
        print(f"prerequisite structs outside the table: {sorted(dangling)}; "
              "refusing to write", file=sys.stderr)
        return 1

    indices = [r["index"] for r in rows]
    if indices != list(range(1, len(rows) + 1)):
        print(f"invocation indices are not 1..{len(rows)}: {indices}; "
              "refusing to write", file=sys.stderr)
        return 1

    table = [HEADER, "", "[toa_invocation]",
             "column=index,int,INDEXED,REQUIRED",
             "column=struct,int,REQUIRED",
             "column=category,int,REQUIRED",
             "column=raidlevel,int,REQUIRED",
             "column=arg,int,REQUIRED",
             "column=prereq,int,REQUIRED", ""]

    by_struct = {r["struct"]: r for r in rows}
    body = [HEADER]
    for r in rows:
        prereq_index = by_struct[r["prereq"]]["index"] if r["prereq"] else 0
        body += [
            "",
            f"// {r['name']} -- +{r['raidlevel']}, "
            f"{CATEGORY_NAMES.get(r['category'], r['category'])}",
            f"[{symbol(r['name'])}]",
            "table=toa_invocation",
            f"data=index,{r['index']}",
            f"data=struct,{r['struct']}",
            f"data=category,{r['category']}",
            f"data=raidlevel,{r['raidlevel']}",
            f"data=arg,{r['arg']}",
            # Stored as the prerequisite's INDEX, not its struct id: the runtime
            # tests "is bit N set", and translating a struct id back to a bit at
            # every check would be a table walk per test.
            f"data=prereq,{prereq_index}",
        ]

    if args.write:
        OUT.mkdir(parents=True, exist_ok=True)
        (OUT / "toa_invocation.dbtable").write_text("\n".join(table) + "\n",
                                                    encoding="utf-8")
        (OUT / "toa_invocation.dbrow").write_text("\n".join(body) + "\n",
                                                  encoding="utf-8")
        print(f"wrote {len(rows)} invocations to {OUT}")
    else:
        print(f"{len(rows)} invocations, ceiling {reachable} (use --write)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
