#!/usr/bin/env python3
"""
gen_shop_scripts — author one `.rs2` + one `.inv` per shop from the catalogue.

    tools/gen_shop_catalog.py --write     # wiki/shop_catalog.csv, shop_stock.csv
    tools/wiki_shop_owners.py --write     # wiki/shop_owners.csv
    tools/gen_shop_inv_map.py --write     # wiki/shop_inv_map.tsv (hand-reviewed)
    tools/gen_shop_scripts.py --write     # this — one file pair per ready shop

See docs/SHOPS_PLAN.md §4. Every shop this writes calls the shared
`~openshop` proc in server/scripts/shop/scripts/shop.rs2 — this tool never
authors shop mechanics, only the per-shop facts: which npc opens it, what
inv backs it, its three multipliers, its title, its stock.

## What counts as ready

A shop generates only when every one of these holds; anything else is
skipped and counted in the report, never silently dropped or guessed:

  * not a duplicate of another catalogued table (`duplicate_of` empty)
  * not a multi-table page's 2nd+/3rd+ section (`__N` in the shop key) —
    those are conditional/account-mode sub-stocks (skillcape tiers, GIM
    variants) whose inv binding needs the `section` field wired into
    gen_shop_inv_map.py first; tracked, not yet done (docs/SHOPS_PLAN.md §7)
  * all three price multipliers present (a coin shop, not a token shop)
  * every stock line resolved with no review flag
  * at least one owner npc gameval is spawned in this world
  * `shop_inv_map.tsv` marks its cache inv binding `verified`
  * that cache inv is not already claimed by an earlier shop in this run
    (a real collision in the map — logged, first claim wins)
  * the wiki stock table fits the cache inv's slot count (§2.4 of the plan)
  * every live owner gameval's `[opnpc3,<gameval>]` trigger is either absent
    from the tree, or is a bare "nothing to trade" stub this tool can safely
    replace (see `patch_stub` below) — anything else (quest-gated dialogue,
    a second copy of the same gameval) is left alone and the shop is skipped

## What gets written

    server/scripts/shop/<area>/scripts/<shop_key>.rs2
    server/scripts/shop/<area>/configs/<shop_key>.inv

`<area>` is the wiki's `location=`, slugged, purely for navigability — it
carries no semantics and a shop never needs to find another by it.

Idempotent: re-running with the same catalogue and the same `shop_inv_map.tsv`
overwrites the same files with the same bytes. Never overwrites a file this
tool did not itself generate — every output opens with the citation header
carrying the wiki revision, and a target file lacking that header is treated
as hand-authored and left alone (docs/SHOPS_PLAN.md §4.4).
"""

from __future__ import annotations

import argparse
import csv
import collections
import glob
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(REPO, "OSRS-Content", "osrs239-content")
WIKI = os.path.join(CONTENT, "wiki")
CATALOG = os.path.join(WIKI, "shop_catalog.csv")
STOCK = os.path.join(WIKI, "shop_stock.csv")
OWNERS = os.path.join(WIKI, "shop_owners.csv")
INV_MAP = os.path.join(WIKI, "shop_inv_map.tsv")
ALL_INV = os.path.join(CONTENT, "configs", "all.inv")
SHOP_ROOT = os.path.join(CONTENT, "server", "scripts", "shop")
SCAN_ROOT = os.path.join(CONTENT, "server", "scripts")

GENERATED_MARK = "// Generated by tools/gen_shop_scripts.py — see docs/SHOPS_PLAN.md §4."

STUB_MES_RE = re.compile(r'^\s*mes\("[^"]*nothing to trade[^"]*"\);\s*$', re.IGNORECASE)


def slug(text: str) -> str:
    text = text.lower().replace("'", "")
    text = re.sub(r"[^a-z0-9]+", "_", text)
    return text.strip("_") or "misc"


# ------------------------------------------------------------------
# Load the pipeline's own output
# ------------------------------------------------------------------


def load_catalog() -> dict[str, dict]:
    with open(CATALOG, newline="", encoding="utf-8") as f:
        return {r["shop_key"]: r for r in csv.DictReader(f)}


def load_stock() -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = collections.defaultdict(list)
    with open(STOCK, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            out[row["shop_key"]].append(row)
    return out


def load_owners() -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = collections.defaultdict(list)
    with open(OWNERS, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["spawned"] == "yes":
                out[row["shop_key"]].append(row)
    return out


def load_inv_map() -> dict[str, dict]:
    with open(INV_MAP, newline="", encoding="utf-8") as f:
        return {r["shop_key"]: r for r in csv.DictReader(f, delimiter="\t") if r["shop_key"]}


def load_inv_sizes() -> dict[str, int]:
    sizes: dict[str, int] = {}
    name = None
    with open(ALL_INV, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line.startswith("[") and line.endswith("]"):
                name = line[1:-1]
            elif line.startswith("size=") and name:
                sizes[name] = int(line[5:])
    return sizes


# ------------------------------------------------------------------
# Trigger-stub scan: is `[opnpc3,<gameval>]` free to take over?
# ------------------------------------------------------------------


CALL_RE = re.compile(r"^@(\w+);$")


def find_opnpc3_blocks(gameval: str) -> list[tuple[str, int, int, bool]]:
    """Every `[opnpc3,<gameval>]` trigger in the tree: (path, start_line,
    end_line, inline).

    Two shapes content uses for a one-line trigger, both seen in this tree's
    own shop stubs:

        [opnpc3,bob]                       (block form — bob.rs2)
        ~chatnpc(...);
        mes("...nothing to trade...");

        [opnpc3,generalshopkeeper2] @generalshop_trade_stub;   (inline —
                                                          generalshop.rs2)

    `inline=True` means the header line itself carries the whole body after
    the `]`; `inline=False` means the body is every line up to the next
    `[...]` header, matching `find_opnpc3_blocks`'s original block-only
    behaviour. Missing the inline shape was a real bug (2026-08-13): four
    `generalshop.rs2` triggers are inline, `line.strip() != header` never
    matched them, so they read as "no existing trigger" and a freshly
    generated file declared the same `[opnpc3,...]` a second time — the
    duplicate `make mock230-scripts` caught.
    """
    header = f"[opnpc3,{gameval}]"
    hits: list[tuple[str, int, int, bool]] = []
    for path in glob.glob(os.path.join(SCAN_ROOT, "**", "*.rs2"), recursive=True):
        lines = open(path, encoding="utf-8", errors="replace").read().split("\n")
        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped == header:
                j = i + 1
                while j < len(lines) and not (
                    lines[j].startswith("[") and lines[j].rstrip().endswith("]")
                ):
                    j += 1
                hits.append((path, i, j, False))
            elif stripped.startswith(header + " ") or stripped.startswith(header + "\t"):
                hits.append((path, i, i + 1, True))
    return hits


def find_label_body(lines: list[str], name: str) -> list[str] | None:
    """The body of `[label,name]` or `[proc,name]` in `lines`, or None."""
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped in (f"[label,{name}]", f"[proc,{name}]") or re.match(
            rf"^\[proc,{re.escape(name)}\]\(", stripped
        ):
            j = i + 1
            while j < len(lines) and not (lines[j].startswith("[") and lines[j].rstrip().endswith("]")):
                j += 1
            return lines[i + 1 : j]
    return None


def stub_body_ok(lines: list[str], body: list[str]) -> bool:
    """A block is a stub this tool may take over when its last non-blank line
    is either a bare `mes("...nothing to trade...")`, or a call to a label
    whose own body (one level of indirection, checked in the same file) is
    exactly that. The second case is `generalshop.rs2`'s shape:
    `@generalshop_trade_stub;` where `[label,generalshop_trade_stub]`'s whole
    body is the mes() line."""
    last = next((ln for ln in reversed(body) if ln.strip()), "")
    if STUB_MES_RE.match(last):
        return True
    m = CALL_RE.match(last.strip())
    if not m:
        return False
    target = find_label_body(lines, m.group(1))
    if target is None:
        return False
    target_last = next((ln for ln in reversed(target) if ln.strip()), "")
    return bool(STUB_MES_RE.match(target_last))


def patch_stub(path: str, start: int, end: int, inline: bool, replacement_call: str) -> bool:
    """Replace a stub's trailing `mes(...)` (or, for the indirect shape, the
    whole `[opnpc3,...]` line) with a call to the new shop's open label.
    `stub_body_ok` is the check that must have already passed; this function
    trusts it and only re-derives which physical line to rewrite."""
    lines = open(path, encoding="utf-8").read().split("\n")
    if inline:
        gameval = re.match(r"^\[opnpc3,(\w+)\]", lines[start].strip()).group(1)
        lines[start] = f"[opnpc3,{gameval}] {replacement_call}"
        open(path, "w", encoding="utf-8").write("\n".join(lines))
        return True
    body = lines[start + 1 : end]
    last_i = len(body) - 1
    while last_i >= 0 and not body[last_i].strip():
        last_i -= 1
    if last_i < 0:
        return False
    if STUB_MES_RE.match(body[last_i]):
        body[last_i] = replacement_call
    else:
        m = CALL_RE.match(body[last_i].strip())
        if not m:
            return False
        target = find_label_body(lines, m.group(1))
        if target is None:
            return False
        # The call target's own body still says "nothing to trade" and may be
        # shared by other npcs (generalshop_trade_stub is); leave it alone and
        # just stop routing *this* trigger through it.
        body[last_i] = replacement_call
    lines[start + 1 : end] = body
    open(path, "w", encoding="utf-8").write("\n".join(lines))
    return True


# ------------------------------------------------------------------
# Content emission
# ------------------------------------------------------------------


def render_inv(shop_key: str, shop: dict, stock_rows: list[dict], cache_inv: str) -> str:
    lines = [
        GENERATED_MARK,
        f"// {shop['shop_name']}",
        f"// https://oldschool.runescape.wiki/w/{shop['page_title'].replace(' ', '_')}",
        f"// Wiki revision {shop['revid']}, scraped {shop['fetch_date']}.",
        f"[{cache_inv}]",
        "scope=shared",
        "restock=yes",
    ]
    if shop.get("special", "").lower() == "general store":
        lines.append("allstock=yes")
        lines.append("stackall=yes")
    for i, row in enumerate(stock_rows, start=1):
        lines.append(f"stock{i}={row['obj_gameval']},{row['stock']},{row['restock']}")
    lines.append("")
    return "\n".join(lines)


def render_rs2(
    shop_key: str,
    shop: dict,
    owner_gamevals: list[str],
    fresh_gamevals: list[str],
    cache_inv: str,
) -> str:
    """`fresh_gamevals` (a subset of `owner_gamevals`) get a `[opnpc3,...]`
    trigger declared here. The rest already have one — an existing "nothing to
    trade" stub this run's `patch_stub` rewrote in place to call this shop's
    open label directly — and declaring it a second time here would be the
    same trigger bound twice (a real duplicate the compiler warns about and
    silently resolves by last-compiled-wins, not a state to ship)."""
    label = f"{shop_key}_open"
    title = shop["shop_name"].replace('"', "'")
    triggers = "\n".join(f"[opnpc3,{g}] @{label};" for g in fresh_gamevals)
    patched_note = (
        f"// {', '.join(sorted(set(owner_gamevals) - set(fresh_gamevals)))} already had an "
        f"[opnpc3] trade stub — that trigger now calls @{label} in place.\n"
        if set(owner_gamevals) - set(fresh_gamevals)
        else ""
    )
    lines = [
        GENERATED_MARK,
        f"// {shop['shop_name']}",
        f"// https://oldschool.runescape.wiki/w/{shop['page_title'].replace(' ', '_')}",
        f"// Wiki revision {shop['revid']}, scraped {shop['fetch_date']}.",
        f"// Owner: {', '.join(owner_gamevals)}. "
        f"{'Members. ' if shop.get('members', '').lower().startswith('y') else ''}"
        f"{shop.get('special', '')}.",
        patched_note.rstrip("\n"),
        "",
        triggers,
        "",
        f"[label,{label}]",
        f'~openshop({cache_inv}, {shop["buymultiplier"]}, {shop["sellmultiplier"]}, '
        f'{shop["delta"]}, "{title}");',
        "",
    ]
    return "\n".join(l for l in lines if l is not None)


def call_for_stub(shop_key: str) -> str:
    return f"@{shop_key}_open;"


# ------------------------------------------------------------------
# The pass
# ------------------------------------------------------------------


def run(write: bool) -> None:
    catalog = load_catalog()
    stock = load_stock()
    owners = load_owners()
    inv_map = load_inv_map()
    sizes = load_inv_sizes()

    skipped = collections.Counter()
    claimed_invs: dict[str, str] = {}
    generated: list[str] = []
    already_generated: list[str] = []

    for shop_key in sorted(catalog):
        shop = catalog[shop_key]

        if shop["duplicate_of"]:
            skipped["duplicate"] += 1
            continue
        # A `__N` key is not, on its own, a reason to skip — `__1` (the base
        # table) is an ordinary shop that happens to share its page with a
        # conditional sub-stock, and generates exactly like any other shop.
        # A `__2`/`__3` sub-table only reaches here with a *verified* binding
        # if `gen_shop_inv_map.py`'s skillcape-naming derivation matched it
        # (docs/SHOPS_PLAN.md §8) — everything else stays gated by "inv
        # binding not verified" below, same as a single-table shop would be.
        if not (shop["sellmultiplier"] and shop["buymultiplier"] and shop["delta"]):
            skipped["not coin-priced"] += 1
            continue
        if int(shop["lines_needing_review"]) or not int(shop["lines"]):
            skipped["stock has unreviewed lines"] += 1
            continue

        live_owners = sorted({o["npc_gameval"] for o in owners.get(shop_key, [])})
        if not live_owners:
            skipped["no spawned owner"] += 1
            continue

        binding = inv_map.get(shop_key)
        if not binding or binding["confidence"] != "verified" or not binding["cache_inv"]:
            skipped["inv binding not verified"] += 1
            continue
        cache_inv = binding["cache_inv"]

        # Already generated by an earlier run: a no-op, not a failure, and —
        # critically — not something to re-scan for a "bare stub" to patch.
        # The stub this shop's *first* run patched now ends in its own
        # `@..._open;` call, which no longer looks like a stub to the scan
        # below; without this early exit every already-generated shop would
        # misreport as "not a bare trade stub" on every later run.
        area = slug(shop.get("location") or "misc")
        rs2_path = os.path.join(SHOP_ROOT, area, "scripts", f"{shop_key}.rs2")
        inv_path = os.path.join(SHOP_ROOT, area, "configs", f"{shop_key}.inv")
        if os.path.exists(rs2_path) and os.path.exists(inv_path):
            head = open(rs2_path, encoding="utf-8").read(len(GENERATED_MARK) + 8)
            if GENERATED_MARK in head:
                claimed_invs[cache_inv] = shop_key
                already_generated.append(shop_key)
                continue

        if cache_inv in claimed_invs:
            skipped[f"inv '{cache_inv}' already claimed by {claimed_invs[cache_inv]}"] += 1
            continue

        rows = [r for r in stock[shop_key] if r["obj_gameval"]]
        if len(rows) != int(shop["lines"]):
            skipped["some stock lines have no obj_gameval"] += 1
            continue
        size = sizes.get(cache_inv)
        if size is None:
            skipped[f"inv '{cache_inv}' has no cache size"] += 1
            continue
        if len(rows) > size:
            skipped[f"stock ({len(rows)}) exceeds inv '{cache_inv}' size ({size})"] += 1
            continue

        # Every live owner's op3 trigger must be free — absent, or a stub this
        # tool can safely replace. One unsafe/ambiguous owner blocks the whole
        # shop rather than binding only some of its staff. `fresh` gamevals
        # (no existing trigger at all) get one declared in the new file;
        # `patched` ones keep their existing trigger, rewritten in place to
        # call the same label — declaring both would bind op3 twice.
        patches: list[tuple[str, int, int, bool]] = []
        fresh: list[str] = []
        patched_gamevals: list[str] = []
        blocked = False
        for gameval in live_owners:
            hits = find_opnpc3_blocks(gameval)
            if len(hits) == 0:
                fresh.append(gameval)
                continue
            if len(hits) > 1:
                skipped[f"[opnpc3,{gameval}] appears in >1 file"] += 1
                blocked = True
                break
            path, start, end, inline = hits[0]
            lines = open(path, encoding="utf-8", errors="replace").read().split("\n")
            body = [lines[start].split("]", 1)[1].strip()] if inline else lines[start + 1 : end]
            if not stub_body_ok(lines, body):
                skipped[f"[opnpc3,{gameval}] is not a bare trade stub"] += 1
                blocked = True
                break
            patches.append((path, start, end, inline))
            patched_gamevals.append(gameval)
        if blocked:
            continue

        # `area` and both paths were already computed for the early-exit check
        # above; only a partial/foreign write survives to here (one of the two
        # files exists and lacks the mark — hand-authored, or a previous run's
        # rs2 without its inv, or vice versa).
        scripts_dir = os.path.join(SHOP_ROOT, area, "scripts")
        configs_dir = os.path.join(SHOP_ROOT, area, "configs")
        for path in (rs2_path, inv_path):
            if os.path.exists(path):
                head = open(path, encoding="utf-8").read(len(GENERATED_MARK) + 8)
                if GENERATED_MARK not in head:
                    skipped[f"{os.path.basename(path)} exists and is not generated"] += 1
                    blocked = True
        if blocked:
            continue

        claimed_invs[cache_inv] = shop_key
        generated.append(shop_key)

        if not write:
            continue

        os.makedirs(scripts_dir, exist_ok=True)
        os.makedirs(configs_dir, exist_ok=True)
        open(rs2_path, "w", encoding="utf-8").write(
            render_rs2(shop_key, shop, live_owners, fresh, cache_inv)
        )
        open(inv_path, "w", encoding="utf-8").write(
            render_inv(shop_key, shop, rows, cache_inv)
        )
        for path, start, end, inline in patches:
            ok = patch_stub(path, start, end, inline, call_for_stub(shop_key))
            if not ok:
                print(f"warning: {path}: stub patch expected but did not apply "
                      f"(re-scan drifted?) for {shop_key}", file=sys.stderr)

    print(
        f"{len(generated)} shop(s) generated"
        + (" (dry run)" if not write else "")
        + f", {len(already_generated)} already up to date"
    )
    for reason, count in skipped.most_common():
        print(f"  {count:4d}  skipped: {reason}")
    if generated:
        inv_of = {k: i for i, k in claimed_invs.items()}
        print("\ngenerated:")
        for k in generated:
            print(f"  {k} -> {inv_of.get(k, '?')}")


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--write", action="store_true", help="write files and patch stubs (default: report only)")
    args = ap.parse_args()
    run(args.write)


if __name__ == "__main__":
    main()
