#!/usr/bin/env python3
"""Generate the STASH-unit loc categories.

Reads   OSRS-Content/osrs239-content/configs/all.loc
Writes  OSRS-Content/osrs239-content/server/scripts/trail/configs/trail_stash.loc

The hidey-hole locs carry `op1=Build` / `op2=Search` and no category, so a
handler would have to bind 44 names twice over. They divide by their own naming
— `hidey_unbuilt_<kind>_<tier>` against `hidey_<kind>_<tier>` — and that is the
division the ops need. Derived rather than typed so absorbing a cache that adds
a stash picks it up.

Only locs that actually state Build or Search are categorised: four `hidey_*`
records do not, and giving those a stash category would put a Build option on
scenery.

  python3 tools/gen_stash_locs.py [--check]
"""

import argparse
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(ROOT, "OSRS-Content", "osrs239-content")
OUT = os.path.join(
    CONTENT, "server", "scripts", "trail", "configs", "trail_stash.loc"
)
OUT_ENUM = os.path.join(
    CONTENT, "server", "scripts", "trail", "configs", "trail_stash.enum"
)

TIERS = ["beginner", "easy", "medium", "hard", "elite", "master"]


def tier_of(name):
    """The clue tier a hidey loc serves, from its own name."""
    for index, tier in enumerate(TIERS):
        if name.endswith("_" + tier):
            return index
    return None


def render_enum(unbuilt, built):
    """unbuilt -> built, and loc -> tier, for both forms.

    A script cannot read a loc's NAME, so the two facts this file's naming
    carries have to be tabled for it. Derived here so that absorbing a cache
    which adds a stash picks it up, rather than being 44 hand-written rows.
    """
    pairs = []
    for name in unbuilt:
        mate = name.replace("hidey_unbuilt_", "hidey_", 1)
        if mate in built:
            pairs.append((name, mate))
    lines = [
        "// STASH units — what an unbuilt unit becomes, and which tier each serves.",
        "//",
        "// GENERATED by tools/gen_stash_locs.py. Hand edits are lost.",
        "//",
        "// A script cannot read a loc's name, so the two facts the naming carries —",
        "// `hidey_unbuilt_<kind>_<tier>` pairs with `hidey_<kind>_<tier>`, and the",
        "// suffix is the clue tier — are tabled for it.",
        "",
        "[stash_built_form]",
        "inputtype=loc",
        "outputtype=loc",
        "default=null",
    ]
    for name, mate in pairs:
        lines.append("val=%s,%s" % (name, mate))
    lines.append("")
    lines.append("// Tier ids match `^trail_tier_*`: beginner 0 .. master 5.")
    lines.append("[stash_tier]")
    lines.append("inputtype=loc")
    lines.append("outputtype=int")
    lines.append("default=-1")
    for name in unbuilt + built:
        tier = tier_of(name)
        if tier is not None:
            lines.append("val=%s,%d" % (name, tier))
    lines.append("")
    return "\n".join(lines), len(pairs)


def collect():
    text = open(os.path.join(CONTENT, "configs", "all.loc"), encoding="utf-8",
                errors="replace").read()
    built, unbuilt = [], []
    for block in re.split(r"\n(?=\[)", text):
        head = re.match(r"\[(hidey_[^\]]+)\]", block)
        if not head:
            continue
        if not re.search(r"^op\d=(Build|Search)", block, re.M):
            continue
        (unbuilt if head.group(1).startswith("hidey_unbuilt_") else built).append(
            head.group(1)
        )
    return sorted(unbuilt), sorted(built)


def render(unbuilt, built):
    lines = [
        "// STASH units — the two categories the cache leaves off.",
        "//",
        "// GENERATED by tools/gen_stash_locs.py. Hand edits are lost.",
        "//",
        "// The hidey-hole locs carry `op1=Build` / `op2=Search` and NO category, so",
        "// a handler would have to bind every name twice over. They divide cleanly by",
        "// their own naming — `hidey_unbuilt_<kind>_<tier>` against",
        "// `hidey_<kind>_<tier>` — and that division is exactly the one the ops need:",
        "// Build belongs to the unbuilt form and Search to the built one.",
        "//",
        "// Only locs that actually state Build or Search are listed. Four `hidey_*`",
        "// records do not (the noticeboard, the `_noop` variants, the `_shortcut`",
        "// rock) and giving them a stash category would put a Build option on",
        "// scenery.",
        "",
    ]
    for name in unbuilt:
        lines += ["[%s]" % name, "category=trail_stash_unbuilt", ""]
    for name in built:
        lines += ["[%s]" % name, "category=trail_stash_built", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    unbuilt, built = collect()
    rendered = render(unbuilt, built)
    if args.check:
        enum, _ = render_enum(unbuilt, built)
        for path, want in ((OUT, rendered), (OUT_ENUM, enum)):
            try:
                have = io.open(path, encoding="utf-8").read()
            except FileNotFoundError:
                print("gen_stash_locs: %s does not exist" % path, file=sys.stderr)
                return 1
            if have != want:
                print("gen_stash_locs: %s is stale — rerun the generator" % path,
                      file=sys.stderr)
                return 1
        print("gen_stash_locs: up to date")
        return 0
    io.open(OUT, "w", encoding="utf-8").write(rendered)
    enum, pairs = render_enum(unbuilt, built)
    io.open(OUT_ENUM, "w", encoding="utf-8").write(enum)
    print("gen_stash_locs: %d unbuilt, %d built, %d pair(s)"
          % (len(unbuilt), len(built), pairs))
    return 0


if __name__ == "__main__":
    sys.exit(main())
