#!/usr/bin/env python3
"""Generate the Ancient Curses server-side configs from the rev558 book table.

Names, levels and book order come from
`docs/rs558_ancient_curses/tables/curses_book.csv`, extracted from the cache.
Two things the cache does not state are supplied here and sourced in the
comments they are written into:

  drain   the 2011 wiki gives seconds-per-prayer-point; this engine's
          [timer,prayer_drain] wants a per-tick accumulator value. Two
          conversions, not one: drain = 36 / seconds-per-point (calibrated
          exactly against Thick Skin, drain 1, client tooltip "1pt per 36s"),
          and the wiki states its seconds on RuneScape's TEN-TIMES prayer
          pool — 990 points at 99 Prayer, where this engine has 99. Same
          wall-clock duration means ten times the seconds per point here:
          drain = 3.6 / wiki-seconds-per-point. See ANCIENT_CURSES.md §6.1.

  group   mutual-exclusion sets, from Void_RS2011Server's prayers.toml.

Writes under OSRS-Content/osrs239-content/server/scripts/ported_rs558_ancient_curses:
  configs/curses.constant  ^curse_* indices, ^curse_count, group ids
  configs/curses.dbtable   the table
  configs/curses.dbrow     20 rows
"""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BOOK = ROOT / "docs/rs558_ancient_curses/tables/curses_book.csv"
LANE = ROOT / "OSRS-Content/osrs239-content/server/scripts/ported_rs558_ancient_curses"

# drain = 3.6 / wiki-seconds-per-point (ANCIENT_CURSES.md §6.1)
#
# These were ten times larger at launch, from reading the wiki's seconds-per-
# point as if its pool were this engine's. It is not: 99 Prayer is 990 points
# there and 99 here, so a curse that lasts 3m18s in 2011 emptied a bar in 20
# seconds here. Deflect Melee is the check that settles it — an overhead
# protect prayer drains the same in every era, and the standard book in this
# tree gives Protect from Melee drain 12, which is what Deflect Melee is now.
DRAIN_EXACT = {"Protect Item": 2, "Berserker": 2, "Wrath": 3,
               "Soul Split": 18, "Turmoil": 18}
DRAIN_FAMILY = (("Sap", 15), ("Deflect", 12), ("Leech", 10))

# Mutual-exclusion groups, from Void_RS2011Server/data/skill/prayer/prayers.toml.
GROUPS = {
    "Protect Item": [], "Sap Warrior": [11], "Sap Ranger": [14], "Sap Mage": [13],
    # Deflect Summoning carries the overhead group (12) as well as its own (9).
    #
    # Source 2 has it in 9 alone, and rev558 agrees with that reading — it ships
    # COMBINED overhead icons (group 440 frames 16/17/18) for Deflect Summoning
    # paired with each of the other three, which only makes sense if the pair is
    # legal. This tree cannot draw that pair: rev 239's appearance block carries
    # ONE overhead index, so a second lit overhead is not merely unpainted, it is
    # unsendable. Every curse that draws an icon is therefore exclusive with
    # every other one, which is the rule the two ends can both keep.
    "Sap Spirit": [16], "Berserker": [], "Deflect Summoning": [9, 12],
    "Deflect Magic": [12], "Deflect Missiles": [12], "Deflect Melee": [12],
    "Leech Attack": [11], "Leech Ranged": [14], "Leech Magic": [13],
    "Leech Defence": [15], "Leech Strength": [10], "Leech Energy": [],
    "Leech Special Attack": [16], "Wrath": [8, 9, 12], "Soul Split": [8, 9, 12],
    "Turmoil": [10, 11, 13, 14, 15, 16],
}

# Overhead icons — frames of the `headicons_prayer` sprite group, which the lane
# ships whole (tools/gen_curses_headicons.py) with rev558's own six curse icons
# appended after the base cache's 24. -1 means the curse draws none.
#
# These were 0/1/2/7/3/5 at launch, which is to say the standard book's Protect
# from Melee/Missiles/Magic, a melee+missiles COMBINED icon, Retribution and
# Redemption. Every one was the wrong picture — a Soul Split player wore
# Redemption's heart — and the wrongness was invisible from the content side,
# because -1 and 0..7 are all valid numbers in a column of numbers.
HEADICON = {"Deflect Melee": 24, "Deflect Missiles": 25, "Deflect Magic": 26,
            "Deflect Summoning": 27, "Wrath": 28, "Soul Split": 29}

GROUP_NAMES = [
    ("^curse_group_deathfx", 8), ("^curse_group_summoning", 9),
    ("^curse_group_attack", 10), ("^curse_group_melee", 11),
    ("^curse_group_overhead", 12), ("^curse_group_magic", 13),
    ("^curse_group_ranged", 14), ("^curse_group_defence", 15),
    ("^curse_group_drainspec", 16),
]

GENERATED = ("// Generated by tools/gen_curses_server_configs.py from the rev558 "
             "cache table.\n// Do not hand-edit; edit the generator.\n")


def slug(name: str) -> str:
    return name.lower().replace(" ", "")


def drain_for(name: str) -> int:
    if name in DRAIN_EXACT:
        return DRAIN_EXACT[name]
    for prefix, value in DRAIN_FAMILY:
        if name.startswith(prefix):
            return value
    raise SystemExit(f"no drain rule for {name!r}")


def main() -> int:
    rows = list(csv.DictReader(BOOK.open()))
    if len(rows) != 20:
        raise SystemExit(f"expected 20 curses, found {len(rows)}")
    (LANE / "configs").mkdir(parents=True, exist_ok=True)
    (LANE / "scripts").mkdir(parents=True, exist_ok=True)

    out = [GENERATED,
           "// Curse indices, in book order — the cache's enum 863 order, which is",
           "// also the bit order of the active mask.", ""]
    out += [f"^curse_{slug(r['name'])} = {r['bit']}" for r in rows]
    out += ["", f"^curse_count = {len(rows)}", "",
            "// Mutual-exclusion group ids, carried as a LIST on each row."]
    out += [f"{n} = {v}" for n, v in GROUP_NAMES]
    # Everything below was hand-added to the generated file after this tool last
    # ran, in spite of its "do not hand-edit" header — which is a fair sign the
    # header is not enough on its own. Folded in here so the next regeneration
    # keeps them: dropping ^curse_stat_* alone would fail the whole tree's
    # compile, and ^curse_berserker_percent is live in
    # player/scripts/stat_restore.rs2.
    out += ["",
            "// Stat selectors for the leech/drain meters. A varp cannot be addressed by",
            "// index, so these pick a branch rather than an array slot.",
            "^curse_stat_attack = 0",
            "^curse_stat_strength = 1",
            "^curse_stat_defence = 2",
            "^curse_stat_ranged = 3",
            "^curse_stat_magic = 4",
            "",
            "// 2011 wiki ceilings: a leech boost tops out at 10%, a sap/leech drain at 25%.",
            "^curse_leech_cap = 10",
            "^curse_drain_cap = 25",
            "",
            "// Berserker: \"Boosted combat stats last 15% longer\" (2011 wiki). Read by",
            "// player/scripts/stat_restore.rs2, which lengthens its restore interval by this",
            "// percentage while the curse is on.",
            "^curse_berserker_percent = 15"]
    out += ["",
            "// Overhead icons — frames of the `headicons_prayer` sprite group. The",
            "// base cache ends at 23; 24 and up are rev558's own, appended by",
            "// tools/gen_curses_headicons.py and present only in the curses cache.",
            "// Named here for the same reason skill_prayer names its six: a raw",
            "// number in the headicon column is indistinguishable from a wrong one."]
    out += [f"^headicon_curse_{slug(name)} = {icon}"
            for name, icon in sorted(HEADICON.items(), key=lambda kv: kv[1])]
    (LANE / "configs/curses.constant").write_text("\n".join(out) + "\n")

    (LANE / "configs/curses.dbtable").write_text(
        GENERATED +
        "//\n"
        "// Mirrors skill_prayer/configs/prayers.dbtable. `bit` and `curse` hold the\n"
        "// same number here, unlike the standard book, because the cache lists the\n"
        "// curses in book order — position IS the bit. Both columns are kept so the\n"
        "// two tables read alike and a future reordering has somewhere to go.\n"
        "//\n"
        "// No `sound` column: curse activation sounds ride the animation frames\n"
        "// (ANCIENT_CURSES.md §3.5), so playing one here would double it up.\n\n"
        "[curse_table]\n"
        "column=curse,int,INDEXED,REQUIRED\n"
        "column=name,string,REQUIRED\n"
        "column=level,int,REQUIRED\n"
        "column=drain,int,REQUIRED\n"
        "column=headicon,int,REQUIRED\n"
        "column=group,int,LIST\n"
        "column=bit,int,INDEXED,REQUIRED\n")

    body = [GENERATED,
            "// Levels and names are the cache's; drain is 3.6/seconds-per-point from",
            "// the 2011 wiki (whose seconds are per point of a ten-times pool, so the",
            "// divisor is 3.6 and not 36); groups are Void_RS2011Server's.", ""]
    for r in rows:
        name = r["name"]
        s = slug(name)
        body += [f"[curse_{s}]", "table=curse_table",
                 f"data=curse,^curse_{s}", f"data=bit,{r['bit']}",
                 f"data=name,{name}", f"data=level,{r['level']}",
                 f"data=drain,{drain_for(name)}",
                 f"data=headicon,{('^headicon_curse_' + s) if name in HEADICON else -1}"]
        body += [f"data=group,{g}" for g in GROUPS[name]]
        body.append("")
    (LANE / "configs/curses.dbrow").write_text("\n".join(body) + "\n")

    print(f"wrote curses.constant / .dbtable / .dbrow for {len(rows)} curses")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
