#!/usr/bin/env python3
"""Generate the Ancient Curses server-side configs from the rev558 book table.

Names, levels and book order come from
`docs/rs558_ancient_curses/tables/curses_book.csv`, extracted from the cache.
Two things the cache does not state are supplied here and sourced in the
comments they are written into:

  drain   the 2011 wiki gives seconds-per-prayer-point; this engine's
          [timer,prayer_drain] wants a per-tick accumulator value. The
          conversion is drain = 36 / seconds-per-point, calibrated exactly
          against Thick Skin (drain 1, and the client tooltip says 36s).
          See ANCIENT_CURSES.md §6.1.

  group   mutual-exclusion sets, from Void_RS2011Server's prayers.toml.

Writes under OSRS-Content/osrs239-content/server/scripts/ported_rs558_ancient_curses:
  configs/curses.constant  ^curse_* indices, ^curse_count, group ids
  configs/curses.dbtable   the table
  configs/curses.dbrow     20 rows
"""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BOOK = ROOT / "docs/rs558_ancient_curses/tables/curses_book.csv"
LANE = ROOT / "OSRS-Content/osrs239-content/server/scripts/ported_rs558_ancient_curses"

# drain = 36 / seconds-per-point (ANCIENT_CURSES.md §6.1)
DRAIN_EXACT = {"Protect Item": 20, "Berserker": 20, "Wrath": 30,
               "Soul Split": 180, "Turmoil": 180}
DRAIN_FAMILY = (("Sap", 150), ("Deflect", 120), ("Leech", 100))

# Mutual-exclusion groups, from Void_RS2011Server/data/skill/prayer/prayers.toml.
GROUPS = {
    "Protect Item": [], "Sap Warrior": [11], "Sap Ranger": [14], "Sap Mage": [13],
    "Sap Spirit": [16], "Berserker": [], "Deflect Summoning": [9],
    "Deflect Magic": [12], "Deflect Missiles": [12], "Deflect Melee": [12],
    "Leech Attack": [11], "Leech Ranged": [14], "Leech Magic": [13],
    "Leech Defence": [15], "Leech Strength": [10], "Leech Energy": [],
    "Leech Special Attack": [16], "Wrath": [8, 9, 12], "Soul Split": [8, 9, 12],
    "Turmoil": [10, 11, 13, 14, 15, 16],
}

# Overhead icons. The Deflect four reuse the standard book's protect-prayer
# icons; Wrath and Soul Split have their own. -1 means the curse draws none.
HEADICON = {"Deflect Melee": 0, "Deflect Missiles": 1, "Deflect Magic": 2,
            "Deflect Summoning": 7, "Wrath": 3, "Soul Split": 5}

GROUP_NAMES = [
    ("^curse_group_deathfx", 8), ("^curse_group_summoning", 9),
    ("^curse_group_attack", 10), ("^curse_group_melee", 11),
    ("^curse_group_overhead", 12), ("^curse_group_magic", 13),
    ("^curse_group_ranged", 14), ("^curse_group_defence", 15),
    ("^curse_group_drainspec", 16),
]

GENERATED = ("// Generated by tools/gen_curses_server_configs.py from the rev558 "
             "cache table.\n// Do not hand-edit; edit the generator.\n")


def slug(name: str) -> str:
    return name.lower().replace(" ", "")


def drain_for(name: str) -> int:
    if name in DRAIN_EXACT:
        return DRAIN_EXACT[name]
    for prefix, value in DRAIN_FAMILY:
        if name.startswith(prefix):
            return value
    raise SystemExit(f"no drain rule for {name!r}")


def main() -> int:
    rows = list(csv.DictReader(BOOK.open()))
    if len(rows) != 20:
        raise SystemExit(f"expected 20 curses, found {len(rows)}")
    (LANE / "configs").mkdir(parents=True, exist_ok=True)
    (LANE / "scripts").mkdir(parents=True, exist_ok=True)

    out = [GENERATED,
           "// Curse indices, in book order — the cache's enum 863 order, which is",
           "// also the bit order of the active mask.", ""]
    out += [f"^curse_{slug(r['name'])} = {r['bit']}" for r in rows]
    out += ["", f"^curse_count = {len(rows)}", "",
            "// Mutual-exclusion group ids, carried as a LIST on each row."]
    out += [f"{n} = {v}" for n, v in GROUP_NAMES]
    (LANE / "configs/curses.constant").write_text("\n".join(out) + "\n")

    (LANE / "configs/curses.dbtable").write_text(
        GENERATED +
        "//\n"
        "// Mirrors skill_prayer/configs/prayers.dbtable. `bit` and `curse` hold the\n"
        "// same number here, unlike the standard book, because the cache lists the\n"
        "// curses in book order — position IS the bit. Both columns are kept so the\n"
        "// two tables read alike and a future reordering has somewhere to go.\n"
        "//\n"
        "// No `sound` column: curse activation sounds ride the animation frames\n"
        "// (ANCIENT_CURSES.md §3.5), so playing one here would double it up.\n\n"
        "[curse_table]\n"
        "column=curse,int,INDEXED,REQUIRED\n"
        "column=name,string,REQUIRED\n"
        "column=level,int,REQUIRED\n"
        "column=drain,int,REQUIRED\n"
        "column=headicon,int,REQUIRED\n"
        "column=group,int,LIST\n"
        "column=bit,int,INDEXED,REQUIRED\n")

    body = [GENERATED,
            "// Levels and names are the cache's; drain is 36/seconds-per-point from the",
            "// 2011 wiki; groups are Void_RS2011Server's.", ""]
    for r in rows:
        name = r["name"]
        s = slug(name)
        body += [f"[curse_{s}]", "table=curse_table",
                 f"data=curse,^curse_{s}", f"data=bit,{r['bit']}",
                 f"data=name,{name}", f"data=level,{r['level']}",
                 f"data=drain,{drain_for(name)}",
                 f"data=headicon,{HEADICON.get(name, -1)}"]
        body += [f"data=group,{g}" for g in GROUPS[name]]
        body.append("")
    (LANE / "configs/curses.dbrow").write_text("\n".join(body) + "\n")

    print(f"wrote curses.constant / .dbtable / .dbrow for {len(rows)} curses")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
