#!/usr/bin/env python3
"""Generate the achievement-diary task registry from the pinned wiki pages.

Reads   docs/diaries/sources/*_Diary.wiki
Writes  OSRS-Content/osrs239-content/server/scripts/interface_diaries/configs/diary_tasks.dbrow

WHAT THIS DOES AND DOES NOT DO
------------------------------
The task TEXT and its (area, tier, number) are generated. The task's completion
CONDITION is not, and cannot be: the wiki states requirements as prose
("Partial completion of Dragon Slayer I", "30 coins or an activated ring of
Charos"), and the cache states nothing at all — the diary task list is not in
cache.osrs239 in any form, checked against every enum, dbtable and struct.

So this is the registry, which is the half that can be derived. It gives:

  * the diary panel a real task list per area and tier, in the wiki's own
    numbering and wording;
  * a stable `(area, tier, index)` id space for content to call
    `~diary_task_complete` against as each task's hook is written;
  * the per-tier task COUNTS, which is what the completion check needs.

Near-Reality carries the same registry inside twelve Java classes with the
conditions inlined. Splitting them is what lets the registry be generated at all.

  python3 tools/gen_diary_tasks.py [--check]
"""

import argparse
import collections
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCES = os.path.join(ROOT, "docs", "diaries", "sources")
OUT = os.path.join(
    ROOT, "OSRS-Content", "osrs239-content", "server", "scripts",
    "interface_diaries", "configs", "diary_tasks.dbrow",
)

# The area ids are `enum_595`'s, read out of configs/all.enum — the cache's own
# numbering for the twelve diaries, so the panel and this table agree.
AREAS = {
    "Karamja": 0,
    "Ardougne": 1,
    "Falador": 2,
    "Fremennik": 3,
    "Kandarin": 4,
    "Desert": 5,
    "Lumbridge & Draynor": 6,
    "Morytania": 7,
    "Varrock": 8,
    # Wilderness is 9 and Western Provinces is 10, which is the opposite of
    # alphabetical and the opposite of what this map said at first. Both
    # `enum_595` and `interface_diaries/configs/diaries.constant` say so, and
    # they were written independently — `~diary_registry_agrees` compares the
    # generated per-tier counts against the authored totals and reported eight
    # disagreeing pairs, all of them these two diaries, which is the check
    # earning its place on its first run.
    "Wilderness": 9,
    "Western Provinces": 10,
    "Kourend & Kebos": 11,
}
TIERS = {"Easy": 0, "Medium": 1, "Hard": 2, "Elite": 3}

TABLE = re.compile(
    r'data-diary-name="([^"]+)"\s+data-diary-tier="([^"]+)"(.*?)(?=\n\|\}|\Z)', re.S
)
ROW = re.compile(r"^\|\s*(\d+)\.\s*(.+?)\s*$", re.M)


def strip_markup(text):
    """Wikitext -> the sentence a player reads."""
    text = re.sub(r"\{\{SCP\|([^|}]+)\|(\d+)[^}]*\}\}", r"\1 \2", text)
    text = re.sub(r"\{\{NA\|([^}]*)\}\}", r"\1", text)
    text = re.sub(r"\{\{[^{}]*\}\}", "", text)
    text = re.sub(r"\[\[[^\]|]*\|([^\]]*)\]\]", r"\1", text)
    text = re.sub(r"\[\[([^\]]*)\]\]", r"\1", text)
    text = re.sub(r"<ref[^>]*>.*?</ref>", "", text, flags=re.S)
    text = re.sub(r"<[^>]+>", "", text)
    text = text.replace("'''", "").replace("''", "")
    text = re.sub(r"\s+", " ", text).strip()
    # The dbrow grammar splits on commas, so a task's own commas are escaped
    # exactly as the cache export escapes them.
    return text.replace(",", "\\\\,")


def collect():
    tasks = []
    unknown = collections.Counter()
    for path in sorted(glob.glob(os.path.join(SOURCES, "*_Diary.wiki"))):
        text = open(path, encoding="utf-8", errors="replace").read()
        for name, tier, body in TABLE.findall(text):
            area = AREAS.get(name.strip())
            tier_id = TIERS.get(tier.strip())
            if area is None or tier_id is None:
                unknown["%s/%s" % (name, tier)] += 1
                continue
            for number, raw in ROW.findall(body):
                clean = strip_markup(raw)
                if not clean:
                    continue
                tasks.append((area, tier_id, int(number), clean))
    return tasks, unknown


def render(tasks, unknown):
    per = collections.Counter((a, t) for a, t, _, _ in tasks)
    lines = [
        "// Achievement diaries — the task registry.",
        "//",
        "// GENERATED by tools/gen_diary_tasks.py from the pinned wikitext in",
        "// docs/diaries/sources/. Hand edits are lost.",
        "//",
        "//     python3 tools/gen_diary_tasks.py",
        "//",
        "// The task TEXT and its (area, tier, number) are generated. The task's",
        "// completion CONDITION is not, and cannot be: the wiki states requirements",
        "// as prose, and cache.osrs239 states the task list nowhere at all — checked",
        "// against every enum, dbtable and struct it holds.",
        "//",
        "// So this is the half that can be derived, and it is the half the rest",
        "// needs: the panel gets a real list in the wiki's own numbering, and content",
        "// gets a stable (area, tier, index) to call `~diary_task_complete` against",
        "// as each hook is written. Area ids are `enum_595`'s — the cache's own",
        "// numbering for the twelve diaries, so the panel and this table agree.",
        "",
        "[diary_task_table]",
        "table=diary_task",
    ]
    for area, tier, number, text in sorted(tasks):
        lines.append("data=task,%d,%d,%d,%s" % (area, tier, number, text))
    lines.append("")
    lines.append("// Tasks per (area, tier), which is what a completion check needs.")
    lines.append("[diary_task_counts]")
    lines.append("table=diary_task_count")
    for (area, tier), count in sorted(per.items()):
        lines.append("data=count,%d,%d,%d" % (area, tier, count))
    lines.append("")
    if unknown:
        lines.append("// Task tables whose diary name or tier this generator does not know:")
        for key, count in unknown.most_common():
            lines.append("//   %s (%d)" % (key, count))
        lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    tasks, unknown = collect()
    rendered = render(tasks, unknown)

    if args.check:
        try:
            have = open(OUT, encoding="utf-8").read()
        except FileNotFoundError:
            print("gen_diary_tasks: %s does not exist" % OUT, file=sys.stderr)
            return 1
        if have != rendered:
            print("gen_diary_tasks: %s is stale — rerun the generator" % OUT, file=sys.stderr)
            return 1
        print("gen_diary_tasks: up to date")
        return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(rendered)
    per_area = collections.Counter(a for a, _, _, _ in tasks)
    print("gen_diary_tasks: %d task(s) over %d diaries" % (len(tasks), len(per_area)))
    for name, area in sorted(AREAS.items(), key=lambda kv: kv[1]):
        print("  %-20s %3d" % (name, per_area.get(area, 0)))
    if unknown:
        print("  unknown tables: %s" % ", ".join(unknown))
    return 0


if __name__ == "__main__":
    sys.exit(main())
