#!/usr/bin/env python3
"""Generate rev_245_2_dat2_cache.ini from legacy dat1 sprite cache bindings."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Legacy revconfig name -> dat2 sprite archive id (table 8 / sprites).
# Values derived from RuneStar names.tsv; sideicon_N handled separately.
LEGACY_SPRITE_MAP: dict[str, int] = {
    "invback": 297,       # tradebacking
    "chatback": 1017,     # chat_background
    "mapback": 12,
    "backbase1": 1032,    # side_background_bottom
    "backbase2": 1032,
    "backleft1": 4,
    "backleft2": 1034,    # side_background_left2
    "backright1": 1035,   # side_background_right
    "backright2": 1035,
    "backtop1": 1036,     # side_background_top
    "backvmid1": 1031,    # side_background
    "backvmid2": 1031,
    "backvmid3": 1032,
    "backhmid1": 1031,
    "backhmid2": 1032,
    "mapscene": 317,
    "mapfunction": 1448,  # mapfunction,0 (multi-frame atlas differs on dat2)
    "hitmarks": 1358,     # hitmark,0
    "headicons": 439,     # headicons_pk
    "cross": 299,
    "compass": 169,
    "mapedge": 424,
    "redstone1": 998,     # tabs_split,0
    "redstone1h": 998,
    "redstone1v": 998,
    "redstone1hv": 998,
    "redstone2": 999,
    "redstone2h": 999,
    "redstone2v": 999,
    "redstone2hv": 999,
    "redstone3": 1000,
    "redstone3v": 1000,
    "scrollbar0": 316,
    "scrollbar1": 316,
}

SIDEICON_BASE_ID = 774  # sideicons_interface,0

# Dat1-only keys omitted from dat2 output; dat2 uses table=sprites + archive_id instead.
DAT1_ONLY_KEYS = frozenset({
    "table", "archive", "container", "index", "filename", "format",
})

PASSTHROUGH_KEYS = (
    "atlas_index",
    "atlas_count",
    "crop_x",
    "crop_y",
    "crop_width",
    "crop_height",
    "transform1",
    "transform2",
    "transform3",
    "transform4",
)


def parse_legacy_cache_sections(path: Path) -> list[tuple[str, dict[str, str]]]:
    """Return ordered (section_name, keyvals) pairs from a dat1 cache ini."""
    sections: list[tuple[str, dict[str, str]]] = []
    current_name: str | None = None
    current_kv: dict[str, str] = {}

    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        m = re.match(r"\[sprite:([^\]]+)\]", stripped)
        if m:
            if current_name is not None:
                sections.append((current_name, current_kv))
            current_name = m.group(1)
            current_kv = {}
            continue
        if current_name is None or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        current_kv[key.strip()] = value.strip()

    if current_name is not None:
        sections.append((current_name, current_kv))
    return sections


def emit_sprite_section(
    lines: list[str],
    name: str,
    archive_id: int,
    legacy_kv: dict[str, str],
) -> None:
    lines.append(f"[sprite:{name}]")
    lines.append("table=sprites")
    lines.append(f"archive_id={archive_id}")
    for key in PASSTHROUGH_KEYS:
        if key in legacy_kv:
            lines.append(f"{key}={legacy_kv[key]}")
    lines.append("")


def emit_ui_cache_ini(legacy_sections: list[tuple[str, dict[str, str]]]) -> str:
    lines = [
        "# Dat2 UI sprite cache bindings for rev_245_2.",
        "# Generated by tools/gen_dat2_ui_cache.py",
        "#",
        "# Dat1 rev_245_2_dat1_cache.ini uses table=configs + jagfile fields.",
        "# Dat2 rev_245_2_dat2_cache.ini uses table=sprites + archive_id instead.",
        "",
    ]

    for name, legacy_kv in legacy_sections:
        if name == "sideicons":
            for i in range(13):
                sid = f"sideicon_{i}"
                emit_sprite_section(lines, sid, SIDEICON_BASE_ID + i, {"atlas_index": "0"})
            continue

        archive_id = LEGACY_SPRITE_MAP.get(name)
        if archive_id is None:
            print(f"warning: no mapping for legacy sprite '{name}'", file=sys.stderr)
            continue

        emit_sprite_section(lines, name, archive_id, legacy_kv)

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--legacy-cache",
        type=Path,
        default=Path("src/osrs/revconfig/configs/rev_245_2/rev_245_2_dat1_cache.ini"),
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("src/osrs/revconfig/configs/rev_245_2/rev_245_2_dat2_cache.ini"),
    )
    args = parser.parse_args()

    legacy_sections = parse_legacy_cache_sections(args.legacy_cache)
    content = emit_ui_cache_ini(legacy_sections)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content)
    print(f"wrote {args.out} ({len(legacy_sections)} legacy sections)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
