#!/usr/bin/env python3
"""Turn `param=levelrequire,<stat>,<level>` into a script-readable dbtable.

The equipment level requirement is data — 857 objs, 1,254 (stat, level) pairs —
and it has been data since the Kronos import (docs/LOSTCITY_PORT_TRIAGE.md
§10.1). What it was *not* was readable from a script: `oc_param` maps one id to
one scalar and this is a repeating pair, `fields/obj.ini`'s `[obj.levelrequire]`
says so in the file, and there is no `oc_levelrequire` in the reference's
`engine.rs2` to invent. So the gate stayed in C
(`mock230_equipment_may_wear`) and `[opheld2,_]` could not be bound without
silently dropping it.

A dbtable is the third option that comment does not consider, and it is the
reference's own mechanism for repeating tabular content data
(`combat.dbtable`'s `column=damagestyle,int,LIST`).

------------------------------------------------------------------
The shape, and why it is keyed by the requirement and not by the obj
------------------------------------------------------------------

The obvious table is one row per obj with a LIST of (stat, level) tuples: 857
rows, 857 names in `configs/all.dbrow.compack`. The one this emits is the
transpose — one row per **distinct (stat, level) pair**, holding the LIST of
objs that require it:

    [levelrequire_attack_60]
    table=levelrequire_table
    data=stat,attack
    data=level,60
    data=obj,3a_axe
    ...

That is **125 rows** rather than 857, because the requirements repeat hard: 111
objs want Defence 40 and 67 want Defence 70. And the read is one `db_find` with
no arithmetic, because `db_find` on a LIST column means *contains*
(`mock230_ops_db.c`, `SS_OP_DB_FIND`) — so "which requirements does this obj
have" is literally "which rows contain it", and `db_findnext` walks them:

    db_find(levelrequire_table:obj, $obj);
    def_dbrow $row = db_findnext;
    while ($row ! null) { ... $row = db_findnext; }

The obj-keyed shape would need the script to walk a tuple list and index two
parallel columns by hand. This one needs neither.

------------------------------------------------------------------
Row order is load-bearing, and it is (stat id, level)
------------------------------------------------------------------

`db_find` returns matches in **load order**, and a player short in two skills is
told about exactly one of them — the first. The C this replaces named the first
requirement in the `.obj` file's own line order. Rows are therefore emitted
sorted by (stat id, level), which reproduces that order for 855 of the 857 objs,
because the `.obj` files list their requirements in stat-id order.

The two that differ are `toxic_tots_charged` and `toxic_tots_uncharged` in
`equipment_disputed.obj`, which say magic-then-attack at the same level 75; a
player short in both is now told about Attack rather than Magic. Both are noted
in that file as unreachable in this world. Stated here rather than fixed by
carrying a per-obj order, which the transpose cannot hold.

------------------------------------------------------------------
Two files hold this now, and the cross-check is not in this tool
------------------------------------------------------------------

The `.obj` params stay the authored home: `equipment.obj` is written by
`tools/kronos_item_import.py` and a human edits `equipment_disputed.obj` and
`equipment_lostcity.obj` by hand, one line per fact, next to the item. This file
is the generated *index* of them, the way `configs/all.obj.compack` is a
generated index, and it says so in its own header.

`--check` exits non-zero when the emitted text would differ, for a build gate.
But the check that matters is not textual: `mock230 --selftest` walks every
`Mock230ObjRequire` the `.obj` loader built and asserts the dbtable agrees, pair
for pair, in both directions — because that is the one place both forms are
loaded at once, and a drift that a regeneration would fix silently is exactly
what a diff of generated output cannot catch.

    tools/gen_levelrequire_dbrow.py --tree OSRS-Content/osrs239-content [--check]

then `tools/ss_allocate.py --tree ...` to give the new rows ids.
"""

import argparse
import os
import re
import sys

CONFIG_DIR = 'server/scripts/skill_combat/configs'
SOURCES = ('equipment.obj', 'equipment_disputed.obj', 'equipment_lostcity.obj')
TABLE_NAME = 'levelrequire_table'

GENERATED = (
    '// GENERATED by tools/gen_levelrequire_dbrow.py — do not hand-edit.\n'
    '//\n'
    '// The authored home of these facts is `param=levelrequire,<stat>,<level>`\n'
    '// in equipment.obj / equipment_disputed.obj / equipment_lostcity.obj. Edit\n'
    '// those and regenerate; a hand edit here is lost on the next run and the\n'
    '// selftest ("the level requirement gate is content\'s") turns red because\n'
    '// the two forms stop agreeing.\n'
    '//\n'
)


def stat_ids(tree):
    ids = {}
    with open(os.path.join(tree, 'pack', 'stat.pack'), encoding='utf-8') as handle:
        for line in handle:
            line = re.sub(r'//.*$', '', line).strip()
            if '=' in line:
                number, name = line.split('=', 1)
                ids[name.strip()] = int(number)
    return ids


def read_requirements(tree):
    """{obj name: [(stat, level), ...]} in file order."""
    out = {}
    for source in SOURCES:
        path = os.path.join(tree, CONFIG_DIR, source)
        current = None
        with open(path, encoding='utf-8') as handle:
            for line in handle:
                line = re.sub(r'//.*$', '', line).strip()
                if line.startswith('[') and line.endswith(']'):
                    current = line[1:-1]
                elif line.startswith('param=levelrequire,'):
                    _, stat, level = line[len('param='):].split(',')
                    out.setdefault(current, []).append((stat, int(level)))
    return out


def render(tree):
    ids = stat_ids(tree)
    requirements = read_requirements(tree)

    rows = {}
    for obj, pairs in requirements.items():
        for pair in pairs:
            rows.setdefault(pair, []).append(obj)

    lines = [GENERATED]
    lines.append('// %d objs, %d (stat, level) pairs, %d distinct requirements.\n\n'
                 % (len(requirements), sum(len(v) for v in requirements.values()), len(rows)))
    for (stat, level) in sorted(rows, key=lambda p: (ids[p[0]], p[1])):
        lines.append('[levelrequire_%s_%d]\n' % (stat, level))
        lines.append('table=%s\n' % TABLE_NAME)
        lines.append('data=stat,%s\n' % stat)
        lines.append('data=level,%d\n' % level)
        for obj in sorted(rows[(stat, level)]):
            lines.append('data=obj,%s\n' % obj)
        lines.append('\n')
    return ''.join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--tree', required=True)
    ap.add_argument('--check', action='store_true',
                    help='exit non-zero if the file is not what would be written')
    args = ap.parse_args()

    path = os.path.join(args.tree, CONFIG_DIR, 'levelrequire.dbrow')
    text = render(args.tree)

    if args.check:
        have = open(path, encoding='utf-8').read() if os.path.exists(path) else None
        if have != text:
            sys.stderr.write('%s is stale; re-run without --check\n' % path)
            return 1
        return 0

    with open(path, 'w', encoding='utf-8') as handle:
        handle.write(text)
    sys.stderr.write('%s: %d rows\n' % (path, text.count('\ntable=')))
    return 0


if __name__ == '__main__':
    sys.exit(main())
