#!/usr/bin/env python3
"""Emit src/osrs/lua_sidecar/lua_api_ht.c — run: python3 tools/ci/gen_lua_api_ht.py"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INC_DIR = ROOT / "src/osrs/lua_sidecar"
OUT_C = INC_DIR / "lua_api_ht.c"
OUT_JS = ROOT / "src/platforms/browser2/luajs_api_maps.js"
INC_FILES = [
    "lua_buildcachedat_api.inc",
    "lua_game_api.inc",
    "lua_dash_api.inc",
    "lua_ui_api.inc",
    "lua_sidecar_misc_api.inc",
]

ROW_RE = __import__("re").compile(
    r'LUA_API_X\s*\(\s*(\w+)\s*,\s*"([^"]+)"\s*,\s*(\w+)\s*,\s*"([^"]*)"\s*\)'
)


def fnv1a32(data: bytes, seed: int = 0x811C9DC5) -> int:
    h = seed & 0xFFFFFFFF
    for b in data:
        h ^= b
        h = (h * 0x01000193) & 0xFFFFFFFF
    return h


def djb2(data: bytes) -> int:
    h = 5381
    for b in data:
        h = ((h << 5) + h + b) & 0xFFFFFFFF
    return h


def poly_mix(data: bytes, seed: int) -> int:
    h = seed & 0xFFFFFFFF
    for b in data:
        h = (h * 0x5BD1E995 + b) & 0xFFFFFFFF
        h ^= h >> 15
    return h


DOM_MAP = {
    "LUA_DOMAIN_BUILDCACHEDAT": 0,
    "LUA_DOMAIN_GAME": 1,
    "LUA_DOMAIN_DASH": 2,
    "LUA_DOMAIN_UI": 3,
    "LUA_DOMAIN_MISC": 4,
}


def parse_rows_full() -> list[tuple[str, str, str, str]]:
    rows = []
    for fn in INC_FILES:
        text = (INC_DIR / fn).read_text()
        for m in ROW_RE.finditer(text):
            rows.append((m.group(1), m.group(2), m.group(3), m.group(4)))
    return rows


def parse_rows() -> list[tuple[str, int]]:
    rows = parse_rows_full()
    return [(full, i + 1) for i, (_e, full, _d, _s) in enumerate(rows)]


def id_to_full(keys: list[tuple[str, int]], eid: int) -> str:
    for f, i in keys:
        if i == eid:
            return f
    raise KeyError(eid)


def emit_js_maps() -> str:
    rows = parse_rows_full()
    by_dom: list[list[tuple[str, int]]] = [[] for _ in range(5)]
    for i, (_eid, _full, dom_s, suf) in enumerate(rows):
        api_id = i + 1
        d = DOM_MAP[dom_s]
        by_dom[d].append((suf, api_id))
    lines = [
        "/* Generated by tools/ci/gen_lua_api_ht.py — DO NOT EDIT */",
        "/** @type {readonly Map<string, number>[]} */",
        "export const luaApiDomainMaps = [",
    ]
    for d in range(5):
        pairs = ", ".join(f'["{k}", {v}]' for k, v in by_dom[d])
        lines.append(f"  new Map([{pairs}]),")
    lines.append("];")
    lines.append("")
    return "\n".join(lines) + "\n"


def build_table(keys: list[tuple[str, int]], mod: int, mix) -> tuple[list[int], list[int], int] | None:
    slot_id = [0] * mod
    slot_kh = [0] * mod
    max_probe = 0

    def empty(i: int) -> bool:
        return slot_id[i] == 0 and slot_kh[i] == 0

    for full, eid in keys:
        data = full.encode("utf-8")
        kh = mix(data) & 0xFFFFFFFF
        i0 = kh % mod
        placed = False
        for step in range(mod):
            i = (i0 + step) % mod
            if empty(i):
                slot_id[i] = eid
                slot_kh[i] = kh
                max_probe = max(max_probe, step)
                placed = True
                break
            if slot_kh[i] == kh:
                ex = id_to_full(keys, slot_id[i])
                if ex == full:
                    placed = True
                    break
                continue
        if not placed:
            return None

    for full, eid in keys:
        data = full.encode("utf-8")
        kh = mix(data) & 0xFFFFFFFF
        i0 = kh % mod
        found = False
        for step in range(mod):
            i = (i0 + step) % mod
            if empty(i):
                break
            if slot_kh[i] != kh:
                continue
            if slot_id[i] == eid and id_to_full(keys, slot_id[i]) == full:
                found = True
                break
        if not found:
            return None
    return slot_id, slot_kh, max_probe


def pick_best(keys: list[tuple[str, int]]):
    best = None
    n = len(keys)
    for p2 in range(7, 12):
        mod = 1 << p2
        if mod < int(n * 1.05):
            continue
        for seed in range(0, 128):
            for hname, mix in (
                ("fnv1a", lambda b, s=seed: fnv1a32(b, 0x811C9DC5 ^ (s & 0xFFFF))),
                ("djb2_xor", lambda b, s=seed: (djb2(b) ^ s) & 0xFFFFFFFF),
                ("poly", lambda b, s=seed: poly_mix(b, s)),
            ):
                r = build_table(keys, mod, mix)
                if r is None:
                    continue
                _sid, _skh, maxp = r
                score = (maxp, mod, hname, seed)
                if best is None or score < best[0]:
                    best = (score, mod, hname, seed, mix, r)
    if best is None:
        raise RuntimeError("no hash table")
    return best[1], best[2], best[3], best[4], best[5]


def emit_c(mod: int, hname: str, seed: int, slot_id: list[int], slot_kh: list[int], maxp: int) -> str:
    lines = [
        "/* Generated by tools/ci/gen_lua_api_ht.py — DO NOT EDIT */",
        '#include "lua_api.h"',
        "#include <assert.h>",
        "#include <stdint.h>",
        "#include <string.h>",
        "",
        f"/* {hname} mod={mod} max_probe={maxp} seed={seed} */",
        "",
        "static uint32_t",
        "lua_api_hash_mix(const char* s, size_t n)",
        "{",
    ]
    if hname == "fnv1a":
        lines += [
            f"    uint32_t h = 0x811C9DC5u ^ (uint32_t)({seed & 0xFFFF}u);",
            "    for (size_t i = 0; i < n; i++) {",
            "        h ^= (uint32_t)(unsigned char)s[i];",
            "        h *= 0x01000193u;",
            "    }",
            "    return h;",
        ]
    elif hname == "djb2_xor":
        lines += [
            "    uint32_t h = 5381u;",
            "    for (size_t i = 0; i < n; i++)",
            "        h = ((h << 5u) + h + (uint32_t)(unsigned char)s[i]) & 0xFFFFFFFFu;",
            f"    return h ^ (uint32_t){seed}u;",
        ]
    else:
        lines += [
            f"    uint32_t h = (uint32_t){seed}u;",
            "    for (size_t i = 0; i < n; i++) {",
            "        h = (h * 0x5BD1E995u + (uint32_t)(unsigned char)s[i]) & 0xFFFFFFFFu;",
            "        h ^= h >> 15;",
            "    }",
            "    return h;",
        ]
    lines += ["}", "", f"#define LUA_API_HT_MOD {mod}u", ""]
    lines.append("static const uint16_t k_lua_api_ht_slot_id[LUA_API_HT_MOD] = {")
    for v in slot_id:
        lines.append(f"    {v}u,")
    lines.append("};")
    lines.append("")
    lines.append("static const uint32_t k_lua_api_ht_slot_kh[LUA_API_HT_MOD] = {")
    for v in slot_kh:
        lines.append(f"    0x{v:08X}u,")
    lines.append("};")
    lines.append("")
    lines += [
        "LuaApiId",
        "lua_api_lookup_full(const char* s, size_t n)",
        "{",
        "    if (!s || n == 0)",
        "        return LUA_API_INVALID;",
        "    uint32_t kh = lua_api_hash_mix(s, n);",
        "    uint32_t i0 = kh % LUA_API_HT_MOD;",
        "    for (uint32_t step = 0; step < LUA_API_HT_MOD; step++) {",
        "        uint32_t i = (i0 + step) % LUA_API_HT_MOD;",
        "        if (k_lua_api_ht_slot_id[i] == 0 && k_lua_api_ht_slot_kh[i] == 0)",
        "            return LUA_API_INVALID;",
        "        if (k_lua_api_ht_slot_kh[i] != kh) {",
        "            continue;",
        "        }",
        "        LuaApiId id = (LuaApiId)k_lua_api_ht_slot_id[i];",
        "        const char* exp = lua_api_full_string(id);",
        "        if (exp && strlen(exp) == n && memcmp(exp, s, n) == 0)",
        "            return id;",
        "    }",
        "    return LUA_API_INVALID;",
        "}",
        "",
        "void",
        "lua_api_ht_verify(void)",
        "{",
        "#ifndef NDEBUG",
        "    for (LuaApiId id = (LuaApiId)1; (int)id < LUA_API__COUNT; id = (LuaApiId)((int)id + 1)) {",
        "        const char* s = lua_api_full_string(id);",
        "        assert(s && s[0]);",
        "        LuaApiId got = lua_api_lookup_full(s, strlen(s));",
        "        assert(got == id);",
        "    }",
        "#endif",
        "}",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    keys = parse_rows()
    if not keys:
        print("no rows", file=sys.stderr)
        return 1
    mod, hname, seed, _mix, r = pick_best(keys)
    sid, skh, maxp = r
    OUT_C.write_text(emit_c(mod, hname, seed, sid, skh, maxp))
    OUT_JS.write_text(emit_js_maps())
    print(f"Wrote {OUT_C} n={len(keys)} mod={mod} {hname} seed={seed} max_probe={maxp}")
    print(f"Wrote {OUT_JS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
