#!/usr/bin/env python3
"""
gen_slayer_queue — build docs/SLAYER_CONTENT_QUEUE.md's task table straight
from the cache, so a cache bump regenerates the list instead of someone
retyping 163 rows by hand.

    tools/gen_slayer_queue.py > /tmp/slayer_tasks.md

Reads `configs/all.dbrow` for every `slayer_task` block (columndef=/values=
grammar — the machine export, not the authored `column=`/`data=` grammar
`mock230_db.c` reads) and prints one Markdown table row per task: id, name,
min_comlevel, min_stat_requirement_all (level, stat).

This is a one-shot lister, not a full membership generator — that is
`tools/gen_slayer_membership.py` (Phase 2), which will also need the
npc_stats id-join to place each npc under its task.
"""
import argparse
import os
import re

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DBROW = os.path.join(REPO, "OSRS-Content", "osrs239-content", "configs", "all.dbrow")
MEMBER_DBROW = os.path.join(
    REPO, "OSRS-Content", "osrs239-content", "server", "scripts",
    "skill_slayer", "configs", "slayer_task_member.dbrow",
)


def covered_task_ids(path):
    """task_id values `slayer_task_member.dbrow` already has a row for."""
    if not os.path.exists(path):
        return set()
    txt = open(path, encoding="utf8", errors="replace").read()
    return {int(m) for m in re.findall(r"data=task_id,(\d+)", txt)}


def parse_slayer_tasks(path):
    txt = open(path, encoding="utf8", errors="replace").read()
    rows = []
    for block in txt.split("\n["):
        if "table=slayer_task\n" not in block:
            continue
        tid = re.search(r"columndef=0:id,int\nvalues=0:0:(-?\d+)", block)
        minc = re.search(r"columndef=1:min_comlevel,int\nvalues=1:0:(\d+)", block)
        stat = re.search(
            r"columndef=2:min_stat_requirement_all,int,stat\nvalues=2:0:(\d+),(\d+)",
            block,
        )
        nm = re.search(r"columndef=9:name_lowercase,string\nvalues=9:0:(.*)", block)
        rows.append(
            {
                "id": int(tid.group(1)) if tid else None,
                "min_comlevel": int(minc.group(1)) if minc else 0,
                "min_level": int(stat.group(1)) if stat else 0,
                "name": nm.group(1).strip() if nm else "?",
            }
        )
    return rows


def wiki_task_link(name):
    """Formulaic `Slayer task/<Title Case>` link, matching the convention
    already visible in Slayer_task's own wikitext (`[[Slayer task/TzHaar|...]]`,
    `[[Slayer task/Abyssal demons|...]]`). Not independently verified per row —
    a generated starting point for whoever implements that task to confirm."""
    if not name:
        return name
    title = name if name[:1].isupper() and " " not in name.lower()[:1] else name[0].upper() + name[1:]
    slug = title.replace(" ", "_")
    return f"[{name}](https://oldschool.runescape.wiki/w/Slayer_task/{slug})"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dbrow", default=DBROW)
    ap.add_argument("--status", default="not started",
                     help="status column text stamped on every generated row")
    args = ap.parse_args()

    rows = parse_slayer_tasks(args.dbrow)
    numbered = sorted((r for r in rows if r["id"] and r["id"] > 0), key=lambda r: r["id"])
    bosses = sorted((r for r in rows if not r["id"] or r["id"] < 0), key=lambda r: r["name"])
    covered = covered_task_ids(MEMBER_DBROW)

    print(f"<!-- generated by tools/gen_slayer_queue.py — {len(numbered)} tasks, {len(bosses)} boss rows, {len(covered)} with membership -->")
    print()
    print("| id | task | min combat | min Slayer lvl | status |")
    print("|--:|---|--:|--:|---|")
    for r in numbered:
        status = "membership: Turael-only" if r["id"] in covered else args.status
        print(f"| {r['id']} | {wiki_task_link(r['name'])} | {r['min_comlevel'] or '-'} | {r['min_level'] or '-'} | {status} |")
    print()
    print("### Boss tasks (id = -1, no kill quantity)")
    print()
    print("| task | status |")
    print("|---|---|")
    for r in bosses:
        if r["name"]:
            print(f"| {wiki_task_link(r['name'])} | {args.status} |")


if __name__ == "__main__":
    main()
