#!/usr/bin/env python3
"""Generate the treasure-trail step pools from the cache.

A clue trail advances by replacing the player's clue obj with another step of
the same tier, drawn at random. rev239 states which objs are steps and which
tier each belongs to -- `param=trail_is_<tier>` plus `param=trail_clue_row`
into the `cluehelper_clue_*` database -- but nothing in the cache states the
*pool*: there is no "all easy steps" list, because the client never needs one.
The server does, so it is derived here rather than typed.

Reads   OSRS-Content/osrs239-content/configs/all.obj
        OSRS-Content/osrs239-content/configs/all.obj.compack   (ids, for sort)
Writes  OSRS-Content/osrs239-content/server/scripts/trail/configs/trail_steps.enum

Rerun after any cache absorb. The output is machine-owned: hand edits are lost,
which is why the header says so in the file itself.

  python3 tools/gen_trail_steps.py [--check]

`--check` regenerates into memory and diffs, so CI can fail on a stale file
without writing to the tree.
"""

import argparse
import os
import re
import sys

TIERS = [
    ("beginner", "trail_is_beginner"),
    ("easy", "trail_is_easy"),
    ("medium", "trail_is_medium"),
    ("hard", "trail_is_hard"),
    ("elite", "trail_is_elite"),
    ("master", "trail_is_master"),
]

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(ROOT, "OSRS-Content", "osrs239-content")
ALL_OBJ = os.path.join(CONTENT, "configs", "all.obj")
COMPACK = os.path.join(CONTENT, "configs", "all.obj.compack")
OUT = os.path.join(
    CONTENT, "server", "scripts", "trail", "configs", "trail_steps.enum"
)


def read_ids():
    ids = {}
    with open(COMPACK, encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("//") or "=" not in line:
                continue
            num, name = line.split("=", 1)
            if num.strip().isdigit():
                ids[name.strip()] = int(num)
    return ids


def read_steps():
    """name -> tier, for every obj that is a clue STEP.

    A step is an obj carrying both a tier marker and `trail_clue_row`. The row
    is what makes it a step rather than a casket, a puzzle box, a key or a
    reward: `trail_clue_easy_emote001_casket` carries the easy marker (it is an
    easy-tier item) and no row (it is not a clue you read).
    """
    with open(ALL_OBJ, encoding="utf-8", errors="replace") as handle:
        text = handle.read()
    steps = {}
    for block in re.split(r"\n(?=\[)", text):
        match = re.match(r"\[([^\]]+)\]", block)
        if not match:
            continue
        name = match.group(1)
        params = dict(
            re.findall(r"^param=([A-Za-z_][A-Za-z0-9_]*),int,(-?\d+)$", block, re.M)
        )
        if "trail_clue_row" not in params:
            continue
        for tier, marker in TIERS:
            if params.get(marker) == "1":
                steps.setdefault(tier, []).append(name)
                break
    return steps


def render(steps, ids):
    lines = [
        "// Treasure Trails — the step pool of each tier.",
        "//",
        "// GENERATED by tools/gen_trail_steps.py. Hand edits are lost on the next",
        "// run; the numbers below are read off cache.osrs239 and nothing here is a",
        "// choice. Regenerate after absorbing a cache:",
        "//",
        "//     python3 tools/gen_trail_steps.py",
        "//",
        "// A trail advances by swapping the player's clue obj for another step of the",
        "// same tier. rev239 gives every easy/medium/hard/elite step its own obj id and",
        "// says which tier it is (`param=trail_is_<tier>`) and which clue it carries",
        "// (`param=trail_clue_row`), but never lists a tier's steps together — the",
        "// client has no use for the set. `~trail_advance` does, so it is derived.",
        "//",
        "// Keyed 0..n-1 so a pick is `enum(int, obj, <tier>_steps, random(n))`, with n",
        "// in the companion `trail_step_counts` enum. `default=null` rather than a",
        "// real obj: an out-of-range key is a bug in the caller's random, and a clue",
        "// scroll handed out because the key ran off the end would be indistinguishable",
        "// from a legitimate one.",
        "//",
        "// Beginner and master hold no steps here and that is not an omission — both",
        "// tiers are ONE stackable obj carrying no `trail_clue_row`, so their step is a",
        "// dbrow in a varp (see trail.varp) and there is no pool of objs to draw from.",
        "",
    ]
    counts = []
    for tier, _ in TIERS:
        names = sorted(steps.get(tier, []), key=lambda n: ids.get(n, 1 << 30))
        counts.append((tier, len(names)))
        if not names:
            continue
        lines.append("[trail_%s_steps]" % tier)
        lines.append("inputtype=int")
        lines.append("outputtype=obj")
        lines.append("default=null")
        for index, name in enumerate(names):
            lines.append("val=%d,%s" % (index, name))
        lines.append("")
    lines.append(
        "// How many steps each tier's pool holds, so the caller's `random()` bound"
    )
    lines.append(
        "// comes from the same generated file as the pool it indexes. A tier with no"
    )
    lines.append("// pool answers 0, which is what stops a beginner pick being attempted.")
    lines.append("[trail_step_counts]")
    lines.append("inputtype=int")
    lines.append("outputtype=int")
    lines.append("default=0")
    for index, (tier, count) in enumerate(counts):
        lines.append("val=%d,%d  // %s" % (index, count, tier))
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the file on disk is not what this would write",
    )
    args = parser.parse_args()

    ids = read_ids()
    steps = read_steps()
    rendered = render(steps, ids)

    if args.check:
        try:
            with open(OUT, encoding="utf-8") as handle:
                have = handle.read()
        except FileNotFoundError:
            print("gen_trail_steps: %s does not exist" % OUT, file=sys.stderr)
            return 1
        if have != rendered:
            print(
                "gen_trail_steps: %s is stale — rerun tools/gen_trail_steps.py" % OUT,
                file=sys.stderr,
            )
            return 1
        print("gen_trail_steps: up to date")
        return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(rendered)
    total = sum(len(v) for v in steps.values())
    print(
        "gen_trail_steps: %d step obj(s) -> %s"
        % (total, os.path.relpath(OUT, ROOT))
    )
    for tier, _ in TIERS:
        print("  %-9s %4d" % (tier, len(steps.get(tier, []))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
