#!/usr/bin/env python3
"""gen_tob_nylo_waves — compile the Nylocas wave schedule into content tables.

    tools/gen_tob_nylo_waves.py --write

Reads the wave dataset downloaded to
`docs/minigames/theater_of_blood/sources/blert_nylocas-waves.json` and writes
two tables under `minigame_tob/configs/`:

  * `tob_nylo_wave`  — one row per wave: the natural stall in ticks.
  * `tob_nylo_spawn` — **one row per nylocas**, not per wave. Lane, slot, size,
    aggro flag, the pillar it attacks, and the full three-step flicker rotation,
    each in its own column.

Why one row per nylo rather than one per wave: a wave-shaped table needs six
slots x five facts = thirty columns, and thirty columns of `slot4_midstyle`
are unreadable and unreviewable. A spawn-shaped table is eight columns that
each mean one thing, and the room script iterates the rows for a wave instead
of unpacking a struct. It costs ~110 rows, which is nothing.

The dataset is blert's (`common/data/nylocas-waves.json`), the same data behind
<https://blert.io/guides/tob/nylocas/mechanics>. It is cross-checked against
the OSRS Wiki's wave table and against `NYLOCAS_WAVES` in the OpenOSRS
`theatre` plugin; see docs/minigames/theater_of_blood/nylocas_waves.md.

The `pillar` column comes from a second file, `blert_nylo_pillar_assignment.json`,
which is measured rather than downloaded — nobody publishes the spawn->pillar
mapping, so it was derived from 199 recorded raids by
`tools/derive_tob_nylo_pillars.py`. It joins on (wave, lane, slot), and the join
is required to be total: every spawn must have a verdict, aggro or pillar.

`CORRECTIONS` below is the one place this tool overrides its input. The sources
folder holds evidence, not specification, so a downloaded file is never edited in
place; a disagreement is resolved here, in the open, with its reason attached.

Re-running rewrites both files. Do not hand-edit them.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "docs", "minigames", "theater_of_blood", "sources",
                   "blert_nylocas-waves.json")
OUT_DIR = os.path.join(REPO, "OSRS-Content", "osrs239-content", "server", "scripts",
                       "minigames", "minigame_tob", "configs")
TABLE_OUT = os.path.join(OUT_DIR, "tob_nylo.dbtable")
ROW_OUT = os.path.join(OUT_DIR, "tob_nylo.dbrow")

# Must match ^tob_nylo_style_* / ^tob_nylo_lane_* / ^tob_nylo_pillar_* in
# tob.constant.
STYLE = {"melee": 1, "ranged": 2, "magic": 3}
LANES = [("east", 0), ("south", 1), ("west", 2)]
PILLAR = {None: 0, "SW": 1, "SE": 2, "NW": 3, "NE": 4}

PILLARS_SRC = os.path.join(REPO, "docs", "minigames", "theater_of_blood", "sources",
                           "blert_nylo_pillar_assignment.json")

# (wave, lane, slot) -> replacement rotation, and why. Conflict register C9 in
# THEATRE_OF_BLOOD_PLAN.md.
CORRECTIONS = {
    (30, "south", 1): (
        ["magic", "ranged", "melee"],
        "blert says melee->ranged->melee. The game spawns npc 8344 "
        "`tob_nylocas_incoming_magic` on that tile in 197 of 197 recorded raids, "
        "and the Wiki's wave table spells the cell mag->rng->mel. Left alone, "
        "the tree makes players null this spawn.",
    ),
}

BANNER = """// GENERATED by tools/gen_tob_nylo_waves.py from
// docs/minigames/theater_of_blood/sources/blert_nylocas-waves.json.
// Re-run the tool; do not hand-edit.
//
// The Nylocas room's whole schedule. See
// docs/minigames/theater_of_blood/nylocas_waves.md for the same data as a
// human-readable table, and ENCOUNTER_TIMING.md §4 for what the room does
// with it.
"""


def load() -> list[dict]:
    with open(SRC, encoding="utf-8") as fh:
        waves = json.load(fh)
    for (num, lane, slot), (rot, _why) in CORRECTIONS.items():
        spawn = [w for w in waves if w["num"] == num][0][lane][slot]
        if spawn is None:
            raise SystemExit("correction %d %s %d has no spawn" % (num, lane, slot))
        if spawn["rotation"] == rot:
            raise SystemExit(
                "correction %d %s %d is now a no-op - upstream fixed it, so "
                "delete the entry rather than leaving a lie in the table"
                % (num, lane, slot))
        spawn["rotation"] = rot
    return waves


def load_pillars() -> dict:
    """(wave, lane, slot) -> pillar name, or None for an aggro."""
    with open(PILLARS_SRC, encoding="utf-8") as fh:
        measured = json.load(fh)
    return {(r["wave"], r["lane"], r["slot"]): r["pillar"]
            for r in measured["spawns"]}


def rotation(nylo: dict) -> tuple[int, int, int]:
    """Spawn style, mid-lane style, final style.

    A non-flickering nylo holds one style for its whole walk, so all three are
    the same rather than 0 — the room script then needs no special case, it
    just applies rotation[1] at the halfway tile and rotation[2] two ticks
    later and both are no-ops.
    """
    rot = [STYLE[r] for r in nylo["rotation"]]
    while len(rot) < 3:
        rot.append(rot[-1])
    if len(rot) != 3:
        raise SystemExit("unexpected rotation length %d: %r" % (len(rot), nylo))
    return rot[0], rot[1], rot[2]


def build() -> tuple[str, str, dict]:
    waves = load()
    pillars = load_pillars()
    if len(waves) != 31:
        raise SystemExit("expected 31 waves, got %d" % len(waves))

    table = [BANNER, "", "[tob_nylo_wave]",
             "column=wave,int,INDEXED,REQUIRED",
             "column=stall,int,REQUIRED", "",
             "[tob_nylo_spawn]",
             "column=wave,int,INDEXED,REQUIRED",
             "column=lane,int,REQUIRED",
             "column=slot,int,REQUIRED",
             "column=big,boolean,REQUIRED",
             "column=aggro,boolean,REQUIRED",
             "column=pillar,int,REQUIRED",
             "column=style1,int,REQUIRED",
             "column=style2,int,REQUIRED",
             "column=style3,int,REQUIRED", ""]

    rows = [BANNER, ""]
    stats = {"spawns": 0, "bigs": 0, "aggros": 0, "flickers": 0, "stall_total": 0,
             "pillar": {name: 0 for name in PILLAR if name}}

    for w in waves:
        n = w["num"]
        stats["stall_total"] += w["naturalStall"]
        rows.append("[tob_nylo_wave_%02d]" % n)
        rows.append("table=tob_nylo_wave")
        rows.append("data=wave,%d" % n)
        rows.append("data=stall,%d" % w["naturalStall"])
        rows.append("")

    for w in waves:
        n = w["num"]
        for lane_name, lane_id in LANES:
            for slot, nylo in enumerate(w[lane_name]):
                if nylo is None:
                    continue
                s1, s2, s3 = rotation(nylo)
                key = (n, lane_name, slot)
                if key not in pillars:
                    raise SystemExit(
                        "no measured verdict for wave %d %s slot %d - re-run "
                        "tools/derive_tob_nylo_pillars.py" % key)
                pillar = pillars[key]
                if (pillar is None) != bool(nylo["aggro"]):
                    raise SystemExit(
                        "wave %d %s slot %d: aggro=%s but measured pillar=%r - "
                        "the two datasets disagree about what this spawn does"
                        % (n, lane_name, slot, nylo["aggro"], pillar))
                if pillar:
                    stats["pillar"][pillar] += 1
                stats["spawns"] += 1
                if nylo["big"]:
                    stats["bigs"] += 1
                if nylo["aggro"]:
                    stats["aggros"] += 1
                if len(nylo["rotation"]) > 1:
                    stats["flickers"] += 1
                rows.append("[tob_nylo_spawn_%02d_%s%d]" % (n, lane_name[0], slot))
                rows.append("table=tob_nylo_spawn")
                rows.append("data=wave,%d" % n)
                rows.append("data=lane,%d" % lane_id)
                rows.append("data=slot,%d" % slot)
                # `1`/`0`, NOT `true`/`false` and NOT `yes`/`no`.
                #
                # `boolean` is a LITERAL column type (torirs_server_db.c
                # db_type_is_literal), so it resolves against no pack and
                # row_value() ends at `atoi(expanded)` - and atoi("true") is 0.
                # A file written with the words looks right, loads without a
                # warning, and reads back all-false.
                #
                # This has now been flipped to the words twice and caught twice
                # by ::tobrun, most recently as `big count 0 wanted 43` plus
                # `wave 1 has a pillar-bound spawn with no pillar` (the aggro
                # column collapsing takes the pillar column down with it). If
                # the words are wanted, teach row_value() to parse them first
                # and the four other tables in the tree that are already
                # silently all-false will start working too.
                rows.append("data=big,%d" % (1 if nylo["big"] else 0))
                rows.append("data=aggro,%d" % (1 if nylo["aggro"] else 0))
                rows.append("data=pillar,%d" % PILLAR[pillar])
                rows.append("data=style1,%d" % s1)
                rows.append("data=style2,%d" % s2)
                rows.append("data=style3,%d" % s3)
                rows.append("")

    return "\n".join(table).rstrip() + "\n", "\n".join(rows).rstrip() + "\n", stats


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true", help="write the tables")
    args = ap.parse_args()

    table, rows, stats = build()

    print("waves            : 31")
    print("nylocas spawned  : %d  (%d big, %d aggro, %d flickering)"
          % (stats["spawns"], stats["bigs"], stats["aggros"], stats["flickers"]))
    print("natural stalls   : %d ticks -> wave 31 spawns no earlier than room tick %d"
          % (stats["stall_total"], stats["stall_total"] + 4))
    print("pillar-bound     : %s"
          % "  ".join("%s %d" % (name, stats["pillar"][name])
                      for name in ("SW", "SE", "NW", "NE")))
    for (num, lane, slot), (_rot, why) in CORRECTIONS.items():
        print("correction       : wave %d %s slot %d - %s" % (num, lane, slot, why))

    if not args.write:
        print("\n(dry run; pass --write)")
        return

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(TABLE_OUT, "w", encoding="utf-8") as fh:
        fh.write(table)
    with open(ROW_OUT, "w", encoding="utf-8") as fh:
        fh.write(rows)
    print("\nwrote %s" % os.path.relpath(TABLE_OUT, REPO))
    print("wrote %s" % os.path.relpath(ROW_OUT, REPO))


if __name__ == "__main__":
    sys.exit(main())
