#!/usr/bin/env python3
"""Generate the mock server's region -> music track table.

    tools/gen_music_regions.py > src/net/mock/mock230_music_regions.gen.h

The client cache says which music tracks exist, what they are called, where the
game claims they unlock (as prose) and which varp bit records the unlock. It
does **not** say which map square plays which track -- that mapping is server
data, and there is no copy of it in any cache. So this table is a join of two
sources, both checked in under docs/audio/:

  music_regions.tsv          region id -> track name, extracted from Kronos's
                             MusicPlayer.java (OSRS 184 era, 440 entries over
                             435 distinct map squares)
  music_tracks_osrs239.tsv   track name -> song archive id + unlock (varp, bit),
                             dumped from DBTable 44 of cache.osrs239

Names are matched case-insensitively and against both the display and sort
forms, because the two sources disagree on the capitalisation of small words
("Army Of Darkness" vs "Army of Darkness") and on where the article goes
("Fallen Empire, The" vs "The Fallen Empire").

The output is committed. Regenerate it when either input changes; do not hand
edit it.
"""

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGIONS = ROOT / "docs/audio/music_regions.tsv"
TRACKS = ROOT / "docs/audio/music_tracks_osrs239.tsv"


def load(path):
    # The cache's own strings are windows-1252, which is what the dump carries.
    with open(path, encoding="cp1252") as f:
        return list(csv.DictReader(f, delimiter="\t"))


def main():
    regions = load(REGIONS)
    tracks = load(TRACKS)

    by_name = {}
    for row in tracks:
        for key in (row["display_name"], row["sort_name"]):
            if key:
                by_name.setdefault(key.strip().lower(), row)

    rows = []
    unmatched = []
    for r in regions:
        name = r["track_name"].strip()
        hit = by_name.get(name.lower())
        if not hit:
            unmatched.append(name)
            continue
        varp, bit = -1, -1
        pair = hit.get("unlock_varp,bit") or ""
        if "," in pair:
            varp, bit = (int(x) for x in pair.split(",", 1))
        song = hit.get("song_archive_id")
        if not song:
            unmatched.append(name)
            continue
        rows.append(
            {
                "region": int(r["region_id"]),
                "song": int(song),
                "varp": varp,
                "bit": bit,
                "name": hit["display_name"],
            }
        )

    # One track per square. Five squares are claimed by two tracks upstream
    # (Courage/Long Way Home at 11826, and four more); the first wins and the
    # rest are reported rather than silently dropped.
    seen = {}
    dupes = []
    for row in rows:
        if row["region"] in seen:
            dupes.append((row["region"], seen[row["region"]]["name"], row["name"]))
            continue
        seen[row["region"]] = row

    out = sys.stdout
    out.write("/*\n")
    out.write(" * GENERATED by tools/gen_music_regions.py -- do not edit.\n")
    out.write(" *\n")
    out.write(" * Map square -> music track. See the generator for provenance: this is a\n")
    out.write(" * join of a community region table with the cache's own DBTable 44, because\n")
    out.write(" * no cache states the region mapping at all.\n")
    out.write(" *\n")
    out.write(" * region id = ((tile_x >> 6) << 8) | (tile_z >> 6)\n")
    out.write(" * song      = js5 index 6 archive id, what MIDI_SONG names\n")
    out.write(" * varp/bit  = the unlock flag the music player reads; -1 when unknown\n")
    out.write(" */\n\n")
    out.write("#ifndef SRC_NET_MOCK_MOCK230_MUSIC_REGIONS_GEN_H\n")
    out.write("#define SRC_NET_MOCK_MOCK230_MUSIC_REGIONS_GEN_H\n\n")
    out.write("struct Mock230MusicRegion\n{\n")
    out.write("    int region;\n    int song;\n    int varp;\n    int bit;\n")
    out.write("    const char* name;\n};\n\n")
    out.write("static const struct Mock230MusicRegion k_mock230_music_regions[] = {\n")
    for region in sorted(seen):
        row = seen[region]
        name = row["name"].replace("\\", "\\\\").replace('"', '\\"')
        out.write(
            '    { %5d, %4d, %3d, %3d, "%s" },\n'
            % (row["region"], row["song"], row["varp"], row["bit"], name)
        )
    out.write("};\n\n")
    out.write(
        "static const int k_mock230_music_region_count =\n"
        "    (int)(sizeof(k_mock230_music_regions) / sizeof(k_mock230_music_regions[0]));\n\n"
    )
    out.write("#endif\n")

    sys.stderr.write(
        "gen_music_regions: %d squares, %d unmatched names, %d duplicate squares\n"
        % (len(seen), len(set(unmatched)), len(dupes))
    )
    for name in sorted(set(unmatched)):
        sys.stderr.write("  unmatched: %s\n" % name)
    for region, kept, dropped in dupes:
        sys.stderr.write("  square %d: kept %s, dropped %s\n" % (region, kept, dropped))


if __name__ == "__main__":
    main()
