#!/usr/bin/env python3
"""Generate fishing_movement.enum from this tree's own `.spawn` roster.

    tools/gen_fishing_movement.py --content OSRS-Content/osrs239-content [--check]

docs/FISHING_COMPLETION_PLAN.md S10: OSRS fishing spots teleport between a
fixed per-location set of tiles every 250-530 ticks rather than standing
still forever. LostCity expresses that set as 20 hand-authored coord enums,
one per river/lake — coordinates this tree has no way to verify without a
LostCity checkout, so this generator builds the same shape from data this
tree already trusts instead: the npc roster.

Every fishing-spot npc identifier is already map-square-scoped by name
(`0_40_53_memberfish`, never a bare `memberfish` spawned outside a square —
verified by grep, zero bare-name spawns in the tree), so grouping every
spawn of one identifier into one enum is grouping by construction, not by
guessing a distance threshold: a `0_40_53_*` identifier's spawns are already
confined to one ~64x64 map square. That is coarser than LostCity's own
per-river grouping in a few squares that hold two disconnected pools, but
every candidate tile is a real spawn point already live in this tree, so a
spot can only ever relocate onto ground it (or a sibling of the same
identifier) already legitimately stands on — it cannot walk itself into a
wall the way a hand-typed coordinate could.

One enum per identifier, and `configs/fishing.npc` gets a matching
`param=fishing_movement_enum,<name>` line spliced into that identifier's
existing block (moverestrict=nomove/wanderrange=0 are already there from the
2026-08-12 fix; this generator only ever adds the one param line, never
touches the rest of a block).
"""

import argparse
import pathlib
import re
import sys

FAMILIES = ("memberfish", "freshfish", "saltfish", "rarefish", "lavafish")
# 0_<mx>_<mz>_<family>, the only shape any fishing-spot spawn uses.
SPAWN_RE = re.compile(r"^(0_(\d+)_(\d+)_(?:" + "|".join(FAMILIES) + r"))\s+(\d+)\s+(\d+)\s+(\d+)$")

ENUM_HEADER = """// Fishing spot relocation targets, one enum per map-square-scoped npc
// identifier. Generated by tools/gen_fishing_movement.py from this tree's
// own .spawn roster — see that script's docstring and
// docs/FISHING_COMPLETION_PLAN.md S10 for why this is built from spawns
// rather than ported LostCity coordinates.
//
//     tools/gen_fishing_movement.py --content OSRS-Content/osrs239-content

"""


def collect_spawns(content: pathlib.Path):
    spawns = {}  # identifier -> list[(level, mx, mz, lx, lz)] deduped
    spawn_dir = content / "server/scripts/areas/world/configs"
    for path in sorted(spawn_dir.glob("*.spawn")):
        for line in path.read_text().splitlines():
            m = SPAWN_RE.match(line.strip())
            if not m:
                continue
            ident, mx, mz, x, z, level = m.groups()
            x, z, level = int(x), int(z), int(level)
            lx, lz = x % 64, z % 64
            coord = (level, x // 64, z // 64, lx, lz)
            spawns.setdefault(ident, [])
            if coord not in spawns[ident]:
                spawns[ident].append(coord)
    return spawns


def render_enum(spawns) -> str:
    out = [ENUM_HEADER]
    for ident in sorted(spawns):
        coords = spawns[ident]
        out.append(f"[fishing_movement_{ident}_enum]")
        out.append("inputtype=int")
        out.append("outputtype=coord")
        for i, (level, mx, mz, lx, lz) in enumerate(coords):
            out.append(f"val={i},{level}_{mx}_{mz}_{lx}_{lz}")
        out.append("")
    return "\n".join(out)


def splice_params(npc_path: pathlib.Path, idents) -> tuple[str, list[str]]:
    """Insert `param=fishing_movement_enum,<name>` into each identifier's
    existing [ident] block in fishing.npc, right after the opening header
    line. Returns (new_text, identifiers with no matching block)."""
    text = npc_path.read_text()
    lines = text.split("\n")
    out = []
    seen = set()
    missing = []
    i = 0
    while i < len(lines):
        line = lines[i]
        out.append(line)
        m = re.match(r"^\[(0_\d+_\d+_(?:" + "|".join(FAMILIES) + r"))\]$", line)
        if m and m.group(1) in idents:
            ident = m.group(1)
            seen.add(ident)
            # Skip past any existing fishing_movement_enum param for this
            # block (idempotent re-run) then insert fresh, before the first
            # blank line that closes the block.
            j = i + 1
            block_lines = []
            while j < len(lines) and lines[j].strip() != "":
                if not lines[j].startswith("param=fishing_movement_enum,"):
                    block_lines.append(lines[j])
                j += 1
            block_lines.append(f"param=fishing_movement_enum,fishing_movement_{ident}_enum")
            out.extend(block_lines)
            i = j
            continue
        i += 1
    for ident in idents:
        if ident not in seen:
            missing.append(ident)
    return "\n".join(out), missing


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--content", required=True, type=pathlib.Path)
    ap.add_argument("--check", action="store_true", help="report only, write nothing")
    args = ap.parse_args()

    spawns = collect_spawns(args.content)
    if not spawns:
        print("gen_fishing_movement: no fishing-spot spawns found", file=sys.stderr)
        return 1

    enum_path = args.content / "server/scripts/skill_fishing/configs/fishing_movement.enum"
    npc_path = args.content / "server/scripts/skill_fishing/configs/fishing.npc"

    enum_text = render_enum(spawns)
    npc_text, missing = splice_params(npc_path, set(spawns))

    single = sum(1 for c in spawns.values() if len(c) == 1)
    print(
        f"gen_fishing_movement: {len(spawns)} identifiers, "
        f"{sum(len(c) for c in spawns.values())} coords, "
        f"{single} single-tile (never visibly relocate)",
        file=sys.stderr,
    )
    if missing:
        print(
            f"gen_fishing_movement: {len(missing)} identifier(s) have spawns but no "
            f"fishing.npc block, param not attached: {', '.join(sorted(missing))}",
            file=sys.stderr,
        )

    if args.check:
        return 1 if missing else 0

    enum_path.write_text(enum_text)
    npc_path.write_text(npc_text)
    print(f"gen_fishing_movement: wrote {enum_path}", file=sys.stderr)
    print(f"gen_fishing_movement: rewrote {npc_path}", file=sys.stderr)
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
