#!/usr/bin/env python3
"""Generate the POH quest-list status dispatcher from quest completion data.

The Construction quest list must read another player's progress.  The cache's
normal quest-list clientscript cannot do that: it reads the viewing player's
varps.  quest_cheat.rs2 already contains the authoritative row-to-progress
mapping for every quest implemented by this content tree, so this generator
reuses its non-mutating completion tests rather than maintaining a second map.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "OSRS-Content" / "osrs239-content"
QUEST_CHEAT = CONTENT / "server/scripts/quests/scripts/quest_cheat.rs2"
DBROWS = CONTENT / "configs/all.dbrow"
OUTPUT = (
    CONTENT
    / "server/scripts/skill_construction/scripts/poh_quest_status_generated.rs2"
)


def quest_unstarted_states() -> dict[str, int]:
    result: dict[str, int] = {}
    row_name: str | None = None
    table: str | None = None
    column: int | None = None
    unstarted = 0

    def finish() -> None:
        if row_name is not None and table == "quest":
            result[row_name] = unstarted

    for line in DBROWS.read_text(encoding="latin1").splitlines() + ["[EOF]"]:
        if line.startswith("["):
            finish()
            row_name = line[1:-1]
            table = None
            column = None
            unstarted = 0
        elif line.startswith("table="):
            table = line.removeprefix("table=")
        elif line.startswith("columndef="):
            column = int(line.removeprefix("columndef=").split(":", 1)[0])
        elif table == "quest" and column == 18 and line.startswith("values=18:0:"):
            unstarted = int(line.rsplit(":", 1)[1])
    return result


def completion_arms() -> list[tuple[str, str, str]]:
    source = QUEST_CHEAT.read_text()
    body = source[source.index("[proc,quest_cheat_complete]") :]
    arms: list[tuple[str, str, str]] = []
    position = 0
    while True:
        start = body.find("if ($row = ", position)
        if start < 0:
            break
        header_end = body.find("\n", start)
        row_match = re.fullmatch(r"if \(\$row = ([a-zA-Z0-9_]+)\) \{", body[start:header_end])
        if row_match is None:
            raise ValueError(f"unrecognised quest arm at offset {start}")
        opening = body.find("{", start)
        depth = 0
        end = opening
        while end < len(body):
            depth += body[end] == "{"
            depth -= body[end] == "}"
            end += 1
            if depth == 0:
                break
        arm = body[start:end]
        condition_line = arm.splitlines()[1].strip()
        condition_match = re.fullmatch(r"if \((.+) >= (.+)\) \{", condition_line)
        if condition_match is None:
            raise ValueError(f"unrecognised completion test for {row_match.group(1)}")
        arms.append(
            (row_match.group(1), condition_match.group(1), condition_match.group(2))
        )
        position = end
    return arms


def render() -> str:
    unstarted = quest_unstarted_states()
    arms = completion_arms()
    missing_rows = [row for row, _, _ in arms if row not in unstarted]
    if missing_rows:
        raise ValueError(f"quest rows missing from cache: {', '.join(missing_rows)}")
    arm_rows = [row for row, _, _ in arms]
    if len(set(arm_rows)) != len(arm_rows):
        raise ValueError("duplicate quest rows in quest_cheat_complete")

    lines = [
        "// Generated by tools/generate_poh_quest_status.py; do not hand-edit.",
        "// Source of truth: quests/scripts/quest_cheat.rs2 plus cache quest rows.",
        f"// Coverage: {len(arms)} runnable rows; "
        f"{len(unstarted) - len(arms)} cache rows unavailable in this world.",
        "// 0 = not started, 1 = started, 2 = complete, 3 = unavailable here.",
        "",
        "[proc,poh_quest_status](dbrow $row)(int)",
    ]
    for row, progress, complete in arms:
        lines.extend(
            [
                f"if ($row = {row}) {{",
                f"    if ({progress} >= {complete}) return(2);",
                f"    if ({progress} ! {unstarted[row]}) return(1);",
                "    return(0);",
                "}",
            ]
        )
    lines.extend(["return(3);", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if the generated file is stale"
    )
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            raise SystemExit(
                f"stale generated quest status file: {OUTPUT.relative_to(ROOT)}"
            )
        print(f"current {OUTPUT.relative_to(ROOT)}")
        return
    OUTPUT.write_text(generated)
    print(f"generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
