#!/usr/bin/env python3
"""Author a `category=` on every ladder and staircase this cache states a climb verb on.

Why this exists
---------------
`interaction_engine_loc` in `src/net/mock/mock230_world.c` answered a ladder by
`strcmp`ing the loc's *cache menu verb* — "Climb-up", "Climb-down", or a bare
"Climb" — and moving the player a plane. That is content's job (LostCity puts it
in `content/scripts/ladders+stairs/scripts/`), but content cannot say
"whichever loc's menu says Climb-up": there is no opcode that exposes a loc's
verb, and a trigger's subject is a loc *name* or a *category*.

There are 1,445 such records in cache.osrs239, which rules out a name list kept
by hand. So the verb becomes a category — the record grouped by what it *is* —
and the grouping is derived from the cache rather than chosen, which is what this
script does. The reference does the same thing in the other direction: a
LostCity category is crawled out of the `.loc` blocks that state it, never
looked up (`CategoryType.ts`).

The grouping
------------
A record is grouped by the SET OF DIRECTIONS its climb ops name, not by which op
slot they sit on: a "Climb-up" on op1 and a "Climb-up" on op2 mean the same
thing, and the script binds both slots. Measured on cache.osrs239 there are
exactly 11 distinct (slot, verb) layouts and they collapse to four groups plus
two records that stand alone.

Records carrying two DIFFERENT climb verbs whose layout is not the spiral
staircase's are NOT given a category — one category cannot say "op2 goes up and
op3 goes down" for a group of one. They are reported and bound by name in
`ladders_stairs/scripts/ladders.rs2`.

The two conflict rules
----------------------
**A record another authored `.loc` already categorises is not categorised here.**
A record carries one category and `cachepack` refuses a second, so this is a hard
error rather than a preference. It is not hypothetical: 15 open trapdoors are
`category=door_opened` in `doors/configs/doors.loc` *and* say "Climb-down" on
op1. They are emitted as **name** bindings into a generated
`ladders_stairs/scripts/climb_shared.rs2` instead — the trigger table's name rung
beats its category rung, so `[oploc1,trapdoor_open]` wins over
`[oploc1,_door_opened]` on the same click and the door's own "Close" (op2 on 13
of the 15) stays with the door script.

**A record already carrying a cache category which `pack/category.pack` *names*
is skipped and reported, never overwritten.** The authored overlay wins at load
time, so silently overwriting would unbind whatever that name is for. Measured
today, 194 of the 1,445 carry a cache category across 47 ids and not one of the
47 is named, so nothing is skipped — the rule exists to make the first future
collision loud instead of silent.

Usage
-----
    python3 tools/ladder_import.py [--content <dir>] [--check] [--report]

`--check` writes nothing and exits non-zero if the file on disk differs, which
is what makes "generated, do not edit" enforceable.
"""

import argparse
import collections
import os
import re
import sys

CLIMB_VERBS = ("Climb-up", "Climb-down", "Climb")

# group name -> the set of distinct climb verbs that defines it
SINGLE_VERB_GROUP = {
    "Climb-up": "climb_up",
    "Climb-down": "climb_down",
    "Climb": "climb_unqualified",
}

# The spiral staircase's middle floor: one unqualified op and both directions
# beside it. 32 records in cache.osrs239 and the only multi-verb layout that is
# a group rather than a one-off.
SPIRAL = {1: "Climb", 2: "Climb-up", 3: "Climb-down"}
SPIRAL_GROUP = "climb_spiral_middle"

HEADER = """\
// Ladders, staircases and every other loc whose menu says Climb.
//
// Generated by tools/ladder_import.py — do not edit, re-run the importer.
// `python3 tools/ladder_import.py --check` fails when this file and the cache
// disagree.
//
// One key per block and it is the whole point: the cache says a loc's climb
// *verb*, and no opcode exposes a verb to a script, so the verb is restated as a
// category — which a trigger CAN be bound to. `ladders_stairs/scripts/
// ladders.rs2` binds four of them and covers {covered} of the {total} records
// cache.osrs239 states a climb verb on.
//
// The four groups, and what puts a record in one (see the importer's docstring
// for why the grouping is by direction and not by op slot):
//
{summary}//
// {exceptions_note}
"""


SHARED_HEADER = """\
// Locs that climb but belong to somebody else's category.
//
// Generated by tools/ladder_import.py — do not edit, re-run the importer.
//
// A loc record carries ONE category and `cachepack` refuses a second, so a loc
// that is already `category=door_opened` in `doors/configs/doors.loc` cannot
// also be `category=climb_down` here. All {count} of these are open trapdoors:
// the cache says "Climb-down" on op1 and "Close" on op2, so they are a door and
// a ladder at the same time and each op belongs to a different script.
//
// Bound by NAME, which is what makes it work: the trigger table's type rung
// beats its category rung, so `[oploc1,trapdoor_open]` below wins over
// `[oploc1,_door_opened]` in doors.rs2 for the same click, and the door script
// keeps the "Close" it is actually for.
//
// This is also the first thing that showed `doors.loc`'s op assumption is not
// universal. `[oploc1,_door_closed]` is right 387 times out of 388; the *opened*
// half is "Close" on op1 only 231 times of 388 — 144 records state no Close op
// at all, 13 put it on op2 (which doors.rs2 binds), and the rest say
// Climb-down, Open, Pass-through, Go-down or Peek. The engine's C door swap
// never noticed because it ignored the op number entirely.
"""


def read_pack(path):
    out = {}
    with open(path) as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("//"):
                continue
            key, _, value = line.partition("=")
            try:
                out[value] = int(key)
            except ValueError:
                continue
    return out


def read_other_overlays(content, mine):
    """Every loc name some OTHER authored `.loc` states a `category=` on."""
    claimed = {}
    root = os.path.join(content, "server", "scripts")
    for base, _dirs, files in os.walk(root):
        for name in files:
            path = os.path.join(base, name)
            if not name.endswith(".loc") or os.path.abspath(path) == os.path.abspath(mine):
                continue
            block = None
            with open(path) as handle:
                for line in handle:
                    line = line.strip()
                    match = re.match(r"^\[([^\]]+)\]$", line)
                    if match:
                        block = match.group(1)
                    elif block and line.startswith("category="):
                        claimed[block] = (os.path.relpath(path, content), line.split("=", 1)[1])
    return claimed


def read_configs(path):
    records = {}
    current = None
    with open(path) as handle:
        for raw in handle:
            line = raw.rstrip("\n")
            match = re.match(r"^\[([^\]]+)\]$", line)
            if match:
                current = match.group(1)
                records[current] = {}
                continue
            if current is None or "=" not in line or line.startswith("//"):
                continue
            key, _, value = line.partition("=")
            records[current][key] = value
    return records


def classify(records):
    """name -> (group | None, slot->verb map)"""
    grouped = {}
    exceptions = {}
    for name, record in records.items():
        ops = {}
        for slot in range(1, 6):
            verb = record.get("op%d" % slot)
            if verb in CLIMB_VERBS:
                ops[slot] = verb
        if not ops:
            continue
        verbs = set(ops.values())
        if len(verbs) == 1:
            grouped[name] = (SINGLE_VERB_GROUP[next(iter(verbs))], ops)
        elif ops == SPIRAL:
            grouped[name] = (SPIRAL_GROUP, ops)
        else:
            exceptions[name] = ops
    return grouped, exceptions


def main():
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    parser = argparse.ArgumentParser()
    parser.add_argument("--content", default=os.path.join(here, "OSRS-Content", "osrs239-content"))
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--report", action="store_true")
    args = parser.parse_args()

    content = args.content
    records = read_configs(os.path.join(content, "configs", "all.loc"))
    named_categories = read_pack(os.path.join(content, "pack", "category.pack"))
    category_names = {v: k for k, v in named_categories.items()}

    grouped, exceptions = classify(records)

    out_path = os.path.join(content, "server", "scripts", "ladders_stairs", "configs", "ladders.loc")
    script_path = os.path.join(
        content, "server", "scripts", "ladders_stairs", "scripts", "climb_shared.rs2"
    )

    # Conflict rule 1: a record another authored `.loc` categorises keeps that
    # category and gets a NAME binding here instead. `cachepack` refuses a second
    # `category=` on one record, so this is an error and not a preference.
    claimed = read_other_overlays(content, out_path)
    shared = {}
    for name in sorted(grouped):
        if name in claimed:
            shared[name] = (grouped[name][1], claimed[name])
            del grouped[name]

    # Conflict rule 2: never overwrite a cache category somebody has named.
    skipped = {}
    for name in sorted(grouped):
        cache_category = records[name].get("category")
        if cache_category and int(cache_category) in category_names:
            skipped[name] = (int(cache_category), category_names[int(cache_category)])
    for name in skipped:
        del grouped[name]

    by_group = collections.defaultdict(list)
    for name, (group, _ops) in grouped.items():
        by_group[group].append(name)

    slots = collections.defaultdict(set)
    for name, (group, ops) in grouped.items():
        slots[group].update(ops)

    total = len(grouped) + len(exceptions) + len(skipped) + len(shared)
    summary_lines = []
    for group in ("climb_up", "climb_down", "climb_unqualified", SPIRAL_GROUP):
        members = by_group.get(group, [])
        summary_lines.append(
            "//   %-21s %5d records, ops %s\n"
            % (group, len(members), ",".join(str(s) for s in sorted(slots[group])))
        )
    exceptions_note = (
        "%d records carry two different climb verbs in a layout no group "
        "describes; they are bound by name in ladders.rs2: %s"
        % (len(exceptions), ", ".join(sorted(exceptions)))
    )
    if shared:
        exceptions_note += (
            "\n// %d more are categorised by another authored .loc and are bound by NAME in "
            "scripts/climb_shared.rs2 instead." % len(shared)
        )
    if skipped:
        exceptions_note += "\n// SKIPPED (already carry a NAMED cache category): " + ", ".join(
            "%s -> %d %s" % (n, c, cn) for n, (c, cn) in sorted(skipped.items())
        )

    body = [
        HEADER.format(
            covered=len(grouped),
            total=total,
            summary="".join(summary_lines),
            exceptions_note=exceptions_note,
        )
    ]
    for group in ("climb_up", "climb_down", "climb_unqualified", SPIRAL_GROUP):
        body.append("\n// ---- %s ----\n" % group)
        for name in sorted(by_group.get(group, [])):
            body.append("\n[%s]\ncategory=%s\n" % (name, group))
    text = "".join(body)

    script = [SHARED_HEADER.format(count=len(shared))]
    for name in sorted(shared):
        ops, (where, other) = shared[name]
        script.append(
            "\n// %s — `%s` in %s\n" % (", ".join("op%d %s" % kv for kv in sorted(ops.items())), other, where)
        )
        for slot, verb in sorted(ops.items()):
            script.append(
                "[oploc%d,%s] %s\n"
                % (slot, name, "~climb(-1);" if verb == "Climb-down"
                   else "~climb(1);" if verb == "Climb-up" else "~climb_unqualified;")
            )
    script_text = "".join(script)

    if args.report:
        sys.stdout.write("".join(summary_lines))
        sys.stdout.write("// exceptions: %s\n" % exceptions_note)
        sys.stdout.write("// shared with another overlay: %s\n" % ", ".join(sorted(shared)))
        return 0
    if args.check:
        for path, want in ((out_path, text), (script_path, script_text)):
            try:
                with open(path) as handle:
                    on_disk = handle.read()
            except OSError:
                print("ladder_import: %s is missing" % path, file=sys.stderr)
                return 1
            if on_disk != want:
                print(
                    "ladder_import: %s does not match the cache — re-run tools/ladder_import.py"
                    % path,
                    file=sys.stderr,
                )
                return 1
        return 0
    for path, want in ((out_path, text), (script_path, script_text)):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as handle:
            handle.write(want)
    print("ladder_import: wrote %d blocks to %s" % (len(grouped), out_path))
    print("ladder_import: wrote %d name bindings to %s" % (len(shared), script_path))
    sys.stdout.write("".join(summary_lines))
    print("// exceptions: %s" % exceptions_note)
    return 0


if __name__ == "__main__":
    sys.exit(main())
