#!/usr/bin/env bash
# Capture one named BMP per Shades of Mort'ton interaction.
# Plugins off. Player unkillable. Each shot must show the mesbox/journal/reward.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/OSRS-Content/osrs239-content/server/scripts/selftest/quest_mortton"
# sailing.ini is embed + cache.osrs239 (the boot image). torirs.ini points at
# the composed rs2012-summoning-curses cache, which this image does not ship.
MANIFEST="${MORTTON_MANIFEST:-$ROOT/manifests/manifest_osrs239_sailing.ini}"
if [[ ! -f "$MANIFEST" ]]; then
  MANIFEST="$ROOT/manifests/manifest_osrs239.ini"
fi
mkdir -p "$OUT"
export TORIRS_PLUGINS=0
export TORIRSSERVER_GOD=1
export SDL_VIDEODRIVER=dummy
export PLATFORM_OBJ_BASE="${PLATFORM_OBJ_BASE:-/tmp/gp-mortton-img-obj}"

shots=(
  "001_shelf_find_book:morttonbmp_001_shelf_find_book"
  "002_shelf_no_room:morttonbmp_002_shelf_no_room"
  "003_shelf_nothing:morttonbmp_003_shelf_nothing"
  "004_table_find_herbs:morttonbmp_004_table_find_herbs"
  "005_table_no_room:morttonbmp_005_table_no_room"
  "006_table_empty:morttonbmp_006_table_empty"
  "007_diary_page11_start:morttonbmp_007_diary_page11_start"
  "008_diary_page12:morttonbmp_008_diary_page12"
  "009_diary_page15_flamtaer:morttonbmp_009_diary_page15_flamtaer"
  "010_diary_page20_serum207:morttonbmp_010_diary_page20_serum207"
  "011_diary_page21_garbled:morttonbmp_011_diary_page21_garbled"
  "012_diary_page23_start:morttonbmp_012_diary_page23_start"
  "013_diary_page25_index:morttonbmp_013_diary_page25_index"
  "014_signpost:morttonbmp_014_signpost"
  "015_apothecary_show_book:morttonbmp_015_apothecary_show_book"
  "016_apothecary_herbi:morttonbmp_016_apothecary_herbi"
  "017_apothecary_fyrneght:morttonbmp_017_apothecary_fyrneght"
  "018_apothecary_recipe:morttonbmp_018_apothecary_recipe"
  "019_apothecary_trade_later:morttonbmp_019_apothecary_trade_later"
  "020_apothecary_trade_offer:morttonbmp_020_apothecary_trade_offer"
  "021_apothecary_trade_choice:morttonbmp_021_apothecary_trade_choice"
  "022_apothecary_give_diary:morttonbmp_022_apothecary_give_diary"
  "023_apothecary_keep_diary:morttonbmp_023_apothecary_keep_diary"
  "024_apothecary_keep_shame:morttonbmp_024_apothecary_keep_shame"
  "025_apothecary_already_sold:morttonbmp_025_apothecary_already_sold"
  "026_afflicted_garbled:morttonbmp_026_afflicted_garbled"
  "027_afflicted_no_sense:morttonbmp_027_afflicted_no_sense"
  "028_afflicted_serum207:morttonbmp_028_afflicted_serum207"
  "029_afflicted_serum207_reward:morttonbmp_029_afflicted_serum207_reward"
  "030_afflicted_serum208:morttonbmp_030_afflicted_serum208"
  "031_afflicted_serum208_reward:morttonbmp_031_afflicted_serum208_reward"
  "032_afflicted_cured_talk:morttonbmp_032_afflicted_cured_talk"
  "033_ulsquire_no_serum:morttonbmp_033_ulsquire_no_serum"
  "034_ulsquire_stale_serum:morttonbmp_034_ulsquire_stale_serum"
  "035_ulsquire_own_serum:morttonbmp_035_ulsquire_own_serum"
  "036_ulsquire_hello_again:morttonbmp_036_ulsquire_hello_again"
  "037_ulsquire_questions:morttonbmp_037_ulsquire_questions"
  "038_ulsquire_who:morttonbmp_038_ulsquire_who"
  "039_ulsquire_who_reply:morttonbmp_039_ulsquire_who_reply"
  "040_ulsquire_place:morttonbmp_040_ulsquire_place"
  "041_ulsquire_place_reply:morttonbmp_041_ulsquire_place_reply"
  "042_ulsquire_going_on:morttonbmp_042_ulsquire_going_on"
  "043_ulsquire_going_on_reply:morttonbmp_043_ulsquire_going_on_reply"
  "044_ulsquire_creatures:morttonbmp_044_ulsquire_creatures"
  "045_ulsquire_creatures_reply:morttonbmp_045_ulsquire_creatures_reply"
  "046_ulsquire_talk_to:morttonbmp_046_ulsquire_talk_to"
  "047_ulsquire_talk_to_razmire:morttonbmp_047_ulsquire_talk_to_razmire"
  "048_ulsquire_thanks:morttonbmp_048_ulsquire_thanks"
  "049_ulsquire_perm_serum:morttonbmp_049_ulsquire_perm_serum"
  "050_ulsquire_perm_coins:morttonbmp_050_ulsquire_perm_coins"
  "051_ulsquire_perm_already:morttonbmp_051_ulsquire_perm_already"
  "052_ulsquire_kill_shades_ack:morttonbmp_052_ulsquire_kill_shades_ack"
  "053_ulsquire_kill_shades_reply:morttonbmp_053_ulsquire_kill_shades_reply"
  "054_ulsquire_no_remains:morttonbmp_054_ulsquire_no_remains"
  "055_ulsquire_no_remains_reply:morttonbmp_055_ulsquire_no_remains_reply"
  "056_ulsquire_show_remains:morttonbmp_056_ulsquire_show_remains"
  "057_ulsquire_show_remains_mes:morttonbmp_057_ulsquire_show_remains_mes"
  "058_ulsquire_post_shades_ops:morttonbmp_058_ulsquire_post_shades_ops"
  "059_ulsquire_remains:morttonbmp_059_ulsquire_remains"
  "060_ulsquire_remains_reply:morttonbmp_060_ulsquire_remains_reply"
  "061_ulsquire_temple:morttonbmp_061_ulsquire_temple"
  "062_ulsquire_temple_reply:morttonbmp_062_ulsquire_temple_reply"
  "063_ulsquire_temple_materials:morttonbmp_063_ulsquire_temple_materials"
  "064_ulsquire_serum:morttonbmp_064_ulsquire_serum"
  "065_ulsquire_serum_reply:morttonbmp_065_ulsquire_serum_reply"
  "066_ulsquire_do_now:morttonbmp_066_ulsquire_do_now"
  "067_ulsquire_do_now_reply:morttonbmp_067_ulsquire_do_now_reply"
  "068_ulsquire_rebuild_hello:morttonbmp_068_ulsquire_rebuild_hello"
  "069_ulsquire_rebuild_reply:morttonbmp_069_ulsquire_rebuild_reply"
  "070_ulsquire_rebuild_ops:morttonbmp_070_ulsquire_rebuild_ops"
  "071_ulsquire_temple_built:morttonbmp_071_ulsquire_temple_built"
  "072_ulsquire_temple_built_flame:morttonbmp_072_ulsquire_temple_built_flame"
  "073_ulsquire_olive_oil:morttonbmp_073_ulsquire_olive_oil"
  "074_ulsquire_knockdown:morttonbmp_074_ulsquire_knockdown"
  "075_ulsquire_knockdown_reply:morttonbmp_075_ulsquire_knockdown_reply"
  "076_ulsquire_materials:morttonbmp_076_ulsquire_materials"
  "077_ulsquire_materials_reply:morttonbmp_077_ulsquire_materials_reply"
  "078_ulsquire_sacred_oil:morttonbmp_078_ulsquire_sacred_oil"
  "079_ulsquire_sacred_oil_reply:morttonbmp_079_ulsquire_sacred_oil_reply"
  "080_ulsquire_pyre_logs:morttonbmp_080_ulsquire_pyre_logs"
  "081_ulsquire_pyre_logs_reply:morttonbmp_081_ulsquire_pyre_logs_reply"
  "082_ulsquire_logs_on_pyre:morttonbmp_082_ulsquire_logs_on_pyre"
  "083_ulsquire_logs_on_pyre_reply:morttonbmp_083_ulsquire_logs_on_pyre_reply"
  "084_ulsquire_lit_pyre:morttonbmp_084_ulsquire_lit_pyre"
  "085_ulsquire_lit_pyre_reply:morttonbmp_085_ulsquire_lit_pyre_reply"
  "086_complete_scroll:morttonbmp_086_complete_scroll"
  "087_ulsquire_post_complete:morttonbmp_087_ulsquire_post_complete"
  "088_razmire_no_serum:morttonbmp_088_razmire_no_serum"
  "089_razmire_stale_serum:morttonbmp_089_razmire_stale_serum"
  "090_razmire_own_serum:morttonbmp_090_razmire_own_serum"
  "091_razmire_hello:morttonbmp_091_razmire_hello"
  "092_razmire_questions:morttonbmp_092_razmire_questions"
  "093_razmire_who:morttonbmp_093_razmire_who"
  "094_razmire_who_reply:morttonbmp_094_razmire_who_reply"
  "095_razmire_who_store_choice:morttonbmp_095_razmire_who_store_choice"
  "096_razmire_place:morttonbmp_096_razmire_place"
  "097_razmire_place_reply:morttonbmp_097_razmire_place_reply"
  "098_razmire_going_on:morttonbmp_098_razmire_going_on"
  "099_razmire_going_on_reply:morttonbmp_099_razmire_going_on_reply"
  "100_razmire_creatures:morttonbmp_100_razmire_creatures"
  "101_razmire_creatures_reply:morttonbmp_101_razmire_creatures_reply"
  "102_razmire_kill_choice:morttonbmp_102_razmire_kill_choice"
  "103_razmire_yes:morttonbmp_103_razmire_yes"
  "104_razmire_yes_reply:morttonbmp_104_razmire_yes_reply"
  "105_razmire_not_now:morttonbmp_105_razmire_not_now"
  "106_razmire_not_now_reply:morttonbmp_106_razmire_not_now_reply"
  "107_razmire_worth_doing:morttonbmp_107_razmire_worth_doing"
  "108_razmire_worth_doing_reply:morttonbmp_108_razmire_worth_doing_reply"
  "109_razmire_shop_closed_general:morttonbmp_109_razmire_shop_closed_general"
  "110_razmire_shop_closed_builders:morttonbmp_110_razmire_shop_closed_builders"
  "111_razmire_shop_closed_choice:morttonbmp_111_razmire_shop_closed_choice"
  "112_razmire_kill_progress:morttonbmp_112_razmire_kill_progress"
  "113_razmire_kill_progress_no:morttonbmp_113_razmire_kill_progress_no"
  "114_razmire_kill_progress_wait:morttonbmp_114_razmire_kill_progress_wait"
  "115_razmire_killed5_no_remains:morttonbmp_115_razmire_killed5_no_remains"
  "116_razmire_killed5_handin:morttonbmp_116_razmire_killed5_handin"
  "117_razmire_killed5_ulsquire:morttonbmp_117_razmire_killed5_ulsquire"
  "118_razmire_store_selection:morttonbmp_118_razmire_store_selection"
  "119_razmire_shop_general_open:morttonbmp_119_razmire_shop_general_open"
  "120_razmire_shop_builders_open:morttonbmp_120_razmire_shop_builders_open"
  "121_razmire_post_shades_ops:morttonbmp_121_razmire_post_shades_ops"
  "122_razmire_shades:morttonbmp_122_razmire_shades"
  "123_razmire_shades_reply:morttonbmp_123_razmire_shades_reply"
  "124_razmire_temple:morttonbmp_124_razmire_temple"
  "125_razmire_temple_reply:morttonbmp_125_razmire_temple_reply"
  "126_razmire_serum:morttonbmp_126_razmire_serum"
  "127_razmire_serum_reply:morttonbmp_127_razmire_serum_reply"
  "128_razmire_store:morttonbmp_128_razmire_store"
  "129_razmire_store_sure:morttonbmp_129_razmire_store_sure"
  "130_razmire_rebuild_hello:morttonbmp_130_razmire_rebuild_hello"
  "131_razmire_rebuild_reply:morttonbmp_131_razmire_rebuild_reply"
  "132_razmire_rebuild_ops:morttonbmp_132_razmire_rebuild_ops"
  "133_razmire_temple_built:morttonbmp_133_razmire_temple_built"
  "134_razmire_knockdown:morttonbmp_134_razmire_knockdown"
  "135_razmire_materials:morttonbmp_135_razmire_materials"
  "136_razmire_lair:morttonbmp_136_razmire_lair"
  "137_razmire_lair_reply:morttonbmp_137_razmire_lair_reply"
  "138_razmire_perm_serum:morttonbmp_138_razmire_perm_serum"
  "139_razmire_perm_coins:morttonbmp_139_razmire_perm_coins"
  "140_razmire_perm_already:morttonbmp_140_razmire_perm_already"
  "141_razmire_thanks:morttonbmp_141_razmire_thanks"
  "142_mix_serum_unknown:morttonbmp_142_mix_serum_unknown"
  "143_mix_serum_207:morttonbmp_143_mix_serum_207"
  "144_sanctify_serum_208:morttonbmp_144_sanctify_serum_208"
  "145_limestone_level:morttonbmp_145_limestone_level"
  "146_limestone_smash:morttonbmp_146_limestone_smash"
  "147_limestone_brick:morttonbmp_147_limestone_brick"
  "148_shade_combat:morttonbmp_148_shade_combat"
  "149_shade_kill_1:morttonbmp_149_shade_kill_1"
  "150_shade_kill_2:morttonbmp_150_shade_kill_2"
  "151_shade_kill_3:morttonbmp_151_shade_kill_3"
  "152_shade_kill_4:morttonbmp_152_shade_kill_4"
  "153_shade_kill_5:morttonbmp_153_shade_kill_5"
  "154_shade_weakened:morttonbmp_154_shade_weakened"
  "155_temple_too_early:morttonbmp_155_temple_too_early"
  "156_temple_no_craft:morttonbmp_156_temple_no_craft"
  "157_temple_no_hammer:morttonbmp_157_temple_no_hammer"
  "158_temple_resources:morttonbmp_158_temple_resources"
  "159_temple_resources_needed:morttonbmp_159_temple_resources_needed"
  "160_temple_rebuild_overlay:morttonbmp_160_temple_rebuild_overlay"
  "161_temple_rebuild_complete:morttonbmp_161_temple_rebuild_complete"
  "162_temple_sanctified:morttonbmp_162_temple_sanctified"
  "163_temple_shade_lash:morttonbmp_163_temple_shade_lash"
  "164_altar_need_tinderbox:morttonbmp_164_altar_need_tinderbox"
  "165_altar_need_repair:morttonbmp_165_altar_need_repair"
  "166_altar_need_sanctity:morttonbmp_166_altar_need_sanctity"
  "167_altar_light:morttonbmp_167_altar_light"
  "168_altar_sanctify_oil:morttonbmp_168_altar_sanctify_oil"
  "169_sacred_oil_stale:morttonbmp_169_sacred_oil_stale"
  "170_create_pyre_logs:morttonbmp_170_create_pyre_logs"
  "171_pyre_need_logs:morttonbmp_171_pyre_need_logs"
  "172_pyre_normal_logs:morttonbmp_172_pyre_normal_logs"
  "173_logs_on_pyre:morttonbmp_173_logs_on_pyre"
  "174_remains_on_pyre:morttonbmp_174_remains_on_pyre"
  "175_light_pyre:morttonbmp_175_light_pyre"
  "176_light_pyre_need_tinderbox:morttonbmp_176_light_pyre_need_tinderbox"
  "177_journal_not_started:morttonbmp_177_journal_not_started"
  "178_journal_read_diary:morttonbmp_178_journal_read_diary"
  "179_journal_mid_kill:morttonbmp_179_journal_mid_kill"
  "180_journal_rebuild:morttonbmp_180_journal_rebuild"
  "181_journal_complete:morttonbmp_181_journal_complete"
  "182_catacombs_locked:morttonbmp_182_catacombs_locked"
)

CLIENT="${MORTTON_CLIENT:-$ROOT/src/torirs}"
if [[ ! -x "$CLIENT" ]]; then
  CLIENT="$ROOT/src/torirs"
fi

only="${1:-}"
for shot in "${shots[@]}"; do
  name="${shot%%:*}"
  cheat="${shot##*:}"
  if [[ -n "$only" && "$name" != *"$only"* && "$cheat" != *"$only"* ]]; then
    continue
  fi
  dest="$OUT/${name}.bmp"
  echo "CAPTURING $name via ::$cheat -> $dest"
  TORIRS_PLUGINS=0 \
  TORIRSSERVER_GOD=1 \
  TORIRS_PAINTER_NOCULL=1 \
  TORIRS_NET_CHEAT="god 1;maxstats;$cheat" \
  TORIRS_EXIT_BMP="$dest" \
  TORIRS_MAX_FRAMES="${TORIRS_MAX_FRAMES:-240}" \
  SDL_VIDEODRIVER=dummy \
  "$CLIENT" --manifest "$MANIFEST" --user testc --pass test --soft3d || true
  if [[ ! -f "$dest" ]]; then
    echo "MISSING $dest" >&2
  else
    echo "WROTE $dest ($(wc -c < "$dest") bytes)"
  fi
done
echo "done. count=$(ls -1 "$OUT"/*.bmp 2>/dev/null | wc -l)"
