#!/usr/bin/env python3
"""
Generate 3rd/rsprot's per-revision prot tables from vendored RSProt Kotlin.

    tools/rsprot_gen_tables.py               # all 19 vendored revisions (221..239)
    tools/rsprot_gen_tables.py 239            # one revision

Unlike tools/rsprot_gen_rev.py (which maps RSProt's prots onto THIS ENGINE's
canonical PKT_NAME_* names for src/net/rev/osrsNNN/), this generator is for the
standalone `3rd/rsprot` library and knows nothing about the engine's packet
enum. It emits RSProt's own prot names verbatim, as plain {name, code, size}
data tables — the library's job is to be a faithful, revision-agnostic wire
codec; naming a payload to an engine concept is 3rd/rsprot's caller's job (see
src/net/rev/osrsNNN/, which does that mapping for the revisions this project
actively speaks).

Data only: no encoder/decoder bodies. This is the part of the port that is
genuinely cheap across all 19 revisions — the opcode/size tables are a few
hundred rows each and RSProt's own JSON dump (rsprot_dump_prot.py) already
extracts them per revision. Message structs and codec bodies are the expensive
part and are handled by a separate, narrower generator scoped to the revisions
this project actually implements (see rsprot_gen_codec.py and 3rd/rsprot/README.md
"What's generated" for the current split).
"""

import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
GEN_DIR = os.path.join(REPO_ROOT, "3rd", "rsprot", "gen")
RSPROT = os.path.expanduser("~/Documents/git_repos/rsprot")

ALL_REVISIONS = list(range(221, 240))

BANNER = """/*
 * GENERATED by tools/rsprot_gen_tables.py -- do not edit.
 * Source: RSProt {src}, revision {rev}.
 */"""


def size_literal(n):
    if n == -1:
        return "RSPROT_VARU8"
    if n == -2:
        return "RSPROT_VARU16"
    return str(n)


def c_ident(name):
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


def read_zone_order(rev):
    """The enclosed sub-packet index is the ORDINAL of RSProt's
    IndexedZoneProtEncoder, not the prot id and not the top-level opcode."""
    path = os.path.join(
        RSPROT,
        f"protocol/osrs-{rev}/osrs-{rev}-desktop/src/main/kotlin/net/rsprot/"
        "protocol/game/outgoing/codec/zone/header/"
        "DesktopUpdateZonePartialEnclosedEncoder.kt",
    )
    if not os.path.exists(path):
        return []
    src = open(path).read()
    marker = "private enum class IndexedZoneProtEncoder"
    if marker not in src:
        return []
    body = src[src.index(marker):]
    body = body[: body.index("\n            ;")]
    return re.findall(r"^\s{12}(\w+)\(OldSchoolZoneProt\.", body, re.M)


def gen_rev_header(rev, dump, src_hash):
    guard = f"RSPROT_GEN_REV{rev}_PROT_H"
    lines = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        BANNER.format(rev=rev, src=src_hash),
        "",
        '#include "../src/rsprot_tables_def.h"',
        "",
        "/* clang-format off */",
        f"static const RsprotProtDef rsprot_rev{rev}_server[] = {{",
    ]
    for r in dump["server"]:
        lines.append(
            '    { "%s", %d, %s },' % (r["name"], r["code"], size_literal(r["size"]))
        )
    lines += [
        "};",
        f"static const RsprotProtDef rsprot_rev{rev}_client[] = {{",
    ]
    for r in dump["client"]:
        lines.append(
            '    { "%s", %d, %s },' % (r["name"], r["code"], size_literal(r["size"]))
        )
    lines += ["};", ""]

    zone = read_zone_order(rev)
    lines.append(f"static const char *const rsprot_rev{rev}_zone_order[] = {{")
    for name in zone:
        lines.append(f'    "{name}",')
    lines += ["};", "/* clang-format on */", ""]

    lines += [
        f"#define RSPROT_REV{rev}_SERVER_COUNT "
        f"((int)(sizeof(rsprot_rev{rev}_server) / sizeof(rsprot_rev{rev}_server[0])))",
        f"#define RSPROT_REV{rev}_CLIENT_COUNT "
        f"((int)(sizeof(rsprot_rev{rev}_client) / sizeof(rsprot_rev{rev}_client[0])))",
        f"#define RSPROT_REV{rev}_ZONE_COUNT "
        f"((int)(sizeof(rsprot_rev{rev}_zone_order) / sizeof(rsprot_rev{rev}_zone_order[0])))",
        "",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def gen_tables_dispatch(revisions, src_hash):
    lines = [
        "#ifndef RSPROT_GEN_TABLES_H",
        "#define RSPROT_GEN_TABLES_H",
        "",
        BANNER.format(rev="all", src=src_hash),
        "",
        "/*",
        " * Umbrella table: every vendored revision's {name, code, size} rows, plus a",
        " * runtime lookup by revision number. This is the ONLY file that needs to",
        " * change to add a revision RSProt vendors -- re-run",
        " * tools/rsprot_gen_tables.py, which regenerates every rev<N>_prot.h and",
        " * this dispatch together so they cannot drift.",
        " */",
        "",
        '#include "../src/rsprot_tables_def.h"',
        "",
    ]
    for r in revisions:
        lines.append(f'#include "rev{r}_prot.h"')
    lines += ["", "/* clang-format off */"]
    lines.append("static const RsprotRevTable rsprot_all_revisions[] = {")
    for r in revisions:
        lines.append(
            "    { %d, rsprot_rev%d_server, RSPROT_REV%d_SERVER_COUNT, "
            "rsprot_rev%d_client, RSPROT_REV%d_CLIENT_COUNT, "
            "rsprot_rev%d_zone_order, RSPROT_REV%d_ZONE_COUNT },"
            % (r, r, r, r, r, r, r)
        )
    lines += ["};", "/* clang-format on */", ""]
    lines += [
        "#define RSPROT_REVISION_COUNT "
        "((int)(sizeof(rsprot_all_revisions) / sizeof(rsprot_all_revisions[0])))",
        "",
        "/* Looks up a revision by its bare number (e.g. 239). Returns NULL if this",
        " * build was not generated with that revision vendored. */",
        "static inline const RsprotRevTable *",
        "rsprot_rev_table(int revision)",
        "{",
        "    for( int i = 0; i < RSPROT_REVISION_COUNT; i++ )",
        "        if( rsprot_all_revisions[i].revision == revision )",
        "            return &rsprot_all_revisions[i];",
        "    return 0;",
        "}",
        "",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def main():
    revisions = [int(a) for a in sys.argv[1:]] or ALL_REVISIONS

    src_hash = (
        subprocess.check_output(["git", "-C", RSPROT, "rev-parse", "--short", "HEAD"])
        .decode()
        .strip()
    )

    os.makedirs(GEN_DIR, exist_ok=True)
    for rev in revisions:
        dump = json.loads(
            subprocess.check_output(
                [sys.executable, os.path.join(HERE, "rsprot_dump_prot.py"), str(rev)]
            )
        )
        text = gen_rev_header(rev, dump, src_hash)
        path = os.path.join(GEN_DIR, f"rev{rev}_prot.h")
        with open(path, "w") as fh:
            fh.write(text)
        print(
            f"rev {rev}: {len(dump['server'])} server prots, "
            f"{len(dump['client'])} client prots -> {path}",
            file=sys.stderr,
        )

    all_revs = sorted(
        set(revisions)
        | {
            int(re.match(r"rev(\d+)_prot\.h", f).group(1))
            for f in os.listdir(GEN_DIR)
            if re.match(r"rev\d+_prot\.h", f)
        }
    )
    dispatch_path = os.path.join(GEN_DIR, "rsprot_tables.h")
    with open(dispatch_path, "w") as fh:
        fh.write(gen_tables_dispatch(all_revs, src_hash))
    print(f"wrote {dispatch_path} ({len(all_revs)} revisions)", file=sys.stderr)


if __name__ == "__main__":
    main()
