#!/usr/bin/env python3
"""
Import OpenRune's Lumbridge spawns as LostCity `.jm2` map files.

    tools/spawn_import.py --out OSRS-Content/osrs239-content/maps

OpenRune declares spawns in Kotlin
(`content/.../areas/lumbridge/spawns/SpawnPlugin.kt`) as `spawnNpc(npc =
"npcs.man", x = 3206, z = 3219, ...)`. LostCity declares them in the map square
they stand on, as `level x z: id` under an `==== NPC ====` banner, with x and z
local to the square. This converts the first into the second.

Only the NPC and OBJ sections are emitted. LostCity's MAP and LOC sections
describe terrain and scenery, which the mock reads from cache.osrs230 — the
same bytes the client draws — so a second copy here could only ever disagree
with what is on screen.

`walkRadius` and `direction` are dropped on purpose, not lost: LostCity carries
wander range on the npc *type* (`wanderrange=` in the .npc config), not on the
spawn, and this tree follows it. Directions are not in the format at all.
"""

import argparse
import collections
import importlib.util
import os
import re

DEFAULT_PLUGIN = os.path.expanduser(
    "~/Documents/git_repos/OpenRune-Server/content/src/main/kotlin/org/alter/areas/"
    "lumbridge/spawns/SpawnPlugin.kt"
)
DEFAULT_GAMEVALS = os.path.expanduser(
    "~/Documents/git_repos/OpenRune-Server/data/cfg/gamevals-binary/gamevals.dat"
)

SPAWN_NPC = re.compile(
    r'spawnNpc\(\s*npc\s*=\s*"npcs\.(?P<name>\w+)"'
    r'(?:[^)]*?\bx\s*=\s*(?P<x>\d+))'
    r'(?:[^)]*?\bz\s*=\s*(?P<z>\d+))'
    r'(?:[^)]*?\bheight\s*=\s*(?P<level>\d+))?'
)
SPAWN_ITEM = re.compile(
    r'spawnItem\(\s*item\s*=\s*"items\.(?P<name>\w+)"'
    r'(?:[^)]*?\bamount\s*=\s*(?P<count>\d+))?'
    r'(?:[^)]*?\bx\s*=\s*(?P<x>\d+))'
    r'(?:[^)]*?\bz\s*=\s*(?P<z>\d+))'
    r'(?:[^)]*?\bheight\s*=\s*(?P<level>\d+))?'
)

# Spawns the mock adds on top of OpenRune's. Its Lumbridge has no guards and no
# livestock north-east of the castle, and the mock needs one genuinely dangerous
# fight and one harmless drop source within walking distance of the start tile.
EXTRA_NPCS = [
    ("guard1", 3236, 3210, 0),
    ("guard1", 3239, 3213, 0),
    ("cow", 3253, 3266, 0),
    ("cow", 3257, 3271, 0),
    ("cow", 3260, 3264, 0),
    ("chicken", 3232, 3295, 0),
    ("chicken", 3236, 3297, 0),
    ("chicken", 3229, 3298, 0),
    ("duck", 3243, 3255, 0),
    # The speaking parts, on the tiles their dialogue assumes.
    ("bob", 3231, 3216, 0),
    ("generalshopkeeper1", 3212, 3246, 0),
    ("generalassistant1", 3214, 3246, 0),
    ("father_aereck", 3243, 3208, 0),
    ("aide_tutor_cooking", 3232, 3186, 0),
    ("aide_tutor_crafting", 3204, 3213, 0),
    ("doomsayer_normal", 3229, 3229, 0),
    ("lumbridge_guide2_man", 3238, 3222, 0),
    ("goblin_cook_charred", 3229, 3213, 1),
    ("hans", 3221, 3218, 0),
]

HEADER = """\
// Generated by tools/spawn_import.py from OpenRune-Server's
// content/.../areas/lumbridge/spawns/SpawnPlugin.kt. Do not edit — re-run the
// importer. Wander range lives on the npc type (see the area's .npc config),
// which is where LostCity keeps it.
//
// MAP and LOC sections are absent on purpose: terrain and scenery come from
// cache.osrs230, the same bytes the client draws.
"""


def load_gamevals(path):
    spec = importlib.util.spec_from_file_location(
        "gameval_import", os.path.join(os.path.dirname(__file__), "gameval_import.py")
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.read_gamevals(path)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plugin", default=DEFAULT_PLUGIN)
    parser.add_argument("--gamevals", default=DEFAULT_GAMEVALS)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    groups = load_gamevals(args.gamevals)
    npcs, items = groups["npcs"], groups["items"]

    with open(args.plugin, "r", encoding="utf-8") as handle:
        source = handle.read()

    # {(map_x, map_z): {"NPC": [...], "OBJ": [...]}}
    squares = collections.defaultdict(lambda: {"NPC": [], "OBJ": []})
    missing = []

    def place(section, table, name, x, z, level, extra=""):
        if name not in table:
            missing.append(name)
            return
        squares[(x >> 6, z >> 6)][section].append(
            f"{level} {x & 63} {z & 63}: {table[name]}{extra}"
        )

    for match in SPAWN_NPC.finditer(source):
        place(
            "NPC", npcs, match["name"],
            int(match["x"]), int(match["z"]), int(match["level"] or 0),
        )
    for name, x, z, level in EXTRA_NPCS:
        place("NPC", npcs, name, x, z, level)

    for match in SPAWN_ITEM.finditer(source):
        place(
            "OBJ", items, match["name"],
            int(match["x"]), int(match["z"]), int(match["level"] or 0),
            extra=f" {int(match['count'] or 1)}",
        )

    if missing:
        raise SystemExit("gamevals has no entry for: " + ", ".join(sorted(set(missing))))

    os.makedirs(args.out, exist_ok=True)
    for (map_x, map_z), sections in sorted(squares.items()):
        path = os.path.join(args.out, f"m{map_x}_{map_z}.jm2")
        body = [HEADER]
        for section in ("NPC", "OBJ"):
            if not sections[section]:
                continue
            body.append(f"==== {section} ====")
            body.extend(sorted(sections[section], key=sort_key))
            body.append("")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write("\n".join(body))
        print(
            f"wrote {path} "
            f"({len(sections['NPC'])} npc, {len(sections['OBJ'])} obj)"
        )


def sort_key(line):
    """Sort by level, then x, then z — LostCity's own jm2 ordering."""
    head = line.split(":", 1)[0]
    return tuple(int(part) for part in head.split())


if __name__ == "__main__":
    main()
