#!/usr/bin/env python3
"""Stage ServerScript constants with one explicit Summoning feature value."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--src", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--enabled", type=int, choices=(0, 1), required=True)
    args = parser.parse_args()

    src = args.src.resolve()
    out = args.out.resolve()
    if src == out or src in out.parents:
        raise SystemExit("output must not be the source tree or one of its parents")
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    constant_count = 0
    dbtable_count = 0
    paths = sorted(path for path in src.rglob("*") if path.suffix in (".constant", ".dbtable"))
    for path in paths:
        if any(part.startswith("build") for part in path.relative_to(src).parts):
            continue
        target = out / path.relative_to(src)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, target)
        if path.suffix == ".constant":
            constant_count += 1
        else:
            dbtable_count += 1
    if constant_count == 0 or dbtable_count == 0:
        raise SystemExit("refusing a vacuous constants stage")

    feature = out / "ported_scape2009_summoning/configs/summoning_feature.constant"
    feature.parent.mkdir(parents=True, exist_ok=True)
    feature.write_text(
        "// Generated by tools/stage_summoning_server_constants.py.\n"
        f"^summoning_enabled = {args.enabled}\n",
        encoding="utf-8",
    )
    print(
        f"staged {constant_count + 1} constants and {dbtable_count} dbtables; "
        f"summoning_enabled={args.enabled}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
