#!/usr/bin/env bash
# Capture one named BMP per Tai Bwo Wannai Trio interaction.
# Plugins off. Player unkillable. Each shot must show the mesbox/journal/reward.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/OSRS-Content/osrs239-content/server/scripts/selftest/quest_tbwt"
MANIFEST="${TBWT_MANIFEST:-$ROOT/manifests/manifest_osrs239_sailing.ini}"
if [[ ! -f "$MANIFEST" ]]; then
  MANIFEST="$ROOT/manifests/manifest_osrs239.ini"
fi
mkdir -p "$OUT"
export TORIRS_PLUGINS=0
export TORIRSSERVER_GOD=1
export SDL_VIDEODRIVER=dummy
export PLATFORM_OBJ_BASE="${PLATFORM_OBJ_BASE:-/tmp/gp-tbwt-img-obj}"

shots=(
  "001_timfraku_title:tbwtbmp_001_timfraku_title"
  "002_timfraku_title_choice:tbwtbmp_002_timfraku_title_choice"
  "003_timfraku_roving:tbwtbmp_003_timfraku_roving"
  "004_timfraku_explorer:tbwtbmp_004_timfraku_explorer"
  "005_timfraku_wayfarer:tbwtbmp_005_timfraku_wayfarer"
  "006_timfraku_nobody:tbwtbmp_006_timfraku_nobody"
  "007_timfraku_unstarted_jp:tbwtbmp_007_timfraku_unstarted_jp"
  "008_timfraku_unstarted_nojp:tbwtbmp_008_timfraku_unstarted_nojp"
  "009_timfraku_why_leave:tbwtbmp_009_timfraku_why_leave"
  "010_timfraku_leave_questions:tbwtbmp_010_timfraku_leave_questions"
  "011_timfraku_where_place:tbwtbmp_011_timfraku_where_place"
  "012_timfraku_going_then:tbwtbmp_012_timfraku_going_then"
  "013_timfraku_prereq_fail:tbwtbmp_013_timfraku_prereq_fail"
  "014_timfraku_prereq_choice:tbwtbmp_014_timfraku_prereq_choice"
  "015_timfraku_prereq_begone:tbwtbmp_015_timfraku_prereq_begone"
  "016_timfraku_trufitus:tbwtbmp_016_timfraku_trufitus"
  "017_timfraku_concentrate:tbwtbmp_017_timfraku_concentrate"
  "018_timfraku_thanks:tbwtbmp_018_timfraku_thanks"
  "019_timfraku_offer_choice:tbwtbmp_019_timfraku_offer_choice"
  "020_timfraku_one_last:tbwtbmp_020_timfraku_one_last"
  "021_timfraku_start_choice:tbwtbmp_021_timfraku_start_choice"
  "022_timfraku_decline:tbwtbmp_022_timfraku_decline"
  "023_timfraku_decline_ok:tbwtbmp_023_timfraku_decline_ok"
  "024_timfraku_accept:tbwtbmp_024_timfraku_accept"
  "025_timfraku_accept_reward:tbwtbmp_025_timfraku_accept_reward"
  "026_timfraku_ready:tbwtbmp_026_timfraku_ready"
  "027_timfraku_started_ops:tbwtbmp_027_timfraku_started_ops"
  "028_timfraku_sons:tbwtbmp_028_timfraku_sons"
  "029_timfraku_son_ops:tbwtbmp_029_timfraku_son_ops"
  "030_timfraku_tell_tamayu:tbwtbmp_030_timfraku_tell_tamayu"
  "031_timfraku_tell_tinsay:tbwtbmp_031_timfraku_tell_tinsay"
  "032_timfraku_tell_tiadeche:tbwtbmp_032_timfraku_tell_tiadeche"
  "033_timfraku_where_sons:tbwtbmp_033_timfraku_where_sons"
  "034_timfraku_patience:tbwtbmp_034_timfraku_patience"
  "035_timfraku_village:tbwtbmp_035_timfraku_village"
  "036_timfraku_chief:tbwtbmp_036_timfraku_chief"
  "037_tamayu_prequest:tbwtbmp_037_tamayu_prequest"
  "038_tamayu_intro:tbwtbmp_038_tamayu_intro"
  "039_tamayu_vow:tbwtbmp_039_tamayu_vow"
  "040_tamayu_shaikahan_ops:tbwtbmp_040_tamayu_shaikahan_ops"
  "041_tamayu_tell_more:tbwtbmp_041_tamayu_tell_more"
  "042_tamayu_how_long:tbwtbmp_042_tamayu_how_long"
  "043_tamayu_when_succeed:tbwtbmp_043_tamayu_when_succeed"
  "044_tamayu_watch_choice:tbwtbmp_044_tamayu_watch_choice"
  "045_tamayu_watch_later:tbwtbmp_045_tamayu_watch_later"
  "046_tamayu_slay_for_you:tbwtbmp_046_tamayu_slay_for_you"
  "047_tamayu_after_watch_ops:tbwtbmp_047_tamayu_after_watch_ops"
  "048_tamayu_assess_agility:tbwtbmp_048_tamayu_assess_agility"
  "049_tamayu_assess_agile:tbwtbmp_049_tamayu_assess_agile"
  "050_tamayu_assess_damage:tbwtbmp_050_tamayu_assess_damage"
  "051_tamayu_assess_health:tbwtbmp_051_tamayu_assess_health"
  "052_tamayu_spear_early:tbwtbmp_052_tamayu_spear_early"
  "053_tamayu_spear:tbwtbmp_053_tamayu_spear"
  "054_tamayu_potion_early:tbwtbmp_054_tamayu_potion_early"
  "055_tamayu_potion:tbwtbmp_055_tamayu_potion"
  "056_tamayu_potion_enough:tbwtbmp_056_tamayu_potion_enough"
  "057_tamayu_skin_early:tbwtbmp_057_tamayu_skin_early"
  "058_tamayu_skin:tbwtbmp_058_tamayu_skin"
  "059_tamayu_slayed:tbwtbmp_059_tamayu_slayed"
  "060_tamayu_meet_village:tbwtbmp_060_tamayu_meet_village"
  "061_shaikahan_blocked:tbwtbmp_061_shaikahan_blocked"
  "062_tinsay_prequest:tbwtbmp_062_tinsay_prequest"
  "063_tinsay_intro:tbwtbmp_063_tinsay_intro"
  "064_tinsay_statue:tbwtbmp_064_tinsay_statue"
  "065_tinsay_need_rum:tbwtbmp_065_tinsay_need_rum"
  "066_tinsay_found_rum:tbwtbmp_066_tinsay_found_rum"
  "067_tinsay_found_choice:tbwtbmp_067_tinsay_found_choice"
  "068_tinsay_how_menu:tbwtbmp_068_tinsay_how_menu"
  "069_tinsay_how_rum:tbwtbmp_069_tinsay_how_rum"
  "070_tinsay_wrong_rum:tbwtbmp_070_tinsay_wrong_rum"
  "071_tinsay_wrong_rum_chat:tbwtbmp_071_tinsay_wrong_rum_chat"
  "072_tinsay_give_rum:tbwtbmp_072_tinsay_give_rum"
  "073_tinsay_need_sandwich:tbwtbmp_073_tinsay_need_sandwich"
  "074_tinsay_found_sandwich:tbwtbmp_074_tinsay_found_sandwich"
  "075_tinsay_how_seaweed:tbwtbmp_075_tinsay_how_seaweed"
  "076_tinsay_how_skin:tbwtbmp_076_tinsay_how_skin"
  "077_tinsay_wrong_stuffed:tbwtbmp_077_tinsay_wrong_stuffed"
  "078_tinsay_give_sandwich:tbwtbmp_078_tinsay_give_sandwich"
  "079_tinsay_need_bones:tbwtbmp_079_tinsay_need_bones"
  "080_tinsay_found_bones:tbwtbmp_080_tinsay_found_bones"
  "081_tinsay_how_burn:tbwtbmp_081_tinsay_how_burn"
  "082_tinsay_wrong_jogre:tbwtbmp_082_tinsay_wrong_jogre"
  "083_tinsay_wrong_burnt:tbwtbmp_083_tinsay_wrong_burnt"
  "084_tinsay_wrong_raw_paste:tbwtbmp_084_tinsay_wrong_raw_paste"
  "085_tinsay_give_marinated:tbwtbmp_085_tinsay_give_marinated"
  "086_tinsay_craving:tbwtbmp_086_tinsay_craving"
  "087_tinsay_complete:tbwtbmp_087_tinsay_complete"
  "088_tinsay_vessel_early:tbwtbmp_088_tinsay_vessel_early"
  "089_tinsay_vessel_manual:tbwtbmp_089_tinsay_vessel_manual"
  "090_tinsay_manual_give:tbwtbmp_090_tinsay_manual_give"
  "091_tiadeche_prequest:tbwtbmp_091_tiadeche_prequest"
  "092_tiadeche_intro:tbwtbmp_092_tiadeche_intro"
  "093_tiadeche_catch_first:tbwtbmp_093_tiadeche_catch_first"
  "094_tiadeche_ops:tbwtbmp_094_tiadeche_ops"
  "095_tiadeche_what_karambwan:tbwtbmp_095_tiadeche_what_karambwan"
  "096_tiadeche_when_finished:tbwtbmp_096_tiadeche_when_finished"
  "097_tiadeche_help:tbwtbmp_097_tiadeche_help"
  "098_tiadeche_how_fishing:tbwtbmp_098_tiadeche_how_fishing"
  "099_tiadeche_refuse_gift:tbwtbmp_099_tiadeche_refuse_gift"
  "100_tiadeche_ji_bait:tbwtbmp_100_tiadeche_ji_bait"
  "101_tiadeche_ji_sacrilege:tbwtbmp_101_tiadeche_ji_sacrilege"
  "102_tiadeche_empty_vessel:tbwtbmp_102_tiadeche_empty_vessel"
  "103_tiadeche_empty_fail:tbwtbmp_103_tiadeche_empty_fail"
  "104_tiadeche_loaded:tbwtbmp_104_tiadeche_loaded"
  "105_tiadeche_catch_offer:tbwtbmp_105_tiadeche_catch_offer"
  "106_tiadeche_first_catch:tbwtbmp_106_tiadeche_first_catch"
  "107_tiadeche_manual:tbwtbmp_107_tiadeche_manual"
  "108_tiadeche_have_manual:tbwtbmp_108_tiadeche_have_manual"
  "109_tiadeche_lost_manual:tbwtbmp_109_tiadeche_lost_manual"
  "110_tiadeche_give_manual:tbwtbmp_110_tiadeche_give_manual"
  "111_tiadeche_complete:tbwtbmp_111_tiadeche_complete"
  "112_lubufu_whip:tbwtbmp_112_lubufu_whip"
  "113_lubufu_first_choice:tbwtbmp_113_lubufu_first_choice"
  "114_lubufu_who:tbwtbmp_114_lubufu_who"
  "115_lubufu_intro:tbwtbmp_115_lubufu_intro"
  "116_lubufu_ops:tbwtbmp_116_lubufu_ops"
  "117_lubufu_what_do:tbwtbmp_117_lubufu_what_do"
  "118_lubufu_help_choice:tbwtbmp_118_lubufu_help_choice"
  "119_lubufu_offered:tbwtbmp_119_lubufu_offered"
  "120_lubufu_fetch_ji:tbwtbmp_120_lubufu_fetch_ji"
  "121_lubufu_need_more:tbwtbmp_121_lubufu_need_more"
  "122_lubufu_give_ji:tbwtbmp_122_lubufu_give_ji"
  "123_lubufu_thanks:tbwtbmp_123_lubufu_thanks"
  "124_lubufu_given_ops:tbwtbmp_124_lubufu_given_ops"
  "125_lubufu_offer_app:tbwtbmp_125_lubufu_offer_app"
  "126_lubufu_app_choice:tbwtbmp_126_lubufu_app_choice"
  "127_lubufu_reject:tbwtbmp_127_lubufu_reject"
  "128_lubufu_teach:tbwtbmp_128_lubufu_teach"
  "129_lubufu_vessel:tbwtbmp_129_lubufu_vessel"
  "130_lubufu_practise:tbwtbmp_130_lubufu_practise"
  "131_lubufu_deceived:tbwtbmp_131_lubufu_deceived"
  "132_lubufu_spot:tbwtbmp_132_lubufu_spot"
  "133_lubufu_spot_bait:tbwtbmp_133_lubufu_spot_bait"
  "134_timfraku_brothers_back:tbwtbmp_134_timfraku_brothers_back"
  "135_timfraku_reward_choice:tbwtbmp_135_timfraku_reward_choice"
  "136_timfraku_2000_coins:tbwtbmp_136_timfraku_2000_coins"
  "137_complete_scroll:tbwtbmp_137_complete_scroll"
  "138_timfraku_speak_sons:tbwtbmp_138_timfraku_speak_sons"
  "139_tamayu_final:tbwtbmp_139_tamayu_final"
  "140_tamayu_spear_gift:tbwtbmp_140_tamayu_spear_gift"
  "141_tinsay_final:tbwtbmp_141_tinsay_final"
  "142_tinsay_cook:tbwtbmp_142_tinsay_cook"
  "143_tiadeche_final:tbwtbmp_143_tiadeche_final"
  "144_tiadeche_fish:tbwtbmp_144_tiadeche_fish"
  "145_journal_not_started:tbwtbmp_145_journal_not_started"
  "146_journal_need_timfraku:tbwtbmp_146_journal_need_timfraku"
  "147_journal_mid:tbwtbmp_147_journal_mid"
  "148_journal_brothers:tbwtbmp_148_journal_brothers"
  "149_journal_complete:tbwtbmp_149_journal_complete"
  "150_banana_rum:tbwtbmp_150_banana_rum"
  "151_slice_banana:tbwtbmp_151_slice_banana"
  "152_seaweed_sandwich:tbwtbmp_152_seaweed_sandwich"
  "153_vessel_load:tbwtbmp_153_vessel_load"
  "154_kp_smear:tbwtbmp_154_kp_smear"
  "155_jogre_furnace:tbwtbmp_155_jogre_furnace"
  "156_jogre_need_fm:tbwtbmp_156_jogre_need_fm"
  "157_monkey_dodge:tbwtbmp_157_monkey_dodge"
  "158_bamboo_door:tbwtbmp_158_bamboo_door"
  "159_statue_pray:tbwtbmp_159_statue_pray"
  "160_sandwich_eat:tbwtbmp_160_sandwich_eat"
)

CLIENT="${TBWT_CLIENT:-$ROOT/src/torirs}"
if [[ ! -x "$CLIENT" ]]; then
  CLIENT="$ROOT/src/torirs"
fi

only="${1:-}"
for shot in "${shots[@]}"; do
  name="${shot%%:*}"
  cheat="${shot##*:}"
  if [[ -n "$only" && "$name" != *"$only"* && "$cheat" != *"$only"* ]]; then
    continue
  fi
  dest="$OUT/${name}.bmp"
  echo "CAPTURING $name via ::$cheat -> $dest"
  TORIRS_PLUGINS=0 \
  TORIRSSERVER_GOD=1 \
  TORIRS_PAINTER_NOCULL=1 \
  TORIRS_NET_CHEAT="god 1;maxstats;$cheat" \
  TORIRS_EXIT_BMP="$dest" \
  TORIRS_MAX_FRAMES="${TORIRS_MAX_FRAMES:-240}" \
  SDL_VIDEODRIVER=dummy \
  "$CLIENT" --manifest "$MANIFEST" --user testc --pass test --soft3d || true
  if [[ ! -f "$dest" ]]; then
    echo "MISSING $dest" >&2
  else
    echo "WROTE $dest ($(wc -c < "$dest") bytes)"
  fi
done
echo "done. count=$(ls -1 "$OUT"/*.bmp 2>/dev/null | wc -l)"
