"""Per-opcode documentation for CS2 opcodes implemented in cs2vm.c and cs2_host_ui.c.

Each value is a single-line comment: effect; stack args (bottom->top); result.
Int stack abbreviated 'in', string stack 'sin', operand field 'op'.
"""

OPCODE_DOCS: dict[str, str] = {
    # --- VM core (cs2vm.c) ---
    "PUSH_CONSTANT_INT": "Push int constant. in: -. out int: op.",
    "PUSH_CONSTANT_STRING": "Push string constant. sin: -. out str: script string at op.",
    "PUSH_VAR": "Read varp. in: -. out int: varp[op].",
    "POP_VAR": "Write varp. in: value. out: -; sets varp[op]=value.",
    "PUSH_VARBIT": "Read varbit. in: -. out int: varbit[op].",
    "POP_VARBIT": "Write varbit. in: value. out: -; sets varbit[op]=value.",
    "PUSH_VARC_INT": "Read client int varc. in: -. out int: varc_int[op].",
    "POP_VARC_INT": "Write client int varc. in: value. out: -; sets varc_int[op]=value.",
    "PUSH_VARC_STRING": "Read client string varc. in: -. out str: varc_string[op].",
    "POP_VARC_STRING": "Write client string varc. sin: value. out: -; sets varc_string[op]=value.",
    "PUSH_INT_LOCAL": "Push int local. in: -. out int: int_local[op].",
    "POP_INT_LOCAL": "Pop int local. in: value. out: -; sets int_local[op]=value.",
    "PUSH_STRING_LOCAL": "Push string local. in: -. out str: str_local[op].",
    "POP_STRING_LOCAL": "Pop string local. sin: value. out: -; sets str_local[op]=value.",
    "JOIN_STRING": "Concatenate strings. sin: a, b (b top). out str: a+b.",
    "POP_INT_DISCARD": "Discard int. in: value (op times). out: -.",
    "POP_STRING_DISCARD": "Discard string. sin: value (op times). out: -.",
    "BRANCH": "Unconditional branch. in: -. out: -; pc += op.",
    "BRANCH_NOT": "Branch if false. in: cond. out: -; pc += op if cond==0.",
    "BRANCH_EQUALS": "Branch if equal. in: a, b (b top). out: -; pc += op if a==b.",
    "BRANCH_LESS_THAN": "Branch if less. in: a, b (b top). out: -; pc += op if a<b.",
    "BRANCH_GREATER_THAN": "Branch if greater. in: a, b (b top). out: -; pc += op if a>b.",
    "BRANCH_LESS_THAN_OR_EQUALS": "Branch if <=. in: a, b (b top). out: -; pc += op if a<=b.",
    "BRANCH_GREATER_THAN_OR_EQUALS": "Branch if >=. in: a, b (b top). out: -; pc += op if a>=b.",
    "SWITCH": "Switch jump. in: key. out: -; pc = case target or fall through.",
    "ADD": "Integer add. in: a, b (b top). out int: a+b.",
    "SUB": "Integer subtract. in: a, b (b top). out int: a-b.",
    "MULTIPLY": "Integer multiply. in: a, b (b top). out int: a*b.",
    "DIV": "Integer divide. in: a, b (b top). out int: a/b (0 if b==0).",
    "MOD": "Integer modulo. in: a, b (b top). out int: a%b (0 if b==0).",
    "AND": "Bitwise and. in: a, b (b top). out int: a&b.",
    "OR": "Bitwise or. in: a, b (b top). out int: a|b.",
    "TESTBIT": "Test bit set. in: value, bit (bit top). out int: (value&(1<<bit))!=0.",
    "GOSUB_WITH_PARAMS": "Call script. in: script args per callee signature. out: callee return values.",
    "DEFINE_ARRAY": "Define int array. in: size. out: -; creates array[op].",
    "PUSH_ARRAY_INT": "Read array element. in: index. out int: array[op][index].",
    "POP_ARRAY_INT": "Write array element. in: index, value (value top). out: -; array[op][index]=value.",
    "ENUM": "Enum lookup. in: key, enum_id, output_type, input_type (key top). out int: mapped value or -1.",
    "RETURN": "Return from script. in: optional return int. out: -; pops frame.",
    # --- Host widget create/find (cs2_host_ui.c) ---
    "CC_CREATE": "Create dynamic child component. in: sub_id. op=widget_type. out: -; sets active to new child.",
    "CC_DELETEALL": "Delete all dynamic children of active parent. in: -. out: -.",
    "CC_FIND": "Find child by sub-id. in: parent, sub (sub top). out int: 1 if found (active set) else 0.",
    "IF_FIND": "Find interface component. in: component. out int: 1 if found (active set) else 0.",
    # --- CC setters (active component) ---
    "CC_SETHIDE": "Hide active child. in: hide. out: -.",
    "CC_SETTEXT": "Set text on active child. sin: text. out: -.",
    "CC_SETTEXTFONT": "Set font on active child. in: font_id. out: -.",
    "CC_SETTEXTALIGN": "Set text alignment. in: x_align, y_align, line_height (line_height top). out: -.",
    "CC_SETTEXTSHADOW": "Set text shadow. in: shadowed. out: -.",
    "CC_SETCOLOUR": "Set colour on active child. in: colour. out: -.",
    "CC_SETFILL": "Set rectangle fill. in: filled. out: -.",
    "CC_SETTRANS": "Set transparency. in: trans. out: -.",
    "CC_SETNOCLICKTHROUGH": "Set no-click-through. in: enabled. out: -.",
    "CC_SETOP": "Set right-click op. sin: text. in: index. out: -.",
    "CC_SETOPBASE": "Set op base text. sin: text. out: -.",
    "CC_SETTARGETVERB": "Set target verb (stub). sin: text. out: -.",
    "CC_CLEAROPS": "Clear all ops on active child. in: -. out: -.",
    "CC_SETDRAGGABLE": "Set draggable parent/child. in: parent_uid, child_index (child_index top). out: -.",
    "CC_SETDRAGGABLEBEHAVIOR": "Set drag behavior. in: behavior. out: -.",
    "CC_SETDRAGDEADZONE": "Set drag dead zone pixels. in: zone. out: -.",
    "CC_SETDRAGDEADTIME": "Set drag dead time ms. in: time. out: -.",
    "CC_SETGRAPHIC": "Set sprite graphic. in: graphic_id. out: -.",
    "CC_SETPOSITION": "Set position modes. in: x, y, x_mode, y_mode (y_mode top). out: -.",
    "CC_SETSIZE": "Set size modes. in: w, h, w_mode, h_mode (h_mode top). out: -.",
    "CC_SETTILING": "Set sprite tiling. in: tiled. out: -.",
    "CC_SETOUTLINE": "Set sprite outline. in: outline. out: -.",
    "CC_SETGRAPHICSHADOW": "Set sprite shadow. in: shadow. out: -.",
    "CC_SETOBJECT": "Set object icon on active child. in: obj_count, obj_id (obj_id top). out: -.",
    "CC_SETOBJECT_ALWAYS_NUM": "Set object icon always showing qty. in: obj_count, obj_id. out: -.",
    "CC_SETOBJECT_NONUM": "Set object icon without qty. in: obj_id. out: -.",
    # --- CC getters (active component) ---
    "CC_GETID": "Get active component id. in: -. out int: active_component.",
    "CC_GETX": "Get relative X of active child. in: -. out int: x.",
    "CC_GETY": "Get relative Y of active child. in: -. out int: y.",
    "CC_GETLAYER": "Get parent component id. in: -. out int: parent_id.",
    "CC_GETOP": "Get op text. in: op_index. out str: op text.",
    "CC_GETOPBASE": "Get op base text. in: -. out str: op_base.",
    "CC_GETTEXT": "Get text. in: -. out str: text.",
    "CC_GETWIDTH": "Get layout width. in: -. out int: width.",
    "CC_GETHEIGHT": "Get layout height. in: -. out int: height.",
    "CC_GETHIDE": "Get hidden flag. in: -. out int: hidden?1:0.",
    "CC_GETSCROLLX": "Get scroll X (stub). in: -. out int: 0.",
    "CC_GETSCROLLY": "Get scroll Y (stub). in: -. out int: 0.",
    "CC_GETSCROLLWIDTH": "Get scroll content width. in: -. out int: scroll_width.",
    "CC_GETSCROLLHEIGHT": "Get scroll content height. in: -. out int: scroll_height.",
    # --- IF setters ---
    "IF_SETNOCLICKTHROUGH": "Set no-click-through. in: component, enabled (enabled top). out: -.",
    "IF_SETTRANS": "Set transparency. in: component, trans (trans top). out: -.",
    "IF_SETOP": "Set op text. sin: text. in: component, index (index top). out: -.",
    "IF_SETDRAGGABLE": "Set draggable. in: component, parent_uid, child_index (child_index top). out: -.",
    "IF_SETDRAGGABLEBEHAVIOR": "Set drag behavior. in: component, behavior (behavior top). out: -.",
    "IF_SETHIDE": "Set hidden. in: component, hide (hide top). out: -.",
    "IF_SETTEXT": "Set text. sin: text. in: component. out: -.",
    "IF_SETTEXTFONT": "Set font. in: component, font_id (font_id top). out: -.",
    "IF_SETTEXTALIGN": "Set text alignment. in: component, x_align, y_align, line_height (line_height top). out: -.",
    "IF_SETTEXTSHADOW": "Set text shadow. in: component, shadow (shadow top). out: -.",
    "IF_SETFILL": "Set fill. in: component, filled (filled top). out: -.",
    "IF_SETGRAPHIC": "Set graphic. in: component, graphic_id (graphic_id top). out: -.",
    "IF_SETCOLOUR": "Set colour. in: component, colour (colour top). out: -.",
    "IF_SETPOSITION": "Set position. in: component, x, y (y top). out: -.",
    "IF_SETSIZE": "Set size. in: component, width, height (height top). out: -.",
    "IF_SETSCROLLSIZE": "Set scroll size. in: component, scroll_w, scroll_h (scroll_h top). out: -.",
    "IF_SETSCROLLPOS": "Set scroll position (stub). in: component, scroll_x, scroll_y. out: -.",
    "IF_SETOBJECT": "Set object icon. in: component, obj_count, obj_id (obj_id top). out: -.",
    "IF_SETOBJECT_ALWAYS_NUM": "Set object icon always showing qty. in: component, obj_count, obj_id. out: -.",
    "IF_SETOBJECT_NONUM": "Set object icon without qty. in: component, obj_id. out: -.",
    "IF_SETMODEL": "Set model id. in: component, model_id (model_id top). out: -.",
    "IF_SETMODELTRANSPARENT": "Set model transparency. in: component, transparent (transparent top). out: -.",
    "IF_SETOPBASE": "Set op base. sin: text. in: component. out: -.",
    "IF_SETTARGETVERB": "Set target verb (stub). sin: text. in: component. out: -.",
    "IF_CLEAROPS": "Clear ops. in: component. out: -.",
    "IF_SETDRAGDEADZONE": "Set drag dead zone. in: component, zone (zone top). out: -.",
    "IF_SETDRAGDEADTIME": "Set drag dead time. in: component, time (time top). out: -.",
    # --- IF getters ---
    "IF_GETWIDTH": "Get layout width. in: component. out int: width.",
    "IF_GETHEIGHT": "Get layout height. in: component. out int: height.",
    "IF_GETX": "Get relative X. in: component. out int: x.",
    "IF_GETY": "Get relative Y. in: component. out int: y.",
    "IF_GETLAYER": "Get parent component id. in: component. out int: parent_id.",
    "IF_GETSCROLLHEIGHT": "Get scroll content height. in: component. out int: scroll_height.",
    "IF_GETHIDE": "Get hidden flag. in: component. out int: hidden?1:0.",
    "IF_GETSCROLLX": "Get scroll X (stub). in: component. out int: 0.",
    "IF_GETSCROLLY": "Get scroll Y (stub). in: component. out int: 0.",
    "IF_GETSCROLLWIDTH": "Get scroll content width. in: component. out int: scroll_width.",
    "IF_GETTOP": "Get root component id. in: -. out int: top component or -1.",
    "IF_GETOP": "Get op text. in: component, op_index (op_index top). out str: op text.",
    "IF_GETOPBASE": "Get op base text. in: component. out str: op_base.",
    "IF_GETTEXT": "Get text. in: component. out str: text.",
    # --- Inventory ---
    "INV_GETOBJ": "Get inventory item id. in: slot, inv_id (slot top). out int: obj_id or -1 if empty.",
    "INV_GETNUM": "Get inventory stack size. in: slot, inv_id (slot top). out int: count.",
    "INV_SIZE": "Get inventory capacity. in: inv_id. out int: slot_count.",
    "INV_TOTAL": "Count item across inventory. in: inv_id, item_id (item_id top). out int: total qty.",
    # --- SETON hooks ---
    "CC_SETONINVTRANSMIT": "Register inv-transmit script on active child. op=script_id; signature in stack.",
    "IF_SETONINVTRANSMIT": "Register inv-transmit script. in: component; op=script_id; signature in stack.",
    # --- String/math host ---
    "TOSTRING": "Int to string. in: value. out str: decimal string.",
    "APPEND": "Append string. sin: dest, src (src top). out str: dest+src.",
    "APPEND_NUM": "Append int as decimal. sin: dest. in: value. out str: dest+value.",
    "APPEND_SIGNNUM": "Append signed int. sin: dest. in: value. out str: dest+signed value.",
    "APPEND_CHAR": "Append char. sin: dest. in: ch. out str: dest+char.",
    "STRING_LENGTH": "String length. sin: str. out int: strlen.",
    "PARAWIDTH": "Wrapped max line width. sin: text. in: max_width, font_id (font_id top). out int: pixels.",
    "PARAHEIGHT": "Wrapped line count. sin: text. in: max_width, font_id (font_id top). out int: lines.",
    "SCALE": "Scale interpolate (c*a)/b. in: a, b, c (c top). out int: result; b==0 yields 0.",
    "INTERPOLATE": "Linear interpolate. in: a, b, c, d, e (e top). out int: a+(b-a)*(e-c)/(d-c).",
    "RANDOMINC": "Random inclusive. in: max. out int: rand()%(max+1).",
    "CLEARBIT": "Clear bit in value. in: value, bit (bit top). out int: value with bit cleared.",
    "SETBIT": "Set bit in value. in: value, bit (bit top). out int: value with bit set.",
    # --- Config / client ---
    "OC_UNPLACEHOLDER": "Resolve placeholder item. in: item_id. out int: underlying id or item_id.",
    "RUNWEIGHT_VISIBLE": "Get visible player weight. in: -. out int: weight kg (0 default).",
    "CLIENTCLOCK": "Get client tick counter. in: -. out int: clock_ticks.",
    "COORD": "Get player coord packed (stub). in: -. out int: 0.",
    "COORDX": "Extract X from packed coord. in: packed. out int: (packed>>14)&0x3FFF.",
    "MAP_WORLD": "Get world id (stub). in: -. out int: 301.",
    "MAP_MEMBERS": "Is members world (stub). in: -. out int: 1.",
    "ON_MOBILE": "Is mobile client (stub). in: -. out int: 0.",
    "CLIENTTYPE": "Get client type (stub). in: -. out int: 10.",
    "ENUM_GETOUTPUTCOUNT": "Get enum output count. in: enum_id. out int: count.",
    "STRUCT_PARAM": "Read struct param. in: struct_id, param_id (param_id top). out int or str.",
}
