#ifndef RSCACHE_DATATYPES_DAT2_CONFIGS_H
#define RSCACHE_DATATYPES_DAT2_CONFIGS_H

enum RSCache_Dat2ConfigKind
{
    RSCACHE_DAT2_CONFIG_KIND_UNDERLAY = 1,
    RSCACHE_DAT2_CONFIG_KIND_IDENTKIT = 3,
    RSCACHE_DAT2_CONFIG_KIND_OVERLAY = 4,
    RSCACHE_DAT2_CONFIG_KIND_INV = 5,
    /** Scenery / locs in RuneLite naming. */
    RSCACHE_DAT2_CONFIG_KIND_LOCS = 6,
    RSCACHE_DAT2_CONFIG_KIND_ENUM = 8,
    RSCACHE_DAT2_CONFIG_KIND_NPC = 9,
    /** Items in RuneLite naming. */
    RSCACHE_DAT2_CONFIG_KIND_OBJECT = 10,
    RSCACHE_DAT2_CONFIG_KIND_PARAMS = 11,
    RSCACHE_DAT2_CONFIG_KIND_SEQUENCE = 12,
    RSCACHE_DAT2_CONFIG_KIND_SPOTANIM = 13,
    RSCACHE_DAT2_CONFIG_KIND_VARBIT = 14,
    RSCACHE_DAT2_CONFIG_KIND_VARCLIENT_STRING = 15,
    RSCACHE_DAT2_CONFIG_KIND_VARPLAYER = 16,
    RSCACHE_DAT2_CONFIG_KIND_VARCLIENT = 19,
    RSCACHE_DAT2_CONFIG_KIND_HITSPLAT = 32,
    RSCACHE_DAT2_CONFIG_KIND_HEALTHBAR = 33,
    RSCACHE_DAT2_CONFIG_KIND_STRUCT = 34,
    RSCACHE_DAT2_CONFIG_KIND_AREA = 35,
    RSCACHE_DAT2_CONFIG_KIND_DBROW = 38,
    RSCACHE_DAT2_CONFIG_KIND_DBTABLE = 39
};

#endif
